import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPPEStandard, ppeStandards } from '../data';

type P={params:Promise<{locale:string;slug:string}>};
export function generateStaticParams(){return ['tr','en'].flatMap(locale=>ppeStandards.map(s=>({locale,slug:s.slug})))}
export async function generateMetadata({params}:P):Promise<Metadata>{const{locale,slug}=await params;const l=locale==='tr'?'tr':'en';const s=getPPEStandard(slug);if(!s)return{};const canonical=`https://www.sernem.com/${l}/ppe-standards/${slug}`;return{title:`${s.code} – ${s.title[l]} | SERNEM`,description:s.purpose[l],alternates:{canonical,languages:{tr:`https://www.sernem.com/tr/ppe-standards/${slug}`,en:`https://www.sernem.com/en/ppe-standards/${slug}`,'x-default':`https://www.sernem.com/en/ppe-standards/${slug}`}},openGraph:{title:`${s.code} – ${s.title[l]}`,description:s.purpose[l],url:canonical,type:'article',siteName:'SERNEM'}}}

const visual:Record<string,{icon:string;gradient:string;label:{tr:string;en:string}}>= {
 'EN 397':{icon:'◉',gradient:'from-amber-500 to-orange-700',label:{tr:'Baş Koruma',en:'Head Protection'}},'EN 361':{icon:'⌁',gradient:'from-blue-600 to-indigo-800',label:{tr:'Düşüş Koruma',en:'Fall Protection'}},'EN 355':{icon:'↯',gradient:'from-cyan-600 to-blue-800',label:{tr:'Düşüş Koruma',en:'Fall Protection'}},'EN 362':{icon:'∞',gradient:'from-slate-500 to-slate-800',label:{tr:'Bağlantı Sistemleri',en:'Connection Systems'}},'EN 166':{icon:'◒',gradient:'from-sky-500 to-blue-800',label:{tr:'Göz Koruma',en:'Eye Protection'}},'EN 388':{icon:'✋',gradient:'from-orange-500 to-red-800',label:{tr:'El Koruma',en:'Hand Protection'}},'EN ISO 374':{icon:'⬡',gradient:'from-emerald-500 to-teal-800',label:{tr:'Kimyasal Koruma',en:'Chemical Protection'}},'EN 149':{icon:'◈',gradient:'from-blue-500 to-cyan-800',label:{tr:'Solunum Koruma',en:'Respiratory Protection'}},'EN 352':{icon:'◖',gradient:'from-violet-500 to-purple-800',label:{tr:'İşitme Koruma',en:'Hearing Protection'}},'EN ISO 20345':{icon:'◢',gradient:'from-zinc-600 to-slate-900',label:{tr:'Ayak Koruma',en:'Foot Protection'}}};

export default async function Page({params}:P){const{locale,slug}=await params;if(!['tr','en'].includes(locale))notFound();const s=getPPEStandard(slug);if(!s)notFound();const l=locale as'tr'|'en',tr=l==='tr',v=visual[s.code]||visual['EN 149'],is149=s.code==='EN 149';const schema={'@context':'https://schema.org','@type':'Article',headline:`${s.code} – ${s.title[l]}`,description:s.purpose[l],inLanguage:l,mainEntityOfPage:`https://www.sernem.com/${l}/ppe-standards/${slug}`,publisher:{'@type':'Organization',name:'SERNEM',url:'https://www.sernem.com'}};
 const checks=tr?['Ürün hasarlı, kirli veya deformasyona uğramış mı?','Doğru standart ve koruma sınıfı işaretli mi?','Ürün kullanıcıya doğru şekilde uyuyor mu?','Üretici/model ve izlenebilirlik bilgileri mevcut mu?','Kullanım süresi ve saklama koşulları uygun mu?']:['Is the product damaged, contaminated or deformed?','Is the correct standard/protection class marked?','Does the product fit the user correctly?','Are manufacturer/model and traceability details present?','Are service life and storage conditions acceptable?'];
 return <main className='min-h-screen bg-[#f4f7fb] pb-20 text-slate-950'><script type='application/ld+json' dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <div className='mx-auto max-w-[1400px] px-4 pt-7 md:px-7'>
  <div className='mb-5 flex items-center gap-2 text-sm text-slate-500'><Link href={`/${l}/ppe-standards`} className='font-bold hover:text-blue-700'>← {tr?'Tüm KKD Standartları':'All PPE Standards'}</Link><span>/</span><span>{v.label[l]}</span><span>/</span><b className='text-slate-800'>{s.code}</b></div>
  <section className={`relative overflow-hidden rounded-[30px] bg-gradient-to-br ${v.gradient} text-white shadow-2xl`}>
   <div className='absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(255,255,255,.22),transparent_28%),linear-gradient(90deg,rgba(2,6,23,.88),rgba(2,6,23,.28))]'/>
   <div className='relative grid min-h-[390px] md:grid-cols-[1.2fr_.8fr]'>
    <div className='flex flex-col justify-center p-7 md:p-12'><span className='w-fit rounded-lg border border-white/20 bg-black/20 px-3 py-2 text-xs font-black uppercase tracking-[.16em]'>{v.label[l]}</span><h1 className='mt-5 text-6xl font-black tracking-tight md:text-8xl'>{s.code}</h1><h2 className='mt-3 max-w-3xl text-2xl font-black leading-tight md:text-4xl'>{s.title[l]}</h2><p className='mt-5 max-w-2xl text-base leading-7 text-white/85 md:text-lg'>{s.purpose[l]}</p>{is149&&<div className='mt-6 flex flex-wrap gap-2'>{['FFP1','FFP2','FFP3','NR','R','D'].map(x=><span key={x} className='rounded-lg border border-white/35 bg-black/20 px-4 py-2 text-sm font-black'>{x}</span>)}</div>}</div>
    <div className='relative flex items-center justify-center p-8'><div className='absolute h-72 w-72 rounded-full bg-white/15 blur-2xl'/><div className='relative flex h-64 w-64 items-center justify-center rounded-[3rem] border border-white/20 bg-white/10 text-[130px] font-black shadow-2xl backdrop-blur-md'>{v.icon}</div></div>
   </div>
  </section>
  <nav className='sticky top-2 z-20 mt-4 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-lg backdrop-blur'>{[['overview',tr?'Genel Bakış':'Overview'],['classes',tr?'Sınıflar':'Classes'],['marking',tr?'İşaretleme':'Marking'],['use',tr?'Kullanım Alanları':'Applications'],['field',tr?'Saha Kontrolü':'Field Check'],['related',tr?'İlgili İçerikler':'Related']].map(([id,x])=><a key={id} href={`#${id}`} className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold text-slate-700 hover:bg-blue-50 hover:text-blue-700'>{x}</a>)}</nav>
  <section id='overview' className='mt-5 grid gap-4 md:grid-cols-3'>{[[tr?'Bu standart neyi kapsar?':'What does it cover?',s.purpose[l],'01'],[tr?'Nerede kullanılır?':'Where is it used?',s.use[l],'02'],[tr?'Üründe ne aranır?':'What to look for?',s.markings[l],'03']].map(([h,p,n])=><article key={n} className='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm'><div className='flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 font-black text-white'>{n}</div><h2 className='mt-5 text-xl font-black'>{h}</h2><p className='mt-3 leading-7 text-slate-600'>{p}</p></article>)}</section>
  {is149&&<section id='classes' className='mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8'><div className='flex items-end justify-between gap-4'><div><span className='text-xs font-black uppercase tracking-widest text-blue-600'>EN 149</span><h2 className='mt-2 text-2xl font-black md:text-3xl'>{tr?'FFP Sınıfları ve Koruma Seviyeleri':'FFP Classes and Protection Levels'}</h2></div><span className='hidden rounded-xl bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700 md:block'>{tr?'Seçim risk değerlendirmesine göre yapılır':'Selection follows risk assessment'}</span></div><div className='mt-6 grid gap-4 md:grid-cols-3'>{[{x:'FFP1',n:'≥ 80%',t:tr?'Temel partikül filtrasyonu':'Basic particle filtration'},{x:'FFP2',n:'≥ 94%',t:tr?'Daha yüksek partikül filtrasyonu':'Higher particle filtration'},{x:'FFP3',n:'≥ 99%',t:tr?'En yüksek EN 149 sınıfı':'Highest EN 149 class'}].map((a,i)=><div key={a.x} className='relative overflow-hidden rounded-2xl border border-slate-200 bg-slate-50 p-6'><div className={`absolute left-0 top-0 h-1.5 w-full ${i===0?'bg-amber-400':i===1?'bg-blue-500':'bg-red-500'}`}/><div className='text-xl font-black'>{a.x}</div><div className='mt-5 text-4xl font-black'>{a.n}</div><div className='mt-2 text-sm font-bold text-slate-500'>{tr?'Filtrasyon verimliliği':'Filtration efficiency'}</div><p className='mt-5 text-sm leading-6 text-slate-600'>{a.t}. {tr?'Doğru fit ve maruziyet değerlendirmesi gereklidir.':'Correct fit and exposure assessment are required.'}</p></div>)}</div></section>}
  <section id='marking' className='mt-5 grid gap-4 lg:grid-cols-[1.25fr_.75fr]'><article className='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8'><h2 className='text-2xl font-black'>{tr?'Ürün İşaretleme ve Kodların Anlamı':'Product Markings and Code Meaning'}</h2><p className='mt-2 text-slate-600'>{s.markings[l]}</p><div className='mt-6 rounded-2xl bg-slate-950 p-6 text-white'><div className='font-mono text-2xl font-black md:text-4xl'>{is149?'EN 149:2001+A1:2009  FFP2 NR D  CE':'STANDARD  •  CLASS  •  CE'}</div><div className='mt-6 grid gap-3 sm:grid-cols-2'>{(is149?(tr?['FFP2 — performans sınıfı','NR — tek vardiya kullanımı','R — yeniden kullanılabilir sınıf','D — dolomit toz testi işareti','CE — uygunluk işaretlemesi','Üretici/model — izlenebilirlik']:['FFP2 — performance class','NR — single-shift use','R — reusable classification','D — dolomite dust test marking','CE — conformity marking','Manufacturer/model — traceability']):checks.slice(0,4)).map(x=><div key={x} className='rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-slate-200'>{x}</div>)}</div></div></article><aside className='rounded-2xl border border-blue-200 bg-blue-50 p-6 md:p-8'><div className='text-sm font-black uppercase tracking-widest text-blue-700'>{tr?'Doğru seçim':'Correct selection'}</div><h3 className='mt-3 text-2xl font-black'>{tr?'Kod tek başına yeterli değildir.':'The code alone is not enough.'}</h3><p className='mt-4 leading-7 text-slate-700'>{tr?'Maruziyet seviyesi, işin türü, uyum/fit, kullanım süresi, diğer KKD’lerle uyumluluk ve üretici talimatları birlikte değerlendirilmelidir.':'Exposure level, task type, fit, duration, compatibility with other PPE and manufacturer instructions must be assessed together.'}</p></aside></section>
  <section id='use' className='mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8'><h2 className='text-2xl font-black'>{tr?'Tipik Kullanım Alanları':'Typical Applications'}</h2><div className='mt-5 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6'>{(tr?['İnşaat ve bakım','Metal işleme','Kimyasal proses','Madencilik','Sağlık hizmetleri','Üretim ve depo']:['Construction & maintenance','Metal work','Chemical process','Mining','Healthcare','Manufacturing & warehouse']).map((x,i)=><div key={x} className='overflow-hidden rounded-2xl border border-slate-200'><div className={`h-24 bg-gradient-to-br ${['from-amber-300 to-orange-700','from-orange-400 to-slate-800','from-blue-400 to-slate-800','from-stone-400 to-slate-900','from-cyan-300 to-blue-700','from-emerald-300 to-slate-700'][i]} flex items-center justify-center text-4xl font-black text-white/80`}>{String(i+1).padStart(2,'0')}</div><div className='p-3 text-sm font-bold'>{x}</div></div>)}</div></section>
  <section id='field' className='mt-5 grid gap-4 lg:grid-cols-[.8fr_1.2fr]'><div className='rounded-2xl bg-slate-950 p-7 text-white'><span className='text-xs font-black uppercase tracking-widest text-cyan-300'>HSE FIELD CHECK</span><h2 className='mt-3 text-3xl font-black'>{tr?'Sahada 30 Saniyelik Kontrol':'30-Second Field Check'}</h2><p className='mt-4 leading-7 text-slate-300'>{tr?'Hızlı görsel doğrulama. Ürün sertifikasyonu veya işe özgü risk değerlendirmesinin yerine geçmez.':'Quick visual verification. It does not replace product certification or task-specific risk assessment.'}</p></div><div className='grid gap-3 rounded-2xl border border-slate-200 bg-white p-6'>{checks.map((x,i)=><div key={x} className='flex items-start gap-4 rounded-xl bg-slate-50 p-4'><span className='flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-emerald-500 font-black text-white'>✓</span><div><b>{String(i+1).padStart(2,'0')}</b><p className='mt-1 text-slate-600'>{x}</p></div></div>)}</div></section>
  <aside className='mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-950'><b>{tr?'Önemli: ':'Important: '}</b>{tr?'Standart numarası tek başına KKD seçimi için yeterli değildir. İşe özgü risk değerlendirmesi, ürünün güncel işaretlemesi, üretici talimatları ve geçerli mevzuat/standart sürümü doğrulanmalıdır.':'A standard number alone is not enough to select PPE. Verify the task-specific risk assessment, current product marking, manufacturer instructions and applicable legislation/standard edition.'}</aside>
  <section id='related' className='mt-5 grid gap-4 md:grid-cols-3'><Link href={`/${l}/knowledge-base/ppe`} className='rounded-2xl border bg-white p-6 font-black shadow-sm hover:-translate-y-1 hover:shadow-lg'>{tr?'KKD Ana Rehberi':'PPE Master Guide'}<span className='float-right text-blue-600'>→</span></Link><Link href={`/${l}/toolbox`} className='rounded-2xl border bg-white p-6 font-black shadow-sm hover:-translate-y-1 hover:shadow-lg'>{tr?'İlgili Toolbox Eğitimleri':'Related Toolbox Talks'}<span className='float-right text-blue-600'>→</span></Link><Link href={`/${l}/risk-assessment`} className='rounded-2xl border bg-white p-6 font-black shadow-sm hover:-translate-y-1 hover:shadow-lg'>{tr?'Risk Değerlendirmeleri':'Risk Assessments'}<span className='float-right text-blue-600'>→</span></Link></section>
 </div></main>}
