import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getPPEStandard, ppeStandards } from '../data';
import { getPPETech } from '../tech-data';
import { getPPEVisual, pexels } from '../visual-data';
import { getPPEExperience } from '../experience-data';

type P={params:Promise<{locale:string;slug:string}>};
type Locale='tr'|'en';

const theme:Record<string,{label:{tr:string;en:string};accent:string;soft:string;line:string}>={
 'EN 397':{label:{tr:'Baş Koruma',en:'Head Protection'},accent:'bg-amber-500',soft:'bg-amber-50',line:'border-amber-200'},
 'EN 361':{label:{tr:'Düşüş Koruma',en:'Fall Protection'},accent:'bg-blue-600',soft:'bg-blue-50',line:'border-blue-200'},
 'EN 355':{label:{tr:'Düşüş Koruma',en:'Fall Protection'},accent:'bg-cyan-600',soft:'bg-cyan-50',line:'border-cyan-200'},
 'EN 362':{label:{tr:'Bağlantı Sistemleri',en:'Connection Systems'},accent:'bg-slate-700',soft:'bg-slate-100',line:'border-slate-300'},
 'EN 166':{label:{tr:'Göz Koruma',en:'Eye Protection'},accent:'bg-sky-600',soft:'bg-sky-50',line:'border-sky-200'},
 'EN 388':{label:{tr:'El Koruma',en:'Hand Protection'},accent:'bg-orange-600',soft:'bg-orange-50',line:'border-orange-200'},
 'EN ISO 374':{label:{tr:'Kimyasal Koruma',en:'Chemical Protection'},accent:'bg-emerald-600',soft:'bg-emerald-50',line:'border-emerald-200'},
 'EN 149':{label:{tr:'Solunum Koruma',en:'Respiratory Protection'},accent:'bg-indigo-600',soft:'bg-indigo-50',line:'border-indigo-200'},
 'EN 352':{label:{tr:'İşitme Koruma',en:'Hearing Protection'},accent:'bg-violet-600',soft:'bg-violet-50',line:'border-violet-200'},
 'EN ISO 20345':{label:{tr:'Ayak Koruma',en:'Foot Protection'},accent:'bg-zinc-800',soft:'bg-zinc-100',line:'border-zinc-300'}
};

const toolboxByCode:Record<string,string>={
 'EN 397':'ppe-safety','EN 361':'working-at-height','EN 355':'working-at-height','EN 362':'working-at-height','EN 166':'ppe-safety','EN 388':'ppe-safety','EN ISO 374':'chemical-safety','EN 149':'respiratory-protection','EN 352':'noise-hearing-protection','EN ISO 20345':'ppe-safety'
};

export function generateStaticParams(){return ['tr','en'].flatMap(locale=>ppeStandards.map(s=>({locale,slug:s.slug})))}

export async function generateMetadata({params}:P):Promise<Metadata>{
 const{locale,slug}=await params; const l:Locale=locale==='tr'?'tr':'en'; const s=getPPEStandard(slug); if(!s)return{};
 const canonical=`https://www.sernem.com/${l}/ppe-standards/${slug}`;
 return{title:`${s.code} – ${s.title[l]} | SERNEM`,description:s.purpose[l],alternates:{canonical,languages:{tr:`https://www.sernem.com/tr/ppe-standards/${slug}`,en:`https://www.sernem.com/en/ppe-standards/${slug}`,'x-default':`https://www.sernem.com/en/ppe-standards/${slug}`}},openGraph:{title:`${s.code} – ${s.title[l]} | SERNEM`,description:s.purpose[l],url:canonical,type:'article',siteName:'SERNEM'}};
}

export default async function Page({params}:P){
 const{locale,slug}=await params; if(!['tr','en'].includes(locale))notFound();
 const s=getPPEStandard(slug); if(!s)notFound(); const l=locale as Locale; const tr=l==='tr'; const d=getPPETech(s.code); const xp=getPPEExperience(s.code); if(!d||!xp)notFound();
 const v=theme[s.code]??theme['EN 397']; const vis=getPPEVisual(s.code); const is149=s.code==='EN 149'; const canonical=`https://www.sernem.com/${l}/ppe-standards/${slug}`; const toolboxSlug=toolboxByCode[s.code]??'ppe-safety';
 const scene=(index:number,width=900)=>pexels(vis.scenes[index%vis.scenes.length]??vis.photo,width);
 const schema={'@context':'https://schema.org','@type':'TechArticle',headline:`${s.code} – ${s.title[l]}`,description:s.purpose[l],inLanguage:l,url:canonical,image:pexels(vis.photo,1600),about:{'@type':'Thing',name:d.product[l]},publisher:{'@type':'Organization',name:'SERNEM',url:'https://www.sernem.com'}};
 const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:tr?'KKD Standartları':'PPE Standards',item:`https://www.sernem.com/${l}/ppe-standards`},{'@type':'ListItem',position:2,name:s.code,item:canonical}]};
 const overview=[[tr?'Standardın amacı':'Purpose',s.purpose[l]],[tr?'Tipik kullanım':'Typical use',s.use[l]],[tr?'Üründe ne aranır?':'What to look for?',s.markings[l]]] as const;
 return <main className='relative min-h-screen overflow-hidden bg-[#eef3f8] pb-20 text-slate-950'>
  <script type='application/ld+json' dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <script type='application/ld+json' dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
  <div className='pointer-events-none absolute inset-x-0 top-0 h-[760px] opacity-80' style={{backgroundImage:`radial-gradient(circle at 16% 10%, ${vis.glow}22, transparent 27%), radial-gradient(circle at 86% 18%, ${vis.glow}18, transparent 23%), linear-gradient(rgba(15,23,42,.035) 1px, transparent 1px), linear-gradient(90deg, rgba(15,23,42,.035) 1px, transparent 1px)`,backgroundSize:'auto,auto,34px 34px,34px 34px'}}/>
  <div className='relative mx-auto max-w-[1460px] px-4 pt-7 md:px-7'>
   <div className='mb-5 flex flex-wrap items-center gap-2 text-sm text-slate-500'><Link href={`/${l}/ppe-standards`} className='font-bold hover:text-blue-700'>← {tr?'Tüm KKD Standartları':'All PPE Standards'}</Link><span>/</span><span>{v.label[l]}</span><span>/</span><strong className='text-slate-800'>{s.code}</strong></div>

   <section className='relative overflow-hidden rounded-[30px] border border-slate-800 bg-slate-950 text-white shadow-[0_28px_70px_rgba(15,23,42,.24)]'>
    <img src={pexels(vis.photo,1800)} alt={vis.alt[l]} className='absolute inset-0 h-full w-full object-cover opacity-35' style={{objectPosition:'center 38%'}}/>
    <div className='absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/92 to-slate-950/52'/>
    <div className='absolute inset-0 opacity-40' style={{backgroundImage:`radial-gradient(circle at 82% 24%, ${vis.glow}66, transparent 22%), linear-gradient(rgba(255,255,255,.04) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.04) 1px, transparent 1px)`,backgroundSize:'auto,36px 36px,36px 36px'}}/>
    <div className='relative grid lg:grid-cols-[1.12fr_.88fr]'>
     <div className='p-7 md:p-11 lg:p-14'>
      <div className='flex flex-wrap gap-2'><span className={`rounded-full ${v.accent} px-4 py-2 text-xs font-black uppercase tracking-[.14em] text-white shadow-lg`}>{v.label[l]}</span><span className='rounded-full border border-white/15 bg-white/8 px-4 py-2 text-xs font-black uppercase tracking-[.14em] text-slate-200 backdrop-blur'>{tr?'TEKNİK KKD KÜTÜPHANESİ':'TECHNICAL PPE LIBRARY'}</span></div>
      <h1 className='mt-7 text-5xl font-black tracking-tight md:text-7xl'>{s.code}</h1>
      <p className='mt-3 max-w-3xl text-2xl font-black leading-tight md:text-4xl'>{s.title[l]}</p>
      <p className='mt-5 max-w-3xl text-base leading-7 text-slate-200 md:text-lg'>{s.purpose[l]}</p>
      <div className='mt-7 grid gap-3 sm:grid-cols-2'><div className='rounded-2xl border border-white/10 bg-white/[.07] p-4 backdrop-blur'><div className='text-[11px] font-black uppercase tracking-[.14em] text-slate-300'>{tr?'Ürün tipi':'Product type'}</div><div className='mt-2 text-base font-bold'>{d.product[l]}</div></div><div className='rounded-2xl border border-white/10 bg-white/[.07] p-4 backdrop-blur'><div className='text-[11px] font-black uppercase tracking-[.14em] text-slate-300'>{tr?'Saha odağı':'Field focus'}</div><div className='mt-2 text-base font-bold'>{tr?'Kod + ürün + kullanım koşulu':'Code + product + conditions of use'}</div></div></div>
     </div>
     <div className='flex items-end border-t border-white/10 p-6 lg:border-l lg:border-t-0 lg:p-8'>
      <div className='w-full rounded-[26px] border border-white/15 bg-slate-950/75 p-5 shadow-2xl backdrop-blur-xl md:p-6'>
       <div className='flex items-center justify-between gap-4'><div><div className='text-xs font-black uppercase tracking-[.16em] text-slate-400'>{tr?'TEKNİK ÜRÜN KİMLİĞİ':'TECHNICAL PRODUCT IDENTITY'}</div><div className='mt-3 text-3xl font-black'>{s.code}</div></div><span className={`h-14 w-2 rounded-full ${v.accent}`}/></div>
       <div className='mt-5 overflow-hidden rounded-2xl border border-white/10'><img src={pexels(vis.photo,900)} alt={vis.alt[l]} className='h-40 w-full object-cover opacity-90'/></div>
       <div className='mt-4 grid gap-2 sm:grid-cols-2'>{d.marks.slice(0,4).map(m=><div key={m.code} className='rounded-xl border border-white/10 bg-white/[.05] p-3'><code className='block text-sm font-black text-white'>{m.code}</code><span className='mt-1 block text-xs font-semibold text-slate-300'>{m.title[l]}</span></div>)}</div>
       <p className='mt-4 text-xs leading-5 text-slate-400'>{tr?'Gerçek ürün etiketi, üretici teknik dokümanı ve uygunluk işaretleri ayrıca doğrulanmalıdır.':'Always verify the actual product label, manufacturer technical documentation and conformity markings.'}</p>
      </div>
     </div>
    </div>
   </section>

   {d.note&&<aside className='mt-5 rounded-2xl border border-amber-300 bg-amber-50/95 p-5 text-sm leading-6 text-amber-950 shadow-sm'><strong>{tr?'Güncel standart notu: ':'Current-standard note: '}</strong>{d.note[l]}</aside>}

   <nav className='sticky top-2 z-20 mt-5 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200/90 bg-white/95 p-2 shadow-lg backdrop-blur'><a href='#overview' className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100'>{tr?'Genel Bakış':'Overview'}</a><a href='#classes' className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100'>{tr?'Sınıflar':'Classes'}</a><a href='#marking' className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100'>{tr?'Kod Çözümleme':'Code Decoder'}</a><a href='#product' className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100'>{tr?'Üründe Nerede?':'On the Product'}</a><a href='#context' className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100'>{tr?'Karşılaştır':'Compare'}</a><a href='#use' className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100'>{tr?'Kullanım':'Applications'}</a><a href='#field' className='whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold hover:bg-slate-100'>{tr?'Saha Kontrolü':'Field Check'}</a></nav>

   <section id='overview' className='mt-5 grid gap-4 md:grid-cols-3'>{overview.map(([h,p],i)=><article key={h} className='group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl'><div className='relative h-32 overflow-hidden'><img src={scene(i,800)} alt={`${h} — ${vis.alt[l]}`} className='h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]'/><div className='absolute inset-0 bg-gradient-to-t from-slate-950/70 via-slate-950/5 to-transparent'/><div className={`absolute bottom-3 left-3 flex h-9 w-9 items-center justify-center rounded-lg ${i===0?v.accent:'bg-slate-900'} text-sm font-black text-white`}>0{i+1}</div></div><div className='p-6'><h2 className='text-xl font-black'>{h}</h2><p className='mt-3 text-[15px] leading-7 text-slate-600'>{p}</p></div></article>)}</section>

   <section id='classes' className='mt-5 rounded-2xl border border-slate-200 bg-white/95 p-6 shadow-sm md:p-8'>
    <div className='max-w-4xl'><div className='text-xs font-black uppercase tracking-[.16em] text-blue-700'>{tr?'SINIFLAR VE SEÇİM MANTIĞI':'CLASSES & SELECTION LOGIC'}</div><h2 className='mt-2 text-2xl font-black md:text-3xl'>{tr?'Bu standarttaki teknik sınıflar':'Technical classes in this standard'}</h2><p className='mt-3 text-[15px] leading-7 text-slate-600'>{tr?'Sınıf kodu tek başına seçim kararı değildir. İşe özgü risk değerlendirmesi ve üretici verileriyle birlikte yorumlanmalıdır.':'A class code is not a selection decision by itself. Interpret it together with task-specific risk assessment and manufacturer data.'}</p></div>
    <div className='mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3'>{d.classes.map((x,i)=><article key={x.code} className={`group overflow-hidden rounded-2xl border ${v.line} ${v.soft} shadow-sm`}><div className='relative h-28 overflow-hidden'><img src={scene(i+2,720)} alt={`${x.title[l]} — ${vis.alt[l]}`} className='h-full w-full object-cover opacity-90 transition duration-500 group-hover:scale-[1.04]'/><div className='absolute inset-0 bg-gradient-to-t from-slate-950/75 to-transparent'/><div className='absolute bottom-3 left-4 font-mono text-xl font-black text-white'>{x.code}</div></div><div className='p-5'><h3 className='font-black'>{x.title[l]}</h3><p className='mt-2 text-sm leading-6 text-slate-600'>{x.detail[l]}</p></div></article>)}</div>
    {is149&&<div className='mt-5 grid gap-3 lg:grid-cols-[1.35fr_.65fr]'><div className='rounded-2xl border border-indigo-200 bg-indigo-50 p-5'><div className='text-xs font-black uppercase tracking-[.14em] text-indigo-700'>{tr?'SEÇİM NOTU':'SELECTION NOTE'}</div><p className='mt-2 text-sm leading-6 text-slate-700'>{tr?'FFP1, FFP2 ve FFP3 partikül sınıflarıdır. Seçim; maruziyet seviyesi, yüz uyumu/sızdırmazlığı ve üretici talimatlarıyla birlikte yapılmalıdır.':'FFP1, FFP2 and FFP3 are particle-protection classes. Selection must consider exposure level, face seal/fit and manufacturer instructions.'}</p></div><div className='rounded-2xl border border-rose-200 bg-rose-50 p-5'><div className='text-xs font-black uppercase tracking-[.14em] text-rose-700'>{tr?'KRİTİK UYARI':'CRITICAL NOTE'}</div><p className='mt-2 text-sm font-semibold leading-6 text-rose-950'>{tr?'EN 149 partiküllere yöneliktir; gaz ve buhar koruması için uygun filtre/solunum koruyucu sistemi ayrıca seçilmelidir.':'EN 149 addresses particles; gas and vapour hazards require a separately selected suitable filter/respirator system.'}</p></div></div>}
   </section>

   <section id='marking' className='mt-5 grid gap-4 lg:grid-cols-[1.15fr_.85fr]'>
    <article className='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8'><div className='text-xs font-black uppercase tracking-[.16em] text-blue-700'>{tr?'ÜRÜN ETİKETİNİ OKU':'READ THE PRODUCT LABEL'}</div><h2 className='mt-2 text-2xl font-black md:text-3xl'>{tr?'Kod ve işaretleme çözümleme':'Code & marking decoder'}</h2><div className='mt-6 overflow-hidden rounded-2xl border border-slate-200'>{d.marks.map((m,i)=><div key={m.code} className={`grid gap-3 p-5 sm:grid-cols-[145px_175px_1fr] ${i%2?'bg-slate-50':'bg-white'}`}><code className={`w-fit rounded-lg px-2.5 py-1 text-sm font-black ${v.soft}`}>{m.code}</code><strong className='text-sm'>{m.title[l]}</strong><span className='text-[14px] leading-6 text-slate-600'>{m.detail[l]}</span></div>)}</div></article>
    <aside className='relative overflow-hidden rounded-2xl bg-slate-950 p-7 text-white shadow-xl'><img src={scene(3,900)} alt={vis.alt[l]} className='absolute inset-0 h-full w-full object-cover opacity-20'/><div className='absolute inset-0 bg-gradient-to-b from-slate-950/70 to-slate-950'/><div className='relative'><div className='text-xs font-black uppercase tracking-[.16em] text-cyan-300'>{tr?'DOĞRU SEÇİM':'CORRECT SELECTION'}</div><h3 className='mt-3 text-2xl font-black'>{tr?'Standart numarasından fazlasını kontrol et.':'Check more than the standard number.'}</h3><p className='mt-4 text-[15px] leading-7 text-slate-300'>{tr?'Üretici, model, sınıf, lot/seri, kullanım ömrü, işe uygunluk, diğer KKD’lerle uyumluluk ve ürün talimatlarını birlikte doğrulayın.':'Verify manufacturer, model, class, lot/serial, service life, task suitability, compatibility with other PPE and product instructions together.'}</p><div className='mt-6 flex flex-wrap gap-2'>{d.marks.slice(0,4).map(m=><span key={m.code} className='rounded-lg border border-white/10 bg-white/[.06] px-3 py-2 font-mono text-xs font-black'>{m.code}</span>)}</div></div></aside>
   </section>

   <section id='product' className='mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm'>
    <div className='grid lg:grid-cols-[.9fr_1.1fr]'><div className='relative min-h-[320px] overflow-hidden'><img src={scene(1,1200)} alt={vis.alt[l]} className='absolute inset-0 h-full w-full object-cover'/><div className='absolute inset-0 bg-gradient-to-t from-slate-950/85 via-slate-950/20 to-transparent'/><div className='absolute bottom-0 left-0 right-0 p-7 text-white'><div className='text-xs font-black uppercase tracking-[.16em] text-cyan-300'>{tr?'ÜRÜNÜ SAHADA OKU':'READ THE PRODUCT IN THE FIELD'}</div><h2 className='mt-2 text-3xl font-black'>{tr?'Standart işareti üründe nerede bulunur?':'Where is the standard marking found?'}</h2></div></div><div className='p-6 md:p-8'><p className='text-[15px] leading-7 text-slate-600'>{tr?'Üreticiye ve ürün tasarımına göre konum değişebilir. Aşağıdaki noktalar ilk kontrol yerleridir; son doğrulama her zaman gerçek ürün ve üretici dokümanıyla yapılır.':'Location varies by manufacturer and design. These are the first places to check; final verification must use the actual product and manufacturer documentation.'}</p><div className='mt-6 grid gap-3'>{xp.labelWhere.map((x,i)=><div key={x[l]} className='flex items-start gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4'><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${v.accent} font-black text-white`}>{i+1}</span><div><strong className='text-sm'>{x[l]}</strong><p className='mt-1 text-xs leading-5 text-slate-500'>{tr?'Kod okunur, kalıcı ve ürünle eşleşir olmalı.':'The marking should be legible, durable and match the product.'}</p></div></div>)}</div></div></div>
   </section>

   <section id='context' className='mt-5 grid gap-4 xl:grid-cols-3'>
    <article className='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm'><div className='text-xs font-black uppercase tracking-[.16em] text-blue-700'>{tr?'STANDART AİLESİ':'STANDARD FAMILY'}</div><h2 className='mt-2 text-2xl font-black'>{tr?'Birlikte görülen standartlar':'Standards often reviewed together'}</h2><div className='mt-5 space-y-3'>{xp.family.map(x=><div key={x.code} className='rounded-xl border border-slate-200 bg-slate-50 p-4'><code className='text-sm font-black text-slate-950'>{x.code}</code><p className='mt-2 text-sm leading-6 text-slate-600'>{x.relation[l]}</p></div>)}</div></article>
    <article className='rounded-2xl border border-amber-200 bg-amber-50 p-6 shadow-sm'><div className='text-xs font-black uppercase tracking-[.16em] text-amber-700'>{tr?'SIK KARIŞTIRILAN':'COMMONLY CONFUSED'}</div><h2 className='mt-2 text-2xl font-black'>{tr?'Aynı şey değiller':'They are not the same thing'}</h2><div className='mt-5 space-y-3'>{xp.confused.map(x=><div key={x.label[l]} className='rounded-xl border border-amber-200 bg-white/70 p-4'><strong className='text-sm text-amber-950'>{x.label[l]}</strong><p className='mt-2 text-sm leading-6 text-amber-950/75'>{x.detail[l]}</p></div>)}</div></article>
    <article className='rounded-2xl border border-rose-200 bg-rose-50 p-6 shadow-sm'><div className='text-xs font-black uppercase tracking-[.16em] text-rose-700'>{tr?'YANLIŞ SEÇİM ÖRNEĞİ':'WRONG-SELECTION EXAMPLE'}</div><h2 className='mt-2 text-2xl font-black'>{tr?'Sahada yapılan tipik hata':'A typical field mistake'}</h2><div className='mt-5 rounded-xl border border-rose-200 bg-white/70 p-4'><strong className='text-sm text-rose-950'>{xp.wrongChoice.scenario[l]}</strong></div><div className='mt-3 rounded-xl border border-rose-200/70 bg-white/60 p-4'><div className='text-[11px] font-black uppercase tracking-[.14em] text-rose-700'>{tr?'Neden sorun?':'Why is this a problem?'}</div><p className='mt-2 text-sm leading-6 text-rose-950/75'>{xp.wrongChoice.why[l]}</p></div><div className='mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4'><div className='text-[11px] font-black uppercase tracking-[.14em] text-emerald-700'>{tr?'Daha doğru yaklaşım':'Better approach'}</div><p className='mt-2 text-sm font-semibold leading-6 text-emerald-950'>{xp.wrongChoice.better[l]}</p></div></article>
   </section>

   <section id='use' className='mt-5 rounded-2xl border border-slate-200 bg-white/95 p-6 shadow-sm md:p-8'><div className='text-xs font-black uppercase tracking-[.16em] text-blue-700'>{tr?'SAHADA NEREDE?':'WHERE IN THE FIELD?'}</div><h2 className='mt-2 text-2xl font-black md:text-3xl'>{tr?'Tipik kullanım alanları':'Typical applications'}</h2><div className='mt-6 grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6'>{d.uses.map((x,i)=><div key={x[l]} className='group relative min-h-40 overflow-hidden rounded-2xl border border-slate-200 bg-slate-900 shadow-sm'><img src={scene(i,700)} alt={`${x[l]} — ${vis.alt[l]}`} className='absolute inset-0 h-full w-full object-cover opacity-75 transition duration-500 group-hover:scale-105'/><div className='absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/45 to-transparent'/><div className='relative flex h-full min-h-40 flex-col justify-end p-4 text-white'><div className='text-[11px] font-black text-white/65'>0{i+1}</div><div className='mt-1 text-sm font-black leading-5'>{x[l]}</div></div></div>)}</div></section>

   <section id='field' className='mt-5 grid gap-4 lg:grid-cols-[.9fr_1.1fr]'>
    <div className='relative overflow-hidden rounded-2xl bg-slate-950 p-7 text-white shadow-xl'><img src={scene(4,900)} alt={vis.alt[l]} className='absolute inset-0 h-full w-full object-cover opacity-20'/><div className='absolute inset-0 bg-gradient-to-br from-slate-950/90 to-slate-950'/><div className='relative'><div className='text-xs font-black uppercase tracking-[.16em] text-emerald-300'>{tr?'SAHA KONTROLÜ':'HSE FIELD CHECK'}</div><h2 className='mt-3 text-3xl font-black'>{tr?'30 saniyelik saha kontrolü':'30-second field check'}</h2><p className='mt-4 text-[15px] leading-7 text-slate-300'>{tr?'Hızlı ön kontrol için kullan. Sertifikasyon, yetkin muayene veya işe özgü risk değerlendirmesinin yerine geçmez.':'Use for quick pre-checks. It does not replace certification, competent inspection or task-specific risk assessment.'}</p><div className='mt-6 grid gap-3'><div className='rounded-xl border border-white/10 bg-white/[.06] p-4'><div className='text-[10px] font-black uppercase tracking-[.14em] text-cyan-300'>{tr?'KONTROL ODAĞI':'CHECK FOCUS'}</div><p className='mt-2 text-sm font-semibold leading-6 text-slate-200'>{d.checks[0]?.[l]}</p></div><div className='rounded-xl border border-rose-300/20 bg-rose-400/[.08] p-4'><div className='text-[10px] font-black uppercase tracking-[.14em] text-rose-300'>{tr?'KRİTİK HATA':'CRITICAL MISTAKE'}</div><p className='mt-2 text-sm font-semibold leading-6 text-slate-200'>{xp.wrongChoice.scenario[l]}</p></div><div className='rounded-xl border border-emerald-300/20 bg-emerald-400/[.08] p-4'><div className='text-[10px] font-black uppercase tracking-[.14em] text-emerald-300'>{tr?'DOĞRU YAKLAŞIM':'BETTER APPROACH'}</div><p className='mt-2 text-sm font-semibold leading-6 text-slate-200'>{xp.wrongChoice.better[l]}</p></div></div></div></div>
    <div className='grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-6'>{d.checks.map((x,i)=><div key={x[l]} className='flex gap-4 rounded-xl border border-slate-100 bg-slate-50 p-4'><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${v.accent} font-black text-white shadow-sm`}>{i+1}</span><p className='pt-1 text-[14px] font-semibold leading-6 text-slate-700'>{x[l]}</p></div>)}</div>
   </section>

   <aside className='mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm leading-6 text-amber-950'><strong>{tr?'Önemli: ':'Important: '}</strong>{tr?'SERNEM bu sayfayı saha referansı olarak sunar. Satın alma veya KKD seçimi öncesinde ürünün güncel standardını, uygunluk işaretlerini, üretici teknik dokümanını ve yerel mevzuatı doğrulayın.':'SERNEM provides this page as a field reference. Before procurement or PPE selection, verify the product’s current standard, conformity markings, manufacturer technical documentation and local legislation.'}</aside>

   <section className='mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8'><div className='text-xs font-black uppercase tracking-[.16em] text-blue-700'>{tr?'İLGİLİ SERNEM KAYNAKLARI':'RELATED SERNEM RESOURCES'}</div><h2 className='mt-2 text-2xl font-black'>{tr?`${s.code} için sonraki adım`:`Next step for ${s.code}`}</h2><div className='mt-5 grid gap-4 md:grid-cols-3'><Link href={`/${l}/knowledge-base/ppe`} className='rounded-2xl border border-slate-200 bg-slate-50 p-6 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-md'><strong>{tr?'KKD ana rehberi →':'PPE master guide →'}</strong><p className='mt-2 text-sm leading-6 text-slate-600'>{tr?'Seçim, kullanım, bakım ve saha kontrol mantığını bağla.':'Connect selection, use, maintenance and field checks.'}</p></Link><Link href={`/${l}/toolbox/${toolboxSlug}`} className='rounded-2xl border border-slate-200 bg-slate-50 p-6 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-md'><strong>{tr?'Bu ürünle ilgili Toolbox →':'Related toolbox talk →'}</strong><p className='mt-2 text-sm leading-6 text-slate-600'>{tr?`${d.product[l]} konusuna doğrudan bağlı saha eğitimini aç.`:`Open field training directly related to ${d.product[l]}.`}</p></Link><Link href={`/${l}/tools/quick-risk-assessment`} className='rounded-2xl border border-slate-200 bg-slate-50 p-6 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-md'><strong>{tr?'Risk analizi oluştur →':'Build a risk assessment →'}</strong><p className='mt-2 text-sm leading-6 text-slate-600'>{tr?'KKD ihtiyacını tehlike ve kontrol tedbirleriyle birlikte değerlendir.':'Assess PPE needs together with hazards and control measures.'}</p></Link></div></section>
  </div>
 </main>;
}