import { buildExpertBlueprint, type ExpertStage } from "./expert-blueprint";

const s=(id:string,titleEn:string,titleTr:string,situationEn:string,situationTr:string,focusEn:string,focusTr:string):ExpertStage=>({id,titleEn,titleTr,situationEn,situationTr,focusEn,focusTr});

const scaffoldLoadModification=buildExpertBlueprint({id:"scaffold-load-modification",titleEn:"Scaffolding: Load Added",titleTr:"İskele: Yük Eklendi",category:"Scaffolding / Structural Change",introEn:"A live scaffold is altered during a maintenance campaign. Material loading, partial dismantling and access changes begin to invalidate the original inspection basis.",introTr:"Bakım kampanyası sırasında kullanılan bir iskele değiştiriliyor. Malzeme yükleme, kısmi söküm ve erişim değişiklikleri ilk kontrol temelini geçersiz hale getirmeye başlıyor.",stages:[
s("load","Material loading increases","Malzeme yükü artıyor","Pipe spools are placed on the working lift although the tag does not state a material-loading allowance.","Etikette malzeme yükleme izni belirtilmemesine rağmen çalışma katına boru spoolları bırakılıyor.","the scaffold design load and actual distributed loading","iskele tasarım yükü ile gerçek dağıtılmış yükü"),
s("board","A board is removed for access","Erişim için kalas sökülüyor","A fitter removes one deck board to route a hose and says it will be replaced before the shift ends.","Bir montajcı hortum geçirmek için bir kalası söküyor ve vardiya bitmeden geri takacağını söylüyor.","platform integrity after unauthorized deck alteration","yetkisiz platform değişikliği sonrası platform bütünlüğünü"),
s("tie","A scaffold tie is obstructing work","İskele bağlantısı işi engelliyor","A wall tie conflicts with equipment installation and the crew proposes removing it temporarily.","Duvar bağlantısı ekipman montajıyla çakışıyor ve ekip geçici olarak sökmeyi öneriyor.","structural stability before any tie removal","herhangi bir bağlantı sökümünden önce yapısal stabiliteyi"),
s("tag","The tag is still green","Etiket hâlâ yeşil","The scaffold tag remains green even though loading and deck configuration have changed since inspection.","Yükleme ve platform düzeni kontrolden sonra değişmiş olmasına rağmen iskele etiketi hâlâ yeşil.","tag validity after configuration change","konfigürasyon değişikliği sonrası etiket geçerliliğini"),
s("access","Access ladder is moved","Erişim merdiveni taşınıyor","The ladder is moved one bay to clear a lifting route, creating a transfer point near an open edge.","Kaldırma güzergahını açmak için merdiven bir aks kaydırılıyor ve açık kenar yakınında geçiş noktası oluşuyor.","safe access geometry and protected landing","güvenli erişim geometrisi ile korumalı çıkış noktasını"),
s("inspection","Inspector is offsite","Kontrolcü sahada değil","The competent scaffold inspector is unavailable for forty minutes while production asks to continue limited work.","Yetkili iskele kontrolcüsü kırk dakika müsait değilken üretim sınırlı işe devam etmek istiyor.","competent reinspection before reuse","yeniden kullanımdan önce yetkili tekrar kontrolünü"),
s("weather","Wind loading increases","Rüzgar yükü artıyor","Temporary sheeting added for weather protection begins acting like a sail during gusts.","Hava koruması için eklenen geçici örtü ani rüzgarlarda yelken gibi davranmaya başlıyor.","temporary sheeting effects on scaffold stability","geçici örtünün iskele stabilitesine etkisini"),
s("handover","Night shift inherits the scaffold","Gece vardiyası iskeleyi devralıyor","The incoming supervisor receives the scaffold tag but not the record of the day's modifications.","Yeni vardiya amiri iskele etiketini alıyor ancak gün içindeki değişiklik kaydını almıyor.","handover of scaffold changes and restrictions","iskele değişiklikleri ve kısıtlarının devir teslimini"),
s("interface","A crane route passes beside the scaffold","Vinç güzergahı iskelenin yanından geçiyor","A mobile crane must slew close to the scaffold and its exclusion zone overlaps the stair access.","Mobil vinç iskelenin yakınına dönmek zorunda ve yasak bölgesi merdiven erişimiyle çakışıyor.","the lifting-scaffold interface and access segregation","kaldırma-iskele arayüzü ile erişim ayrımını"),
s("release","Work wants immediate release","Ekip hemen serbest bırakma istiyor","Loading is reduced and the deck is restored, but several temporary changes occurred during the shift.","Yük azaltıldı ve platform düzeltildi ancak vardiya boyunca birkaç geçici değişiklik yapıldı.","final competent inspection against the restored configuration","düzeltilmiş konfigürasyona göre son yetkili kontrolünü") ]});

const scaffoldSimopsHandover=buildExpertBlueprint({id:"scaffold-simops-handover",titleEn:"Scaffolding: Multi-Contractor Handover",titleTr:"İskele: Çoklu Firma Devir Teslimi",category:"Scaffolding / SIMOPS",introEn:"Three contractors share a large process scaffold during shutdown. Ownership, loading and modifications shift between crews during the day.",introTr:"Shutdown sırasında üç yüklenici büyük bir proses iskelesini paylaşıyor. Gün boyunca sorumluluk, yükleme ve değişiklikler ekipler arasında değişiyor.",stages:[
s("owner","No single scaffold owner is clear","Tek iskele sahibi net değil","Construction, insulation and mechanical teams each believe another contractor controls the scaffold handover.","İnşaat, izolasyon ve mekanik ekiplerinin her biri iskele devrini başka yüklenicinin yönettiğini düşünüyor.","one accountable scaffold owner and handover authority","tek sorumlu iskele sahibi ile devir yetkisini"),
s("zones","Crews occupy different lifts","Ekipler farklı katlarda çalışıyor","Insulators work above mechanics while tools and materials move through the same stair tower.","İzolasyon ekibi mekanik ekibinin üstünde çalışırken alet ve malzemeler aynı merdiven kulesinden taşınıyor.","vertical SIMOPS segregation and dropped-object controls","dikey SIMOPS ayrımı ile düşen cisim kontrollerini"),
s("loadmap","Material locations keep changing","Malzeme konumları sürekli değişiyor","Each contractor stores materials near its workface and no combined loading map exists.","Her yüklenici malzemesini kendi çalışma noktasına bırakıyor ve birleşik yükleme haritası bulunmuyor.","combined scaffold loading across contractors","yükleniciler arası toplam iskele yüklemesini"),
s("alteration","One contractor modifies a guardrail","Bir yüklenici korkuluğu değiştiriyor","A mechanical crew removes a midrail to pass equipment without notifying the scaffold owner.","Mekanik ekip ekipman geçirmek için orta korkuluğu iskele sahibine haber vermeden söküyor.","authorization and restoration of contractor-made alterations","yüklenici değişikliklerinin yetkilendirilmesi ve geri kurulmasını"),
s("tagcopy","Two tag copies disagree","İki etiket kaydı çelişiyor","The physical tag shows today's inspection but the digital register still shows yesterday's restriction.","Fiziksel etiket bugünkü kontrolü gösterirken dijital kayıt dünkü kısıtlamayı gösteriyor.","single verified scaffold status across records","kayıtlar arasında tek doğrulanmış iskele durumunu"),
s("night","Night shift arrives early","Gece vardiyası erken geliyor","Night-shift workers begin staging tools before the formal scaffold handover is complete.","Gece vardiyası çalışanları resmi iskele devri tamamlanmadan alet hazırlamaya başlıyor.","handover completion before new-shift occupation","yeni vardiya kullanmadan önce devir teslimin tamamlanmasını"),
s("rescue","Rescue route is partially blocked","Kurtarma güzergahı kısmen kapanıyor","Temporary ducting narrows the stair tower used in the rescue plan.","Geçici kanal hattı kurtarma planında kullanılan merdiven kulesini daraltıyor.","rescue access after temporary route changes","geçici güzergah değişikliği sonrası kurtarma erişimini"),
s("crane","Lifting starts beside the scaffold","İskele yanında kaldırma başlıyor","A crane lift requires people to leave one side of the scaffold, but one contractor says its task cannot stop.","Vinç kaldırması iskelenin bir tarafının boşaltılmasını gerektiriyor ancak bir yüklenici işinin duramayacağını söylüyor.","shared stop-work authority during overlapping lifting","çakışan kaldırma sırasında ortak işi durdurma yetkisini"),
s("storm","Storm preparation differs by contractor","Fırtına hazırlığı firmalara göre farklı","One crew wants to remove loose sheeting; another wants it retained to protect unfinished insulation.","Bir ekip gevşek örtüyü sökmek isterken diğeri bitmemiş izolasyonu korumak için kalmasını istiyor.","one coordinated weather-response configuration","tek koordineli hava durumu müdahale konfigürasyonunu"),
s("release","Area requests full handback","Alan tam devir istiyor","Contractors report their own tasks complete, but the combined scaffold condition has not been jointly verified.","Yükleniciler kendi işlerinin bittiğini bildiriyor ancak birleşik iskele durumu ortak doğrulanmamış.","joint final handback and configuration verification","ortak son devir ve konfigürasyon doğrulamasını") ]});

const excavationUtilityConflict=buildExpertBlueprint({id:"excavation-utility-conflict",titleEn:"Excavation: Unknown Utility",titleTr:"Kazı: Bilinmeyen Hat",category:"Excavation / Underground Services",introEn:"An excavation permit is valid, but field indications begin to conflict with utility drawings and locator results as digging progresses.",introTr:"Kazı izni geçerli ancak kazı ilerledikçe saha işaretleri, altyapı çizimleri ve dedektör sonuçları birbiriyle çelişmeye başlıyor.",stages:[
s("mark","A locator signal appears outside the drawing","Çizim dışında sinyal alınıyor","The locator shows a linear signal 0.8 m from the mapped cable route.","Hat dedektörü çizimdeki kablo güzergahından 0,8 m uzakta doğrusal sinyal gösteriyor.","the discrepancy between mapped and detected utility position","haritalı ve tespit edilen hat konumu arasındaki çelişkiyi"),
s("records","As-built drawings disagree","As-built çizimler çelişiyor","Two revisions show different routes and neither is clearly marked superseded.","İki revizyon farklı güzergahlar gösteriyor ve hangisinin iptal olduğu net işaretlenmemiş.","authoritative utility record identification","yetkili altyapı kaydının belirlenmesini"),
s("trial","Trial holes show unexpected concrete","Deneme çukuru beklenmeyen beton gösteriyor","Hand digging exposes a concrete encasement not mentioned in the permit pack.","Elle kazı izin paketinde belirtilmeyen beton muhafaza ortaya çıkarıyor.","positive identification before mechanical excavation","mekanik kazıdan önce pozitif hat tanımlamasını"),
s("schedule","Supervisor wants excavator productivity maintained","Amir ekskavatör verimini korumak istiyor","The supervisor proposes moving the machine to the opposite end while the unknown service is investigated.","Amir bilinmeyen hat araştırılırken makineyi kazının diğer ucuna taşımayı öneriyor.","permit boundary validity across the entire excavation footprint","tüm kazı alanı boyunca izin sınırı geçerliliğini"),
s("depth","Expected utility depth is wrong","Beklenen hat derinliği yanlış","A known water line is found 400 mm shallower than the drawing indicates.","Bilinen su hattı çizimde gösterilenden 400 mm daha sığ bulunuyor.","confidence in remaining depth assumptions","kalan derinlik varsayımlarının güvenilirliğini"),
s("owner","Utility owner cannot attend immediately","Hat sahibi hemen gelemiyor","The asset owner can verify the line in two hours; the workfront wants to continue hand digging meanwhile.","Varlık sahibi hattı iki saat sonra doğrulayabiliyor; ekip bu sırada elle kazıya devam etmek istiyor.","utility-owner verification before exposure increases","maruziyet artmadan hat sahibi doğrulamasını"),
s("live","A supposedly dead cable tests ambiguous","Enerjisiz denilen kablo belirsiz test veriyor","A cable identified as abandoned gives an intermittent induced-voltage reading.","Terk edilmiş olarak tanımlanan kablo aralıklı indüklenmiş gerilim ölçümü veriyor.","electrical status and test-method validity","elektriksel durum ile test yöntemi geçerliliğini"),
s("support","Excavation sidewall exposes the service","Kazı yan yüzü hattı açığa çıkarıyor","The service becomes unsupported over a longer span than expected.","Hat beklenenden daha uzun bir açıklıkta desteksiz kalıyor.","temporary support requirements for exposed utilities","açığa çıkan hatlar için geçici destek gereksinimini"),
s("rain","Rain changes soil around the exposed line","Yağmur hat çevresindeki zemini değiştiriyor","Overnight rain softens the trench shoulder near the exposed utility.","Gece yağmuru açığa çıkan hat yakınındaki hendek omzunu yumuşatıyor.","combined ground-stability and utility-support risk","zemin stabilitesi ile hat destek riskinin birleşimini"),
s("resume","Updated mark-out is complete","Güncel işaretleme tamamlandı","New marks and owner confirmation are available, but the excavation permit still references the old drawing revision.","Yeni işaretler ve hat sahibi teyidi hazır ancak kazı izni hâlâ eski çizim revizyonuna referans veriyor.","permit revalidation against corrected utility information","düzeltilmiş altyapı bilgisine göre izin yeniden doğrulamasını") ]});

const excavationAdjacentLoad=buildExpertBlueprint({id:"excavation-adjacent-load",titleEn:"Excavation: Crane Beside the Trench",titleTr:"Kazı: Hendek Yanında Vinç",category:"Excavation / SIMOPS",introEn:"A crane must set equipment beside an active trench. Outrigger reactions, spoil placement and changing ground conditions create a coupled geotechnical and lifting problem.",introTr:"Bir vinç aktif hendeğin yanında ekipman yerleştirecek. Ayak reaksiyonları, hafriyat konumu ve değişen zemin koşulları birleşik geoteknik ve kaldırma problemi oluşturuyor.",stages:[
s("setup","Crane setup moves closer to the trench","Vinç kurulumu hendeğe yaklaşıyor","The planned crane position is blocked, so the operator proposes moving an outrigger 1.5 m toward the trench edge.","Planlanan vinç konumu kapalı olduğu için operatör bir ayağı hendek kenarına 1,5 m yaklaştırmayı öneriyor.","outrigger setback versus trench influence zone","vinç ayağı mesafesi ile hendek etki bölgesini"),
s("bearing","Ground bearing data is incomplete","Zemin taşıma verisi eksik","The lift plan uses general site bearing capacity, not the recently backfilled strip beside the trench.","Kaldırma planı hendek yanındaki yeni dolgu yerine genel saha taşıma kapasitesini kullanıyor.","local bearing capacity under actual outrigger reactions","gerçek vinç ayağı reaksiyonları altında yerel taşıma kapasitesini"),
s("spoil","Spoil pile grows near the edge","Hafriyat yığını kenarda büyüyor","Excavated material is temporarily stacked on the same side where the crane will set up.","Kazı malzemesi geçici olarak vincin kurulacağı tarafta istifleniyor.","combined surcharge from spoil and crane loading","hafriyat ve vinç yükünün birleşik sürşarjını"),
s("water","Seepage appears in the trench","Hendekte sızıntı görülüyor","Water begins entering at the toe of the trench wall closest to the crane position.","Vinç konumuna en yakın hendek ayağında su girişi başlıyor.","ground degradation from seepage before applying crane load","vinç yükü uygulanmadan önce sızıntı kaynaklı zemin bozulmasını"),
s("people","Excavation crew wants to remain inside","Kazı ekibi içeride kalmak istiyor","The trench crew says they can shelter at the far end while the crane slews overhead outside the trench.","Hendek ekibi vinç dışarıdan dönerken uzak uçta kalabileceklerini söylüyor.","personnel exclusion during crane loading beside excavation","kazı yanında vinç yüklemesi sırasında personel yasak bölgesini"),
s("mat","Larger mats are offered","Daha büyük takozlar öneriliyor","The crane team offers larger outrigger mats but no recalculation of trench stability.","Vinç ekibi daha büyük ayak takozları öneriyor ancak hendek stabilitesi yeniden hesaplanmıyor.","whether load spreading actually resolves slope influence","yük yaymanın şev etkisini gerçekten çözüp çözmediğini"),
s("radius","Lift radius increases during trial","Deneme sırasında yarıçap artıyor","A trial slew shows the load must be placed farther away than the approved lift radius.","Deneme dönüşü yükün onaylı yarıçaptan daha uzağa bırakılması gerektiğini gösteriyor.","revised crane reactions at increased radius","artan yarıçapta değişen vinç reaksiyonlarını"),
s("vibration","Compactor starts nearby","Yakında kompaktör çalışıyor","Another crew begins compaction behind the trench while the crane is being prepared.","Başka bir ekip vinç hazırlanırken hendeğin arkasında sıkıştırma başlatıyor.","vibration and surcharge effects on trench stability","titreşim ve sürşarjın hendek stabilitesine etkisini"),
s("inspection","Trench inspection predates crane setup","Hendek kontrolü vinç kurulumundan önce yapılmış","The competent-person trench inspection was completed before mats, spoil and access arrangements changed.","Yetkili kişi hendek kontrolünü takozlar, hafriyat ve erişim düzeni değişmeden önce tamamlamış.","competent reinspection after loading conditions change","yükleme koşulları değiştikten sonra yetkili tekrar kontrolünü"),
s("release","Both teams report ready","İki ekip de hazır olduğunu bildiriyor","Crane and excavation supervisors each sign their own permits but no joint interface release has occurred.","Vinç ve kazı amirleri kendi izinlerini imzalıyor ancak ortak arayüz serbest bırakması yapılmamış.","joint SIMOPS release across lifting and excavation controls","kaldırma ve kazı kontrolleri için ortak SIMOPS serbest bırakmasını") ]});

const liftingPlanDeviation=buildExpertBlueprint({id:"lifting-plan-deviation",titleEn:"Lifting: Plan No Longer Fits",titleTr:"Kaldırma: Plan Artık Uymuyor",category:"Lifting Operations",introEn:"A planned lift develops several small deviations: rigging, radius, wind and landing conditions all change while the team argues the lift remains within capacity.",introTr:"Planlı kaldırmada birkaç küçük sapma oluşuyor: sapan düzeni, yarıçap, rüzgar ve indirme koşulları değişirken ekip kaldırmanın hâlâ kapasite içinde olduğunu savunuyor.",stages:[
s("rigging","Specified sling is unavailable","Belirlenen sapan yok","The planned 6 m slings are unavailable and the rigger proposes shorter slings with a different angle.","Planlanan 6 m sapanlar yok ve sapancı farklı açılı daha kısa sapan öneriyor.","rigging geometry and resulting leg tension","sapan geometrisi ile oluşan kol gerilimini"),
s("cog","Load centre of gravity is uncertain","Yük ağırlık merkezi belirsiz","A temporary component remains attached, shifting the expected centre of gravity.","Geçici bir parça bağlı kaldığı için beklenen ağırlık merkezi değişiyor.","verified centre of gravity before lifting clear","yükü kaldırmadan önce doğrulanmış ağırlık merkezini"),
s("radius","Crane cannot reach planned setup","Vinç planlanan kurulumdan ulaşamıyor","Barricades force the crane two metres farther from the pick point.","Bariyerler vinci kaldırma noktasından iki metre daha uzağa kurmaya zorluyor.","capacity and outrigger reactions at the revised radius","değişen yarıçapta kapasite ve ayak reaksiyonlarını"),
s("wind","Wind approaches the planning limit","Rüzgar plan limitine yaklaşıyor","Average wind is acceptable but gusts intermittently exceed the planning value used for the load area.","Ortalama rüzgar uygun ancak ani esintiler yük alanı için kullanılan plan değerini aralıklı aşıyor.","gust criteria for the actual load sail area","gerçek yük yüzey alanı için ani rüzgar kriterini"),
s("tagline","Tag-line route is obstructed","Yönlendirme halatı güzergahı kapalı","The planned tag-line handler position is occupied by temporary pipework.","Planlanan yönlendirme halatı operatör pozisyonu geçici borulama ile kapalı.","safe load-control positions outside line of fire","ateş hattı dışında güvenli yük kontrol pozisyonlarını"),
s("landing","Landing area is not level","İndirme alanı düz değil","The receiving skid has settled and one side is 40 mm lower than the drawing assumption.","Kabul kızağı oturmuş ve bir taraf çizim varsayımından 40 mm daha düşük.","landing stability before load release","yük bırakılmadan önce indirme stabilitesini"),
s("signal","Backup signaler joins","Yedek işaretçi katılıyor","The primary signaler is moved to another lift and a qualified backup takes over without a full briefing.","Ana işaretçi başka kaldırmaya alınır ve yetkili yedek tam bilgilendirme olmadan devralır.","command protocol after signaler change","işaretçi değişimi sonrası komuta protokolünü"),
s("trial","Trial lift shows unexpected tilt","Deneme kaldırması beklenmeyen eğim gösteriyor","At 100 mm clear, the load hangs with a visible tilt not predicted by the plan.","Yük 100 mm kaldırıldığında planda öngörülmeyen belirgin eğimle asılı kalıyor.","trial-lift feedback and rigging reassessment","deneme kaldırması geri bildirimi ile sapan yeniden değerlendirmesini"),
s("pressure","Production asks to continue slowly","Üretim yavaşça devam etmeyi istiyor","The supervisor argues the crane has plenty of spare capacity despite the deviations.","Amir sapmalara rağmen vincin yeterli kapasite payı olduğunu savunuyor.","lift-plan validity beyond simple crane capacity","yalnızca vinç kapasitesinin ötesinde kaldırma planı geçerliliğini"),
s("release","Revised controls are agreed","Güncellenen kontroller kabul edildi","Rigging and setup are corrected, but the original lift plan has not yet been formally reissued.","Sapan ve kurulum düzeltildi ancak ilk kaldırma planı henüz resmi olarak yeniden yayımlanmadı.","formal authorization of the revised lift plan","güncellenmiş kaldırma planının resmi yetkilendirmesini") ]});

const liftingTandemCritical=buildExpertBlueprint({id:"lifting-tandem-critical",titleEn:"Lifting: Tandem Critical Lift",titleTr:"Kaldırma: Tandem Kritik Kaldırma",category:"Critical Lifting",introEn:"Two cranes must rotate and transfer a long vessel into position. Small differences in radius, communication and load share can rapidly overload one crane.",introTr:"İki vinç uzun bir ekipmanı döndürüp yerine aktaracak. Yarıçap, iletişim ve yük paylaşımındaki küçük farklar bir vinci hızla aşırı yükleyebilir.",stages:[
s("loadshare","Calculated load share changes","Hesaplanan yük paylaşımı değişiyor","The tail crane starts at a slightly larger radius than the engineered plan.","Kuyruk vinci mühendislik planından biraz daha büyük yarıçapta başlıyor.","engineered load-share calculation at actual radii","gerçek yarıçaplarda mühendislik yük paylaşımı hesabını"),
s("sync","Crane motions are not synchronized","Vinç hareketleri senkron değil","One operator responds slower to radio commands during the rehearsal.","Prova sırasında bir operatör telsiz komutlarına daha geç tepki veriyor.","synchronized command-and-response protocol","senkron komuta ve yanıt protokolünü"),
s("comms","Radio channel becomes congested","Telsiz kanalı yoğunlaşıyor","Other site traffic is heard on the same radio channel used by the lift director.","Kaldırma direktörünün kullandığı aynı kanalda başka saha trafiği duyuluyor.","dedicated critical-lift communications","kritik kaldırma için özel iletişimi"),
s("wind","Crosswind increases","Yan rüzgar artıyor","Crosswind rises during the rotation phase and affects the vessel tail.","Döndürme aşamasında yan rüzgar artıyor ve ekipmanın kuyruğunu etkiliyor.","wind effects during tandem rotation","tandem döndürme sırasında rüzgar etkilerini"),
s("radius2","Lead crane radius changes","Ana vincin yarıçapı değişiyor","A barricade prevents the lead crane from slewing through the planned path.","Bir bariyer ana vincin planlanan dönüş yolunu kullanmasını engelliyor.","recalculated tandem geometry after path change","güzergah değişimi sonrası yeniden hesaplanan tandem geometrisini"),
s("transfer","Load transfer starts unevenly","Yük transferi dengesiz başlıyor","Load cells show the receiving crane taking weight faster than planned.","Yük hücreleri alıcı vincin yükü planlanandan daha hızlı aldığını gösteriyor.","controlled load-transfer rate and live load-share data","kontrollü yük transfer hızı ile canlı yük paylaşım verisini"),
s("signal","A second supervisor gives hand signals","İkinci amir el işareti veriyor","A contractor supervisor begins signaling one operator directly to speed alignment.","Bir yüklenici amiri hizalamayı hızlandırmak için bir operatöre doğrudan işaret vermeye başlıyor.","single command authority during critical lifting","kritik kaldırmada tek komuta yetkisini"),
s("ground","One outrigger mat settles","Bir ayak takozu oturuyor","The tail crane mat settles visibly during the hold point.","Bekleme noktasında kuyruk vincin ayak takozu gözle görülür şekilde oturuyor.","ground response before resuming tandem loading","tandem yüklemeye dönmeden önce zemin tepkisini"),
s("landing","Landing orientation is off","İndirme yönü sapmış","The vessel is 150 mm out of orientation and requires another coordinated rotation.","Ekipman yönünden 150 mm sapmış ve yeni koordineli döndürme gerekiyor.","replanned final rotation rather than improvised correction","doğaçlama düzeltme yerine yeniden planlanan son döndürmeyi"),
s("completion","Pressure rises to land immediately","Hemen indirme baskısı artıyor","Both cranes are holding load near planned limits while the team asks to complete without another engineering check.","Her iki vinç plan limitlerine yakın yük tutarken ekip yeni mühendislik kontrolü olmadan tamamlamak istiyor.","final engineered confirmation before the last tandem transfer","son tandem transfer öncesi son mühendislik doğrulamasını") ]});

const electricalInducedVoltage=buildExpertBlueprint({id:"electrical-induced-voltage",titleEn:"Electrical: Voltage Returns",titleTr:"Elektrik: Gerilim Geri Dönüyor",category:"Electrical Safety",introEn:"An isolated circuit repeatedly shows low voltage after proving dead. The team must distinguish induced voltage, backfeed and test-method limitations before touching conductors.",introTr:"İzole edilmiş bir devre enerjisiz doğrulamadan sonra tekrar düşük gerilim gösteriyor. Ekip iletkenlere dokunmadan indüklenmiş gerilim, geri besleme ve test yöntemi sınırlarını ayırmalı.",stages:[
s("prove","Voltage reappears after proving dead","Enerjisiz doğrulama sonrası gerilim geri geliyor","A previously zero conductor measures 38 V ten minutes later.","Daha önce sıfır ölçülen iletkende on dakika sonra 38 V görülüyor.","source identification for the reappearing voltage","geri gelen gerilimin kaynak tanımlamasını"),
s("tester","Two testers disagree","İki test cihazı farklı gösteriyor","A high-impedance meter reads voltage while a proving unit behaves differently.","Yüksek empedanslı ölçü aleti gerilim gösterirken doğrulama cihazı farklı davranıyor.","test instrument suitability and proving method","test cihazı uygunluğu ile doğrulama yöntemini"),
s("parallel","Parallel energized cables run nearby","Yakında enerjili paralel kablolar var","The isolated cable shares a tray with loaded feeders for 70 metres.","İzole kablo 70 metre boyunca yüklü besleyicilerle aynı tavayı paylaşıyor.","induced-voltage potential from parallel circuits","paralel devrelerden indüklenmiş gerilim potansiyelini"),
s("backfeed","A UPS connection is discovered","UPS bağlantısı bulunuyor","A local UPS drawing shows a possible alternate feed not listed on the isolation sheet.","Yerel UPS çizimi izolasyon formunda olmayan olası alternatif beslemeyi gösteriyor.","all alternate energy sources and backfeed paths","tüm alternatif enerji kaynakları ile geri besleme yollarını"),
s("earth","Temporary earth is proposed","Geçici topraklama öneriliyor","The electrician proposes applying temporary earths before the source is fully understood.","Elektrikçi kaynak tam anlaşılmadan geçici topraklama uygulamayı öneriyor.","safe earthing sequence after source assessment","kaynak değerlendirmesi sonrası güvenli topraklama sırasını"),
s("remote","Remote operator reports breaker open","Uzak operatör kesicinin açık olduğunu söylüyor","Control room status confirms open, but no local visible break is available.","Kontrol odası durumu açık gösteriyor ancak yerelde görünür ayırma yok.","independent isolation verification beyond remote indication","uzak gösterimin ötesinde bağımsız izolasyon doğrulamasını"),
s("permit","Permit still says dead work","İzin hâlâ enerjisiz çalışma diyor","The permit classification has not been changed despite recurring voltage readings.","Tekrarlayan gerilim ölçümlerine rağmen izin sınıfı değiştirilmemiş.","permit basis after electrical condition changes","elektriksel koşul değişimi sonrası izin temelini"),
s("touch","Mechanic asks to disconnect a terminal","Mekanikçi terminal ayırmak istiyor","A mechanic wants to proceed because the measured voltage is below the site's nominal hazardous-voltage threshold.","Mekanikçi ölçülen gerilim saha nominal tehlikeli gerilim eşiğinin altında olduğu için devam etmek istiyor.","test-before-touch and uncertainty rather than nominal threshold alone","yalnızca nominal eşik yerine dokunmadan önce test ve belirsizliği"),
s("bond","Bonding changes the reading","Bonding ölçümü değiştiriyor","A temporary bond reduces the measured voltage substantially but the source remains uncertain.","Geçici bağlama ölçülen gerilimi ciddi düşürüyor ancak kaynak hâlâ belirsiz.","cause verification rather than symptom suppression","belirtiyi bastırmak yerine neden doğrulamasını"),
s("release","Stable zero is achieved","Stabil sıfır sağlanıyor","After tracing the UPS and applying approved isolation, repeated tests show zero.","UPS izi bulunup onaylı izolasyon uygulandıktan sonra tekrarlı testler sıfır gösteriyor.","full re-proving and permit revalidation before touch","dokunmadan önce tam yeniden doğrulama ve izin yenilemeyi") ]});

const electricalSwitchingConflict=buildExpertBlueprint({id:"electrical-switching-conflict",titleEn:"Electrical: Switching Conflict",titleTr:"Elektrik: Manevra Çatışması",category:"Electrical / Switching",introEn:"A network restoration involves remote switching, local permits and two operating authorities. Conflicting status information appears during restoration pressure.",introTr:"Şebeke geri alma işlemi uzaktan manevra, yerel izinler ve iki işletme yetkilisini içeriyor. Devreye alma baskısı sırasında çelişkili durum bilgileri ortaya çıkıyor.",stages:[
s("schedule","Switching schedule versions differ","Manevra programı sürümleri farklı","Control room and field team hold different revisions of the switching schedule.","Kontrol odası ve saha ekibinde manevra programının farklı revizyonları bulunuyor.","one authoritative switching schedule revision","tek yetkili manevra programı revizyonunu"),
s("remote","Remote indication conflicts with local position","Uzak gösterim yerel konumla çelişiyor","SCADA shows open while the local mechanical indicator appears intermediate.","SCADA açık gösterirken yerel mekanik gösterge ara konumda görünüyor.","verified device position before subsequent switching","sonraki manevra öncesi doğrulanmış ekipman konumunu"),
s("permit","A work permit remains active","Bir çalışma izni hâlâ aktif","One feeder scheduled for restoration still has an open maintenance permit in another area.","Devreye alınacak besleyicinin başka bölgede açık bakım izni bulunuyor.","permit clearance across the entire energization boundary","tüm enerjilendirme sınırında izin kapanışını"),
s("authority","Two operators issue instructions","İki operatör talimat veriyor","Grid control and site electrical control both give sequence instructions to the switching person.","Şebeke kontrol ve saha elektrik kontrolü manevra görevlisine sıra talimatı veriyor.","single switching authority and command hierarchy","tek manevra yetkisi ile komuta hiyerarşisini"),
s("comms","Radio communication drops","Telsiz iletişimi kesiliyor","The switching person loses radio contact immediately after opening an isolator.","Manevra görevlisi ayırıcıyı açtıktan hemen sonra telsiz bağlantısını kaybediyor.","communication requirements before continuing the sequence","manevra dizisine devamdan önce iletişim gereksinimini"),
s("earth","Earth switch status is uncertain","Toprak ayırıcısı durumu belirsiz","The mimic diagram shows earth removed, but the field key interlock has not been returned.","Mimik diyagram topraklamayı kaldırılmış gösteriyor ancak saha anahtar kilidi geri dönmemiş.","positive earth-switch status before energization","enerjilendirme öncesi pozitif toprak ayırıcısı durumunu"),
s("test","Protection test is still in progress","Koruma testi hâlâ sürüyor","Protection engineers request five more minutes while operations wants the feeder energized.","Koruma ekibi beş dakika daha isterken operasyon besleyicinin enerjilendirilmesini istiyor.","completion and release of protection testing","koruma testinin tamamlanması ve serbest bırakılmasını"),
s("sync","Synchronization conditions drift","Senkron koşulları değişiyor","Voltage and phase values move outside the planned window during a delay.","Gecikme sırasında gerilim ve faz değerleri planlanan pencerenin dışına çıkıyor.","fresh synchronization criteria at the actual closing time","gerçek kapama anında güncel senkron kriterini"),
s("pressure","Operations requests one-step bypass","Operasyon bir adımı atlamayı istiyor","A supervisor suggests skipping a verification step because the equipment was checked earlier.","Amir ekipman daha önce kontrol edildiği için bir doğrulama adımının atlanmasını öneriyor.","procedural hold points under restoration pressure","devreye alma baskısında prosedürel bekleme noktalarını"),
s("close","Final breaker close is ready","Son kesici kapama hazır","All major issues are resolved, but field and control-room logs have not yet been reconciled.","Ana sorunlar çözüldü ancak saha ve kontrol odası kayıtları henüz uzlaştırılmadı.","final status reconciliation before energization","enerjilendirme öncesi son durum uzlaştırmasını") ]});

export const expertPackTwo={
 [scaffoldLoadModification.id]:scaffoldLoadModification,
 [scaffoldSimopsHandover.id]:scaffoldSimopsHandover,
 [excavationUtilityConflict.id]:excavationUtilityConflict,
 [excavationAdjacentLoad.id]:excavationAdjacentLoad,
 [liftingPlanDeviation.id]:liftingPlanDeviation,
 [liftingTandemCritical.id]:liftingTandemCritical,
 [electricalInducedVoltage.id]:electricalInducedVoltage,
 [electricalSwitchingConflict.id]:electricalSwitchingConflict,
};
