import { buildExpertBlueprint } from "./expert-blueprint";

const liftingBlindZone = buildExpertBlueprint({
  id:"lifting-blind-zone", titleEn:"Lifting: The Blind Zone", titleTr:"Kaldırma: Kör Nokta", category:"Lifting Operations",
  introEn:"A routine lift becomes progressively less routine as visibility, route control and suspended-load interfaces change.", introTr:"Rutin bir kaldırma; görüş, güzergah kontrolü ve askıdaki yük arayüzleri değiştikçe giderek karmaşıklaşıyor.",
  stages:[
    {id:"blind",titleEn:"The load enters a blind zone",titleTr:"Yük kör noktaya giriyor",situationEn:"The operator will lose direct sight of the load for the final part of the travel.",situationTr:"Operatör hareketin son bölümünde yükü doğrudan göremeyecek.",focusEn:"blind-lift communication and signaler control",focusTr:"kör kaldırmada iletişim ve işaretçi kontrolünü"},
    {id:"signaler",titleEn:"Two signalers are visible",titleTr:"İki işaretçi görünür durumda",situationEn:"A second contractor signaler begins giving hand signals near the route.",situationTr:"Başka bir yüklenicinin işaretçisi güzergah yakınında el işareti vermeye başlıyor.",focusEn:"single-point command authority for the lift",focusTr:"kaldırma için tek komuta yetkisini"},
    {id:"exclusion",titleEn:"The exclusion zone is breached",titleTr:"Yasak bölge ihlal ediliyor",situationEn:"A worker enters the landing area to move loose materials before the load arrives.",situationTr:"Bir çalışan yük gelmeden önce gevşek malzemeleri taşımak için indirme alanına giriyor.",focusEn:"exclusion-zone integrity",focusTr:"yasak bölgenin bütünlüğünü"},
    {id:"tagline",titleEn:"The tag line snags",titleTr:"Yönlendirme halatı takılıyor",situationEn:"The tag line catches on temporary steelwork while the load is suspended.",situationTr:"Yük askıdayken yönlendirme halatı geçici çelik yapıya takılıyor.",focusEn:"safe control of the suspended load and tag line",focusTr:"askıdaki yükün ve yönlendirme halatının güvenli kontrolünü"},
    {id:"wind",titleEn:"Wind becomes variable",titleTr:"Rüzgar değişkenleşiyor",situationEn:"Wind remains below the nominal limit but starts rotating the load intermittently.",situationTr:"Rüzgar nominal limitin altında ancak yükü aralıklı döndürmeye başlıyor.",focusEn:"dynamic wind effects on load control",focusTr:"rüzgarın yük kontrolündeki dinamik etkilerini"},
    {id:"route",titleEn:"The travel route changes",titleTr:"Yük güzergahı değişiyor",situationEn:"A parked vehicle blocks the planned route and the team proposes a tighter swing path.",situationTr:"Park edilmiş bir araç planlanan güzergahı kapatıyor ve ekip daha dar bir dönüş yolu öneriyor.",focusEn:"lift-plan validity after route change",focusTr:"güzergah değişikliği sonrası kaldırma planı geçerliliğini"},
    {id:"landing",titleEn:"The landing area is not level",titleTr:"İndirme alanı düz değil",situationEn:"The prepared landing point has shifted and one support is now partially obstructed.",situationTr:"Hazırlanan indirme noktası değişmiş ve bir destek kısmen engellenmiş.",focusEn:"verified landing-area readiness",focusTr:"indirme alanı hazırlığının doğrulanmasını"},
    {id:"radio",titleEn:"Radio communication becomes intermittent",titleTr:"Telsiz iletişimi kesintili oluyor",situationEn:"The operator reports broken radio transmissions while the load is still suspended.",situationTr:"Yük askıdayken operatör telsiz konuşmalarının kesildiğini bildiriyor.",focusEn:"reliable communication before continued movement",focusTr:"harekete devam etmeden güvenilir iletişimi"},
    {id:"release",titleEn:"The final set-down is requested quickly",titleTr:"Son indirme hızlandırılmak isteniyor",situationEn:"Production asks for immediate set-down before another vehicle reaches the area.",situationTr:"Üretim başka bir araç alana gelmeden yükün hemen indirilmesini istiyor.",focusEn:"controlled final placement without schedule pressure",focusTr:"program baskısı olmadan kontrollü son yerleştirmeyi"},
  ],
});

const electricalBackfeed = buildExpertBlueprint({
  id:"electrical-backfeed", titleEn:"Electrical: Backfeed Detected", titleTr:"Elektrik: Geri Besleme Tespit Edildi", category:"Electrical Safety",
  introEn:"An isolated electrical system shows unexpected voltage during test-before-touch verification.", introTr:"İzole edilmiş bir elektrik sisteminde dokunmadan önce test sırasında beklenmeyen gerilim görülüyor.",
  stages:[
    {id:"voltage",titleEn:"Voltage is detected after isolation",titleTr:"İzolasyon sonrası gerilim tespit ediliyor",situationEn:"A proving test identifies voltage on a conductor expected to be dead.",situationTr:"Doğrulama testi enerjisiz olması beklenen iletkende gerilim tespit ediyor.",focusEn:"test-before-touch and unexpected energization",focusTr:"dokunmadan önce test ve beklenmeyen enerjilenmeyi"},
    {id:"source",titleEn:"The source is unclear",titleTr:"Kaynak belirsiz",situationEn:"The single-line diagram shows more than one possible auxiliary feed.",situationTr:"Tek hat şeması birden fazla olası yardımcı besleme gösteriyor.",focusEn:"identification of every possible energy source",focusTr:"tüm olası enerji kaynaklarının tanımlanmasını"},
    {id:"generator",titleEn:"A temporary generator is connected",titleTr:"Geçici jeneratör bağlı",situationEn:"A temporary generator installed for commissioning is tied into the same distribution section.",situationTr:"Devreye alma için kurulan geçici jeneratör aynı dağıtım bölümüne bağlı.",focusEn:"temporary-source isolation and backfeed prevention",focusTr:"geçici kaynak izolasyonu ve geri besleme önlemeyi"},
    {id:"ups",titleEn:"UPS supply remains available",titleTr:"UPS beslemesi mevcut",situationEn:"Control circuits remain supported by a UPS not listed on the original isolation sheet.",situationTr:"Kontrol devreleri orijinal izolasyon formunda yer almayan UPS tarafından beslenmeye devam ediyor.",focusEn:"secondary and stored electrical energy",focusTr:"ikincil ve depolanmış elektrik enerjisini"},
    {id:"label",titleEn:"Panel labeling conflicts with drawings",titleTr:"Pano etiketleri çizimlerle çelişiyor",situationEn:"Field labels do not fully match the latest issued drawing revision.",situationTr:"Saha etiketleri son yayımlanan çizim revizyonuyla tamamen eşleşmiyor.",focusEn:"positive equipment identification",focusTr:"ekipmanın pozitif tanımlanmasını"},
    {id:"earth",titleEn:"Temporary earthing is questioned",titleTr:"Geçici topraklama sorgulanıyor",situationEn:"The team proposes relying on isolation alone because the task is short.",situationTr:"Ekip iş kısa olduğu için yalnızca izolasyona güvenmeyi öneriyor.",focusEn:"required protective earthing and discharge controls",focusTr:"gerekli koruyucu topraklama ve deşarj kontrollerini"},
    {id:"handover",titleEn:"Shift handover occurs",titleTr:"Vardiya devri gerçekleşiyor",situationEn:"The incoming authorized person did not witness the original isolation or voltage finding.",situationTr:"Yeni yetkili kişi orijinal izolasyonu veya gerilim bulgusunu görmedi.",focusEn:"electrical-isolation handover and accountability",focusTr:"elektrik izolasyonu devri ve sorumluluğunu"},
    {id:"retest",titleEn:"Voltage is now absent",titleTr:"Gerilim artık yok",situationEn:"After source corrections, repeat testing shows zero voltage.",situationTr:"Kaynak düzeltmelerinden sonra tekrar test sıfır gerilim gösteriyor.",focusEn:"verified de-energization before contact",focusTr:"temas öncesi doğrulanmış enerjisizliği"},
    {id:"restore",titleEn:"Restoration pressure starts",titleTr:"Enerjilendirme baskısı başlıyor",situationEn:"Operations asks to restore power before the isolation review is fully closed.",situationTr:"Operasyon izolasyon incelemesi tamamen kapanmadan enerjinin geri verilmesini istiyor.",focusEn:"controlled restoration and formal isolation closure",focusTr:"kontrollü enerjilendirme ve resmi izolasyon kapanışını"},
  ],
});

const chemicalReleaseWind = buildExpertBlueprint({
  id:"chemical-release-wind", titleEn:"Chemical Release: Wind Shift", titleTr:"Kimyasal Salım: Rüzgar Değişti", category:"Chemical / Process Safety",
  introEn:"A minor chemical release changes direction as wind and worksite occupancy shift.", introTr:"Küçük bir kimyasal salım, rüzgar ve saha doluluğu değiştikçe yön değiştiriyor.",
  stages:[
    {id:"release",titleEn:"A release is reported",titleTr:"Salım bildiriliyor",situationEn:"Operators report a small vapor release with no confirmed exposure.",situationTr:"Operatörler doğrulanmış maruziyet olmadan küçük bir buhar salımı bildiriyor.",focusEn:"release recognition and immediate area control",focusTr:"salımın tanınması ve ilk alan kontrolünü"},
    {id:"wind",titleEn:"Wind direction shifts",titleTr:"Rüzgar yönü değişiyor",situationEn:"The wind sock turns toward an occupied contractor workfront.",situationTr:"Rüzgar tulumu çalışanların bulunduğu taşeron çalışma alanına dönüyor.",focusEn:"plume direction and downwind exposure",focusTr:"yayılım yönü ve rüzgar altı maruziyetini"},
    {id:"identity",titleEn:"Substance identity is not fully confirmed",titleTr:"Madde kimliği tam doğrulanmamış",situationEn:"Two process streams could plausibly be involved.",situationTr:"İki proses akışının da olaya dahil olması mümkün.",focusEn:"chemical identification before PPE or response decisions",focusTr:"KKD veya müdahale kararı öncesi kimyasal tanımlamayı"},
    {id:"ppe",titleEn:"Workers request respiratory protection",titleTr:"Çalışanlar solunum koruması istiyor",situationEn:"A crew asks whether escape masks are enough to finish a nearby task.",situationTr:"Bir ekip yakındaki işi bitirmek için kaçış maskelerinin yeterli olup olmadığını soruyor.",focusEn:"PPE limitations versus source and exposure control",focusTr:"kaynak ve maruziyet kontrolüne karşı KKD sınırlarını"},
    {id:"muster",titleEn:"One route is now downwind",titleTr:"Bir toplanma güzergahı rüzgar altında",situationEn:"The normal evacuation route now crosses the projected plume path.",situationTr:"Normal tahliye güzergahı artık tahmini yayılım hattını kesiyor.",focusEn:"safe evacuation routing under changing wind",focusTr:"değişen rüzgarda güvenli tahliye güzergahını"},
    {id:"monitor",titleEn:"Portable readings disagree",titleTr:"Portatif ölçümler uyuşmuyor",situationEn:"Two instruments show different concentrations at the boundary.",situationTr:"İki cihaz sınırda farklı konsantrasyonlar gösteriyor.",focusEn:"instrument verification and conservative exposure assessment",focusTr:"cihaz doğrulaması ve muhafazakâr maruziyet değerlendirmesini"},
    {id:"isolate",titleEn:"Source isolation is available",titleTr:"Kaynak izolasyonu mümkün",situationEn:"Operations can isolate the suspected source but it will affect production.",situationTr:"Operasyon şüpheli kaynağı izole edebilir ancak üretim etkilenecek.",focusEn:"source control over production continuity",focusTr:"üretim devamlılığına karşı kaynak kontrolünü"},
    {id:"allclear",titleEn:"Readings begin to fall",titleTr:"Ölçümler düşmeye başlıyor",situationEn:"Concentrations decrease after isolation but remain detectable at one boundary point.",situationTr:"İzolasyon sonrası konsantrasyonlar düşüyor ancak bir sınır noktasında hâlâ ölçülebiliyor.",focusEn:"evidence-based all-clear criteria",focusTr:"kanıta dayalı tehlike geçti kriterlerini"},
    {id:"return",titleEn:"Teams request re-entry",titleTr:"Ekipler alana dönmek istiyor",situationEn:"Contractors ask to resume work as soon as the alarm is reset.",situationTr:"Taşeronlar alarm resetlenir resetlenmez işe dönmek istiyor.",focusEn:"controlled re-entry after atmospheric release",focusTr:"atmosferik salım sonrası kontrollü yeniden girişi"},
  ],
});

const mobileReversing = buildExpertBlueprint({
  id:"mobile-equipment-reversing", titleEn:"Mobile Equipment: Reversing Conflict", titleTr:"Hareketli Ekipman: Geri Manevra Çatışması", category:"Mobile Equipment / Traffic",
  introEn:"A reversing operation develops multiple pedestrian and visibility conflicts in a busy workfront.", introTr:"Geri manevra operasyonu yoğun çalışma alanında birden fazla yaya ve görüş çatışması oluşturuyor.",
  stages:[
    {id:"reverse",titleEn:"The reversing route is busy",titleTr:"Geri manevra güzergahı yoğun",situationEn:"Pedestrians are using a temporary crossing near the vehicle route.",situationTr:"Yayalar araç güzergahı yakınındaki geçici geçidi kullanıyor.",focusEn:"pedestrian-vehicle segregation",focusTr:"yaya-araç ayrımını"},
    {id:"spotter",titleEn:"The spotter changes position",titleTr:"İşaretçi konum değiştiriyor",situationEn:"The driver temporarily loses sight of the designated spotter.",situationTr:"Sürücü belirlenmiş işaretçiyi geçici olarak göremiyor.",focusEn:"continuous spotter visibility and command",focusTr:"sürekli işaretçi görüşü ve komutasını"},
    {id:"alarm",titleEn:"The reversing alarm is hard to hear",titleTr:"Geri vites alarmı zor duyuluyor",situationEn:"Nearby grinding and plant noise masks the audible alarm.",situationTr:"Yakındaki taşlama ve ekipman gürültüsü sesli alarmı bastırıyor.",focusEn:"effective warning under high ambient noise",focusTr:"yüksek çevre gürültüsünde etkili uyarıyı"},
    {id:"blind",titleEn:"A blind corner develops",titleTr:"Kör köşe oluşuyor",situationEn:"Stored materials now block the driver's view of part of the route.",situationTr:"Depolanan malzemeler artık sürücünün güzergahın bir bölümünü görmesini engelliyor.",focusEn:"visibility and blind-spot control",focusTr:"görüş ve kör nokta kontrolünü"},
    {id:"delivery",titleEn:"Another delivery arrives",titleTr:"Başka bir teslimat geliyor",situationEn:"A second truck enters the same workfront earlier than planned.",situationTr:"İkinci kamyon planlanandan erken aynı çalışma alanına giriyor.",focusEn:"traffic coordination between simultaneous vehicle movements",focusTr:"eş zamanlı araç hareketleri arasında trafik koordinasyonunu"},
    {id:"route",titleEn:"The planned route is blocked",titleTr:"Planlanan güzergah kapalı",situationEn:"The team proposes a shorter temporary route beside active workers.",situationTr:"Ekip aktif çalışanların yanından geçen daha kısa geçici güzergah öneriyor.",focusEn:"route-change risk assessment",focusTr:"güzergah değişikliği risk değerlendirmesini"},
    {id:"light",titleEn:"Visibility deteriorates",titleTr:"Görüş kötüleşiyor",situationEn:"Temporary lighting fails on part of the reversing path.",situationTr:"Geri manevra yolunun bir bölümünde geçici aydınlatma arızalanıyor.",focusEn:"minimum visibility before vehicle movement",focusTr:"araç hareketi öncesi asgari görüşü"},
    {id:"restart",titleEn:"The route appears clear again",titleTr:"Güzergah tekrar açık görünüyor",situationEn:"Supervisors ask to restart immediately after pedestrians move away.",situationTr:"Yayalar uzaklaşınca amirler hemen yeniden başlamayı istiyor.",focusEn:"final route verification before reversing",focusTr:"geri manevra öncesi son güzergah doğrulamasını"},
  ],
});

const fireFirstMinutes = buildExpertBlueprint({
  id:"fire-emergency-first-minutes", titleEn:"Fire & Emergency: First Five Minutes", titleTr:"Yangın ve Acil Durum: İlk Beş Dakika", category:"Emergency Response",
  introEn:"The first minutes of a developing fire require rapid but disciplined command decisions.", introTr:"Gelişen bir yangının ilk dakikaları hızlı ancak disiplinli komuta kararları gerektiriyor.",
  stages:[
    {id:"alarm",titleEn:"Smoke is reported",titleTr:"Duman bildiriliyor",situationEn:"A worker reports smoke from an equipment area but no flame is visible yet.",situationTr:"Bir çalışan ekipman alanından duman bildiriyor ancak henüz alev görünmüyor.",focusEn:"early alarm activation and incident confirmation",focusTr:"erken alarm aktivasyonu ve olay doğrulamasını"},
    {id:"source",titleEn:"The fire source is uncertain",titleTr:"Yangın kaynağı belirsiz",situationEn:"Electrical and hydrocarbon sources are both possible in the affected area.",situationTr:"Etkilenen alanda hem elektrik hem hidrokarbon kaynağı olasılığı var.",focusEn:"hazard identification before first response",focusTr:"ilk müdahale öncesi tehlike tanımlamayı"},
    {id:"extinguisher",titleEn:"A worker wants to attack the fire",titleTr:"Bir çalışan yangına müdahale etmek istiyor",situationEn:"A trained worker is nearby with a portable extinguisher.",situationTr:"Eğitimli bir çalışan portatif söndürücüyle yakınında bulunuyor.",focusEn:"limits of safe incipient-stage firefighting",focusTr:"güvenli başlangıç aşaması yangın müdahalesi sınırlarını"},
    {id:"evac",titleEn:"Evacuation routes begin to conflict",titleTr:"Tahliye yolları çakışıyor",situationEn:"One normal route is close to the smoke-affected boundary.",situationTr:"Normal güzergahlardan biri duman etkisindeki sınıra yakın.",focusEn:"safe evacuation routing",focusTr:"güvenli tahliye güzergahını"},
    {id:"muster",titleEn:"Headcount is incomplete",titleTr:"Personel sayımı eksik",situationEn:"Two contractors have not yet reported at the muster point.",situationTr:"İki taşeron çalışan henüz toplanma noktasında kayıt vermedi.",focusEn:"personnel accountability before rescue decisions",focusTr:"kurtarma kararı öncesi personel hesabını"},
    {id:"isolate",titleEn:"Energy isolation is requested",titleTr:"Enerji izolasyonu isteniyor",situationEn:"Operations can isolate the area but needs confirmation of the correct boundary.",situationTr:"Operasyon alanı izole edebilir ancak doğru sınırın teyidine ihtiyaç var.",focusEn:"safe emergency isolation of energy sources",focusTr:"enerji kaynaklarının güvenli acil izolasyonunu"},
    {id:"command",titleEn:"Multiple supervisors give instructions",titleTr:"Birden fazla amir talimat veriyor",situationEn:"Operations and contractor supervision issue overlapping directions.",situationTr:"Operasyon ve taşeron yönetimi çakışan talimatlar veriyor.",focusEn:"single incident-command authority",focusTr:"tek acil durum komuta yetkisini"},
    {id:"fireteam",titleEn:"Emergency team arrives",titleTr:"Acil durum ekibi geliyor",situationEn:"The response team requests a concise handover before entry.",situationTr:"Müdahale ekibi giriş öncesi kısa ve net devir bilgisi istiyor.",focusEn:"structured emergency handover",focusTr:"yapılandırılmış acil durum devir bilgisini"},
    {id:"allclear",titleEn:"Visible smoke reduces",titleTr:"Görünür duman azalıyor",situationEn:"Some supervisors ask to release unaffected work areas immediately.",situationTr:"Bazı amirler etkilenmeyen çalışma alanlarının hemen açılmasını istiyor.",focusEn:"formal all-clear and controlled return to work",focusTr:"resmi tehlike geçti kararı ve kontrollü işe dönüşü"},
  ],
});

const lineResidual = buildExpertBlueprint({
  id:"line-breaking-residual", titleEn:"Line Breaking: Residual Pressure", titleTr:"Hat Açma: Kalan Basınç", category:"Line Breaking",
  introEn:"A prepared line-breaking task reveals signs that stored pressure and trapped contents may remain.", introTr:"Hazırlanmış bir hat açma işi depolanmış basınç ve hapsolmuş içeriğin kalmış olabileceğine dair işaretler gösteriyor.",
  stages:[
    {id:"gauge",titleEn:"A gauge shows a small residual reading",titleTr:"Manometrede düşük kalan basınç var",situationEn:"The local gauge is above zero although the isolation sheet is complete.",situationTr:"İzolasyon formu tamam olmasına rağmen yerel manometre sıfırın üzerinde.",focusEn:"positive verification of zero pressure",focusTr:"sıfır basıncın pozitif doğrulamasını"},
    {id:"drain",titleEn:"The drain stops flowing",titleTr:"Drenaj akışı duruyor",situationEn:"The drain runs briefly and then stops, but the line geometry includes a high point.",situationTr:"Drenaj kısa süre akıp duruyor ancak hat geometrisinde yüksek nokta bulunuyor.",focusEn:"trapped inventory and complete draining",focusTr:"hapsolmuş içerik ve tam drenajı"},
    {id:"vent",titleEn:"The vent path is uncertain",titleTr:"Vent güzergahı belirsiz",situationEn:"The designated vent may connect to a common header still in service.",situationTr:"Belirlenen vent hâlâ serviste olan ortak bir kolektöre bağlı olabilir.",focusEn:"safe vent destination and connected-system status",focusTr:"güvenli vent çıkışı ve bağlı sistem durumunu"},
    {id:"flange",titleEn:"Bolts are requested to be cracked open",titleTr:"Cıvataların gevşetilmesi isteniyor",situationEn:"The crew proposes loosening the flange slightly to prove the line is depressurized.",situationTr:"Ekip hattın basınçsız olduğunu kanıtlamak için flanşı hafif gevşetmeyi öneriyor.",focusEn:"prohibition of using flange opening as pressure verification",focusTr:"basınç doğrulaması için flanş açılmaması kuralını"},
    {id:"blind",titleEn:"Blind status is disputed",titleTr:"Körleme durumu tartışmalı",situationEn:"The blind list and field tag show different installation times.",situationTr:"Körleme listesi ile saha etiketi farklı montaj zamanları gösteriyor.",focusEn:"physical verification of isolation blinds",focusTr:"izolasyon körlerinin fiziksel doğrulamasını"},
    {id:"lof",titleEn:"The line of fire changes",titleTr:"Ateş hattı değişiyor",situationEn:"Access limitations force the mechanic to stand closer to the flange face than planned.",situationTr:"Erişim kısıtı mekanikçinin flanş yüzüne planlanandan daha yakın durmasını gerektiriyor.",focusEn:"line-of-fire positioning during line breaking",focusTr:"hat açma sırasında ateş hattı konumlanmasını"},
    {id:"ppe",titleEn:"The contents are believed to be water",titleTr:"İçeriğin su olduğu düşünülüyor",situationEn:"Process history indicates water service, but contamination from previous service is possible.",situationTr:"Proses geçmişi su servisini gösteriyor ancak önceki servisten kontaminasyon mümkün.",focusEn:"contents verification and chemical PPE basis",focusTr:"içerik doğrulaması ve kimyasal KKD temelini"},
    {id:"restart",titleEn:"Pressure remains stable at zero",titleTr:"Basınç sıfırda stabil",situationEn:"Repeated checks are zero and the isolation boundary has been reconciled.",situationTr:"Tekrarlanan kontroller sıfır ve izolasyon sınırı uzlaştırılmış durumda.",focusEn:"final line-breaking authorization",focusTr:"son hat açma yetkilendirmesini"},
    {id:"open",titleEn:"The first opening is ready",titleTr:"İlk açma hazır",situationEn:"The crew is ready to make the initial controlled separation of the flange.",situationTr:"Ekip flanşın ilk kontrollü ayrımını yapmaya hazır.",focusEn:"controlled first break and residual-release precautions",focusTr:"kontrollü ilk açma ve kalan salım önlemlerini"},
  ],
});

export const expertPackFour = {
  [liftingBlindZone.id]: liftingBlindZone,
  [electricalBackfeed.id]: electricalBackfeed,
  [chemicalReleaseWind.id]: chemicalReleaseWind,
  [mobileReversing.id]: mobileReversing,
  [fireFirstMinutes.id]: fireFirstMinutes,
  [lineResidual.id]: lineResidual,
};
