import { buildExpertScenario, type ExpertStep } from "./expert-builder";

const step = (
  id:string,titleEn:string,titleTr:string,situationEn:string,situationTr:string,
  strongEn:string,strongTr:string,acceptableEn:string,acceptableTr:string,
  weakEn:string,weakTr:string,criticalEn:string,criticalTr:string,
  lessonEn:string,lessonTr:string,
): ExpertStep => ({ id,titleEn,titleTr,situationEn,situationTr,strongEn,strongTr,acceptableEn,acceptableTr,weakEn,weakTr,criticalEn,criticalTr,lessonEn,lessonTr });

const hotWorkProcessInstability = buildExpertScenario({
  id:"hot-work-process-instability", titleEn:"Hot Work: Process Instability", titleTr:"Sıcak Çalışma: Proses Kararsızlığı", category:"Hot Work / SIMOPS",
  introEn:"A permitted hot-work task is underway beside an operating process unit. The process is unstable but not in alarm. Production wants the job completed before a short operating window closes.",
  introTr:"İzinli sıcak çalışma, çalışan bir proses ünitesinin yanında devam ediyor. Proses kararsız ancak alarmda değil. Üretim kısa operasyon penceresi kapanmadan işin bitmesini istiyor.",
  steps:[
    step("trend","A low LEL trend appears","Düşük LEL trendi başlıyor","Continuous monitoring rises from 0% to 3% LEL over several minutes while remaining below the alarm setpoint.","Sürekli ölçüm birkaç dakika içinde %0'dan %3 LEL'e yükseliyor ancak alarm sınırının altında kalıyor.","Suspend ignition work and investigate the trend","Ateşlemeli işi askıya al ve trendi araştır","Hold the torch off while Operations checks the area","Torcu kapalı tut, Operasyon alanı kontrol etsin","Continue with continuous monitoring and a second detector","Sürekli ölçüm ve ikinci dedektörle devam et","Finish the current weld before the reading rises further","Değer daha fazla yükselmeden mevcut kaynağı bitir","the changed atmospheric trend","değişen atmosfer trendini"),
    step("process-upset","Operations reports a minor process upset","Operasyon küçük proses sapması bildiriyor","A control valve is hunting and a nearby vent is cycling. Operations says no hydrocarbon release is confirmed.","Bir kontrol vanası kararsız çalışıyor ve yakındaki vent periyodik açılıyor. Operasyon hidrokarbon salımı doğrulanmadığını söylüyor.","Keep hot work suspended until the upset is stabilized and verified","Sapma stabilize edilip doğrulanana kadar sıcak çalışmayı askıda tut","Maintain suspension but allow cold preparation work outside the hot-work boundary","Sıcak işi askıda tut ancak sınır dışında soğuk hazırlığa izin ver","Resume if the detector remains below the site alarm threshold","Dedektör saha alarm sınırının altında kalırsa devam et","Resume for a short controlled window before Operations intervenes","Operasyon müdahale etmeden kısa kontrollü pencereyle devam et","process stability as a permit assumption","proses stabilitesini izin varsayımı olarak"),
    step("permit-basis","Permit validity is challenged","İzin geçerliliği sorgulanıyor","The permit is still within time validity, but the process state no longer matches the conditions recorded at issue.","İznin süresi dolmamış ancak proses durumu düzenlendiği andaki koşullarla artık eşleşmiyor.","Suspend and formally revalidate the permit against current conditions","İzni askıya al ve mevcut koşullara göre resmi olarak yeniden doğrula","Document the change and obtain joint Operations-HSE confirmation","Değişikliği kaydet ve Operasyon-HSE ortak teyidi al","Treat time validity as sufficient if controls remain physically present","Fiziksel kontroller mevcutsa süre geçerliliğini yeterli kabul et","Keep the old permit and add a handwritten note after the job","Eski izinle devam et ve iş bitince el yazısı not ekle","permit validity after a process change","proses değişikliği sonrası izin geçerliliğini"),
    step("firewatch","Fire-watch coverage becomes divided","Yangın gözcüsü iki işe bölünüyor","The assigned fire watch is asked to cover a second nearby hot-work task for ten minutes.","Atanan yangın gözcüsünden on dakika boyunca yakındaki ikinci sıcak işi de takip etmesi isteniyor.","Restore dedicated fire-watch coverage before restart","Yeniden başlamadan önce özel yangın gözcüsü kapsamını geri getir","Keep work paused until a relief fire watch arrives","Yedek yangın gözcüsü gelene kadar işi beklet","Let one fire watch cover both jobs because both are visible","İki iş de görülebildiği için tek gözcünün ikisini takip etmesine izin ver","Continue and ask the welder to self-monitor the second side","Devam et ve kaynakçıdan ikinci tarafı da kendi izlemesini iste","dedicated fire-watch effectiveness","özel yangın gözcüsü etkinliğini"),
    step("drain","A nearby drain is opened","Yakındaki drenaj açılıyor","Operations opens a low-point drain twenty metres upstream. The liquid is believed to be water but the line shares process service history.","Operasyon yirmi metre üst taraftaki alçak nokta drenajını açıyor. Sıvının su olduğu düşünülüyor ancak hat geçmişte proses servisi görmüş.","Stop hot work and verify drain service, contents and gas trend","Sıcak işi durdur; drenaj servisini, içeriğini ve gaz trendini doğrula","Increase exclusion distance and wait for Operations identification","Yasak bölgeyi genişlet ve Operasyon tanımlamasını bekle","Continue because the drain is outside the hot-work barricade","Drenaj sıcak çalışma bariyerinin dışında olduğu için devam et","Continue until a detector response confirms a problem","Dedektör tepki verene kadar devam et","the new ignition-source interface created by line opening","hat açılmasıyla oluşan yeni ateşleme kaynağı arayüzünü"),
    step("wind","Wind direction shifts toward the job","Rüzgar çalışma alanına dönüyor","The wind sock rotates and now points from the process equipment toward the hot-work location.","Rüzgar tulumu yön değiştiriyor ve artık proses ekipmanından sıcak çalışma alanına doğru akış gösteriyor.","Reassess gas-monitor locations and suspend until the plume path is verified","Dedektör konumlarını yeniden değerlendir ve yayılım yolu doğrulanana kadar durdur","Move personnel upwind and repeat perimeter readings before deciding","Personeli rüzgar üstüne al ve karar öncesi çevre ölçümlerini tekrarla","Keep the same monitor positions because readings are currently low","Değerler şu an düşük olduğu için aynı dedektör konumlarını koru","Move the nearest detector upwind to avoid nuisance readings","Gereksiz alarmı önlemek için en yakın dedektörü rüzgar üstüne taşı","monitor placement after a wind-direction change","rüzgar yönü değişiminden sonra dedektör yerleşimini"),
    step("isolation","Operations offers a temporary isolation","Operasyon geçici izolasyon öneriyor","A single valve can stop the suspected source quickly, but the normal isolation standard for hot work would require a verified double block arrangement.","Şüpheli kaynağı tek vana hızlıca durdurabilir ancak sıcak çalışma için normal izolasyon standardı doğrulanmış çift blok düzeni gerektiriyor.","Require the approved isolation standard before accepting restart","Yeniden başlatma için onaylı izolasyon standardını uygulat","Use the single valve only as an interim measure while the job remains suspended","İş askıdayken tek vanayı yalnızca geçici önlem olarak kullan","Accept the single valve with continuous gas monitoring","Sürekli gaz ölçümüyle tek vanayı kabul et","Accept verbal assurance that the valve is tight and restart","Vananın sızdırmaz olduğuna dair sözlü güvenceyi kabul edip başlat","the specified process-isolation standard","belirlenmiş proses izolasyon standardını"),
    step("retest","Readings return to zero","Ölçümler tekrar sıfıra dönüyor","After isolation and ventilation, all current readings are zero. Only one five-minute sampling period has been completed.","İzolasyon ve havalandırma sonrası mevcut ölçümlerin tamamı sıfır. Yalnızca bir adet beş dakikalık örnekleme yapılmış.","Demonstrate stable readings over the required monitoring period before restart","Yeniden başlatmadan önce gerekli izleme süresince stabil değerleri göster","Extend monitoring while the crew completes non-ignition setup","Ekip ateşlemesiz hazırlık yaparken izlemeyi uzat","Restart because zero is below every alarm criterion","Sıfır tüm alarm kriterlerinin altında olduğu için başlat","Switch off continuous monitoring once the first zero reading is confirmed","İlk sıfır ölçümü doğrulanınca sürekli ölçümü kapat","stable atmospheric verification rather than a single reading","tek ölçüm yerine stabil atmosfer doğrulamasını"),
    step("handover","Shift handover begins","Vardiya devri başlıyor","The incoming Operations supervisor has not been part of the upset response but is about to accept the permit handover.","Yeni Operasyon amiri proses sapması müdahalesinde yer almadı ancak izin devrini almak üzere.","Conduct a field handover covering the upset, isolation and restart criteria","Sapma, izolasyon ve yeniden başlatma kriterlerini içeren saha devri yap","Hold restart until the incoming supervisor reviews the amended permit","Yeni amir güncellenen izni inceleyene kadar başlatma","Rely on the outgoing supervisor's signature and proceed","Çıkan amirin imzasına güvenip devam et","Restart first and brief the incoming supervisor when available","Önce başlat, yeni amiri müsait olunca bilgilendir","continuity of control ownership during handover","devir sırasında kontrol sorumluluğu sürekliliğini"),
    step("restart","Production asks for immediate restart","Üretim hemen yeniden başlatma istiyor","The source is isolated, readings are stable and the amended permit is signed. Production asks to restart without a final joint field check.","Kaynak izole, ölçümler stabil ve güncellenen izin imzalı. Üretim son ortak saha kontrolü olmadan yeniden başlatma istiyor.","Perform the final joint field verification and explicitly release hot work","Son ortak saha doğrulamasını yap ve sıcak çalışmayı açıkça serbest bırak","Complete a rapid joint walkdown focused on changed controls","Değişen kontrollere odaklı hızlı ortak saha turu yap","Restart based on paperwork because all signatures are complete","Tüm imzalar tamam olduğu için evraka dayanarak başlat","Let the welder restart while supervisors finish the field check","Amirler saha kontrolünü bitirirken kaynakçının başlamasına izin ver","final verification of all changed controls before ignition","ateşleme öncesi değişen tüm kontrollerin son doğrulamasını"),
  ],
});

const hotWorkSimopsShutdown = buildExpertScenario({
  id:"hot-work-simops-shutdown", titleEn:"Hot Work: SIMOPS During Shutdown", titleTr:"Sıcak Çalışma: Shutdown Sırasında SIMOPS", category:"Hot Work / SIMOPS",
  introEn:"During a shutdown, hot work shares a congested process area with line breaking, scaffolding and commissioning preparations. Ownership of isolations changes between teams.",
  introTr:"Shutdown sırasında sıcak çalışma; hat açma, iskele ve devreye alma hazırlıklarıyla aynı sıkışık proses alanını paylaşıyor. İzolasyon sorumluluğu ekipler arasında değişiyor.",
  steps:[
    step("simops-map","The SIMOPS map is already outdated","SIMOPS haritası güncelliğini yitirmiş","A line-breaking job has moved closer to the hot-work boundary since the morning coordination meeting.","Hat açma işi sabah koordinasyon toplantısından sonra sıcak çalışma sınırına yaklaşmış.","Suspend startup and update the SIMOPS interface with both permit owners","Başlangıcı durdur ve iki izin sahibiyle SIMOPS arayüzünü güncelle","Increase separation temporarily while permit owners meet","İzin sahipleri görüşürken geçici olarak mesafeyi artır","Continue because both permits were independently approved","İki izin ayrı ayrı onaylandığı için devam et","Start hot work before the line-breaking team opens the flange","Hat açma ekibi flanşı açmadan sıcak işi başlat","the changed SIMOPS interface between simultaneous permits","eş zamanlı izinler arasındaki değişen SIMOPS arayüzünü"),
    step("ownership","Isolation ownership is unclear","İzolasyon sorumluluğu belirsiz","Operations says Mechanical owns the blind list; Mechanical says Operations owns final valve verification.","Operasyon körleme listesinin Mekanikte olduğunu, Mekanik ise son vana doğrulamasının Operasyonda olduğunu söylüyor.","Stop and assign one accountable isolation owner before relying on the boundary","Sınırı kabul etmeden önce dur ve tek sorumlu izolasyon sahibi ata","Freeze work while both groups jointly reconcile the list","İki ekip listeyi birlikte uzlaştırana kadar işi dondur","Accept split ownership if each group signs its section","Her ekip kendi bölümünü imzalarsa bölünmüş sorumluluğu kabul et","Proceed using the latest signed copy even though ownership is disputed","Sorumluluk tartışmalı olsa da son imzalı kopyayla devam et","clear accountability for the isolation boundary","izolasyon sınırı için net sorumluluğu"),
    step("scaffold-change","Scaffold modification affects the fire blanket","İskele değişikliği yangın örtüsünü etkiliyor","Scaffolders remove a board and move the fire blanket to gain access for a modification.","İskele ekibi değişiklik için bir kalası söküp yangın örtüsünü yerinden alıyor.","Pause hot work until the scaffold change is complete and fire protection is re-established","İskele değişikliği bitip yangın koruması yeniden kurulana kadar sıcak işi durdur","Keep ignition off while the scaffold team restores the barrier","İskele ekibi bariyeri geri kurarken ateşlemeyi kapalı tut","Continue welding on the opposite side of the joint","Birleşimin diğer tarafında kaynağa devam et","Use a worker to hold the fire blanket temporarily during welding","Kaynak sırasında bir çalışanın yangın örtüsünü tutmasını sağla","fire protection after a simultaneous scaffold modification","eş zamanlı iskele değişikliği sonrası yangın korumasını"),
    step("purge","A connected line begins nitrogen purging","Bağlı hatta azot purj başlıyor","Commissioning starts nitrogen purging on a connected system that was not active when the hot-work permit was issued.","Devreye alma ekibi sıcak çalışma izni düzenlenirken aktif olmayan bağlı bir sistemde azot purj başlatıyor.","Suspend hot work and assess both oxygen-deficiency and process-interface effects","Sıcak işi durdur; oksijen düşüklüğü ve proses arayüzü etkilerini değerlendir","Move personnel upwind and verify monitoring coverage before any decision","Personeli rüzgar üstüne al ve karar öncesi ölçüm kapsamını doğrula","Continue because nitrogen is non-flammable","Azot yanıcı olmadığı için devam et","Continue while relying only on the flammable-gas detector","Yalnız yanıcı gaz dedektörüne güvenerek devam et","the new purge hazard and changed atmospheric assumptions","yeni purj tehlikesini ve değişen atmosfer varsayımlarını"),
    step("spark-path","Spark path now reaches another workfront","Kıvılcım yolu başka çalışma alanına ulaşıyor","Removal of temporary sheeting creates a direct spark path toward cable pulling below.","Geçici kaplamanın kaldırılması aşağıdaki kablo çekme işine doğrudan kıvılcım yolu oluşturuyor.","Stop and re-establish physical separation before hot work resumes","Sıcak iş yeniden başlamadan fiziksel ayrımı geri kur","Suspend the lower activity and verify a temporary barrier","Alt faaliyeti durdur ve geçici bariyeri doğrula","Assign an additional spotter between the activities","İki faaliyet arasına ek gözcü ata","Continue while warning the cable crew to watch for sparks","Kablo ekibini kıvılcıma karşı uyarıp devam et","physical control of the changed spark trajectory","değişen kıvılcım yolunun fiziksel kontrolünü"),
    step("blind-list","Blind list revision arrives late","Körleme listesi revizyonu geç geliyor","A revised blind list shows one process connection was changed from blind to closed-valve isolation overnight.","Revize körleme listesi bir proses bağlantısının gece körlemeden kapalı vana izolasyonuna çevrildiğini gösteriyor.","Stop and revalidate the entire affected isolation boundary in the field","Dur ve etkilenen izolasyon sınırının tamamını sahada yeniden doğrula","Hold work while the changed connection is independently verified","Değişen bağlantı bağımsız doğrulanana kadar işi beklet","Accept the revision because Operations issued it","Operasyon yayınladığı için revizyonu kabul et","Continue because the changed connection is not directly beside the weld","Değişen bağlantı kaynağın hemen yanında olmadığı için devam et","field proof of revised isolation status","revize izolasyon durumunun saha kanıtını"),
    step("gas-test","Gas-test responsibility changes","Gaz ölçüm sorumluluğu değişiyor","The authorized gas tester is reassigned and a trained but not project-authorized technician offers to continue monitoring.","Yetkili gaz ölçüm personeli başka işe alınıyor ve eğitimli ancak proje yetkisi olmayan teknisyen ölçümü sürdürmeyi teklif ediyor.","Pause until an authorized gas tester assumes the monitoring role","Yetkili gaz ölçüm personeli görevi alana kadar dur","Maintain suspension while the technician performs advisory readings only","Teknisyen yalnız bilgilendirici ölçüm yaparken işi askıda tut","Let the trained technician monitor under phone supervision","Eğitimli teknisyenin telefonla gözetim altında ölçüm yapmasına izin ver","Continue welding and perform periodic checks when the tester returns","Kaynağa devam et, yetkili döndüğünde periyodik ölçüm yap","authorized ownership of atmospheric monitoring","atmosfer ölçümünün yetkili sorumluluğunu"),
    step("restart-pressure","A critical path task is waiting","Kritik yol işi bekliyor","Planning states the shutdown will lose six hours if the hot-work joint is not released now.","Planlama sıcak çalışma birleşimi şimdi serbest bırakılmazsa shutdown'ın altı saat kaybedeceğini söylüyor.","Keep release criteria unchanged despite schedule impact","Program etkisine rağmen serbest bırakma kriterlerini değiştirme","Escalate the delay to shutdown leadership while maintaining stop-work","İşi durdurmayı koruyarak gecikmeyi shutdown yönetimine eskale et","Allow a reduced-scope weld to protect the schedule","Programı korumak için dar kapsamlı kaynağa izin ver","Authorize completion of the current pass as an exception","İstisna olarak mevcut paso tamamlanmasına izin ver","independence of safety criteria from schedule pressure","güvenlik kriterlerinin program baskısından bağımsızlığını"),
    step("handover","Permit ownership transfers at night shift","İzin sorumluluğu gece vardiyasına geçiyor","Three simultaneous permits and two isolation revisions must be handed over during a compressed shift change.","Sıkıştırılmış vardiya devrinde üç eş zamanlı izin ve iki izolasyon revizyonu devredilmeli.","Conduct a joint field handover of all interfaces and changed controls","Tüm arayüzler ve değişen kontroller için ortak saha devri yap","Delay hot-work restart until the incoming team reviews the SIMOPS board","Yeni ekip SIMOPS panosunu inceleyene kadar sıcak iş başlangıcını geciktir","Use written handover only because all documents are signed","Tüm dokümanlar imzalı olduğu için yalnız yazılı devir kullan","Let the outgoing supervisor release the job before leaving","Çıkan amirin ayrılmadan işi serbest bırakmasına izin ver","control continuity across a complex SIMOPS handover","karmaşık SIMOPS devrinde kontrol sürekliliğini"),
    step("final-release","All teams request simultaneous release","Tüm ekipler eş zamanlı serbest bırakma istiyor","Line breaking is complete, scaffolding is released and commissioning wants to start immediately after the weld begins.","Hat açma tamam, iskele serbest ve devreye alma kaynağın başlamasıyla hemen başlamak istiyor.","Sequence the releases and verify no new interface is created before hot work starts","Serbest bırakmaları sırala ve sıcak iş öncesi yeni arayüz oluşmadığını doğrula","Release hot work first and hold commissioning until a field check is complete","Önce sıcak işi serbest bırak, saha kontrolüne kadar devreye almayı beklet","Release both because their permits are independently valid","İzinleri ayrı ayrı geçerli olduğu için ikisini birden serbest bırak","Let each permit owner manage their own interface after release","Serbest bırakma sonrası her izin sahibinin kendi arayüzünü yönetmesine bırak","coordinated sequencing of simultaneous permit releases","eş zamanlı izin serbest bırakmalarının koordineli sıralamasını"),
  ],
});

const heightWeatherRescue = buildExpertScenario({
  id:"height-weather-rescue", titleEn:"Work at Height: Weather Turns", titleTr:"Yüksekte Çalışma: Hava Değişiyor", category:"Work at Height",
  introEn:"A tower maintenance task is in progress when wind, access and rescue assumptions begin to change. The formal wind limit has not yet been exceeded.",
  introTr:"Kule bakım işi sürerken rüzgar, erişim ve kurtarma varsayımları değişmeye başlıyor. Resmi rüzgar limiti henüz aşılmış değil.",
  steps:[
    step("gusts","Gusts increase below the formal limit","Ani esintiler resmi limitin altında artıyor","Average wind is acceptable, but gusts are moving loose sheeting and making the worker brace against the structure.","Ortalama rüzgar uygun ancak ani esintiler gevşek kaplamayı hareket ettiriyor ve çalışan yapıya tutunmak zorunda kalıyor.","Pause and reassess exposure using gusts and task stability, not only the average","Yalnız ortalamaya değil ani esinti ve iş stabilitesine göre durup yeniden değerlendir","Move to a sheltered position and monitor the next wind cycle","Korunaklı konuma geç ve sonraki rüzgar çevrimini izle","Continue until the formal project wind limit is reached","Resmi proje rüzgar limitine ulaşana kadar devam et","Finish the current fastening sequence before conditions worsen","Koşullar kötüleşmeden mevcut sabitlemeyi bitir","task stability under gusting wind","ani esintide iş stabilitesini"),
    step("rescue-team","The trained rescuer is called away","Eğitimli kurtarıcı başka yere çağrılıyor","The rescue kit remains at the base, but the nominated rescuer is redirected to another incident.","Kurtarma ekipmanı tabanda kalıyor ancak atanmış kurtarıcı başka olaya yönlendiriliyor.","Suspend work at height until equivalent rescue capability is restored","Eşdeğer kurtarma kapasitesi geri gelene kadar yüksekte çalışmayı durdur","Keep the worker in a safe platform area while replacement rescue coverage is arranged","Yedek kurtarma kapsamı ayarlanırken çalışanı güvenli platform alanında tut","Continue because the general emergency team is on site","Genel acil durum ekibi sahada olduğu için devam et","Continue and rely on self-rescue if a fall occurs","Düşme olursa kendi kurtarmasına güvenerek devam et","immediate rescue capability as a work-at-height control","yüksekte çalışmanın kontrolü olarak anlık kurtarma kapasitesini"),
    step("access","Temporary stair access is partially closed","Geçici merdiven erişimi kısmen kapanıyor","Material staging blocks the normal descent route, leaving a ladder as the only immediate exit.","Malzeme istifi normal iniş yolunu kapatıyor ve tek anlık çıkış olarak merdiven kalıyor.","Restore the planned emergency egress before continuing","Devam etmeden planlanan acil çıkışı geri getir","Hold the task while the staging area is cleared","İstif alanı temizlenirken işi beklet","Continue because a ladder remains available","Merdiven mevcut olduğu için devam et","Use the blocked stair only in an emergency","Acil durumda kapalı merdiveni kullanmayı planla","reliable emergency egress from the work position","çalışma noktasından güvenilir acil çıkışı"),
    step("sheeting","A loose sheet becomes a dropped-object hazard","Gevşek kaplama düşen cisim tehlikesine dönüşüyor","Wind lifts one edge of a temporary sheet above an active access road.","Rüzgar aktif erişim yolunun üzerindeki geçici kaplamanın bir kenarını kaldırıyor.","Stop, secure the sheet and extend the exclusion zone before resuming","Dur, kaplamayı sabitle ve devam öncesi yasak bölgeyi genişlet","Close the road temporarily while a crew secures the sheet","Ekip kaplamayı sabitlerken yolu geçici kapat","Post a spotter below and continue the height task","Aşağıya gözcü koyup yüksekte çalışmaya devam et","Remove the sheet quickly from height while traffic continues","Trafik sürerken kaplamayı yüksekte hızlıca sök","control of a newly mobile dropped-object source","yeni hareketli düşen cisim kaynağının kontrolünü"),
    step("lanyard","A worker changes to a shorter lanyard","Çalışan daha kısa lanyarda geçiyor","The shorter lanyard limits movement but may reduce free-fall distance; its compatibility with the anchor system has not been checked.","Daha kısa lanyard hareketi sınırlıyor ancak serbest düşüş mesafesini azaltabilir; ankraj sistemiyle uyumu kontrol edilmemiş.","Verify compatibility and clearance before changing the fall-arrest setup","Düşüş durdurma düzenini değiştirmeden uyum ve açıklığı doğrula","Keep the original system until competent review is complete","Yetkin inceleme bitene kadar mevcut sistemi koru","Use the shorter lanyard because less slack appears safer","Daha az boşluk daha güvenli göründüğü için kısa lanyardı kullan","Change equipment based only on worker preference and reach","Yalnız çalışan tercihi ve erişime göre ekipmanı değiştir","compatibility and clearance of the fall-arrest system","düşüş durdurma sisteminin uyum ve açıklığını"),
    step("lightning","A distant lightning warning is issued","Uzak yıldırım uyarısı veriliyor","The storm cell is outside the exclusion radius but moving toward the site faster than forecast.","Fırtına hücresi yasak yarıçapın dışında ancak sahaya tahminden hızlı yaklaşıyor.","Use the site lightning trigger and travel time to initiate controlled descent early","Saha yıldırım tetik değeri ve iniş süresine göre kontrollü inişi erken başlat","Stop new work and prepare descent while tracking the cell","Yeni işi durdur, hücreyi izlerken inişe hazırlan","Wait until the official radius is crossed before reacting","Resmi yarıçap aşılana kadar tepki verme","Keep working because the current reading is still outside the limit","Mevcut değer sınırın dışında olduğu için çalışmayı sürdür","lead time needed for safe descent before lightning exposure","yıldırım maruziyetinden önce güvenli iniş için gereken ön süreyi"),
    step("radio","Radio communication becomes intermittent","Telsiz iletişimi kesintili oluyor","Wind noise and structure shielding cause repeated missed calls between the worker and ground supervisor.","Rüzgar gürültüsü ve yapı gölgelemesi çalışan ile yer amiri arasındaki çağrıların kaçmasına neden oluyor.","Suspend exposed work until reliable communication is restored","Güvenilir iletişim geri gelene kadar maruziyetli işi durdur","Move the ground supervisor to a verified communication point","Yer amirini doğrulanmış iletişim noktasına taşı","Continue using hand signals where visible","Görüş varsa el işaretleriyle devam et","Rely on the worker to call only if assistance is needed","Yalnız yardıma ihtiyaç olursa çalışanın aramasına güven","reliable communication for supervision and rescue activation","gözetim ve kurtarma aktivasyonu için güvenilir iletişimi"),
    step("anchor-load","A temporary line is loaded by another worker","Geçici hat başka çalışan tarafından yükleniyor","A second contractor clips into the same temporary horizontal lifeline without coordination.","Başka yükleniciden bir çalışan koordinasyonsuz şekilde aynı geçici yatay yaşam hattına bağlanıyor.","Stop and verify system capacity, user limits and coordination before shared use","Ortak kullanım öncesi sistem kapasitesi, kullanıcı limiti ve koordinasyonu doğrula","Keep both workers stationary until a competent person confirms capacity","Yetkin kişi kapasiteyi doğrulayana kadar iki çalışanı sabit tut","Allow both because the line is certified","Hat sertifikalı olduğu için ikisine de izin ver","Let the second worker use it only for a few minutes","İkinci çalışanın birkaç dakika kullanmasına izin ver","rated capacity and user limits of the shared fall-protection system","ortak düşüş koruma sisteminin kapasite ve kullanıcı limitlerini"),
    step("descent","Conditions improve briefly","Koşullar kısa süreli düzeliyor","Wind drops for ten minutes and the storm cell slows. The crew proposes finishing the remaining twenty-minute task.","Rüzgar on dakika düşüyor ve fırtına hücresi yavaşlıyor. Ekip kalan yirmi dakikalık işi bitirmeyi öneriyor.","Base the restart on a defined stable-condition period and restored rescue controls","Yeniden başlamayı tanımlı stabil koşul süresi ve geri gelen kurtarma kontrollerine bağla","Keep the task paused while verifying the updated weather forecast and rescue coverage","Güncel hava tahmini ve kurtarma kapsamını doğrularken işi beklet","Restart because current wind is below the limit","Mevcut rüzgar limitin altında olduğu için başlat","Use the short calm window to rush completion","Kısa sakin pencereyi işi hızla bitirmek için kullan","sustained stable conditions rather than a temporary lull","geçici sakinlik yerine sürdürülebilir stabil koşulları"),
    step("release","Supervisor requests final release","Amir son serbest bırakmayı istiyor","Access, communication, rescue cover and weather criteria are now restored. The work team asks to restart immediately.","Erişim, iletişim, kurtarma kapsamı ve hava kriterleri geri sağlandı. Ekip hemen yeniden başlamak istiyor.","Complete a final field verification of all changed controls before release","Serbest bırakmadan önce değişen tüm kontrolleri son kez sahada doğrula","Perform a focused check on rescue, egress and weather triggers","Kurtarma, çıkış ve hava tetiklerine odaklı kontrol yap","Release based on the updated permit notes","Güncellenen izin notlarına dayanarak serbest bırak","Allow restart while the supervisor completes the final checklist","Amir son kontrol listesini tamamlarken yeniden başlat","final confirmation that all degraded controls are restored","bozulan tüm kontrollerin geri geldiğinin son doğrulamasını"),
  ],
});

const heightSimopsLift = buildExpertScenario({
  id:"height-simops-lift", titleEn:"Work at Height: Lift Below", titleTr:"Yüksekte Çalışma: Altında Kaldırma Var", category:"Work at Height / SIMOPS",
  introEn:"A maintenance crew is working at height while a planned crane lift is introduced below. Both jobs are individually permitted, but their exclusion zones and rescue plans begin to conflict.",
  introTr:"Bakım ekibi yüksekte çalışırken aşağıda planlı vinç kaldırması başlıyor. İki işin de izni var ancak yasak bölgeleri ve kurtarma planları çakışmaya başlıyor.",
  steps:[
    step("overlap","Exclusion zones overlap","Yasak bölgeler çakışıyor","The crane lift path now passes partly beneath the elevated work platform.","Vinç yük yolu artık yükseltilmiş çalışma platformunun kısmen altından geçiyor.","Stop one activity and formally sequence the two permits","Faaliyetlerden birini durdur ve iki izni resmi olarak sırala","Hold the lift while the height crew reaches a safe pause point","Yüksekte ekip güvenli bekleme noktasına gelene kadar kaldırmayı beklet","Continue both with radio coordination between supervisors","Amirler arası telsiz koordinasyonuyla ikisini sürdür","Allow the lift to pass quickly while the worker stays clipped on","Çalışan bağlı kalırken kaldırmanın hızlıca geçmesine izin ver","physical separation of suspended-load and work-at-height exposures","askıdaki yük ile yüksekte çalışma maruziyetlerinin fiziksel ayrımını"),
    step("rescue-route","The rescue route crosses the lift zone","Kurtarma güzergahı kaldırma bölgesinden geçiyor","The planned rescue lowering area is inside the crane exclusion zone during the lift.","Planlanan kurtarma indirme alanı kaldırma sırasında vinç yasak bölgesinin içinde kalıyor.","Do not permit simultaneous work until an independent rescue route is established","Bağımsız kurtarma güzergahı kurulmadan eş zamanlı işe izin verme","Hold the lift whenever the height worker is exposed outside the platform","Çalışan platform dışında maruz kaldığında kaldırmayı beklet","Rely on stopping the crane if a rescue becomes necessary","Kurtarma gerekirse vinci durdurmaya güven","Assume emergency response can override the lift zone if needed","Gerekirse acil durumun kaldırma bölgesini aşacağını varsay","unobstructed rescue access during simultaneous operations","eş zamanlı işlerde kesintisiz kurtarma erişimini"),
    step("tagline","A tagline could strike the structure","Tagline yapıya çarpabilir","The lift requires a tagline that may sweep near the worker's access ladder in a wind shift.","Kaldırma, rüzgar değişiminde çalışanın erişim merdivenine yaklaşabilecek tagline gerektiriyor.","Redesign the lift control or sequence work so the tagline cannot enter the access area","Tagline erişim alanına giremeyecek şekilde kaldırmayı değiştir veya işleri sırala","Establish a dedicated tagline exclusion corridor before the lift","Kaldırma öncesi özel tagline yasak koridoru kur","Use an additional spotter to warn the worker if the line approaches","Hat yaklaşırsa çalışanı uyarmak için ek gözcü kullan","Proceed and ask the height worker to watch the tagline","Devam et ve yüksekte çalışandan tagline'ı izlemesini iste","control of moving-line interaction with access and fall exposure","hareketli halatın erişim ve düşme maruziyetiyle etkileşimini"),
    step("dropped-object","Tools remain above the lift crew","Aletler kaldırma ekibinin üstünde kalıyor","Small tools are tethered, but loose consumables are stored on the platform edge above the lifting team.","Küçük aletler bağlı ancak gevşek sarf malzemeleri platform kenarında kaldırma ekibinin üstünde duruyor.","Clear and secure all potential dropped objects before the lift enters the zone","Kaldırma bölgeye girmeden tüm düşebilecek cisimleri temizle ve sabitle","Hold the lift while platform housekeeping is completed","Platform temizliği bitene kadar kaldırmayı beklet","Continue because primary tools are tethered","Ana aletler bağlı olduğu için devam et","Move the lift crew through quickly beneath the platform","Kaldırma ekibini platform altından hızlı geçir","control of secondary dropped-object sources above the lift team","kaldırma ekibi üzerindeki ikincil düşen cisim kaynaklarını"),
    step("command","Two supervisors give conflicting instructions","İki amir çelişkili talimat veriyor","The lifting supervisor wants the platform crew frozen in place; the height supervisor wants them to descend before the lift.","Kaldırma amiri platform ekibinin yerinde kalmasını, yüksekte çalışma amiri kaldırma öncesi inmelerini istiyor.","Establish one SIMOPS authority and agree the safe sequence before either job moves","Tek SIMOPS yetkilisi belirle ve iki iş hareket etmeden güvenli sırayı kararlaştır","Keep both activities static until command authority is resolved","Komuta yetkisi çözülene kadar iki faaliyeti de sabit tut","Let each supervisor control only their own team","Her amirin yalnız kendi ekibini yönetmesine izin ver","Follow the lift supervisor because crane movement is time-critical","Vinç hareketi zaman kritik olduğu için kaldırma amirini takip et","single-point command for conflicting simultaneous operations","çakışan eş zamanlı işler için tek nokta komutayı"),
    step("wind","Wind changes the load path","Rüzgar yük yolunu değiştiriyor","A gust pushes the suspended load toward the structure, narrowing clearance from the platform.","Ani esinti askıdaki yükü yapıya doğru iterek platformla açıklığı azaltıyor.","Abort or hold the lift in a safe position and reassess simultaneous work","Kaldırmayı güvenli konumda durdur/iptal et ve eş zamanlı işi yeniden değerlendir","Land the load if feasible and reset the lift plan","Mümkünse yükü indir ve kaldırma planını yeniden kur","Continue at slower crane speed while monitoring clearance","Açıklığı izleyerek daha yavaş vinç hızıyla devam et","Use taglines to pull the load away while the height crew remains exposed","Yüksekte ekip maruzken yükü tagline ile çekerek uzaklaştır","minimum dynamic clearance between suspended load and occupied structure","askıdaki yük ile kullanılan yapı arasındaki minimum dinamik açıklığı"),
    step("permit","One permit is amended but the other is not","Bir izin değişiyor diğeri değişmiyor","The lifting plan is revised for a new radius, but the work-at-height permit still references the original exclusion zone.","Kaldırma planı yeni yarıçapa göre revize ediliyor ancak yüksekte çalışma izni eski yasak bölgeyi referanslıyor.","Reconcile both permits and their shared boundaries before restart","Yeniden başlatmadan önce iki izni ve ortak sınırlarını uzlaştır","Hold both jobs while the height permit is updated","Yüksekte çalışma izni güncellenirken iki işi de beklet","Continue height work because only the lift plan changed","Yalnız kaldırma planı değiştiği için yüksekte işe devam et","Update the height permit after the lift is complete","Yüksekte çalışma iznini kaldırma bittikten sonra güncelle","cross-permit consistency after a SIMOPS change","SIMOPS değişikliği sonrası izinler arası tutarlılığı"),
    step("rescue-kit","Rescue equipment is moved by riggers","Kurtarma ekipmanı rigging ekibi tarafından taşınıyor","Riggers move the rescue tripod and rope bag to make room for crane mats without informing the height team.","Rigging ekibi vinç altlıklarına yer açmak için kurtarma tripodu ve halat çantasını yüksekte çalışma ekibine haber vermeden taşıyor.","Suspend exposure until rescue equipment is restored, checked and accessible","Kurtarma ekipmanı geri getirilip kontrol edilene ve erişilebilir olana kadar maruziyeti durdur","Keep the worker in a protected location while the kit is repositioned","Kit geri yerleştirilirken çalışanı korumalı konumda tut","Continue because the equipment remains on site","Ekipman sahada kaldığı için devam et","Rely on the crane crew to return the kit if an emergency occurs","Acil durumda vinç ekibinin kiti geri getirmesine güven","availability and location control of rescue equipment","kurtarma ekipmanının erişilebilirlik ve konum kontrolünü"),
    step("schedule","The lift window is about to close","Kaldırma penceresi kapanmak üzere","Operations says the road closure ends in fifteen minutes and asks both jobs to compress their remaining work.","Operasyon yol kapamasının on beş dakika sonra biteceğini söylüyor ve iki işten kalan işi sıkıştırmalarını istiyor.","Maintain the agreed sequence and extend the closure if needed","Kararlaştırılan sırayı koru, gerekirse kapamayı uzat","Escalate schedule impact while keeping one activity suspended","Bir faaliyeti askıda tutarak program etkisini eskale et","Run the lift and height work together for the final fifteen minutes","Son on beş dakikada kaldırma ve yüksekte işi birlikte yürüt","Allow simultaneous completion because both crews are experienced","İki ekip deneyimli olduğu için eş zamanlı tamamlamaya izin ver","separation controls despite schedule pressure","program baskısına rağmen ayrım kontrollerini"),
    step("closeout","Both teams declare their work complete","İki ekip de işin bittiğini bildiriyor","The load is landed and the height task is complete, but temporary barriers and rescue gear have not yet been restored to normal configuration.","Yük indirildi ve yüksekte iş tamamlandı ancak geçici bariyerler ve kurtarma ekipmanı normal düzene dönmedi.","Close both permits only after shared-area controls and equipment are restored","Ortak alan kontrolleri ve ekipman geri kurulmadan iki izni kapatma","Keep the area restricted until restoration is jointly verified","Restorasyon ortak doğrulanana kadar alanı kısıtlı tut","Close permits and leave restoration to the next shift","İzinleri kapatıp restorasyonu sonraki vardiyaya bırak","Open the area immediately because the high-risk work is finished","Yüksek riskli iş bittiği için alanı hemen aç","safe restoration and handback of the shared work area","ortak çalışma alanının güvenli restorasyon ve teslimini"),
  ],
});

const confinedEntrantSymptoms = buildExpertScenario({
  id:"confined-space-entrant-symptoms", titleEn:"Confined Space: Entrant Feels Unwell", titleTr:"Kapalı Alan: Çalışanın Durumu Bozuluyor", category:"Confined Space / Rescue",
  introEn:"A vessel entry begins with normal atmosphere and valid isolation. One entrant develops subtle symptoms while monitoring remains within numerical limits.",
  introTr:"Bir kapalı alan girişi normal atmosfer ve geçerli izolasyonla başlıyor. Ölçümler sayısal limitler içinde kalırken bir çalışanda hafif belirtiler gelişiyor.",
  steps:[
    step("symptom","An entrant reports a mild headache","Çalışan hafif baş ağrısı bildiriyor","The gas monitor shows acceptable values, but one entrant reports headache and unusual fatigue.","Gaz ölçüm cihazı uygun değer gösteriyor ancak bir çalışan baş ağrısı ve olağandışı yorgunluk bildiriyor.","Stop work and withdraw entrants for medical and atmospheric reassessment","İşi durdur, çalışanları çıkar ve tıbbi/atmosferik yeniden değerlendirme yap","Withdraw the symptomatic entrant and pause the remaining task pending checks","Belirti gösteren çalışanı çıkar, kontroller bitene kadar kalan işi beklet","Let the entrant rest near the manway while work continues","Çalışma sürerken çalışanın menhol yakınında dinlenmesine izin ver","Continue because the monitor has not alarmed","Cihaz alarm vermediği için devam et","symptoms as evidence of a possible atmospheric or heat-stress change","belirtileri olası atmosfer veya ısı stresi değişiminin kanıtı olarak"),
    step("sensor","One sensor is near calibration due date","Bir sensör kalibrasyon tarihine yakın","The multi-gas detector is in calibration, but its toxic sensor is due for service tomorrow and recently showed slow response during bump testing.","Çoklu gaz cihazının kalibrasyonu geçerli ancak toksik sensör yarın servise girecek ve son bump testte yavaş tepki gösterdi.","Replace or independently verify monitoring before any re-entry","Yeniden giriş öncesi cihazı değiştir veya bağımsız ölçümle doğrula","Keep entry suspended while a second calibrated detector is obtained","İkinci kalibre cihaz gelene kadar girişi askıda tut","Use the current detector with more frequent checks","Mevcut cihazı daha sık kontrolle kullan","Ignore the concern because the calibration certificate is still valid","Kalibrasyon belgesi geçerli olduğu için endişeyi dikkate alma","monitor reliability when symptoms conflict with instrument readings","belirtiler cihaz ölçümüyle çeliştiğinde ölçüm güvenilirliğini"),
    step("ventilation","Ventilation flow is lower than planned","Havalandırma debisi planlanandan düşük","The fan is running, but a kinked duct reduces airflow at the far end of the vessel.","Fan çalışıyor ancak kıvrılmış kanal tankın uzak ucunda hava debisini düşürüyor.","Correct airflow and verify distribution before re-entry","Yeniden giriş öncesi hava akışını düzelt ve dağılımı doğrula","Keep entry suspended while ducting is repositioned and retested","Kanal düzeltilip tekrar test edilirken girişi askıda tut","Increase fan speed without checking distribution","Dağılımı kontrol etmeden fan hızını artır","Re-enter because the fan itself is operating","Fan çalıştığı için yeniden gir","effective ventilation at the entrant's actual work location","çalışanın gerçek çalışma noktasındaki etkin havalandırmayı"),
    step("attendant","Attendant is pressured to enter","Gözcü içeri girmesi için baskı görüyor","The symptomatic worker left a tool bag inside. The supervisor asks the attendant to step in briefly to retrieve it.","Belirti gösteren çalışan içeride takım çantası bıraktı. Amir gözcüden kısa süreli içeri girip almasını istiyor.","Keep the attendant outside and retrieve items only under a revalidated entry plan","Gözcüyü dışarıda tut ve eşyayı yalnız yeniden doğrulanmış giriş planıyla al","Secure the space and wait for a properly authorized entrant","Alanı güvene al ve yetkili giriş personelini bekle","Let the attendant enter tethered for less than a minute","Gözcünün bağlı şekilde bir dakikadan kısa girmesine izin ver","Let the attendant enter without changing roles because the manway is open","Menhol açık olduğu için rol değiştirmeden gözcünün girmesine izin ver","attendant role integrity during an abnormal condition","anormal koşulda gözcü rol bütünlüğünü"),
    step("medical","Symptoms resolve outside","Belirtiler dışarıda geçiyor","After fresh air and rest, the worker feels normal and asks to re-enter to finish the job.","Temiz hava ve dinlenme sonrası çalışan normale dönüyor ve işi bitirmek için tekrar girmek istiyor.","Require medical clearance and root-cause review before considering re-entry","Yeniden giriş öncesi tıbbi onay ve kök neden incelemesi iste","Keep the worker out while another qualified entrant completes the task after controls are revalidated","Kontroller yeniden doğrulandıktan sonra işi başka yetkili çalışanla sürdür","Allow re-entry if the worker signs that symptoms have cleared","Belirtiler geçtiğine dair imza verirse yeniden girişe izin ver","Allow a short final entry with the manway attendant watching closely","Gözcü yakından izlerken kısa son girişe izin ver","fitness and cause verification after unexplained symptoms","açıklanamayan belirtiler sonrası uygunluk ve neden doğrulamasını"),
    step("isolation","A process valve position is questioned","Bir proses vanasının konumu sorgulanıyor","Operations notices one upstream valve indication does not match the isolation sheet, although no flow is detected.","Operasyon üst taraftaki bir vananın göstergesinin izolasyon formuyla eşleşmediğini fark ediyor ancak akış tespit edilmiyor.","Treat the discrepancy as isolation invalidation and verify the boundary before entry","Uyuşmazlığı izolasyon geçersizliği kabul et ve giriş öncesi sınırı doğrula","Keep entry suspended while Operations proves valve position locally","Operasyon vana konumunu sahada kanıtlarken girişi askıda tut","Continue because no flow or pressure is indicated","Akış veya basınç olmadığı için devam et","Rely on the isolation sheet because it was signed earlier","Daha önce imzalı olduğu için izolasyon formuna güven","physical proof of isolation when records and indications conflict","kayıt ve göstergeler çeliştiğinde izolasyonun fiziksel kanıtını"),
    step("rescue","Rescue team response time increases","Kurtarma ekibi müdahale süresi uzuyor","A site ambulance call removes two rescue-team members, doubling the estimated confined-space response time.","Saha ambulans çağrısı kurtarma ekibinden iki kişiyi alıyor ve tahmini kapalı alan müdahale süresini iki katına çıkarıyor.","Suspend entry until the required rescue capability is restored","Gerekli kurtarma kapasitesi geri gelene kadar girişi durdur","Maintain the space isolated and ready while replacement rescuers mobilize","Yedek kurtarıcılar gelirken alanı izole ve hazır tut","Continue with fewer rescuers because the entry is almost complete","Giriş bitmek üzere olduğu için daha az kurtarıcıyla devam et","Rely on external emergency services if another entrant becomes unwell","Başka çalışan rahatsızlanırsa dış acil servislere güven","planned rescue response time as a permit condition","planlanan kurtarma müdahale süresini izin koşulu olarak"),
    step("heat","Internal temperature has increased","İç sıcaklık yükselmiş","Ventilation changes improved gas readings but vessel temperature has risen several degrees.","Havalandırma değişikliği gaz ölçümlerini iyileştirdi ancak tank içi sıcaklık birkaç derece yükseldi.","Reassess work-rest limits, hydration and entry duration before restart","Yeniden başlatmadan önce çalışma-dinlenme, hidrasyon ve giriş süresini değerlendir","Shorten planned entry duration and add physiological monitoring","Planlanan giriş süresini kısalt ve fizyolojik izlem ekle","Keep the original work-rest cycle because gas readings are good","Gaz ölçümleri iyi olduğu için eski çalışma-dinlenme düzenini koru","Use the same entrant to avoid delaying the job","İşi geciktirmemek için aynı çalışanı kullan","heat-stress controls after ventilation and condition changes","havalandırma ve koşul değişimi sonrası ısı stresi kontrollerini"),
    step("reentry","All checks are acceptable again","Tüm kontroller yeniden uygun","Atmosphere, ventilation, isolation and rescue coverage are restored. The team wants immediate re-entry.","Atmosfer, havalandırma, izolasyon ve kurtarma kapsamı geri sağlandı. Ekip hemen yeniden girmek istiyor.","Revalidate the permit, brief the symptom event and define new stop triggers before re-entry","İzni yeniden doğrula, belirti olayını ekibe aktar ve yeni durdurma tetiklerini belirle","Conduct a focused re-entry brief covering changed controls","Değişen kontrolleri kapsayan odaklı yeniden giriş brifingi yap","Resume under the old permit because controls are back to normal","Kontroller normale döndüğü için eski izinle devam et","Re-enter first and update the permit after the task","Önce yeniden gir, izin güncellemesini iş sonrası yap","formal revalidation after an unexplained entrant-health event","açıklanamayan çalışan sağlık olayı sonrası resmi yeniden doğrulamayı"),
    step("closeout","The job finishes without further symptoms","İş başka belirti olmadan bitiyor","No alarms occur after re-entry and the job is completed.","Yeniden giriş sonrası alarm oluşmuyor ve iş tamamlanıyor.","Record the event, preserve monitoring data and close corrective actions before normalizing the lesson","Olayı kaydet, ölçüm verisini koru ve dersi normalleştirmeden düzeltici aksiyonları kapat","Complete a formal near-miss review with Operations and contractor supervision","Operasyon ve yüklenici amirleriyle resmi ramak kala incelemesi yap","Close the permit with no further action because there was no injury","Yaralanma olmadığı için ek aksiyon almadan izni kapat","Delete the abnormal readings once the permit is closed","İzin kapandıktan sonra anormal ölçümleri sil","learning and evidence preservation after a symptom event","belirti olayı sonrası öğrenme ve kanıt korumasını"),
  ],
});

const confinedIsolationDoubt = buildExpertScenario({
  id:"confined-space-isolation-doubt", titleEn:"Confined Space: Isolation Doubt", titleTr:"Kapalı Alan: İzolasyon Şüphesi", category:"Confined Space / Isolation",
  introEn:"A vessel entry is prepared against a complex process system. Drawings, valve tags and shift records do not fully agree on the isolation boundary.",
  introTr:"Karmaşık proses sistemine bağlı bir tank için giriş hazırlanıyor. Çizimler, vana etiketleri ve vardiya kayıtları izolasyon sınırında tam uyuşmuyor.",
  steps:[
    step("drawing","P&ID and field tag disagree","P&ID ile saha etiketi uyuşmuyor","The P&ID identifies XV-204, but the physical valve carries an older tag XV-204A.","P&ID XV-204'ü gösteriyor ancak sahadaki vana eski XV-204A etiketini taşıyor.","Stop and positively identify the component using field tracing and controlled drawings","Dur ve saha takibi ile kontrollü çizim kullanarak ekipmanı kesin tanımla","Hold entry while Operations and Engineering reconcile the tag history","Operasyon ve Mühendislik etiket geçmişini uzlaştırırken girişi beklet","Accept the valve because location and line size match the drawing","Konum ve hat çapı çizimle uyduğu için vanayı kabul et","Use the isolation sheet signature as proof of identity","İzolasyon formu imzasını kimlik kanıtı kabul et","positive equipment identification before relying on an isolation point","izolasyon noktasına güvenmeden kesin ekipman tanımlamasını"),
    step("shared-header","A shared header is discovered","Ortak kolektör tespit ediliyor","A small branch connects the vessel to another unit through a common vent header not shown on the entry sketch.","Giriş krokisinde görünmeyen küçük bir branş tankı ortak vent kolektörü üzerinden başka üniteye bağlıyor.","Expand the isolation review to include the shared header and connected unit","İzolasyon incelemesini ortak kolektör ve bağlı üniteyi kapsayacak şekilde genişlet","Keep entry suspended while the header service is traced","Kolektör servisi takip edilirken girişi askıda tut","Rely on the vessel's local valves because the branch is small","Branş küçük olduğu için tankın lokal vanalarına güven","Ignore the branch because no pressure is currently indicated","Şu an basınç olmadığı için branşı dikkate alma","all connected process paths, not only the main line","yalnız ana hat değil tüm bağlı proses yollarını"),
    step("blind","Blind thickness is undocumented","Kör flanş kalınlığı belgelenmemiş","A blind is installed, but its rating cannot be confirmed from markings or the isolation pack.","Kör flanş takılı ancak işaretlerden veya izolasyon paketinden basınç sınıfı doğrulanamıyor.","Verify blind rating and installation against the maximum credible pressure","Kör flanş sınıfı ve montajını olası maksimum basınca göre doğrula","Treat the blind as unverified until engineering records or replacement confirm rating","Mühendislik kaydı veya değişim sınıfı doğrulayana kadar körü doğrulanmamış kabul et","Accept the blind because it is physically present and not leaking","Fiziksel olarak var ve kaçırmadığı için körü kabul et","Enter because pressure has already been drained","Basınç zaten boşaltıldığı için giriş yap","mechanical isolation rating against credible pressure","mekanik izolasyon sınıfını olası basınca göre"),
    step("drain","A drain valve will not prove zero energy","Drenaj vanası sıfır enerjiyi kanıtlamıyor","The low-point drain passes only a few drops, making it unclear whether the vessel is empty or the drain is plugged.","Alçak nokta drenajından yalnız birkaç damla geliyor; tankın boş mu yoksa drenajın tıkalı mı olduğu belirsiz.","Use an independent method to prove zero pressure and clear the drain uncertainty","Bağımsız yöntemle sıfır basıncı kanıtla ve drenaj belirsizliğini gider","Keep entry suspended while the drain path is verified or cleared","Drenaj yolu doğrulanıp açılana kadar girişi beklet","Assume the vessel is depressurized because only drops appear","Yalnız damla geldiği için tankın basınçsız olduğunu varsay","Crack the manway slightly to confirm whether pressure remains","Basınç kaldı mı görmek için menholü hafif arala","positive zero-energy verification without using personnel as the test","personeli test aracı yapmadan pozitif sıfır enerji doğrulamasını"),
    step("control-room","Control-room indication conflicts with local gauge","Kontrol odası göstergesi lokal manometreyle çelişiyor","DCS shows zero pressure while the local gauge sits slightly above zero and is overdue for calibration.","DCS sıfır basınç gösterirken lokal manometre sıfırın biraz üstünde ve kalibrasyon süresi geçmiş.","Treat the conflict as unresolved and verify with an independent calibrated instrument","Çelişkiyi çözülmemiş kabul et ve bağımsız kalibre cihazla doğrula","Keep the space closed while both instruments are checked","İki cihaz kontrol edilirken alanı kapalı tut","Trust DCS because it is the primary process indication","Ana proses göstergesi olduğu için DCS'e güven","Trust the local gauge because it is physically closest","Fiziksel olarak yakın olduğu için lokal manometreye güven","independent verification when process indications conflict","proses göstergeleri çeliştiğinde bağımsız doğrulamayı"),
    step("ownership","Night shift changed one isolation","Gece vardiyası bir izolasyonu değiştirdi","The handover log notes a valve was repositioned for another maintenance task, but the entry isolation sheet was not revised.","Devir kaydı başka bakım işi için bir vananın konumunun değiştirildiğini gösteriyor ancak giriş izolasyon formu revize edilmemiş.","Invalidate the existing entry isolation and rewalk the affected boundary","Mevcut giriş izolasyonunu geçersiz say ve etkilenen sınırı yeniden sahada dolaş","Suspend entry until night-shift change is reconciled in the isolation pack","Gece vardiyası değişikliği izolasyon paketine işlenene kadar girişi beklet","Accept the current field position after verbal confirmation","Sözlü teyit sonrası mevcut saha konumunu kabul et","Ignore the log because the entry sheet has more signatures","Giriş formunda daha çok imza olduğu için devir kaydını dikkate alma","configuration control across shift changes","vardiya değişimlerinde konfigürasyon kontrolünü"),
    step("rescue","Rescue plan depends on a nozzle now isolated differently","Kurtarma planı artık farklı izole edilen nozüle bağlı","The rescue plan uses a side nozzle for retrieval, but a new blind arrangement partially obstructs it.","Kurtarma planı geri alma için yan nozülü kullanıyor ancak yeni körleme düzeni nozülü kısmen engelliyor.","Revise and physically prove the rescue route before entry","Giriş öncesi kurtarma güzergahını revize et ve sahada kanıtla","Hold entry while rescue equipment is repositioned and tested","Kurtarma ekipmanı yeniden konumlandırılıp test edilirken girişi beklet","Proceed because the main manway is still available","Ana menhol hâlâ mevcut olduğu için devam et","Use the blocked nozzle only if an emergency occurs","Acil durumda engelli nozülü kullanmayı planla","rescue feasibility after isolation configuration changes","izolasyon düzeni değişince kurtarma uygulanabilirliğini"),
    step("sample","A residue sample is unexpectedly reactive","Kalıntı numunesi beklenmedik reaktif","A wipe sample from the vessel bottom reacts with the field test kit in a way not predicted by the cleaning certificate.","Tank tabanından alınan sürüntü numunesi temizlik sertifikasında beklenmeyen şekilde saha test kitine tepki veriyor.","Stop entry preparation and identify the residue before relying on the cleaning certificate","Temizlik sertifikasına güvenmeden giriş hazırlığını durdur ve kalıntıyı tanımla","Maintain isolation and send a representative sample for confirmation","İzolasyonu koru ve temsili numuneyi doğrulamaya gönder","Proceed with upgraded PPE while awaiting identification","Tanımlama beklenirken daha yüksek KKD ile devam et","Ignore the field test because the cleaning certificate is signed","Temizlik sertifikası imzalı olduğu için saha testini yok say","verification of residual chemical hazards after cleaning","temizlik sonrası kalıntı kimyasal tehlikelerin doğrulanmasını"),
    step("pressure-test","Another unit schedules a pressure test","Başka ünite basınç testi planlıyor","A connected unit plans a hydrotest that could load the shared header during the entry window.","Bağlı ünite giriş süresinde ortak kolektörü yükleyebilecek hidrotest planlıyor.","Prevent the test from challenging the entry isolation or sequence the activities separately","Testin giriş izolasyonunu zorlamasını önle veya işleri ayrı sırala","Hold entry until the hydrotest is complete and boundary is reverified","Hidrotest bitip sınır tekrar doğrulanana kadar girişi beklet","Continue because the shared header has a closed valve","Ortak kolektörde kapalı vana olduğu için devam et","Allow both because hydrotest fluid is water","Hidrotest sıvısı su olduğu için ikisine de izin ver","protection of the entry isolation from external pressure sources","giriş izolasyonunun harici basınç kaynaklarından korunmasını"),
    step("release","All discrepancies are reconciled","Tüm uyuşmazlıklar çözüldü","Tags, blinds, drains, rescue route and connected systems have been reverified in the field.","Etiketler, körlemeler, drenajlar, kurtarma güzergahı ve bağlı sistemler sahada yeniden doğrulandı.","Issue a newly validated entry permit based on the rebuilt isolation boundary","Yeniden oluşturulan izolasyon sınırına göre yeni doğrulanmış giriş izni düzenle","Conduct a final joint field walkdown and then revalidate the permit","Son ortak saha turunu yap ve ardından izni yeniden doğrula","Reuse the original permit because the job scope did not change","İş kapsamı değişmediği için eski izni kullan","Let entrants begin while paperwork catches up","Evrak sonradan tamamlanırken çalışanların girmesine izin ver","formal permit revalidation after isolation reconstruction","izolasyon yeniden kurulunca resmi izin yeniden doğrulamasını"),
  ],
});

const lotoGroupLockout = buildExpertScenario({
  id:"loto-group-lockout", titleEn:"LOTO: Shift Change", titleTr:"LOTO: Vardiya Değişimi", category:"LOTO / Group Lockout",
  introEn:"A multi-craft shutdown task uses group lockout across two shifts. One worker is unaccounted for during handover and Operations is pressing for restart.",
  introTr:"Çok disiplinli shutdown işi iki vardiya boyunca grup kilitleme kullanıyor. Devir sırasında bir çalışan eksik ve Operasyon yeniden başlatma baskısı yapıyor.",
  steps:[
    step("missing","One worker is not at handover","Bir çalışan devirde yok","The lock box register shows a worker signed in, but the worker cannot be located at the normal shift-change point.","Kilit kutusu kaydı bir çalışanın giriş yaptığını gösteriyor ancak çalışan normal vardiya devir noktasında bulunamıyor.","Freeze lockout transfer and positively locate the worker before any lock removal","Herhangi kilit sökülmeden devri dondur ve çalışanı kesin olarak bul","Hold the box and verify workfronts, transport and supervisor records","Kutuyu kapalı tut, çalışma alanı/servis/amir kayıtlarını kontrol et","Proceed with handover because the worker's personal lock is still on the box","Kişisel kilidi kutuda olduğu için devre devam et","Cut the lock after calling the worker's phone twice","İki kez telefonla aradıktan sonra kilidi kes","positive personnel accountability before group-lock transfer","grup kilit devri öncesi kesin personel sayımını"),
    step("key","Primary lock-box key ownership changes","Ana kilit kutusu anahtar sorumluluğu değişiyor","The outgoing authorized person must leave before the incoming authorized person finishes reviewing the isolation list.","Çıkan yetkili kişi, yeni yetkili izolasyon listesini bitirmeden ayrılmak zorunda.","Maintain continuous authorized custody until review and formal transfer are complete","İnceleme ve resmi devir tamamlanana kadar kesintisiz yetkili anahtar sorumluluğunu koru","Delay outgoing release until the incoming person completes the critical isolation checks","Yeni yetkili kritik izolasyonları bitirene kadar çıkan kişinin ayrılışını geciktir","Leave the key sealed with the supervisor for later transfer","Anahtarı daha sonra devretmek üzere amirde mühürlü bırak","Leave the key in the control room because the box itself is locked","Kutu zaten kilitli olduğu için anahtarı kontrol odasında bırak","continuous custody of the group-lock control key","grup kilit kontrol anahtarının kesintisiz sorumluluğunu"),
    step("scope","A new task is added mid-handover","Devir sırasında yeni iş ekleniyor","Maintenance adds a flange job on equipment believed to be inside the existing group isolation.","Bakım mevcut grup izolasyonunun içinde olduğu düşünülen ekipmanda flanş işi ekliyor.","Verify the new task against the isolation boundary before adding workers to the box","Yeni çalışanları kutuya eklemeden işi izolasyon sınırına göre doğrula","Keep the new task out of scope until line tracing confirms coverage","Hat takibi kapsamı doğrulayana kadar yeni işi kapsam dışında tut","Add the task because the equipment shares the same unit number","Ekipman aynı ünite numarasını taşıdığı için işi ekle","Let the crew start cold work while isolation coverage is checked","İzolasyon kapsamı kontrol edilirken ekibin soğuk işe başlamasına izin ver","scope control when new work is introduced into group lockout","grup kilitlemeye yeni iş eklendiğinde kapsam kontrolünü"),
    step("stored","Stored hydraulic energy is found","Depolanmış hidrolik enerji bulunuyor","An actuator remains pressurized even though electrical and process isolations are locked.","Elektrik ve proses izolasyonları kilitli olmasına rağmen bir aktüatör basınçlı kalıyor.","Add, dissipate and verify the hydraulic energy isolation before work continues","İşe devam etmeden hidrolik enerji izolasyonunu ekle, boşalt ve doğrula","Suspend affected work while pressure is safely discharged and zero verified","Basınç güvenli boşaltılıp sıfır doğrulanırken etkilenen işi durdur","Secure the actuator mechanically and continue without updating the isolation list","İzolasyon listesini güncellemeden aktüatörü mekanik sabitleyip devam et","Assume the actuator cannot move because electrical power is isolated","Elektrik izole olduğu için aktüatör hareket edemez varsay","all hazardous-energy forms included in the group boundary","grup sınırına tüm tehlikeli enerji türlerinin dahil edilmesini"),
    step("register","Two names do not match badge IDs","İki isim yaka kartı ID'siyle uyuşmuyor","Contractor manpower was swapped during the shift and the lock register was updated by nickname only.","Vardiya sırasında taşeron personel değişti ve kilit kaydı yalnız lakapla güncellendi.","Stop additions/removals until every personal lock is reconciled to a unique worker ID","Her kişisel kilit benzersiz çalışan ID'siyle eşleşene kadar ekleme/sökme işlemini durdur","Reconcile the two entries with supervisor and badge records before continuing","Devam etmeden iki kaydı amir ve yaka kartı kayıtlarıyla uzlaştır","Accept supervisor verbal confirmation for the two names","İki isim için amirin sözlü teyidini kabul et","Remove unidentified locks if no one claims them at handover","Devirde kimse sahiplenmezse tanımsız kilitleri sök","one-to-one identity control for personal locks","kişisel kilitlerde birebir kimlik kontrolünü"),
    step("test","Incoming shift wants to skip try-test","Yeni vardiya try-test atlamak istiyor","The isolation was proven on day shift. Incoming workers argue no configuration changed and want to rely on the previous test.","İzolasyon gündüz vardiyasında kanıtlandı. Yeni ekip konfigürasyon değişmediğini söyleyip önceki teste güvenmek istiyor.","Require the defined verification/try-test for the incoming shift before work","Yeni vardiya işe başlamadan tanımlı doğrulama/try-test işlemini uygulat","Perform a representative verification of affected energy points before release","Serbest bırakmadan etkilenen enerji noktalarında temsili doğrulama yap","Accept prior verification if the register shows no isolation changes","Kayıtta izolasyon değişikliği yoksa önceki doğrulamayı kabul et","Let work start and repeat try-test only if a problem appears","İşi başlat, sorun çıkarsa try-test yap","shift-specific verification of continued zero-energy state","devam eden sıfır enerji durumunun vardiyaya özgü doğrulanmasını"),
    step("operations","Operations requests partial energization","Operasyon kısmi enerjilendirme istiyor","Operations needs to energize an auxiliary pump for another test while the group lock remains active on the main system.","Operasyon ana sistem grup kilit altındayken başka test için yardımcı pompayı enerjilendirmek istiyor.","Treat partial energization as a boundary change and formally separate or suspend affected work","Kısmi enerjilendirmeyi sınır değişikliği kabul et; etkilenen işi ayır veya askıya al","Freeze affected craft work while the auxiliary test is planned and isolated separately","Yardımcı test ayrı planlanıp izole edilirken etkilenen işleri dondur","Allow energization if the pump is outside the immediate work area","Pompa yakın çalışma alanı dışında ise enerjilendirmeye izin ver","Energize briefly while workers remain on the group lock box","Çalışanlar grup kutusunda kilitliyken kısa süre enerjilendir","control of temporary energization inside an active group-lock system","aktif grup kilit sistemi içinde geçici enerjilendirme kontrolünü"),
    step("absence","Missing worker is located off site","Eksik çalışan saha dışında bulunuyor","The missing worker left site sick without removing a personal lock or signing out.","Eksik çalışan rahatsızlanıp kişisel kilidini sökmeden ve çıkış yapmadan sahadan ayrılmış.","Use the formal absent-worker lock-removal procedure with independent verification","Resmi sahada olmayan çalışan kilit sökme prosedürünü bağımsız doğrulamayla uygula","Keep the system locked while supervisor and HSE complete the exception process","Amir ve HSE istisna sürecini tamamlarken sistemi kilitli tut","Remove the lock after confirming the worker is off site","Çalışanın saha dışında olduğunu doğrulayıp kilidi sök","Cut the lock immediately because Operations needs restart","Operasyon yeniden başlatma istediği için kilidi hemen kes","formal exception controls for absent-worker lock removal","sahada olmayan çalışan kilidi sökümünde resmi istisna kontrollerini"),
    step("release","Crafts begin clearing locks","Disiplinler kilitlerini kaldırıyor","Mechanical work is complete, but electrical troubleshooting is still active on a branch circuit within the same group boundary.","Mekanik iş bitti ancak aynı grup sınırındaki bir branş devrede elektrik arıza arama sürüyor.","Maintain group isolation until every affected craft and energy scope is formally clear","Her etkilenen disiplin ve enerji kapsamı resmi olarak kapanana kadar grup izolasyonunu koru","Allow completed crafts to remove personal locks while the master isolation remains controlled","Ana izolasyon kontrollü kalırken biten ekiplerin kişisel kilitlerini sökmesine izin ver","Begin restoring non-electrical energy because mechanical work is complete","Mekanik iş bittiği için elektrik dışı enerjileri geri ver","Release the master box once most personal locks are removed","Kişisel kilitlerin çoğu sökülünce ana kutuyu serbest bırak","complete scope clearance before group isolation release","grup izolasyonunu kaldırmadan tam kapsam temizliğini"),
    step("restart","Final restart is requested","Son yeniden başlatma isteniyor","All personal locks are removed, the register reconciles and Operations asks to restore energy immediately.","Tüm kişisel kilitler sökülmüş, kayıt uzlaşmış ve Operasyon enerjiyi hemen geri vermek istiyor.","Perform final area clearance, equipment status check and controlled energy restoration","Son alan temizliği, ekipman durum kontrolü ve kontrollü enerji geri verme yap","Complete a joint Operations-Maintenance walkdown before restoration","Enerji vermeden Operasyon-Bakım ortak saha turu yap","Restore energy based on the cleared register alone","Yalnız temizlenmiş kayda dayanarak enerjiyi geri ver","Restore remotely while crews are still leaving the area","Ekipler alanı terk ederken uzaktan enerji ver","final field clearance before controlled re-energization","kontrollü yeniden enerjilendirme öncesi son saha temizliğini"),
  ],
});

const lotoComplexIsolation = buildExpertScenario({
  id:"loto-complex-isolation", titleEn:"LOTO: Complex Isolation Boundary", titleTr:"LOTO: Karmaşık İzolasyon Sınırı", category:"LOTO / Process Isolation",
  introEn:"A maintenance scope crosses electrical, hydraulic, pneumatic and process-energy boundaries. Drawings have recent redlines and one isolation owner disputes responsibility for a shared system.",
  introTr:"Bakım kapsamı elektrik, hidrolik, pnömatik ve proses enerji sınırlarını kesiyor. Çizimlerde yeni redline'lar var ve bir izolasyon sahibi ortak sistem sorumluluğunu tartışıyor.",
  steps:[
    step("redline","Redlined drawing differs from controlled P&ID","Redline çizim kontrollü P&ID'den farklı","A recent field modification appears only on a redlined print and adds a bypass around one isolation point.","Yakın tarihli saha değişikliği yalnız redline çizimde görünüyor ve bir izolasyon noktasını by-pass eden hat ekliyor.","Trace the modification in the field and incorporate it into the approved isolation boundary","Değişikliği sahada takip et ve onaylı izolasyon sınırına dahil et","Hold work while Engineering validates the redline against as-built condition","Mühendislik redline'ı as-built durumla doğrularken işi beklet","Use the controlled P&ID because redlines are unofficial","Redline resmi olmadığı için kontrollü P&ID'yi kullan","Ignore the bypass if its valve is normally closed","Vanası normalde kapalı olduğu için by-pass'ı dikkate alma","configuration control for undocumented modifications","belgelenmemiş değişikliklerde konfigürasyon kontrolünü"),
    step("hydraulic","Hydraulic accumulator retains pressure","Hidrolik akümülatör basınç tutuyor","Electrical isolation is proven, but a pressure gauge on the accumulator remains above zero.","Elektrik izolasyonu kanıtlı ancak akümülatör manometresi sıfırın üzerinde kalıyor.","Isolate, discharge and prove zero hydraulic energy before mechanical work","Mekanik iş öncesi hidrolik enerjiyi izole et, boşalt ve sıfırı kanıtla","Keep mechanical work suspended while the accumulator is safely bled down","Akümülatör güvenli boşaltılırken mekanik işi askıda tut","Install a mechanical restraint and proceed while pressure remains","Basınç kalırken mekanik sabitleme yapıp devam et","Treat electrical isolation as sufficient because controls cannot actuate","Kontroller çalışamayacağı için elektrik izolasyonunu yeterli kabul et","stored hydraulic energy independent of electrical isolation","elektrik izolasyonundan bağımsız depolanmış hidrolik enerjiyi"),
    step("pneumatic","Instrument air can re-pressurize an actuator","Enstrüman havası aktüatörü yeniden basınçlandırabilir","A solenoid is de-energized, but the actuator still has instrument-air supply through a local manifold.","Solenoid enerjisiz ancak aktüatör lokal manifold üzerinden enstrüman havası alıyor.","Isolate and vent instrument air, then verify actuator state","Enstrüman havasını izole edip tahliye et, sonra aktüatör durumunu doğrula","Block the actuator mechanically while air isolation is established","Hava izolasyonu kurulurken aktüatörü mekanik sabitle","Rely on the de-energized solenoid to prevent movement","Hareketi önlemek için enerjisiz solenoide güven","Disconnect the air tube at the actuator as the primary isolation","Ana izolasyon olarak aktüatörde hava hortumunu sök","all secondary energy supplies capable of movement","hareket oluşturabilecek tüm ikincil enerji kaynaklarını"),
    step("shared-steam","A shared steam tracing header crosses the scope","Ortak buhar tracing kolektörü kapsamdan geçiyor","The equipment is process-isolated, but steam tracing remains live and can heat trapped material in a dead leg.","Ekipman proses olarak izole ancak buhar tracing canlı ve kör uçta hapsolmuş malzemeyi ısıtabilir.","Include tracing isolation and trapped-thermal-energy control in the boundary","Tracing izolasyonu ve hapsolmuş ısıl enerji kontrolünü sınıra dahil et","Suspend opening work while tracing is isolated and temperature stabilizes","Tracing izole edilip sıcaklık stabilize olana kadar açma işini beklet","Continue because tracing does not move the main equipment","Tracing ana ekipmanı hareket ettirmediği için devam et","Use heat-resistant PPE instead of isolating the tracing","Tracing izolasyonu yerine ısıya dayanıklı KKD kullan","thermal energy and pressure generation from live tracing","canlı tracing kaynaklı ısıl enerji ve basınç oluşumunu"),
    step("owner","Two departments dispute a boundary valve","İki bölüm sınır vanasını tartışıyor","Utilities says the valve belongs to Process; Process says Utilities owns it and neither will sign final verification.","Utilities vananın Prosese ait olduğunu, Proses ise Utilities'e ait olduğunu söylüyor ve ikisi de son doğrulamayı imzalamıyor.","Stop until one accountable owner is assigned and the valve is jointly verified","Tek sorumlu atanıp vana ortak doğrulanana kadar dur","Escalate ownership while keeping the work boundary frozen","Sorumluluğu eskale ederken çalışma sınırını dondur","Accept both departments' verbal agreement that the valve is closed","İki bölümün vananın kapalı olduğuna dair sözlü mutabakatını kabul et","Proceed because ownership is administrative rather than technical","Sorumluluk idari olduğu için devam et","accountable ownership of each isolation point","her izolasyon noktasının sorumlu sahipliğini"),
    step("drain","Drain path shares a live collection system","Drenaj yolu canlı toplama sistemini paylaşıyor","Depressurization drains into a header receiving intermittent flow from another unit.","Basınç boşaltma hattı başka üniteden aralıklı akış alan ortak kolektöre bağlanıyor.","Protect against backflow or isolate the shared drain before relying on depressurization","Basınç boşaltmaya güvenmeden geri akışı önle veya ortak drenajı izole et","Hold opening work while the drain header interface is controlled","Drenaj kolektör arayüzü kontrol edilirken açma işini beklet","Continue if local pressure reads zero","Lokal basınç sıfırsa devam et","Leave the drain open and assume any backflow will be visible","Drenajı açık bırak, geri akışın görünür olacağını varsay","backflow risk through shared drain systems","ortak drenaj sistemlerinde geri akış riskini"),
    step("test","Zero-energy test gives mixed results","Sıfır enerji testi karışık sonuç veriyor","Electrical try-test is satisfactory, but one actuator moves slightly when manual override is touched.","Elektrik try-test uygun ancak manuel override'a dokunulunca bir aktüatör hafif hareket ediyor.","Treat any movement as failed zero-energy verification and identify the source","Her hareketi başarısız sıfır enerji doğrulaması kabul et ve kaynağı bul","Keep work suspended while mechanical and fluid energy paths are rechecked","Mekanik ve akışkan enerji yolları tekrar kontrol edilirken işi beklet","Accept small movement as stored mechanical slack","Küçük hareketi mekanik boşluk olarak kabul et","Repeat the test until the actuator stops moving and then proceed without investigation","Aktüatör durana kadar testi tekrarla, nedeni araştırmadan devam et","zero-energy verification across every energy form","her enerji türünde sıfır enerji doğrulamasını"),
    step("scope-change","Maintenance changes the dismantling sequence","Bakım söküm sırasını değiştiriyor","The crew wants to remove a component earlier, exposing a section outside the originally verified isolation boundary.","Ekip bir parçayı daha erken sökmek istiyor ve bu, ilk doğrulanan izolasyon sınırı dışındaki bölümü açığa çıkarıyor.","Stop and revalidate the isolation against the revised dismantling sequence","Dur ve revize söküm sırasına göre izolasyonu yeniden doğrula","Keep work inside the original sequence until the boundary is extended","Sınır genişletilene kadar işi ilk sıranın içinde tut","Allow the sequence change because the same equipment remains locked out","Aynı ekipman kilitli olduğu için sıra değişikliğine izin ver","Remove the component and assess the new boundary afterward","Parçayı sök, yeni sınırı sonra değerlendir","scope-dependent validity of the isolation boundary","izolasyon sınırının iş kapsamına bağlı geçerliliğini"),
    step("handover","Isolation spans a 24-hour handover","İzolasyon 24 saatlik devri aşıyor","Three departments and two contractor teams must hand over a boundary containing sixteen isolation points.","On altı izolasyon noktası içeren sınır üç bölüm ve iki taşeron ekibine devredilmeli.","Perform structured point-by-point handover for critical isolations and ownership changes","Kritik izolasyonlar ve sorumluluk değişimleri için nokta nokta yapılandırılmış devir yap","Keep work suspended until incoming owners sign and field-check assigned points","Yeni sahipler atanmış noktaları imzalayıp sahada kontrol edene kadar işi beklet","Rely on the master isolation list and signatures only","Yalnız ana izolasyon listesi ve imzalara güven","Hand over by email because the boundary is already established","Sınır zaten kurulu olduğu için e-postayla devir yap","control continuity across multi-owner isolation handover","çok sahipli izolasyon devrinde kontrol sürekliliğini"),
    step("restart","Energy restoration sequence is complex","Enerji geri verme sırası karmaşık","Process, instrument air, hydraulic power and electrical supply must be restored in a defined sequence to prevent unintended movement.","İstenmeyen hareketi önlemek için proses, enstrüman havası, hidrolik ve elektrik belirli sırayla geri verilmeli.","Use a controlled restoration plan with area clearance and stepwise verification","Alan temizliği ve adım adım doğrulamalı kontrollü enerji geri verme planı kullan","Restore one energy source at a time with hold points between steps","Enerji kaynaklarını aralarda duraklama noktalarıyla tek tek geri ver","Restore utilities together to save time after personnel clear","Personel çıktıktan sonra zaman kazanmak için yardımcı enerjileri birlikte ver","Restore remotely from the control room once locks are removed","Kilitler sökülünce kontrol odasından uzaktan enerji ver","sequenced re-energization to prevent unexpected movement or pressure","beklenmeyen hareket veya basıncı önleyen sıralı yeniden enerjilendirmeyi"),
  ],
});

export const expertPackOne = {
  [hotWorkProcessInstability.id]: hotWorkProcessInstability,
  [hotWorkSimopsShutdown.id]: hotWorkSimopsShutdown,
  [heightWeatherRescue.id]: heightWeatherRescue,
  [heightSimopsLift.id]: heightSimopsLift,
  [confinedEntrantSymptoms.id]: confinedEntrantSymptoms,
  [confinedIsolationDoubt.id]: confinedIsolationDoubt,
  [lotoGroupLockout.id]: lotoGroupLockout,
  [lotoComplexIsolation.id]: lotoComplexIsolation,
};
