import { buildExpertBlueprint, type ExpertStage } from "./expert-blueprint";

const s=(id:string,titleEn:string,titleTr:string,situationEn:string,situationTr:string,focusEn:string,focusTr:string):ExpertStage=>({id,titleEn,titleTr,situationEn,situationTr,focusEn,focusTr});

const chemicalReleaseUnknown=buildExpertBlueprint({id:"chemical-release-unknown",titleEn:"Chemical Release: Substance Unknown",titleTr:"Kimyasal Salım: Madde Bilinmiyor",category:"Chemical / Emergency",introEn:"A visible vapor release is detected near a chemical transfer area. Labels, SDS references and process information do not initially agree on the substance involved.",introTr:"Kimyasal transfer alanı yakınında görünür bir buhar salımı tespit ediliyor. Etiketler, SDS referansları ve proses bilgisi başlangıçta hangi maddenin salındığı konusunda uyuşmuyor.",stages:[
s("plume","A visible plume appears","Görünür bulut oluşuyor","Workers report eye irritation near a low drifting vapor cloud, but the source line is not yet identified.","Çalışanlar alçaktan sürüklenen buhar bulutu yakınında göz yanması bildiriyor ancak kaynak hat henüz tanımlanmadı.","initial isolation and conservative hazard assumption","ilk izolasyon ile muhafazakâr tehlike varsayımını"),
s("label","Container label conflicts with transfer sheet","Kap etiketi transfer formuyla çelişiyor","The tote label shows one product while the transfer sheet lists another compatible-looking chemical.","IBC etiketi bir ürünü gösterirken transfer formu benzer görünen başka bir kimyasalı listeliyor.","positive chemical identification before response selection","müdahale yöntemi seçmeden pozitif kimyasal tanımlamayı"),
s("sds","Two SDS files are available","İki SDS dosyası var","The control room finds two SDS revisions with different emergency PPE recommendations.","Kontrol odası farklı acil KKD önerileri olan iki SDS revizyonu buluyor.","authoritative SDS revision and product identity","yetkili SDS revizyonu ile ürün kimliğini"),
s("wind","Wind shifts toward occupied cabins","Rüzgar dolu kabinlere dönüyor","The wind turns and the plume path now points toward occupied contractor cabins.","Rüzgar dönüyor ve yayılım yolu dolu yüklenici kabinlerine yöneliyor.","dynamic downwind exclusion and evacuation boundary","dinamik rüzgar altı yasak ve tahliye sınırını"),
s("meter","Gas detector response is inconclusive","Gaz dedektörü net sonuç vermiyor","The available detector shows no alarm, but its sensor list does not specifically cover the suspected vapor.","Mevcut dedektör alarm vermiyor ancak sensör listesi şüpheli buharı özel olarak kapsamıyor.","instrument suitability for the suspected substance","şüpheli madde için cihaz uygunluğunu"),
s("ppe","Responder proposes cartridge respirator","Müdahaleci kartuşlu maske öneriyor","A trained responder suggests approaching with an organic-vapor cartridge while identity remains uncertain.","Eğitimli müdahaleci madde kimliği belirsizken organik buhar kartuşuyla yaklaşmayı öneriyor.","respiratory protection based on confirmed contaminant and concentration","doğrulanmış kirletici ve konsantrasyona göre solunum korumasını"),
s("drain","Liquid reaches a storm drain","Sıvı yağmur drenajına ulaşıyor","A small liquid pool begins moving toward an open storm-water drain.","Küçük sıvı birikintisi açık yağmur suyu drenajına doğru ilerliyor.","secondary containment without exposing unprotected personnel","korumasız personeli maruz bırakmadan ikincil çevreleme kontrolünü"),
s("account","One contractor is unaccounted for","Bir taşeron eksik","Muster shows one person missing from a nearby work group last seen near the transfer area.","Toplanmada transfer alanı yakınında en son görülen çalışma grubundan bir kişi eksik.","rescue escalation without spontaneous entry into unknown atmosphere","bilinmeyen atmosfere kontrolsüz giriş yapmadan kurtarma eskalasyonunu"),
s("source","Source valve is identified remotely","Kaynak vana uzaktan tanımlanıyor","Operations believes a remote valve will stop the leak, but field position feedback is unavailable.","Operasyon uzaktan bir vananın sızıntıyı durduracağını düşünüyor ancak saha konum geri bildirimi yok.","verified source isolation and confirmation of leak cessation","doğrulanmış kaynak izolasyonu ile sızıntının durduğunun teyidini"),
s("reentry","Readings and symptoms improve","Ölçümler ve belirtiler iyileşiyor","The plume is no longer visible and exposed workers report improvement, but the substance identity was only recently confirmed.","Bulut artık görünmüyor ve maruz kalanlar iyileşme bildiriyor ancak madde kimliği ancak kısa süre önce doğrulandı.","formal re-entry criteria after an unknown-chemical release","bilinmeyen kimyasal salımı sonrası resmi yeniden giriş kriterlerini") ]});

const processReleaseSimops=buildExpertBlueprint({id:"process-release-simops",titleEn:"Process Release: Contractors in the Plume",titleTr:"Proses Salımı: Yayılım Alanında Taşeronlar",category:"Process Safety / SIMOPS",introEn:"A process leak develops during heavy contractor activity. Changing wind, incomplete headcounts and competing isolation actions complicate emergency command.",introTr:"Yoğun taşeron faaliyeti sırasında proses sızıntısı gelişiyor. Değişen rüzgar, eksik personel sayımı ve çakışan izolasyon müdahaleleri acil durum komutasını zorlaştırıyor.",stages:[
s("alarm","Local alarm activates","Yerel alarm devreye giriyor","A hydrocarbon detector alarms near a unit where several contractor crews are working under different permits.","Farklı izinlerle çalışan birkaç taşeron ekibinin bulunduğu ünitede hidrokarbon dedektörü alarm veriyor.","immediate permit suspension and area accountability","anlık izin askıya alma ile alan personel sayımını"),
s("plume","Wind drives plume across escape route","Rüzgar bulutu kaçış yoluna sürüklüyor","The designated escape route becomes downwind of the release.","Belirlenen kaçış yolu salımın rüzgar altına geçiyor.","dynamic evacuation routing based on plume movement","bulut hareketine göre dinamik tahliye güzergahını"),
s("count","Contractor headcount is inconsistent","Taşeron sayımı tutarsız","Two supervisors report different numbers for the same crew because one worker changed workfronts.","Bir çalışanın çalışma alanı değiştirmesi nedeniyle iki amir aynı ekip için farklı sayı bildiriyor.","single reconciled personnel accountability record","tek uzlaştırılmış personel sayım kaydını"),
s("isolation","Two isolation options compete","İki izolasyon seçeneği yarışıyor","Operations can trip the unit immediately or attempt a local valve isolation that may reduce production impact.","Operasyon üniteyi hemen trip edebilir veya üretim etkisini azaltabilecek yerel vana izolasyonu deneyebilir.","risk-based source isolation under an active release","aktif salım altında risk temelli kaynak izolasyonunu"),
s("hotwork","Nearby hot work has not stopped","Yakındaki sıcak iş durmamış","A contractor outside the alarmed zone continues grinding because their permit area did not receive the first alarm.","Alarm bölgesi dışında bir yüklenici ilk alarmı almadığı için taşlamaya devam ediyor.","site-wide ignition-source control as plume boundaries change","bulut sınırları değişirken saha genel ateşleme kaynağı kontrolünü"),
s("rescue","A worker reports dizziness by phone","Bir çalışan telefonda baş dönmesi bildiriyor","A worker calls from a shelter-in-place room inside the affected unit and says they feel dizzy.","Bir çalışan etkilenen ünite içindeki sığınma odasından arayıp baş dönmesi yaşadığını söylüyor.","managed rescue under uncertain atmospheric conditions","belirsiz atmosferik koşullarda kontrollü kurtarmayı"),
s("command","Operations and emergency team disagree","Operasyon ve acil ekip anlaşamıyor","Operations wants a local response while the emergency controller wants full-area evacuation.","Operasyon yerel müdahale isterken acil durum kontrolörü tüm alan tahliyesi istiyor.","single emergency command authority and escalation criteria","tek acil durum komuta yetkisi ile eskalasyon kriterini"),
s("drain","Release enters closed drain system","Salım kapalı drenaja giriyor","The leaking liquid reaches a closed drain that connects to another process area.","Sızan sıvı başka proses alanına bağlı kapalı drenaj sistemine ulaşıyor.","secondary migration pathways beyond the visible plume","görünür bulut dışındaki ikincil yayılım yollarını"),
s("weather","Wind direction reverses","Rüzgar yönü tersine dönüyor","The previously safe muster point becomes potentially downwind.","Daha önce güvenli olan toplanma noktası potansiyel rüzgar altına geçiyor.","continuous reassessment of muster and exclusion zones","toplanma ve yasak bölgelerin sürekli yeniden değerlendirilmesini"),
s("recovery","Leak is stopped","Sızıntı durduruldu","The source is isolated and detectors fall, but several permits and contractor workfronts were disrupted during the event.","Kaynak izole ve dedektör değerleri düşüyor ancak olay sırasında birçok izin ve taşeron çalışma alanı etkilendi.","controlled area re-entry and permit-by-permit recovery","kontrollü alan yeniden girişi ile izin bazında toparlanmayı") ]});

const mobileEquipmentCongestion=buildExpertBlueprint({id:"mobile-equipment-congestion",titleEn:"Mobile Equipment: Congested Workfront",titleTr:"Hareketli Ekipman: Sıkışık Çalışma Alanı",category:"Mobile Equipment / Logistics",introEn:"Multiple vehicles, pedestrians and temporary routes converge around a high-production workfront. Controls that worked in the morning degrade as congestion builds.",introTr:"Birden fazla araç, yaya ve geçici güzergah yüksek üretimli çalışma alanında kesişiyor. Sabah çalışan kontroller sıkışıklık arttıkça bozuluyor.",stages:[
s("queue","Vehicle queue blocks sight lines","Araç kuyruğu görüşü kapatıyor","Three trucks queue beside the pedestrian crossing, hiding approaching people from a loader operator.","Üç kamyon yaya geçidi yanında kuyruk oluşturup yükleyici operatörünün yaklaşan yayaları görmesini engelliyor.","restored visibility and pedestrian segregation","yeniden sağlanan görüş ile yaya ayrımını"),
s("route","Temporary one-way route becomes two-way","Geçici tek yön çift yöne dönüyor","A blocked exit causes drivers to use the inbound lane for both directions.","Kapalı çıkış sürücülerin giriş şeridini iki yönlü kullanmasına neden oluyor.","traffic-plan validity after route reversal","güzergah tersine dönünce trafik planı geçerliliğini"),
s("spotter","One spotter covers two machines","Bir işaretçi iki makineyi yönetiyor","The same banksman is asked to control a reversing truck and an excavator swing zone.","Aynı işaretçiden geri giden kamyon ile ekskavatör dönüş bölgesini yönetmesi isteniyor.","dedicated signaling attention for simultaneous movements","eş zamanlı hareketler için özel işaretçi dikkatini"),
s("radio","Drivers use different radio channels","Sürücüler farklı telsiz kanalları kullanıyor","Subcontractor trucks are on another channel and cannot hear site movement instructions.","Alt yüklenici kamyonları farklı kanalda ve saha hareket talimatlarını duyamıyor.","common communication protocol across vehicle operators","araç operatörleri arasında ortak iletişim protokolünü"),
s("pedestrian","Shortcut appears through staging area","Stok alanından kestirme yol oluşuyor","Workers begin walking between parked trailers because the official walkway is longer.","Çalışanlar resmi yaya yolu daha uzun olduğu için park edilmiş treylerlerin arasından yürümeye başlıyor.","physical pedestrian routing rather than behavioral expectation","davranış beklentisi yerine fiziksel yaya yönlendirmesini"),
s("lighting","Dusk reduces visibility","Alacakaranlık görüşü düşürüyor","Dust and low light make reflective vests harder to see from machine cabs.","Toz ve düşük ışık reflektif yelekleri makine kabinlerinden görmeyi zorlaştırıyor.","visibility controls as environmental conditions deteriorate","çevresel koşullar kötüleşirken görüş kontrollerini"),
s("delivery","Unscheduled delivery enters","Plansız teslimat giriyor","A delivery truck unfamiliar with the site arrives during peak movement and follows another vehicle through the gate.","Sahayı bilmeyen teslimat kamyonu yoğun saatte geliyor ve başka aracı takip ederek kapıdan giriyor.","site induction and controlled routing for unfamiliar drivers","sahayı bilmeyen sürücüler için oryantasyon ile kontrollü güzergahı"),
s("alarm","Reversing alarm is intermittent","Geri vites alarmı aralıklı","A telehandler's reversing alarm works intermittently, but cameras remain operational.","Teleskopik yükleyicinin geri vites alarmı aralıklı çalışıyor ancak kameraları çalışıyor.","equipment defect management without substituting unrelated controls","ilgisiz kontrolleri ikame etmeden ekipman arıza yönetimini"),
s("pressure","Production asks to keep all lanes open","Üretim tüm şeritleri açık tutmak istiyor","The logistics lead resists closing one route because truck turnaround time is already high.","Lojistik sorumlusu kamyon çevrim süresi yüksek olduğu için bir güzergahın kapatılmasına karşı çıkıyor.","traffic density reduction before exposure becomes unmanageable","maruziyet yönetilemez olmadan trafik yoğunluğunu azaltmayı"),
s("reset","Shift change doubles pedestrian flow","Vardiya değişimi yaya akışını ikiye katlıyor","Incoming and outgoing crews overlap with deliveries for twenty minutes.","Gelen ve çıkan vardiyalar yirmi dakika boyunca teslimatlarla çakışıyor.","planned movement reset during predictable peak interface","öngörülebilir yoğun arayüz sırasında planlı hareket sıfırlamasını") ]});

const mobileEquipmentSimops=buildExpertBlueprint({id:"mobile-equipment-simops",titleEn:"Mobile Equipment: SIMOPS Crossing",titleTr:"Hareketli Ekipman: SIMOPS Geçişi",category:"Mobile Equipment / SIMOPS",introEn:"A heavy transport convoy must cross an active construction zone where cranes, pedestrians and temporary access routes are already operating.",introTr:"Ağır nakliye konvoyu vinçlerin, yayaların ve geçici erişim yollarının zaten aktif olduğu inşaat alanından geçmek zorunda.",stages:[
s("route","Convoy route overlaps a crane exclusion zone","Konvoy güzergahı vinç yasak bölgesiyle çakışıyor","The transport path crosses a crane tail-swing boundary for 25 metres.","Nakliye güzergahı 25 metre boyunca vinç kuyruk dönüş sınırını kesiyor.","single coordinated control of convoy and crane movements","konvoy ile vinç hareketlerinin tek koordineli kontrolünü"),
s("bridge","Temporary crossing load is uncertain","Geçici geçiş yük kapasitesi belirsiz","The convoy axle load is higher than the vehicle normally using the temporary crossing.","Konvoy aks yükü geçici geçişi normal kullanan araçtan daha yüksek.","structural capacity of the temporary crossing for actual axle loads","gerçek aks yükleri için geçici geçişin yapısal kapasitesini"),
s("escort","Escort visibility is broken","Eskort görüşü kesiliyor","A building corner prevents the lead escort from seeing the rear transporter.","Bina köşesi ön eskortun arka taşıyıcıyı görmesini engelliyor.","continuous convoy communication through blind sections","kör bölümlerde kesintisiz konvoy iletişimini"),
s("ped","Pedestrian route cannot fully close","Yaya güzergahı tamamen kapanamıyor","A canteen access path crosses the convoy route and remains heavily used.","Yemekhane erişim yolu konvoy güzergahını kesiyor ve yoğun kullanılmaya devam ediyor.","physical pedestrian hold points during convoy passage","konvoy geçişi sırasında fiziksel yaya bekleme noktalarını"),
s("slope","Transporter pauses on gradient","Taşıyıcı eğimde duruyor","The transporter must stop on a gradient while another workfront clears ahead.","Öndeki çalışma alanı boşalırken taşıyıcı eğimde durmak zorunda.","vehicle stability and restart capability on the gradient","eğimde araç stabilitesi ile yeniden hareket kabiliyetini"),
s("weather","Rain reduces tire-ground friction","Yağmur lastik-zemin sürtünmesini düşürüyor","Light rain starts on a compacted but dusty temporary road.","Sıkıştırılmış ancak tozlu geçici yolda hafif yağmur başlıyor.","route traction under changing surface conditions","değişen yüzey koşullarında güzergah çekişini"),
s("crane","Crane operator asks for a short lift window","Vinç operatörü kısa kaldırma penceresi istiyor","The crane team wants to complete one suspended-load movement while the convoy waits nearby.","Vinç ekibi konvoy yakında beklerken bir askıdaki yük hareketini tamamlamak istiyor.","separation of suspended-load and heavy-transport hazards","askıdaki yük ile ağır nakliye tehlikelerinin ayrımını"),
s("power","Overhead line clearance becomes tight","Havai hat açıklığı daralıyor","The transporter deck height increases slightly after suspension adjustment.","Süspansiyon ayarından sonra taşıyıcı tabla yüksekliği biraz artıyor.","verified overhead electrical clearance at actual transport height","gerçek nakliye yüksekliğinde doğrulanmış elektrik açıklığını"),
s("authority","Two marshals give different instructions","İki işaretçi farklı talimat veriyor","Construction and logistics marshals each believe they control the crossing point.","İnşaat ve lojistik işaretçilerinin her biri geçiş noktasını kendisinin yönettiğini düşünüyor.","single movement authority at the SIMOPS crossing","SIMOPS geçişinde tek hareket yetkisini"),
s("final","Convoy is close to destination","Konvoy hedefe yakın","The last 50 metres require entering a work area that has not yet completed its planned shutdown.","Son 50 metre planlanan duruşunu henüz tamamlamamış çalışma alanına girmeyi gerektiriyor.","final area handover before convoy entry","konvoy girişinden önce son alan devrini") ]});

const fireEmergencyMissingPerson=buildExpertBlueprint({id:"fire-emergency-missing-person",titleEn:"Fire & Emergency: Person Unaccounted For",titleTr:"Yangın ve Acil Durum: Bir Kişi Eksik",category:"Emergency Response",introEn:"A process-area fire is controlled to one zone, but muster reports one person missing. Smoke conditions, conflicting witness reports and rescue pressure complicate command decisions.",introTr:"Proses alanı yangını bir bölgede kontrol altında ancak toplanmada bir kişi eksik. Duman koşulları, çelişkili görgü bilgileri ve kurtarma baskısı komuta kararlarını zorlaştırıyor.",stages:[
s("count","Muster shows one person missing","Toplanmada bir kişi eksik","The electronic roster and supervisor headcount differ by one person.","Elektronik liste ile amir sayımı bir kişi farklı.","positive reconciliation of the missing-person identity","eksik kişinin kimliğinin pozitif uzlaştırmasını"),
s("lastseen","Witness reports conflict","Son görülme bilgileri çelişiyor","One worker says the missing person left the unit; another saw them near the fire area shortly before alarm.","Bir çalışan eksik kişinin üniteden çıktığını, diğeri alarmdan kısa süre önce yangın alanı yakınında gördüğünü söylüyor.","validated last-known-location information","doğrulanmış son bilinen konum bilgisini"),
s("smoke","Smoke boundary worsens","Duman sınırı kötüleşiyor","Visibility at the access route falls and gas readings begin changing.","Erişim güzergahında görüş düşüyor ve gaz ölçümleri değişmeye başlıyor.","rescue entry criteria under deteriorating atmosphere","kötüleşen atmosferde kurtarma giriş kriterini"),
s("volunteer","Coworker offers to search","İş arkadaşı aramayı teklif ediyor","A coworker familiar with the area asks to enter with an escape hood.","Alanı iyi bilen bir iş arkadaşı kaçış maskesiyle içeri girmeyi teklif ediyor.","trained rescue team deployment rather than spontaneous entry","kontrolsüz giriş yerine eğitimli kurtarma ekibi sevkini"),
s("firewater","Firewater limits access","Yangın suyu erişimi etkiliyor","Runoff creates slippery access and begins flooding a low-level route.","Yangın suyu kaygan erişim oluşturuyor ve alçak güzergahı su basmaya başlıyor.","secondary access hazards during rescue deployment","kurtarma sevkinde ikincil erişim tehlikelerini"),
s("phone","Missing person's phone rings","Eksik kişinin telefonu çalıyor","A phone signal appears from inside the unit but location accuracy is poor.","Ünite içinden telefon sinyali geliyor ancak konum doğruluğu düşük.","use of uncertain location data without narrowing rescue controls","kurtarma kontrollerini gevşetmeden belirsiz konum verisi kullanımını"),
s("command","Family information reaches command","Aile bilgisi komutaya geliyor","A supervisor says the missing worker may have left early for a medical appointment, but this was not logged.","Amir eksik çalışanın sağlık randevusu için erken ayrılmış olabileceğini ancak bunun kaydedilmediğini söylüyor.","accountability evidence before downgrading rescue urgency","kurtarma aciliyetini düşürmeden personel sayım kanıtını"),
s("team","Rescue team reaches hold point","Kurtarma ekibi bekleme noktasına geliyor","The rescue team is ready, but process isolation of the affected equipment is not fully confirmed.","Kurtarma ekibi hazır ancak etkilenen ekipmanın proses izolasyonu tam doğrulanmamış.","rescue entry versus unresolved process-energy hazards","kurtarma girişi ile çözülmemiş proses enerji tehlikelerini"),
s("found","Badge scan appears at another gate","Başka kapıda kart geçişi görünüyor","A recent badge event suggests the person may be outside the emergency zone, but camera confirmation is unavailable.","Yeni kart kaydı kişinin acil durum bölgesi dışında olabileceğini gösteriyor ancak kamera teyidi yok.","positive person confirmation before standing down rescue","kurtarmayı sonlandırmadan pozitif kişi doğrulamasını"),
s("close","Person is confirmed safe","Kişinin güvende olduğu doğrulanıyor","The worker is located at another muster point and the fire remains controlled.","Çalışan başka toplanma noktasında bulunuyor ve yangın kontrol altında.","formal stand-down, accountability correction and incident learning","resmi stand-down, sayım düzeltmesi ve olay öğrenimini") ]});

const fireEmergencySimops=buildExpertBlueprint({id:"fire-emergency-simops",titleEn:"Fire & Emergency: Multiple Events",titleTr:"Yangın ve Acil Durum: Eş Zamanlı Olaylar",category:"Emergency / SIMOPS",introEn:"A site-wide emergency develops two simultaneous events: a process fire and a medical emergency in another area. Resources, communications and command priorities are stretched.",introTr:"Saha genelinde iki eş zamanlı olay gelişiyor: proses yangını ve başka alanda tıbbi acil durum. Kaynaklar, iletişim ve komuta öncelikleri zorlanıyor.",stages:[
s("dual","Two alarms arrive together","İki alarm aynı anda geliyor","A process fire alarm and a serious medical call are received within one minute.","Proses yangın alarmı ile ciddi tıbbi çağrı bir dakika içinde geliyor.","incident prioritization without abandoning either emergency","iki acil durumdan birini ihmal etmeden olay önceliklendirmesini"),
s("resources","Response resources overlap","Müdahale kaynakları çakışıyor","The same emergency vehicle is listed for both response plans.","Aynı acil durum aracı iki müdahale planında da listelenmiş.","resource allocation against simultaneous incident needs","eş zamanlı olay ihtiyaçlarına göre kaynak tahsisini"),
s("command","Two incident commanders emerge","İki olay komutanı ortaya çıkıyor","Area supervisors independently establish command posts with no common coordination point.","Alan amirleri ortak koordinasyon noktası olmadan ayrı komuta noktaları kuruyor.","site-level unified command and authority boundaries","saha seviyesi birleşik komuta ile yetki sınırlarını"),
s("radio","Emergency channel saturates","Acil kanal yoğunlaşıyor","Both events generate frequent radio traffic and critical messages are repeated or missed.","İki olay da yoğun telsiz trafiği oluşturuyor ve kritik mesajlar tekrarlanıyor veya kaçıyor.","priority communications and channel discipline","öncelikli iletişim ile kanal disiplinini"),
s("evac","Evacuation conflicts with ambulance route","Tahliye ambulans yoluyla çakışıyor","Evacuating personnel block the fastest route to the medical casualty.","Tahliye olan personel tıbbi vakaya en hızlı ambulans yolunu kapatıyor.","traffic separation between evacuation and emergency access","tahliye ile acil erişim arasında trafik ayrımını"),
s("water","Firewater demand reduces utility pressure","Yangın suyu talebi şebeke basıncını düşürüyor","High firewater demand affects another emergency system serving the medical area.","Yüksek yangın suyu talebi tıbbi alanı destekleyen başka acil sistemi etkiliyor.","shared emergency-utility capacity under simultaneous demand","eş zamanlı talepte ortak acil altyapı kapasitesini"),
s("mutual","Mutual aid arrives without full briefing","Dış destek tam brifingsiz geliyor","External responders arrive and move toward the fire while site-specific hazards are still changing.","Dış müdahale ekibi geliyor ve saha özel tehlikeleri değişirken yangına doğru ilerliyor.","site hazard briefing before mutual-aid deployment","dış destek sevkinden önce saha tehlike brifingini"),
s("shift","Emergency command handover occurs","Acil komuta devri oluyor","A senior manager arrives and informally begins giving directions before a structured handover.","Üst düzey yönetici geliyor ve yapılandırılmış devir olmadan talimat vermeye başlıyor.","formal command transfer during active multi-event response","aktif çoklu olay müdahalesinde resmi komuta devrini"),
s("status","One event appears controlled","Bir olay kontrol altında görünüyor","The medical casualty is transported, but no formal confirmation has closed that incident branch.","Tıbbi vaka taşınıyor ancak olay kolunu resmi kapatan teyit yok.","verified event closure before reallocating resources","kaynakları yeniden dağıtmadan doğrulanmış olay kapanışını"),
s("recovery","Site asks to normalize operations","Saha normale dönmek istiyor","The fire is controlled and casualty transport is complete, but emergency resources and access routes remain displaced.","Yangın kontrol altında ve vaka taşındı ancak acil kaynaklar ile erişim yolları hâlâ yer değiştirmiş durumda.","staged recovery and readiness restoration after simultaneous incidents","eş zamanlı olaylar sonrası aşamalı toparlanma ile hazırlığın geri kurulmasını") ]});

const lineBreakingWrongLine=buildExpertBlueprint({id:"line-breaking-wrong-line",titleEn:"Line Breaking: Identification Conflict",titleTr:"Hat Açma: Hat Tanımlama Çatışması",category:"Line Breaking / Isolation",introEn:"A line-breaking task reaches the flange, but tag numbers, field routing and drawings no longer align. Several indicators suggest the crew may be at the wrong line.",introTr:"Hat açma işi flanşa ulaşıyor ancak etiket numaraları, saha güzergahı ve çizimler artık uyuşmuyor. Birkaç gösterge ekibin yanlış hatta olabileceğini düşündürüyor.",stages:[
s("tag","Line tag is partly unreadable","Hat etiketi kısmen okunmuyor","The final digit on the line tag is obscured by corrosion and resembles two possible numbers.","Hat etiketinin son rakamı korozyon nedeniyle kapanmış ve iki farklı numaraya benzeyebiliyor.","positive line identification before disturbance","müdahale öncesi pozitif hat tanımlamasını"),
s("drawing","Drawing route differs from field","Çizim güzergahı sahayla farklı","The isometric shows one elbow, while the field line has an undocumented branch.","İzometrik bir dirsek gösterirken saha hattında belgelenmemiş bir branş var.","drawing-field reconciliation for the exact line","tam hat için çizim-saha uzlaştırmasını"),
s("blind","Blind list references nearby flange","Körleme listesi yakındaki flanşı gösteriyor","The blind number is present, but the listed flange location is one support away from the work point.","Kör numarası mevcut ancak listelenen flanş konumu çalışma noktasından bir destek ötede.","physical blind location versus isolation documentation","fiziksel kör konumu ile izolasyon dokümantasyonunu"),
s("trace","Tracing reaches a shared manifold","Hat takibi ortak manifolda ulaşıyor","Both candidate lines enter the same congested manifold before separating again.","İki aday hat da tekrar ayrılmadan önce aynı sıkışık manifolda giriyor.","continuous physical tracing through the ambiguous manifold","belirsiz manifold boyunca kesintisiz fiziksel hat takibini"),
s("pressure","Gauge reads zero on both candidates","İki adayda da manometre sıfır","Nearby gauges show zero, but one gauge has no current calibration sticker.","Yakındaki manometreler sıfır gösteriyor ancak birinin güncel kalibrasyon etiketi yok.","independent zero-energy proof rather than gauge indication alone","yalnızca manometre göstergesi yerine bağımsız sıfır enerji kanıtını"),
s("drain","Drain point produces liquid","Drenajdan sıvı geliyor","A drain thought to belong to the isolated line releases a small amount of unexpected product.","İzole hatta ait olduğu düşünülen drenajdan az miktarda beklenmeyen ürün geliyor.","process-content confirmation before opening the flange","flanş açılmadan proses içeriği doğrulamasını"),
s("owner","Operations recognizes one route from memory","Operasyon bir güzergahı hafızadan tanıyor","An experienced operator says the undocumented branch was added years ago and points to the intended line.","Deneyimli operatör belgelenmemiş branşın yıllar önce eklendiğini söyleyip hedef hattı gösteriyor.","documented verification rather than memory-based identification","hafızaya dayalı tanımlama yerine belgeli doğrulamayı"),
s("permit","Permit number matches one tag","İzin numarası bir etiketle eşleşiyor","The permit references the same partial tag number but not the physical flange coordinates.","İzin aynı kısmi etiket numarasına referans veriyor ancak fiziksel flanş koordinatını vermiyor.","permit scope tied to positively identified equipment","izin kapsamının pozitif tanımlanmış ekipmana bağlanmasını"),
s("bolt","Crew loosens first bolt for proof","Ekip kanıt için ilk cıvatayı gevşetmek istiyor","A fitter suggests cracking one bolt slowly to confirm whether pressure remains.","Montajcı basınç kalıp kalmadığını anlamak için bir cıvatayı yavaşça gevşetmeyi öneriyor.","non-intrusive zero-energy verification before line breaking","hat açmadan önce müdahalesiz sıfır enerji doğrulamasını"),
s("restart","Correct line is finally confirmed","Doğru hat sonunda doğrulanıyor","Field tracing, updated drawing and isolation points now agree, but the original permit pack still contains the ambiguous copy.","Saha takibi, güncel çizim ve izolasyon noktaları artık uyumlu ancak ilk izin paketinde belirsiz kopya hâlâ var.","permit-pack correction before authorized line opening","yetkili hat açma öncesi izin paketinin düzeltilmesini") ]});

const lineBreakingLiveProcess=buildExpertBlueprint({id:"line-breaking-live-process",titleEn:"Line Breaking: Live Process Nearby",titleTr:"Hat Açma: Yakında Canlı Proses",category:"Line Breaking / SIMOPS",introEn:"A line must be opened beside live process systems sharing drains, supports and operating space. The target line is isolated, but adjacent systems remain active and unstable.",introTr:"Bir hat, ortak drenaj, destek ve çalışma alanını paylaşan canlı proses sistemlerinin yanında açılacak. Hedef hat izole ancak komşu sistemler aktif ve kararsız.",stages:[
s("adjacent","Adjacent live line shares the rack","Komşu canlı hat aynı rack üzerinde","The isolated line runs directly beside a hot live process line with limited physical separation.","İzole hat sınırlı fiziksel ayrımla sıcak canlı proses hattının hemen yanında ilerliyor.","line-of-fire and thermal/process interaction with adjacent live service","komşu canlı servisle ateş hattı ve termal/proses etkileşimini"),
s("drain","Both systems share a drain header","İki sistem ortak drenaj kullanıyor","The target line is drained, but the drain header remains connected to the live unit.","Hedef hat drene edildi ancak drenaj kollektörü canlı üniteye bağlı kalıyor.","reverse migration through shared drain systems","ortak drenajdan ters yayılımı"),
s("valve","Isolation valve passes slightly","İzolasyon vanası hafif kaçırıyor","A downstream bleed slowly re-pressurizes after being vented to zero.","Aşağı yönlü bleed sıfıra indirildikten sonra yavaşça tekrar basınçlanıyor.","positive isolation against passing valves","kaçıran vanalara karşı pozitif izolasyonu"),
s("support","Line support is shared","Hat desteği ortak","Removing the target spool will change load on a support carrying an adjacent live line.","Hedef spool söküldüğünde komşu canlı hattı taşıyan ortak desteğin yükü değişecek.","structural support effects on adjacent live equipment","komşu canlı ekipman üzerindeki yapısal destek etkisini"),
s("process","Live unit enters minor upset","Canlı ünite küçük sapmaya giriyor","Pressure cycles increase in the adjacent system while mechanical work is preparing to open the flange.","Mekanik ekip flanşı açmaya hazırlanırken komşu sistemde basınç dalgalanmaları artıyor.","process stability as a SIMOPS condition for line breaking","hat açma için SIMOPS koşulu olarak proses stabilitesini"),
s("bleed","Bleed route discharges near workers","Bleed çıkışı çalışanlara yakın","The safest bleed point directs residual vapor toward another contractor's access route.","En güvenli bleed noktası kalıntı buharı başka yüklenicinin erişim yoluna yönlendiriyor.","controlled depressurization without transferring exposure","maruziyeti başka yere taşımadan kontrollü basınç düşürmeyi"),
s("permit","Adjacent permit changes","Komşu izin değişiyor","A nearby hot-work permit is issued after the line-breaking permit was already approved.","Hat açma izni onaylandıktan sonra yakında yeni sıcak çalışma izni düzenleniyor.","permit-interface revalidation after new simultaneous work appears","yeni eş zamanlı iş oluşunca izin arayüzü yeniden doğrulamasını"),
s("flange","First flange separation reveals odor","İlk flanş ayrımında koku geliyor","Despite zero gauge pressure, a faint process odor appears as the flange gap opens.","Sıfır manometre basıncına rağmen flanş aralığı açılırken hafif proses kokusu geliyor.","immediate stop and reassessment on unexpected product indication","beklenmeyen ürün belirtisinde anlık duruş ve yeniden değerlendirmeyi"),
s("handover","Operations shift changes mid-task","Operasyon vardiyası iş ortasında değişiyor","The incoming operator did not participate in the isolation proof and questions one blind location.","Yeni operatör izolasyon doğrulamasına katılmadı ve bir kör konumunu sorguluyor.","isolation ownership continuity through shift handover","vardiya devrinde izolasyon sorumluluğu sürekliliğini"),
s("close","Line is ready for full opening","Hat tam açmaya hazır","Leakage is controlled and interfaces are corrected, but adjacent process conditions have changed twice during the task.","Kaçak kontrol edildi ve arayüzler düzeltildi ancak iş sırasında komşu proses koşulları iki kez değişti.","final SIMOPS revalidation before irreversible line opening","geri dönüşsüz hat açma öncesi son SIMOPS doğrulamasını") ]});

export const expertPackThree={
 [chemicalReleaseUnknown.id]:chemicalReleaseUnknown,
 [processReleaseSimops.id]:processReleaseSimops,
 [mobileEquipmentCongestion.id]:mobileEquipmentCongestion,
 [mobileEquipmentSimops.id]:mobileEquipmentSimops,
 [fireEmergencyMissingPerson.id]:fireEmergencyMissingPerson,
 [fireEmergencySimops.id]:fireEmergencySimops,
 [lineBreakingWrongLine.id]:lineBreakingWrongLine,
 [lineBreakingLiveProcess.id]:lineBreakingLiveProcess,
};
