export type IncidentCatalogItem = {
  id: string;
  titleEn: string;
  titleTr: string;
  category: string;
  difficulty: "basic" | "advanced" | "professional";
  decisions: number;
  status: "live" | "coming";
  descEn: string;
  descTr: string;
};

export const incidentCatalog: IncidentCatalogItem[] = [
  // HOT WORK
  { id: "hot-work-gas-drift", titleEn: "Hot Work: The Reading Changes", titleTr: "Sıcak Çalışma: Ölçüm Değişiyor", category: "Hot Work / Gas Testing", difficulty: "basic", decisions: 10, status: "live", descEn: "Changing gas readings, permit control, isolation, retesting and restart decisions.", descTr: "Değişen gaz ölçümleri, izin kontrolü, izolasyon, tekrar ölçüm ve yeniden başlatma kararları." },
  { id: "hot-work-process-instability", titleEn: "Hot Work: Process Instability", titleTr: "Sıcak Çalışma: Proses Kararsızlığı", category: "Hot Work / SIMOPS", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Competing controls, process changes, fire watch limits and permit validity under production pressure.", descTr: "Çakışan kontroller, proses değişimleri, yangın gözcüsü sınırları ve üretim baskısı altında izin geçerliliği." },
  { id: "hot-work-simops-shutdown", titleEn: "Hot Work: SIMOPS During Shutdown", titleTr: "Sıcak Çalışma: Shutdown Sırasında SIMOPS", category: "Hot Work / SIMOPS", difficulty: "professional", decisions: 10, status: "coming", descEn: "Multiple simultaneous activities, uncertain isolation ownership and restart pressure during shutdown work.", descTr: "Eş zamanlı işler, belirsiz izolasyon sorumluluğu ve shutdown sırasında yeniden başlatma baskısı." },

  // WORK AT HEIGHT
  { id: "height-anchor-choice", titleEn: "Work at Height: One Anchor Left", titleTr: "Yüksekte Çalışma: Tek Ankraj Kaldı", category: "Work at Height", difficulty: "basic", decisions: 9, status: "coming", descEn: "Anchor choice, access, dropped-object exposure and basic stop-work judgment.", descTr: "Ankraj seçimi, erişim, düşen cisim riski ve temel işi durdurma muhakemesi." },
  { id: "height-weather-rescue", titleEn: "Work at Height: Weather Turns", titleTr: "Yüksekte Çalışma: Hava Değişiyor", category: "Work at Height", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Wind escalation, rescue readiness, temporary access and changing exclusion zones.", descTr: "Rüzgar artışı, kurtarma hazırlığı, geçici erişim ve değişen yasak bölgeler." },
  { id: "height-simops-lift", titleEn: "Work at Height: Lift Below", titleTr: "Yüksekte Çalışma: Altında Kaldırma Var", category: "Work at Height / SIMOPS", difficulty: "professional", decisions: 10, status: "coming", descEn: "Work at height above lifting operations with competing permits, line-of-fire and rescue constraints.", descTr: "Altında kaldırma operasyonu bulunan yüksekte çalışma; çakışan izinler, ateş hattı ve kurtarma kısıtları." },

  // CONFINED SPACE
  { id: "confined-space-atmosphere", titleEn: "Confined Space: Conditions Shift", titleTr: "Kapalı Alan: Koşullar Değişiyor", category: "Confined Space", difficulty: "basic", decisions: 9, status: "coming", descEn: "Atmospheric change, ventilation loss, attendant response and permit suspension.", descTr: "Atmosfer değişimi, havalandırma kaybı, gözcü müdahalesi ve izin askıya alma." },
  { id: "confined-space-entrant-symptoms", titleEn: "Confined Space: Entrant Feels Unwell", titleTr: "Kapalı Alan: Çalışanın Durumu Bozuluyor", category: "Confined Space / Rescue", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Early symptoms, rescue activation, ventilation uncertainty and unauthorized rescue pressure.", descTr: "Erken belirtiler, kurtarma aktivasyonu, havalandırma belirsizliği ve yetkisiz kurtarma baskısı." },
  { id: "confined-space-isolation-doubt", titleEn: "Confined Space: Isolation Doubt", titleTr: "Kapalı Alan: İzolasyon Şüphesi", category: "Confined Space / Isolation", difficulty: "professional", decisions: 10, status: "coming", descEn: "Conflicting isolation records, process ownership, rescue constraints and permit revalidation.", descTr: "Çelişkili izolasyon kayıtları, proses sorumluluğu, kurtarma kısıtları ve izin yeniden doğrulama." },

  // LOTO
  { id: "loto-unexpected-energy", titleEn: "LOTO: Unexpected Energy", titleTr: "LOTO: Beklenmeyen Enerji", category: "LOTO / Isolation", difficulty: "basic", decisions: 9, status: "coming", descEn: "Zero-energy verification, stored energy and individual lockout decisions.", descTr: "Sıfır enerji doğrulaması, depolanmış enerji ve bireysel kilitleme kararları." },
  { id: "loto-group-lockout", titleEn: "LOTO: Shift Change", titleTr: "LOTO: Vardiya Değişimi", category: "LOTO / Group Lockout", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Group lockout transfer, missing worker, shift handover and restart pressure.", descTr: "Grup kilitleme devri, eksik çalışan, vardiya teslimi ve yeniden başlatma baskısı." },
  { id: "loto-complex-isolation", titleEn: "LOTO: Complex Isolation Boundary", titleTr: "LOTO: Karmaşık İzolasyon Sınırı", category: "LOTO / Process Isolation", difficulty: "professional", decisions: 10, status: "coming", descEn: "Multi-energy systems, conflicting drawings, trapped pressure and disputed isolation ownership.", descTr: "Çoklu enerji sistemleri, çelişkili çizimler, hapsolmuş basınç ve tartışmalı izolasyon sorumluluğu." },

  // SCAFFOLDING
  { id: "scaffold-status-change", titleEn: "Scaffolding: Status Changed", titleTr: "İskele: Durum Değişti", category: "Scaffolding", difficulty: "basic", decisions: 8, status: "coming", descEn: "Tag status, access, guardrails and unauthorized modification decisions.", descTr: "Etiket durumu, erişim, korkuluk ve yetkisiz değişiklik kararları." },
  { id: "scaffold-load-modification", titleEn: "Scaffolding: Load Added", titleTr: "İskele: Yük Eklendi", category: "Scaffolding", difficulty: "advanced", decisions: 9, status: "coming", descEn: "Material loading, partial dismantling, access changes and inspector escalation.", descTr: "Malzeme yükleme, kısmi söküm, erişim değişikliği ve iskele kontrolcüsüne eskalasyon." },
  { id: "scaffold-simops-handover", titleEn: "Scaffolding: Multi-Contractor Handover", titleTr: "İskele: Çoklu Firma Devir Teslimi", category: "Scaffolding / SIMOPS", difficulty: "professional", decisions: 10, status: "coming", descEn: "Multiple contractors, disputed ownership, altered loading and incomplete handover controls.", descTr: "Birden fazla firma, tartışmalı sorumluluk, değişen yükleme ve eksik devir kontrolleri." },

  // EXCAVATION
  { id: "excavation-water-ingress", titleEn: "Excavation: Water Is Rising", titleTr: "Kazı: Su Yükseliyor", category: "Excavation", difficulty: "basic", decisions: 9, status: "coming", descEn: "Ground stability, access, spoil placement and emergency withdrawal.", descTr: "Zemin stabilitesi, erişim, hafriyat konumu ve acil tahliye." },
  { id: "excavation-utility-conflict", titleEn: "Excavation: Unknown Utility", titleTr: "Kazı: Bilinmeyen Hat", category: "Excavation / Underground Services", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Conflicting drawings, cable detection uncertainty, hand digging and permit escalation.", descTr: "Çelişkili çizimler, hat tespit belirsizliği, elle kazı ve izin eskalasyonu." },
  { id: "excavation-adjacent-load", titleEn: "Excavation: Crane Beside the Trench", titleTr: "Kazı: Hendek Yanında Vinç", category: "Excavation / SIMOPS", difficulty: "professional", decisions: 10, status: "coming", descEn: "Ground bearing, crane outrigger loads, trench stability and competing work priorities.", descTr: "Zemin taşıma kapasitesi, vinç ayağı yükleri, hendek stabilitesi ve çakışan iş öncelikleri." },

  // LIFTING
  { id: "lifting-blind-zone", titleEn: "Lifting: The Blind Zone", titleTr: "Kaldırma: Kör Nokta", category: "Lifting Operations", difficulty: "basic", decisions: 9, status: "coming", descEn: "Exclusion zone, signaler control, blind lift and suspended-load decisions.", descTr: "Yasak bölge, işaretçi kontrolü, kör kaldırma ve askıdaki yük kararları." },
  { id: "lifting-plan-deviation", titleEn: "Lifting: Plan No Longer Fits", titleTr: "Kaldırma: Plan Artık Uymuyor", category: "Lifting Operations", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Lift-plan deviations, rigging changes, wind limits and supervisor pressure.", descTr: "Kaldırma planı sapmaları, sapan değişiklikleri, rüzgar limitleri ve amir baskısı." },
  { id: "lifting-tandem-critical", titleEn: "Lifting: Tandem Critical Lift", titleTr: "Kaldırma: Tandem Kritik Kaldırma", category: "Critical Lifting", difficulty: "professional", decisions: 10, status: "coming", descEn: "Two-crane coordination, load transfer, changing radius and conflicting command authority.", descTr: "İki vinç koordinasyonu, yük transferi, değişen yarıçap ve çakışan komuta yetkisi." },

  // ELECTRICAL
  { id: "electrical-backfeed", titleEn: "Electrical: Backfeed Detected", titleTr: "Elektrik: Geri Besleme Tespit Edildi", category: "Electrical Safety", difficulty: "basic", decisions: 9, status: "coming", descEn: "Isolation boundaries, test-before-touch and unexpected voltage decisions.", descTr: "İzolasyon sınırları, dokunmadan önce test ve beklenmeyen gerilim kararları." },
  { id: "electrical-induced-voltage", titleEn: "Electrical: Voltage Returns", titleTr: "Elektrik: Gerilim Geri Dönüyor", category: "Electrical Safety", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Induced voltage, temporary earthing, testing method and energized-work escalation.", descTr: "İndüklenen gerilim, geçici topraklama, test yöntemi ve enerjili çalışma eskalasyonu." },
  { id: "electrical-switching-conflict", titleEn: "Electrical: Switching Conflict", titleTr: "Elektrik: Manevra Çatışması", category: "Electrical / Switching", difficulty: "professional", decisions: 10, status: "coming", descEn: "Remote switching, conflicting permits, communication failure and system restoration pressure.", descTr: "Uzaktan manevra, çakışan izinler, iletişim kaybı ve sistemi devreye alma baskısı." },

  // CHEMICAL / PROCESS RELEASE
  { id: "chemical-release-wind", titleEn: "Chemical Release: Wind Shift", titleTr: "Kimyasal Salım: Rüzgar Değişti", category: "Chemical / Process Safety", difficulty: "basic", decisions: 9, status: "coming", descEn: "Release recognition, wind direction, PPE limits and evacuation decisions.", descTr: "Salım tespiti, rüzgar yönü, KKD sınırları ve tahliye kararları." },
  { id: "chemical-release-unknown", titleEn: "Chemical Release: Substance Unknown", titleTr: "Kimyasal Salım: Madde Bilinmiyor", category: "Chemical / Emergency", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Unknown substance, conflicting SDS information, zone control and responder escalation.", descTr: "Bilinmeyen madde, çelişkili SDS bilgisi, bölge kontrolü ve müdahale ekibine eskalasyon." },
  { id: "process-release-simops", titleEn: "Process Release: Contractors in the Plume", titleTr: "Proses Salımı: Yayılım Alanında Taşeronlar", category: "Process Safety / SIMOPS", difficulty: "professional", decisions: 10, status: "coming", descEn: "Contractor accountability, process isolation, changing plume and emergency command decisions.", descTr: "Taşeron personel sayımı, proses izolasyonu, değişen yayılım ve acil durum komuta kararları." },

  // MOBILE EQUIPMENT
  { id: "mobile-equipment-reversing", titleEn: "Mobile Equipment: Reversing Conflict", titleTr: "Hareketli Ekipman: Geri Manevra Çatışması", category: "Mobile Equipment / Traffic", difficulty: "basic", decisions: 8, status: "coming", descEn: "Pedestrian segregation, spotter control, visibility and route-change decisions.", descTr: "Yaya ayrımı, işaretçi kontrolü, görüş ve güzergah değişikliği kararları." },
  { id: "mobile-equipment-congestion", titleEn: "Mobile Equipment: Congested Workfront", titleTr: "Hareketli Ekipman: Sıkışık Çalışma Alanı", category: "Mobile Equipment / Logistics", difficulty: "advanced", decisions: 9, status: "coming", descEn: "Multiple vehicles, temporary routes, blind spots and production-driven congestion.", descTr: "Birden fazla araç, geçici güzergahlar, kör noktalar ve üretim kaynaklı sıkışıklık." },
  { id: "mobile-equipment-simops", titleEn: "Mobile Equipment: SIMOPS Crossing", titleTr: "Hareketli Ekipman: SIMOPS Geçişi", category: "Mobile Equipment / SIMOPS", difficulty: "professional", decisions: 10, status: "coming", descEn: "Heavy transport crossing active work zones with competing traffic controls and schedule pressure.", descTr: "Aktif çalışma alanından geçen ağır nakliye; çakışan trafik kontrolleri ve program baskısı." },

  // FIRE & EMERGENCY
  { id: "fire-emergency-first-minutes", titleEn: "Fire & Emergency: First Five Minutes", titleTr: "Yangın ve Acil Durum: İlk Beş Dakika", category: "Emergency Response", difficulty: "basic", decisions: 9, status: "coming", descEn: "Alarm, evacuation, accountability and first-response decisions.", descTr: "Alarm, tahliye, personel sayımı ve ilk müdahale kararları." },
  { id: "fire-emergency-missing-person", titleEn: "Fire & Emergency: One Person Missing", titleTr: "Yangın ve Acil Durum: Bir Kişi Eksik", category: "Emergency Response", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Missing-person reports, responder entry, conflicting information and accountability control.", descTr: "Kayıp kişi bildirimi, müdahale ekibi girişi, çelişkili bilgiler ve personel sayımı kontrolü." },
  { id: "fire-emergency-command", titleEn: "Fire & Emergency: Command Under Pressure", titleTr: "Yangın ve Acil Durum: Baskı Altında Komuta", category: "Emergency Command", difficulty: "professional", decisions: 10, status: "coming", descEn: "Escalating incident, contractor interface, process shutdown and external responder coordination.", descTr: "Büyüyen olay, taşeron koordinasyonu, proses shutdown ve dış müdahale ekibi yönetimi." },

  // LINE BREAKING
  { id: "line-breaking-residual", titleEn: "Line Breaking: Residual Pressure", titleTr: "Hat Açma: Kalıntı Basınç", category: "Line Breaking", difficulty: "basic", decisions: 9, status: "coming", descEn: "Isolation, drain/vent verification and line-of-fire decisions.", descTr: "İzolasyon, drenaj/havalandırma doğrulaması ve ateş hattı kararları." },
  { id: "line-breaking-wrong-line", titleEn: "Line Breaking: Tag Does Not Match", titleTr: "Hat Açma: Etiket Uyuşmuyor", category: "Line Breaking / Isolation", difficulty: "advanced", decisions: 10, status: "coming", descEn: "Mismatched line identification, drawing conflicts, process ownership and permit suspension.", descTr: "Uyuşmayan hat tanımlaması, çizim çelişkisi, proses sorumluluğu ve izin askıya alma." },
  { id: "line-breaking-live-process", titleEn: "Line Breaking: Live Process Nearby", titleTr: "Hat Açma: Yakında Canlı Proses", category: "Line Breaking / SIMOPS", difficulty: "professional", decisions: 10, status: "coming", descEn: "Adjacent live systems, common headers, disputed isolation and production pressure.", descTr: "Bitişik canlı sistemler, ortak kolektörler, tartışmalı izolasyon ve üretim baskısı." },
];
