import type { IncidentScenario } from "./incident-simulator";

type Step = {
  id: string;
  titleEn: string;
  titleTr: string;
  situationEn: string;
  situationTr: string;
  bestEn: string;
  bestTr: string;
  bestConsequenceEn: string;
  bestConsequenceTr: string;
  weakEn: string;
  weakTr: string;
  weakConsequenceEn: string;
  weakConsequenceTr: string;
  weakImpact?: { safety: number; judgment: number; response: number };
  weakCritical?: boolean;
};

function buildScenario(config: {
  id: string;
  titleEn: string;
  titleTr: string;
  category: string;
  introEn: string;
  introTr: string;
  steps: Step[];
}): IncidentScenario {
  const nodes = config.steps.map((step, index) => {
    const next = index === config.steps.length - 1 ? "finish-safe" : config.steps[index + 1].id;
    const weakNext = step.weakCritical ? "finish-recovered" : next;
    return {
      id: step.id,
      titleEn: step.titleEn,
      titleTr: step.titleTr,
      situationEn: step.situationEn,
      situationTr: step.situationTr,
      choices: [
        {
          id: `${step.id}-best`,
          labelEn: step.bestEn,
          labelTr: step.bestTr,
          consequenceEn: step.bestConsequenceEn,
          consequenceTr: step.bestConsequenceTr,
          impact: { safety: 4, judgment: 4, response: 3 },
          next,
        },
        {
          id: `${step.id}-weak`,
          labelEn: step.weakEn,
          labelTr: step.weakTr,
          consequenceEn: step.weakConsequenceEn,
          consequenceTr: step.weakConsequenceTr,
          impact: step.weakImpact ?? { safety: -8, judgment: -9, response: -6 },
          next: weakNext,
          critical: Boolean(step.weakCritical),
        },
      ],
    };
  });

  return {
    id: config.id,
    titleEn: config.titleEn,
    titleTr: config.titleTr,
    category: config.category,
    difficulty: "hard",
    introEn: config.introEn,
    introTr: config.introTr,
    start: config.steps[0].id,
    nodes: [
      ...nodes,
      {
        id: "finish-safe",
        titleEn: "Controlled outcome",
        titleTr: "Kontrollü sonuç",
        situationEn: "The work is completed with the changing conditions identified, verified and controlled before exposure escalates.",
        situationTr: "Değişen koşullar maruziyet büyümeden tespit edilir, doğrulanır ve kontrol altına alınarak çalışma tamamlanır.",
        choices: [],
      },
      {
        id: "finish-recovered",
        titleEn: "Recovered after escalation",
        titleTr: "Eskalasyon sonrası kontrol",
        situationEn: "The work is stopped before injury, but the decision chain allowed a significant control weakness to develop and requires review.",
        situationTr: "Yaralanma olmadan iş durdurulur; ancak karar zinciri önemli bir kontrol zafiyetinin gelişmesine izin verdiği için inceleme gerekir.",
        choices: [],
      },
    ],
  };
}

export const heightAnchorChoice = buildScenario({
  id: "height-anchor-choice",
  titleEn: "Work at Height: One Anchor Left",
  titleTr: "Yüksekte Çalışma: Tek Ankraj Kaldı",
  category: "Work at Height",
  introEn: "You are supervising a short maintenance task at height. The original access and anchorage plan begins to change while the crew is already mobilized.",
  introTr: "Kısa süreli bir yüksekte çalışma bakım işini yönetiyorsun. Ekip hazırken planlanan erişim ve ankraj koşulları değişmeye başlıyor.",
  steps: [
    { id:"anchor-status", titleEn:"The planned anchor is unavailable", titleTr:"Planlanan ankraj kullanılamıyor", situationEn:"The certified anchor point is blocked by temporary equipment. A nearby structural member looks strong but is not identified on the rescue or fall-protection plan.", situationTr:"Sertifikalı ankraj noktası geçici ekipmanla kapanmış. Yakındaki taşıyıcı eleman sağlam görünüyor ancak düşüş koruma veya kurtarma planında tanımlı değil.", bestEn:"Pause and verify an approved alternative anchor", bestTr:"Dur ve onaylı alternatif ankrajı doğrula", bestConsequenceEn:"The attachment point is verified before exposure begins.", bestConsequenceTr:"Maruziyet başlamadan bağlantı noktası doğrulanır.", weakEn:"Use the structural member for this short task", weakTr:"Kısa iş için taşıyıcı elemana bağlan", weakConsequenceEn:"The crew relies on an unverified anchorage because it appears adequate.", weakConsequenceTr:"Ekip yeterli göründüğü için doğrulanmamış bir ankraja güvenir.", weakImpact:{safety:-14,judgment:-12,response:-7} },
    { id:"access", titleEn:"Access no longer reaches correctly", titleTr:"Erişim artık uygun değil", situationEn:"The ladder reaches the platform but the landing extension is shorter than planned. The crew suggests stepping across while tied off.", situationTr:"Merdiven platforma ulaşıyor ancak çıkış uzantısı planlanandan kısa. Ekip bağlıyken adım atarak geçmeyi öneriyor.", bestEn:"Correct the access before climbing", bestTr:"Tırmanmadan önce erişimi düzelt", bestConsequenceEn:"Access is restored to the planned safe arrangement.", bestConsequenceTr:"Erişim planlanan güvenli düzene getirilir.", weakEn:"Allow the transfer with a spotter", weakTr:"Gözcü ile geçişe izin ver", weakConsequenceEn:"A spotter does not remove the unstable transfer hazard.", weakConsequenceTr:"Gözcü dengesiz geçiş tehlikesini ortadan kaldırmaz." },
    { id:"transition", titleEn:"The worker reaches a transition point", titleTr:"Çalışan geçiş noktasına ulaşıyor", situationEn:"To move around a column, the worker would need to change connection points. One lanyard is available immediately; the second is in the tool bag.", situationTr:"Kolon etrafından geçmek için çalışan bağlantı noktasını değiştirmeli. Bir lanyard hazır, ikincisi takım çantasında.", bestEn:"Stop and establish 100% tie-off before moving", bestTr:"Dur ve hareketten önce %100 bağlılığı sağla", bestConsequenceEn:"Continuous protection is maintained through the transition.", bestConsequenceTr:"Geçiş boyunca sürekli koruma sağlanır.", weakEn:"Disconnect briefly while holding the handrail", weakTr:"Korkuluğu tutarak kısa süreli bağlantıyı kes", weakConsequenceEn:"The highest-risk moment becomes unprotected.", weakConsequenceTr:"En riskli geçiş anı korumasız kalır.", weakCritical:true, weakImpact:{safety:-28,judgment:-22,response:-18} },
    { id:"dropped-object", titleEn:"Tools are needed above an active walkway", titleTr:"Aktif yürüme yolunun üzerinde alet kullanılacak", situationEn:"The task needs a spanner and small parts above a route still used by another contractor.", situationTr:"İş, başka bir yüklenicinin kullandığı güzergahın üzerinde anahtar ve küçük parçalar gerektiriyor.", bestEn:"Establish exclusion and tether the tools", bestTr:"Yasak bölge kur ve aletleri sabitle", bestConsequenceEn:"People and dropped-object sources are controlled together.", bestConsequenceTr:"İnsanlar ve düşen cisim kaynakları birlikte kontrol edilir.", weakEn:"Warn people below and continue", weakTr:"Aşağıdakileri uyar ve devam et", weakConsequenceEn:"Verbal warning leaves the exposure route open.", weakConsequenceTr:"Sözlü uyarı maruziyet güzergahını açık bırakır." },
    { id:"wind", titleEn:"Wind begins to gust", titleTr:"Rüzgar ani esmeye başlıyor", situationEn:"Wind is still below the project stop limit but gusts are increasing and the worker reports movement in loose sheeting nearby.", situationTr:"Rüzgar proje durdurma limitinin altında ancak ani esintiler artıyor ve çalışan yakındaki gevşek kaplamanın hareket ettiğini bildiriyor.", bestEn:"Pause and reassess the changed condition", bestTr:"Dur ve değişen koşulu yeniden değerlendir", bestConsequenceEn:"The decision responds to trend and exposure, not only the numeric limit.", bestConsequenceTr:"Karar yalnızca sayısal limite değil trende ve maruziyete dayanır.", weakEn:"Continue until the formal wind limit is reached", weakTr:"Resmi rüzgar limitine kadar devam et", weakConsequenceEn:"The crew waits for a threshold while stability is already deteriorating.", weakConsequenceTr:"Stabilite bozulurken ekip yalnızca limite ulaşmayı bekler." },
    { id:"rescue", titleEn:"Rescue readiness is questioned", titleTr:"Kurtarma hazırlığı sorgulanıyor", situationEn:"The rescue kit is available, but the trained rescuer has been temporarily reassigned to another workfront.", situationTr:"Kurtarma ekipmanı mevcut ancak eğitimli kurtarıcı geçici olarak başka çalışma alanına gönderilmiş.", bestEn:"Hold the task until rescue capability is restored", bestTr:"Kurtarma kapasitesi geri gelene kadar işi beklet", bestConsequenceEn:"The permit assumptions remain valid before work resumes.", bestConsequenceTr:"İşe dönmeden önce izin varsayımları tekrar geçerli hale gelir.", weakEn:"Rely on the general emergency team if needed", weakTr:"Gerekirse genel acil durum ekibine güven", weakConsequenceEn:"A planned immediate rescue control is replaced by an uncertain response time.", weakConsequenceTr:"Planlanan hızlı kurtarma kontrolü belirsiz müdahale süresiyle değiştirilir." },
    { id:"deck-gap", titleEn:"A small deck gap is discovered", titleTr:"Platformda küçük boşluk tespit ediliyor", situationEn:"A board has shifted, leaving a gap near the work position. The crew says it is easy to step around.", situationTr:"Bir kalas kaymış ve çalışma noktasında boşluk oluşmuş. Ekip etrafından geçmenin kolay olduğunu söylüyor.", bestEn:"Stop and have the platform corrected and rechecked", bestTr:"Dur, platformu düzelttir ve yeniden kontrol ettir", bestConsequenceEn:"The work surface is restored before exposure continues.", bestConsequenceTr:"Maruziyet devam etmeden çalışma yüzeyi düzeltilir.", weakEn:"Mark the gap and keep working", weakTr:"Boşluğu işaretle ve çalışmaya devam et", weakConsequenceEn:"A known fall hazard remains inside the active work area.", weakConsequenceTr:"Bilinen düşme tehlikesi aktif çalışma alanında kalır." },
    { id:"interface", titleEn:"Another crew enters below", titleTr:"Başka bir ekip alt bölgeye giriyor", situationEn:"A materials team enters the exclusion zone because their supervisor says their route cannot be delayed.", situationTr:"Malzeme ekibi, amirleri güzergahın gecikemeyeceğini söylediği için yasak bölgeye giriyor.", bestEn:"Stop the height task until the interface is controlled", bestTr:"Arayüz kontrol edilene kadar yüksekte çalışmayı durdur", bestConsequenceEn:"Competing work is resolved before exposure resumes.", bestConsequenceTr:"Maruziyet yeniden başlamadan çakışan iş çözülür.", weakEn:"Let them pass quickly while the worker waits", weakTr:"Çalışan beklerken hızlıca geçmelerine izin ver", weakConsequenceEn:"The exclusion control becomes conditional and easy to breach again.", weakConsequenceTr:"Yasak bölge kontrolü koşullu hale gelir ve tekrar ihlal edilmesi kolaylaşır." },
    { id:"release", titleEn:"The task is ready to restart", titleTr:"İş yeniden başlamaya hazır", situationEn:"Access, anchor, rescue and exclusion controls have been restored. The crew asks for immediate release.", situationTr:"Erişim, ankraj, kurtarma ve yasak bölge kontrolleri yeniden sağlandı. Ekip hemen onay istiyor.", bestEn:"Complete one final field verification", bestTr:"Son bir saha doğrulaması yap", bestConsequenceEn:"Restart is based on actual conditions at the workfront.", bestConsequenceTr:"Yeniden başlatma gerçek saha koşullarına dayanır.", weakEn:"Release based on the updated paperwork", weakTr:"Güncellenen evraka dayanarak onay ver", weakConsequenceEn:"The final opportunity to catch a field mismatch is skipped.", weakConsequenceTr:"Saha ile evrak arasındaki son uyumsuzluğu yakalama fırsatı atlanır." },
  ],
});

export const confinedSpaceAtmosphere = buildScenario({
  id: "confined-space-atmosphere",
  titleEn: "Confined Space: Conditions Shift",
  titleTr: "Kapalı Alan: Koşullar Değişiyor",
  category: "Confined Space",
  introEn: "A vessel entry starts with acceptable tests and valid isolation. During the job, ventilation and atmospheric conditions begin to change.",
  introTr: "Bir kapalı alan girişi uygun ölçümler ve geçerli izolasyonla başlıyor. Çalışma sırasında havalandırma ve atmosfer koşulları değişmeye başlıyor.",
  steps: [
    { id:"o2-trend", titleEn:"Oxygen begins to trend down", titleTr:"Oksijen düşüş trendine giriyor", situationEn:"Continuous monitoring shows oxygen reducing from 20.9% to 20.2%. It remains within the project entry range but the trend is continuing.", situationTr:"Sürekli ölçüm oksijenin %20,9'dan %20,2'ye düştüğünü gösteriyor. Değer hâlâ proje giriş aralığında ancak düşüş sürüyor.", bestEn:"Pause entry work and investigate the trend", bestTr:"Giriş işini durdur ve trendin nedenini araştır", bestConsequenceEn:"The changing atmosphere is treated as a control change before limits are exceeded.", bestConsequenceTr:"Limit aşılmadan değişen atmosfer kontrol değişikliği olarak ele alınır.", weakEn:"Continue while watching the monitor closely", weakTr:"Cihazı yakından izleyerek devam et", weakConsequenceEn:"The team waits for a limit instead of addressing the deteriorating condition.", weakConsequenceTr:"Ekip kötüleşen koşulu ele almak yerine limite ulaşmasını bekler." },
    { id:"vent-loss", titleEn:"Ventilation trips", titleTr:"Havalandırma duruyor", situationEn:"The extraction fan stops unexpectedly. Maintenance says they can restart it within a few minutes.", situationTr:"Egzoz fanı beklenmedik şekilde duruyor. Bakım ekibi birkaç dakika içinde yeniden başlatabileceğini söylüyor.", bestEn:"Withdraw entrants and suspend the permit", bestTr:"Çalışanları çıkar ve izni askıya al", bestConsequenceEn:"Entry assumptions are restored before re-entry.", bestConsequenceTr:"Yeniden girişten önce giriş varsayımları tekrar sağlanır.", weakEn:"Keep entrants inside while the fan is restarted", weakTr:"Fan yeniden başlatılırken çalışanları içeride tut", weakConsequenceEn:"Entrants remain exposed while a primary atmospheric control is unavailable.", weakConsequenceTr:"Temel atmosfer kontrolü yokken çalışanlar maruziyette kalır.", weakCritical:true, weakImpact:{safety:-30,judgment:-24,response:-22} },
    { id:"symptom", titleEn:"An entrant reports a headache", titleTr:"Bir çalışan baş ağrısı bildiriyor", situationEn:"One entrant says he feels a mild headache but wants to finish the inspection before exiting.", situationTr:"Bir çalışan hafif baş ağrısı hissettiğini ancak çıkmadan önce kontrolü bitirmek istediğini söylüyor.", bestEn:"Order withdrawal and initiate medical assessment", bestTr:"Çıkış talimatı ver ve sağlık değerlendirmesi başlat", bestConsequenceEn:"A potential exposure symptom is treated conservatively and early.", bestConsequenceTr:"Olası maruziyet belirtisi erken ve ihtiyatlı ele alınır.", weakEn:"Let him finish if the gas monitor remains normal", weakTr:"Gaz ölçümü normalse bitirmesine izin ver", weakConsequenceEn:"A human symptom is discounted because instruments have not alarmed.", weakConsequenceTr:"Cihaz alarm vermediği için insandaki belirti göz ardı edilir." },
    { id:"attendant", titleEn:"The attendant is pulled away", titleTr:"Gözcü başka işe çağrılıyor", situationEn:"The entry attendant is asked to help with a nearby delivery for five minutes while maintaining radio contact.", situationTr:"Kapalı alan gözcüsünden telsiz bağlantısını sürdürerek beş dakika yakındaki teslimata yardım etmesi isteniyor.", bestEn:"Keep a dedicated attendant at the entry", bestTr:"Girişte özel görevlendirilmiş gözcüyü koru", bestConsequenceEn:"Continuous entry control and accountability are maintained.", bestConsequenceTr:"Kesintisiz giriş kontrolü ve personel takibi korunur.", weakEn:"Allow the short absence with radio contact", weakTr:"Telsiz bağlantısıyla kısa süreli ayrılmasına izin ver", weakConsequenceEn:"The dedicated attendant control is lost during active entry.", weakConsequenceTr:"Aktif giriş sırasında özel gözcü kontrolü kaybedilir." },
    { id:"isolation", titleEn:"An isolation tag does not match", titleTr:"Bir izolasyon etiketi uyuşmuyor", situationEn:"During revalidation, one valve number on the field tag differs from the isolation list by one digit.", situationTr:"Yeniden doğrulama sırasında saha etiketindeki bir vana numarası izolasyon listesinden bir rakam farklı.", bestEn:"Stop and physically verify the isolation boundary", bestTr:"Dur ve izolasyon sınırını fiziksel olarak doğrula", bestConsequenceEn:"The discrepancy is resolved before reliance on the isolation.", bestConsequenceTr:"İzolasyona güvenmeden önce uyumsuzluk çözülür.", weakEn:"Accept the operator's verbal confirmation that it is a typo", weakTr:"Operatörün yazım hatası olduğu sözlü teyidini kabul et", weakConsequenceEn:"A documentation conflict remains unverified on a critical control.", weakConsequenceTr:"Kritik bir kontroldeki doküman çelişkisi doğrulanmadan kalır." },
    { id:"sampling", titleEn:"Only one test point is available", titleTr:"Sadece tek ölçüm noktası hazır", situationEn:"The gas tester proposes sampling at the manway only because the lower sampling hose is temporarily unavailable.", situationTr:"Gaz ölçümcüsü alt seviye hortumu geçici olarak olmadığı için yalnızca menhol ağzından ölçüm yapmayı öneriyor.", bestEn:"Restore representative multi-level testing before entry", bestTr:"Girişten önce temsili çok seviyeli ölçümü sağla", bestConsequenceEn:"Stratification risk is controlled before re-entry.", bestConsequenceTr:"Tabakalaşma riski yeniden girişten önce kontrol edilir.", weakEn:"Use the manway reading because ventilation is running", weakTr:"Havalandırma çalıştığı için menhol ölçümünü kullan", weakConsequenceEn:"A single location may miss a hazardous pocket elsewhere in the space.", weakConsequenceTr:"Tek nokta ölçümü alanın başka yerindeki tehlikeli cebi kaçırabilir." },
    { id:"comms", titleEn:"Radio communication becomes intermittent", titleTr:"Telsiz iletişimi kesintili hale geliyor", situationEn:"The attendant can hear the entrants only intermittently because of interference from nearby work.", situationTr:"Yakındaki işin paraziti nedeniyle gözcü çalışanları yalnızca kesintili duyabiliyor.", bestEn:"Suspend entry until reliable communication is restored", bestTr:"Güvenilir iletişim sağlanana kadar girişi askıya al", bestConsequenceEn:"Emergency communication remains dependable.", bestConsequenceTr:"Acil durum iletişimi güvenilir tutulur.", weakEn:"Continue using agreed hand signals when visible", weakTr:"Görüş olduğunda belirlenen el işaretleriyle devam et", weakConsequenceEn:"The communication method is no longer reliable throughout the space.", weakConsequenceTr:"İletişim yöntemi alanın tamamında güvenilir değildir." },
    { id:"rescue", titleEn:"The rescue team is delayed", titleTr:"Kurtarma ekibi gecikiyor", situationEn:"The standby rescue team reports a ten-minute delay returning from another callout. The job has only twenty minutes left.", situationTr:"Hazır kurtarma ekibi başka çağrıdan dönüşte on dakika gecikeceğini bildiriyor. İşin yalnızca yirmi dakikası kalmış.", bestEn:"Hold entry until rescue capability is available", bestTr:"Kurtarma kapasitesi hazır olana kadar girişi beklet", bestConsequenceEn:"Rescue readiness remains part of the entry authorization.", bestConsequenceTr:"Kurtarma hazırlığı giriş yetkisinin bir parçası olarak korunur.", weakEn:"Continue because the remaining task is short", weakTr:"Kalan iş kısa olduğu için devam et", weakConsequenceEn:"Duration is used to justify loss of a required emergency control.", weakConsequenceTr:"Gerekli acil durum kontrolünün kaybı iş süresiyle gerekçelendirilir." },
    { id:"revalidate", titleEn:"Conditions are restored", titleTr:"Koşullar yeniden sağlandı", situationEn:"Ventilation, monitoring, communication and rescue readiness are restored. The team wants to re-enter under the original permit.", situationTr:"Havalandırma, ölçüm, iletişim ve kurtarma hazırlığı yeniden sağlandı. Ekip eski izinle tekrar girmek istiyor.", bestEn:"Revalidate the permit and brief all entrants before re-entry", bestTr:"İzni yeniden doğrula ve girişten önce tüm çalışanları bilgilendir", bestConsequenceEn:"The changed conditions are formally incorporated before restart.", bestConsequenceTr:"Değişen koşullar yeniden başlamadan resmi olarak izne dahil edilir.", weakEn:"Resume under the original permit because the controls are back", weakTr:"Kontroller geri geldiği için eski izinle devam et", weakConsequenceEn:"The interruption and changed conditions are not captured in the authorization.", weakConsequenceTr:"Kesinti ve değişen koşullar yetkilendirmeye yansıtılmaz." },
  ],
});

export const lotoUnexpectedEnergy = buildScenario({
  id: "loto-unexpected-energy",
  titleEn: "LOTO: Unexpected Energy",
  titleTr: "LOTO: Beklenmeyen Enerji",
  category: "LOTO / Isolation",
  introEn: "A maintenance isolation appears complete, but signs of stored and secondary energy challenge the original LOTO plan.",
  introTr: "Bir bakım izolasyonu tamamlanmış görünüyor ancak depolanmış ve ikincil enerji belirtileri ilk LOTO planını sorgulatıyor.",
  steps: [
    { id:"coast", titleEn:"The equipment is still coasting", titleTr:"Ekipman hâlâ dönüyor", situationEn:"Power is isolated but the rotating assembly continues moving longer than expected.", situationTr:"Enerji kesilmiş ancak döner ekipman beklenenden uzun süre hareket etmeye devam ediyor.", bestEn:"Wait for complete stop and verify zero energy", bestTr:"Tam durmayı bekle ve sıfır enerjiyi doğrula", bestConsequenceEn:"Stored kinetic energy is treated as part of the isolation.", bestConsequenceTr:"Depolanmış kinetik enerji izolasyonun parçası olarak ele alınır.", weakEn:"Begin non-contact inspection while it slows", weakTr:"Yavaşlarken temassız kontrole başla", weakConsequenceEn:"Work begins before all hazardous energy has dissipated.", weakConsequenceTr:"Tüm tehlikeli enerji boşalmadan çalışma başlar." },
    { id:"meter", titleEn:"The test instrument was not proved", titleTr:"Test cihazı doğrulanmadı", situationEn:"The electrician measures zero volts but did not test the meter on a known live source immediately before the check.", situationTr:"Elektrikçi sıfır volt ölçüyor ancak kontrol öncesi cihazı bilinen enerjili bir kaynakta doğrulamadı.", bestEn:"Perform live-dead-live verification", bestTr:"Canlı-ölü-canlı doğrulamasını yap", bestConsequenceEn:"The absence-of-voltage test is validated.", bestConsequenceTr:"Gerilim yokluğu testi doğrulanır.", weakEn:"Accept the zero reading because the meter passed yesterday", weakTr:"Cihaz dün kontrolden geçtiği için sıfır ölçümünü kabul et", weakConsequenceEn:"Instrument condition at the moment of testing is not verified.", weakConsequenceTr:"Ölçüm anındaki cihaz durumu doğrulanmaz." },
    { id:"pressure", titleEn:"Pressure slowly rebuilds", titleTr:"Basınç yavaşça geri geliyor", situationEn:"A gauge that was at zero begins to rise slightly after ten minutes, suggesting a passing valve or trapped source.", situationTr:"Sıfırdaki manometre on dakika sonra hafif yükselmeye başlıyor; kaçıran vana veya hapsolmuş kaynak ihtimali var.", bestEn:"Stop and re-establish the isolation boundary", bestTr:"Dur ve izolasyon sınırını yeniden kur", bestConsequenceEn:"The unexpected energy source is identified before work continues.", bestConsequenceTr:"Beklenmeyen enerji kaynağı işe devam etmeden belirlenir.", weakEn:"Bleed the pressure periodically and continue", weakTr:"Basıncı aralıklarla boşaltıp devam et", weakConsequenceEn:"A symptom is managed without controlling its source.", weakConsequenceTr:"Kaynak kontrol edilmeden yalnızca belirti yönetilir.", weakCritical:true, weakImpact:{safety:-30,judgment:-26,response:-18} },
    { id:"lockbox", titleEn:"One worker is missing from the lockbox list", titleTr:"Bir çalışan kilit kutusu listesinde yok", situationEn:"A mechanic is inside the work scope but his personal lock is not recorded on the group lockbox sheet.", situationTr:"Bir mekanikçi çalışma kapsamında ancak kişisel kilidi grup kilit kutusu formunda kayıtlı değil.", bestEn:"Stop and reconcile personnel and personal locks", bestTr:"Dur, personel ve kişisel kilitleri eşleştir", bestConsequenceEn:"Every exposed person is tied to the isolation control.", bestConsequenceTr:"Maruz kalan her kişi izolasyon kontrolüne bağlanır.", weakEn:"Add his name to the sheet after the task", weakTr:"İşten sonra adını forma ekle", weakConsequenceEn:"The active isolation record does not reflect who is exposed.", weakConsequenceTr:"Aktif izolasyon kaydı maruz kalan kişiyi göstermiyor." },
    { id:"shift", titleEn:"Shift change begins", titleTr:"Vardiya değişimi başlıyor", situationEn:"The outgoing authorized person wants to leave before the incoming person completes the lock transfer.", situationTr:"Çıkan yetkili kişi gelen yetkili kilit devrini tamamlamadan ayrılmak istiyor.", bestEn:"Complete controlled lock transfer before handover", bestTr:"Devirden önce kontrollü kilit transferini tamamla", bestConsequenceEn:"Isolation ownership remains continuous.", bestConsequenceTr:"İzolasyon sahipliği kesintisiz kalır.", weakEn:"Use a verbal handover and transfer locks later", weakTr:"Sözlü devir yap ve kilitleri sonra aktar", weakConsequenceEn:"A gap is created in formal isolation ownership.", weakConsequenceTr:"Resmi izolasyon sahipliğinde boşluk oluşur." },
    { id:"contractor", titleEn:"A contractor has no personal lock", titleTr:"Taşeronun kişisel kilidi yok", situationEn:"A specialist contractor arrives for a five-minute measurement but did not bring an approved personal lock.", situationTr:"Uzman taşeron beş dakikalık ölçüm için geliyor ancak onaylı kişisel kilidi yanında değil.", bestEn:"Do not permit exposure until personal lock control is available", bestTr:"Kişisel kilit kontrolü sağlanana kadar maruziyete izin verme", bestConsequenceEn:"Short duration does not bypass LOTO ownership.", bestConsequenceTr:"Kısa süre LOTO sahipliğini bypass etmez.", weakEn:"Let him work under the supervisor's lock", weakTr:"Amirin kilidi altında çalışmasına izin ver", weakConsequenceEn:"Personal control of hazardous energy is lost.", weakConsequenceTr:"Tehlikeli enerji üzerinde kişisel kontrol kaybolur." },
    { id:"try-start", titleEn:"The start control is available", titleTr:"Start kumandası erişilebilir", situationEn:"After isolation, the team is ready to open the equipment but no functional try-start has been performed.", situationTr:"İzolasyon sonrası ekip ekipmanı açmaya hazır ancak fonksiyonel start denemesi yapılmadı.", bestEn:"Perform the approved try-start and return controls to safe state", bestTr:"Onaylı start denemesini yap ve kumandayı güvenli duruma getir", bestConsequenceEn:"Isolation effectiveness is challenged before intrusive work.", bestConsequenceTr:"Müdahaleli işten önce izolasyon etkinliği sınanır.", weakEn:"Skip it because electrical tests already showed zero", weakTr:"Elektrik testi sıfır gösterdiği için atla", weakConsequenceEn:"Other energy paths or control logic remain unchallenged.", weakConsequenceTr:"Diğer enerji yolları veya kontrol mantığı sınanmamış kalır." },
    { id:"scope", titleEn:"The maintenance scope expands", titleTr:"Bakım kapsamı genişliyor", situationEn:"The mechanic discovers a second component must be removed, but it sits across the original isolation boundary.", situationTr:"Mekanikçi ikinci bir parçanın da sökülmesi gerektiğini fark ediyor ancak parça ilk izolasyon sınırının dışında.", bestEn:"Stop and revise the isolation for the expanded scope", bestTr:"Dur ve genişleyen kapsam için izolasyonu revize et", bestConsequenceEn:"The energy boundary follows the real work scope.", bestConsequenceTr:"Enerji sınırı gerçek çalışma kapsamına uyarlanır.", weakEn:"Proceed because the adjacent component is not powered", weakTr:"Yan parça enerjili olmadığı için devam et", weakConsequenceEn:"The expanded mechanical and process energy paths are not assessed.", weakConsequenceTr:"Genişleyen mekanik ve proses enerji yolları değerlendirilmez." },
    { id:"restart", titleEn:"Operations requests restart", titleTr:"Operasyon yeniden başlatma istiyor", situationEn:"Maintenance is complete. Operations is waiting, but one worker has not yet confirmed tools and body parts are clear.", situationTr:"Bakım tamamlandı. Operasyon bekliyor ancak bir çalışan aletlerin ve personelin tamamen çıktığını henüz teyit etmedi.", bestEn:"Hold restart until full personnel and tool clearance is verified", bestTr:"Tüm personel ve alet açıklığı doğrulanana kadar başlatmayı beklet", bestConsequenceEn:"Restart is authorized only after complete clearance.", bestConsequenceTr:"Yeniden başlatma yalnızca tam açıklık sonrası yetkilendirilir.", weakEn:"Restart once the supervisor says the area looks clear", weakTr:"Amir alan temiz görünüyor dediğinde başlat", weakConsequenceEn:"Visual confidence replaces individual clearance verification.", weakConsequenceTr:"Bireysel açıklık doğrulamasının yerini görsel güven alır." },
  ],
});

export const scaffoldStatusChange = buildScenario({
  id: "scaffold-status-change",
  titleEn: "Scaffolding: Status Changed",
  titleTr: "İskele: Durum Değişti",
  category: "Scaffolding",
  introEn: "A scaffold that was acceptable earlier in the shift is altered by several crews. You must decide when its status is no longer valid.",
  introTr: "Vardiya başında uygun olan bir iskele farklı ekiplerce değiştirilir. Etiket geçerliliğinin ne zaman sona erdiğine karar vermelisin.",
  steps: [
    { id:"tag", titleEn:"The tag is yellow", titleTr:"Etiket sarı", situationEn:"The scaffold carries a yellow tag allowing restricted use, but the crew cannot explain the listed restriction.", situationTr:"İskelede kısıtlı kullanıma izin veren sarı etiket var ancak ekip kısıtlamayı açıklayamıyor.", bestEn:"Clarify the restriction before access", bestTr:"Erişimden önce kısıtlamayı netleştir", bestConsequenceEn:"Users understand the exact conditions of permitted use.", bestConsequenceTr:"Kullanıcılar izin verilen kullanım koşullarını tam olarak anlar.", weakEn:"Allow access with harnesses as an extra precaution", weakTr:"Ek önlem olarak emniyet kemeriyle erişime izin ver", weakConsequenceEn:"PPE is used to compensate for an unknown scaffold condition.", weakConsequenceTr:"Bilinmeyen iskele koşulu KKD ile telafi edilmeye çalışılır." },
    { id:"ladder", titleEn:"The access ladder has been moved", titleTr:"Erişim merdiveni taşınmış", situationEn:"A materials crew shifted the ladder one bay to make room for a delivery. It is tied but no longer reaches the designed landing.", situationTr:"Malzeme ekibi teslimat için merdiveni bir açıklık yana taşımış. Merdiven bağlı ancak tasarlanan çıkış noktasına ulaşmıyor.", bestEn:"Stop access and restore approved ladder position", bestTr:"Erişimi durdur ve onaylı merdiven konumunu geri getir", bestConsequenceEn:"The designed access route is reinstated.", bestConsequenceTr:"Tasarlanan erişim güzergahı yeniden sağlanır.", weakEn:"Use the moved ladder until the delivery is complete", weakTr:"Teslimat bitene kadar taşınan merdiveni kullan", weakConsequenceEn:"Temporary convenience overrides the approved access arrangement.", weakConsequenceTr:"Geçici kolaylık onaylı erişim düzeninin önüne geçer." },
    { id:"rail", titleEn:"A guardrail is removed", titleTr:"Bir korkuluk sökülüyor", situationEn:"A pipe cannot pass through the bay, so a worker removes a midrail and says it will be replaced immediately after lifting.", situationTr:"Boru açıklıktan geçmediği için çalışan ara korkuluğu söküyor ve kaldırma sonrası hemen takacağını söylüyor.", bestEn:"Suspend use and control the modification through the scaffold process", bestTr:"Kullanımı askıya al ve değişikliği iskele prosedürüyle yönet", bestConsequenceEn:"The scaffold status changes before uncontrolled use occurs.", bestConsequenceTr:"Kontrolsüz kullanım oluşmadan iskele statüsü değiştirilir.", weakEn:"Allow it if nobody works in that bay", weakTr:"O açıklıkta kimse çalışmazsa izin ver", weakConsequenceEn:"An unauthorized structural protection change remains on an active scaffold.", weakConsequenceTr:"Aktif iskelede yetkisiz koruma değişikliği kalır.", weakCritical:true, weakImpact:{safety:-25,judgment:-20,response:-16} },
    { id:"load", titleEn:"Materials accumulate on the deck", titleTr:"Platformda malzeme birikiyor", situationEn:"Valve parts and pipe supports are placed on one platform because the ground staging area is full.", situationTr:"Zemin stok alanı dolu olduğu için vana parçaları ve boru destekleri tek platformda birikiyor.", bestEn:"Check load class and redistribute or remove excess materials", bestTr:"Yük sınıfını kontrol et ve fazla malzemeyi dağıt veya kaldır", bestConsequenceEn:"Platform loading remains within verified limits.", bestConsequenceTr:"Platform yüklemesi doğrulanmış sınırlar içinde kalır.", weakEn:"Keep the load if the boards show no visible deflection", weakTr:"Kalaslarda görünür eğilme yoksa yükü bırak", weakConsequenceEn:"Visible deflection is used instead of the scaffold load rating.", weakConsequenceTr:"İskele yük sınıfı yerine görünür eğilme kriter olur." },
    { id:"gap", titleEn:"A board has shifted", titleTr:"Bir kalas kaymış", situationEn:"A small opening appears near the access point after materials are dragged across the deck.", situationTr:"Malzemeler platformda sürüklendikten sonra erişim noktasında küçük bir boşluk oluşuyor.", bestEn:"Close the scaffold and have it corrected and reinspected", bestTr:"İskeleyi kapat, düzelt ve yeniden kontrol ettir", bestConsequenceEn:"The changed platform condition is formally restored.", bestConsequenceTr:"Değişen platform koşulu resmi olarak düzeltilir.", weakEn:"Mark the opening and keep the scaffold in use", weakTr:"Boşluğu işaretleyip iskeleyi kullanmaya devam et", weakConsequenceEn:"A known trip/fall opening remains in the access path.", weakConsequenceTr:"Bilinen takılma/düşme boşluğu erişim yolunda kalır." },
    { id:"modification", titleEn:"A user wants to move a board", titleTr:"Kullanıcı bir kalası taşımak istiyor", situationEn:"A welder asks to move one board 150 mm to gain torch access and promises to put it back afterward.", situationTr:"Kaynakçı torç erişimi için bir kalası 150 mm kaydırmak istiyor ve sonra geri koyacağını söylüyor.", bestEn:"Require an authorized scaffold modification", bestTr:"Yetkili iskele değişikliği talep et", bestConsequenceEn:"The scaffold remains under competent-person control.", bestConsequenceTr:"İskele yetkin kişi kontrolünde kalır.", weakEn:"Allow the small adjustment under supervisor observation", weakTr:"Amir gözetiminde küçük ayarlamaya izin ver", weakConsequenceEn:"User modification bypasses the scaffold control system.", weakConsequenceTr:"Kullanıcı değişikliği iskele kontrol sistemini bypass eder." },
    { id:"weather", titleEn:"Wind increases", titleTr:"Rüzgar artıyor", situationEn:"Sheeting fitted to one side begins to flap as wind rises. The scaffold itself still looks stable.", situationTr:"Rüzgar arttıkça bir yandaki kaplama sallanmaya başlıyor. İskele hâlâ stabil görünüyor.", bestEn:"Stop use and reassess wind loading and sheeting", bestTr:"Kullanımı durdur ve rüzgar yükü ile kaplamayı yeniden değerlendir", bestConsequenceEn:"Added wind load is treated as a changed scaffold condition.", bestConsequenceTr:"Ek rüzgar yükü değişen iskele koşulu olarak ele alınır.", weakEn:"Continue because the scaffold frame is not moving", weakTr:"İskele gövdesi hareket etmediği için devam et", weakConsequenceEn:"The effect of sheeting on wind load is ignored.", weakConsequenceTr:"Kaplamanın rüzgar yüküne etkisi göz ardı edilir." },
    { id:"below", titleEn:"People work below the scaffold", titleTr:"İskelenin altında çalışma var", situationEn:"Another crew starts cable pulling directly below while small tools are being used on the upper level.", situationTr:"Üst seviyede küçük aletler kullanılırken başka ekip doğrudan altta kablo çekmeye başlıyor.", bestEn:"Coordinate the interface and establish dropped-object controls", bestTr:"Arayüzü koordine et ve düşen cisim kontrollerini kur", bestConsequenceEn:"Simultaneous work is controlled before both crews continue.", bestConsequenceTr:"İki ekip devam etmeden eş zamanlı çalışma kontrol edilir.", weakEn:"Tell the lower crew to stay alert", weakTr:"Alt ekibe dikkatli olmalarını söyle", weakConsequenceEn:"Awareness replaces physical control of the exposure.", weakConsequenceTr:"Fiziksel maruziyet kontrolünün yerini farkındalık alır." },
  ],
});

export const excavationWaterIngress = buildScenario({
  id: "excavation-water-ingress",
  titleEn: "Excavation: Water Is Rising",
  titleTr: "Kazı: Su Yükseliyor",
  category: "Excavation",
  introEn: "A trench starts dry and stable. Water, nearby plant and changing ground conditions gradually challenge the original excavation controls.",
  introTr: "Bir hendek kuru ve stabil başlıyor. Su, yakındaki ekipman ve değişen zemin koşulları ilk kazı kontrollerini giderek zorluyor.",
  steps: [
    { id:"seepage", titleEn:"Water starts seeping through one wall", titleTr:"Bir duvardan su sızmaya başlıyor", situationEn:"A small wet patch grows at the base of the trench after nearby utility flushing begins.", situationTr:"Yakındaki hat yıkaması başladıktan sonra hendeğin tabanında küçük bir ıslak alan büyüyor.", bestEn:"Stop and reassess ground stability and water source", bestTr:"Dur, zemin stabilitesini ve su kaynağını yeniden değerlendir", bestConsequenceEn:"The changed ground condition is assessed before workers remain exposed.", bestConsequenceTr:"Çalışanlar maruziyette kalmadan değişen zemin koşulu değerlendirilir.", weakEn:"Pump the water while work continues", weakTr:"Çalışma sürerken suyu pompala", weakConsequenceEn:"Water is removed without understanding its effect on soil stability.", weakConsequenceTr:"Suyun zemin stabilitesine etkisi anlaşılmadan yalnızca su tahliye edilir." },
    { id:"spoil", titleEn:"The spoil pile moves closer", titleTr:"Hafriyat yığını yaklaşıyor", situationEn:"A loader operator places additional spoil near the trench because the designated area is full.", situationTr:"Belirlenen alan dolu olduğu için yükleyici operatörü ek hafriyatı hendeğe yakın döküyor.", bestEn:"Restore the required setback before entry continues", bestTr:"Giriş devam etmeden gerekli mesafeyi yeniden sağla", bestConsequenceEn:"Surcharge loading at the edge is controlled.", bestConsequenceTr:"Kenar üzerindeki ek yük kontrol edilir.", weakEn:"Continue if the pile remains below the trench depth", weakTr:"Yığın hendek derinliğinden düşükse devam et", weakConsequenceEn:"Pile height is used instead of safe setback and ground assessment.", weakConsequenceTr:"Güvenli mesafe ve zemin değerlendirmesi yerine yığın yüksekliği kullanılır." },
    { id:"access", titleEn:"The ladder is now too far away", titleTr:"Merdiven artık fazla uzakta", situationEn:"The excavation advanced another section and the nearest ladder is now beyond the project's maximum travel distance.", situationTr:"Kazı bir bölüm ilerledi ve en yakın merdiven proje maksimum yürüme mesafesinin dışında kaldı.", bestEn:"Add compliant access before workers re-enter", bestTr:"Çalışanlar yeniden girmeden uygun erişim ekle", bestConsequenceEn:"Emergency egress remains practical from the active workface.", bestConsequenceTr:"Aktif çalışma cephesinden acil çıkış pratik kalır.", weakEn:"Use the existing ladder because the trench is open and visible", weakTr:"Hendek açık ve görünür olduğu için mevcut merdiveni kullan", weakConsequenceEn:"Visibility does not reduce travel distance during an emergency.", weakConsequenceTr:"Görünürlük acil durumda çıkış mesafesini azaltmaz." },
    { id:"crack", titleEn:"A tension crack appears", titleTr:"Gerilme çatlağı oluşuyor", situationEn:"A narrow crack appears parallel to the trench edge after a vehicle passes nearby.", situationTr:"Yakından bir araç geçtikten sonra hendek kenarına paralel dar bir çatlak oluşuyor.", bestEn:"Evacuate and have the excavation reassessed by the competent person", bestTr:"Tahliye et ve kazıyı yetkin kişiye yeniden değerlendir", bestConsequenceEn:"A possible collapse precursor is treated as a stop-work trigger.", bestConsequenceTr:"Olası göçme öncülü işi durdurma tetikleyicisi olarak ele alınır.", weakEn:"Mark the crack and monitor whether it grows", weakTr:"Çatlağı işaretle ve büyüyüp büyümediğini izle", weakConsequenceEn:"Workers remain exposed while a possible failure indicator is monitored.", weakConsequenceTr:"Olası göçme göstergesi izlenirken çalışanlar maruziyette kalır.", weakCritical:true, weakImpact:{safety:-32,judgment:-26,response:-22} },
    { id:"plant", titleEn:"An excavator needs to pass beside the trench", titleTr:"Ekskavatör hendek yanından geçmek istiyor", situationEn:"The operator requests a short pass close to the edge to reach another workfront.", situationTr:"Operatör başka çalışma alanına ulaşmak için kenara yakın kısa bir geçiş istiyor.", bestEn:"Stop trench work and verify ground/load controls before passage", bestTr:"Hendek işini durdur ve geçişten önce zemin/yük kontrollerini doğrula", bestConsequenceEn:"Dynamic surcharge and line-of-fire are controlled together.", bestConsequenceTr:"Dinamik ek yük ve ateş hattı birlikte kontrol edilir.", weakEn:"Let the machine pass slowly with a banksman", weakTr:"İşaretçi ile makinenin yavaş geçmesine izin ver", weakConsequenceEn:"Speed control does not verify edge stability or surcharge capacity.", weakConsequenceTr:"Hız kontrolü kenar stabilitesini veya ek yük kapasitesini doğrulamaz." },
    { id:"utility", titleEn:"The drawing and detector do not agree", titleTr:"Çizim ve dedektör uyuşmuyor", situationEn:"Utility drawings show no service, but the locator gives an intermittent signal across the next excavation section.", situationTr:"Hat çizimleri servis göstermiyor ancak dedektör sonraki kazı bölümünde kesintili sinyal veriyor.", bestEn:"Stop mechanical excavation and verify the service before proceeding", bestTr:"Mekanik kazıyı durdur ve ilerlemeden hattı doğrula", bestConsequenceEn:"Uncertainty is resolved before contact risk is created.", bestConsequenceTr:"Temas riski oluşmadan belirsizlik çözülür.", weakEn:"Proceed carefully because the drawing is the controlled document", weakTr:"Kontrollü doküman çizim olduğu için dikkatli devam et", weakConsequenceEn:"Field evidence is discounted despite a conflicting indication.", weakConsequenceTr:"Çelişkili saha göstergesine rağmen saha kanıtı göz ardı edilir." },
    { id:"rain", titleEn:"Heavy rain is forecast", titleTr:"Şiddetli yağmur bekleniyor", situationEn:"Rain is expected within thirty minutes. The crew estimates the task needs twenty minutes to finish.", situationTr:"Otuz dakika içinde yağmur bekleniyor. Ekip işi bitirmek için yirmi dakika gerektiğini söylüyor.", bestEn:"Exit early and secure the excavation before the weather arrives", bestTr:"Hava gelmeden erken çık ve kazıyı güvenli hale getir", bestConsequenceEn:"Weather margin is preserved rather than consumed by production pressure.", bestConsequenceTr:"Hava payı üretim baskısıyla tüketilmek yerine korunur.", weakEn:"Finish the task if rain has not started", weakTr:"Yağmur başlamadıysa işi bitir", weakConsequenceEn:"The plan relies on forecast timing remaining exact.", weakConsequenceTr:"Plan hava tahmininin tam zamanında gerçekleşmesine dayanır." },
    { id:"reinspect", titleEn:"Conditions appear normal again", titleTr:"Koşullar tekrar normal görünüyor", situationEn:"Water is controlled, spoil is moved and the crack area has been stabilized. Workers want to re-enter immediately.", situationTr:"Su kontrol edildi, hafriyat taşındı ve çatlak bölgesi stabilize edildi. Çalışanlar hemen yeniden girmek istiyor.", bestEn:"Require a competent-person reinspection before re-entry", bestTr:"Yeniden girişten önce yetkin kişi kontrolü iste", bestConsequenceEn:"The excavation is formally accepted after the changed condition.", bestConsequenceTr:"Değişen koşul sonrası kazı resmi olarak kabul edilir.", weakEn:"Allow re-entry because the visible problems are corrected", weakTr:"Görünür sorunlar düzeldiği için yeniden girişe izin ver", weakConsequenceEn:"Visible correction is treated as proof of overall stability.", weakConsequenceTr:"Görünür düzeltme genel stabilitenin kanıtı kabul edilir." },
    { id:"close", titleEn:"The shift is ending", titleTr:"Vardiya bitiyor", situationEn:"The trench will remain open overnight and another contractor will work nearby before your crew returns.", situationTr:"Hendek gece açık kalacak ve ekibin dönmeden başka bir yüklenici yakınında çalışacak.", bestEn:"Secure the excavation and hand over changed conditions and restrictions", bestTr:"Kazıyı güvenli hale getir ve değişen koşulları/kısıtları devret", bestConsequenceEn:"The next workfront inherits the correct excavation status.", bestConsequenceTr:"Sonraki çalışma ekibi doğru kazı statüsünü devralır.", weakEn:"Barricade it and brief your own crew next morning", weakTr:"Bariyerle ve kendi ekibini sabah bilgilendir", weakConsequenceEn:"Other workers may encounter the excavation without the changed-condition handover.", weakConsequenceTr:"Diğer çalışanlar değişen koşul devri olmadan kazıyla karşılaşabilir." },
  ],
});

export const starterIncidentScenarios: Record<string, IncidentScenario> = {
  [heightAnchorChoice.id]: heightAnchorChoice,
  [confinedSpaceAtmosphere.id]: confinedSpaceAtmosphere,
  [lotoUnexpectedEnergy.id]: lotoUnexpectedEnergy,
  [scaffoldStatusChange.id]: scaffoldStatusChange,
  [excavationWaterIngress.id]: excavationWaterIngress,
};
