export type PPEStandard = { slug:string; code:string; category:string; title:{tr:string;en:string}; purpose:{tr:string;en:string}; use:{tr:string;en:string}; markings:{tr:string;en:string}; };

export const ppeStandards:PPEStandard[]=[
{slug:'en-397-industrial-safety-helmets',code:'EN 397',category:'Head protection',title:{tr:'Endüstriyel Baret Standardı',en:'Industrial Safety Helmet Standard'},purpose:{tr:'Endüstriyel baretlerin darbe, penetrasyon ve ilgili koruma performansını kapsar.',en:'Covers impact, penetration and related protective performance for industrial safety helmets.'},use:{tr:'İnşaat, bakım, üretim ve başa düşen cisim riskinin bulunduğu endüstriyel işler.',en:'Construction, maintenance, manufacturing and industrial work with falling-object hazards.'},markings:{tr:'Ürün üzerindeki EN 397 işareti, üretici, beden ve uygulanabilir ek işaretleri kontrol edin.',en:'Check EN 397 marking, manufacturer, size and applicable optional markings on the product.'}},
{slug:'en-361-full-body-harnesses',code:'EN 361',category:'Fall protection',title:{tr:'Tam Vücut Emniyet Kemeri Standardı',en:'Full Body Harness Standard'},purpose:{tr:'Düşüş durdurma sistemlerinde kullanılan tam vücut kemerlerini kapsar.',en:'Covers full body harnesses used in fall-arrest systems.'},use:{tr:'Yüksekte çalışma, iskele, çatı, çelik montaj ve düşüş durdurma gereken işler.',en:'Work at height, scaffolds, roofs, steel erection and tasks requiring fall arrest.'},markings:{tr:'EN 361 işareti ile bağlantı noktası işaretlerini, üretici bilgisini ve izlenebilirliği kontrol edin.',en:'Check EN 361 marking, attachment-point markings, manufacturer information and traceability.'}},
{slug:'en-355-energy-absorbers',code:'EN 355',category:'Fall protection',title:{tr:'Şok Emici (Enerji Emici) Standardı',en:'Energy Absorber Standard'},purpose:{tr:'Düşüş durdurma sistemlerinde düşüş enerjisini sınırlayan enerji emicileri (şok emicileri) kapsar.',en:'Covers energy absorbers intended to limit fall energy in fall-arrest systems.'},use:{tr:'Şok emicili lanyard ve uygun kişisel düşüş durdurma sistemleri.',en:'Shock-absorbing lanyards and compatible personal fall-arrest systems.'},markings:{tr:'EN 355 işareti, üretici bilgisi, ürün kimliği ve kullanım talimatlarını doğrulayın.',en:'Verify EN 355 marking, manufacturer, product identity and instructions.'}},
{slug:'en-362-connectors',code:'EN 362',category:'Fall protection',title:{tr:'Karabina ve Bağlantı Elemanı Standardı',en:'Connector and Carabiner Standard'},purpose:{tr:'Düşmeye karşı kişisel koruyucu sistemlerdeki bağlantı elemanlarını kapsar.',en:'Covers connectors used in personal fall-protection systems.'},use:{tr:'Emniyet kemeri, lanyard, yaşam hattı ve ankraj sistemi bağlantıları.',en:'Harness, lanyard, lifeline and anchorage-system connections.'},markings:{tr:'EN 362 işareti, sınıf, kilitleme mekanizması ve üretici bilgilerini kontrol edin.',en:'Check EN 362 marking, connector class, locking mechanism and manufacturer information.'}},
{slug:'en-166-eye-protection',code:'EN 166',category:'Eye protection',title:{tr:'Göz Koruyucu Standardı',en:'Eye Protection Standard'},purpose:{tr:'Kişisel göz koruyucular için genel performans ve işaretleme gerekliliklerini kapsar.',en:'Covers general performance and marking requirements for personal eye protection.'},use:{tr:'Taşlama, delme, kesme, sıçrama ve parçacık riski bulunan işler.',en:'Grinding, drilling, cutting and work with splash or particle hazards.'},markings:{tr:'Lens ve çerçeve işaretlerini, optik sınıfı ve mekanik dayanım kodlarını kontrol edin.',en:'Check lens/frame markings, optical class and mechanical-strength codes.'}},
{slug:'en-388-protective-gloves',code:'EN 388',category:'Hand protection',title:{tr:'Mekanik Risklere Karşı Eldiven Standardı',en:'Protective Gloves Against Mechanical Risks'},purpose:{tr:'Aşınma, kesilme, yırtılma ve delinme gibi mekanik risklere karşı eldiven performansını kapsar.',en:'Covers glove performance against mechanical risks such as abrasion, cut, tear and puncture.'},use:{tr:'Malzeme taşıma, montaj, bakım ve mekanik el yaralanması riski bulunan işler.',en:'Material handling, assembly, maintenance and tasks with mechanical hand hazards.'},markings:{tr:'EN 388 piktogramı ile ürünün performans kodlarını kontrol edin; kodu işe özgü riskle eşleştirin.',en:'Check the EN 388 pictogram and performance codes; match the rating to the task hazard.'}},
{slug:'en-374-chemical-gloves',code:'EN ISO 374',category:'Hand protection',title:{tr:'Kimyasallara Karşı Koruyucu Eldiven Standardı',en:'Protective Gloves Against Chemicals'},purpose:{tr:'Tehlikeli kimyasallar ve mikroorganizmalara karşı koruyucu eldivenleri kapsayan standart ailesidir.',en:'Standard family covering protective gloves against dangerous chemicals and microorganisms.'},use:{tr:'Kimyasal transfer, laboratuvar, temizlik ve kimyasal temas riski bulunan işler.',en:'Chemical transfer, laboratory, cleaning and tasks with chemical-contact hazards.'},markings:{tr:'İlgili EN ISO 374 işaretini, kimyasal kodlarını ve üreticinin geçirgenlik verilerini kontrol edin.',en:'Check the applicable EN ISO 374 marking, chemical codes and manufacturer permeation data.'}},
{slug:'en-149-filtering-half-masks',code:'EN 149',category:'Respiratory protection',title:{tr:'Partiküllere Karşı Filtreli Yarım Maske Standardı',en:'Filtering Half Mask Standard'},purpose:{tr:'Partiküllere karşı filtreli yarım maskelerin performans sınıflarını kapsar.',en:'Covers performance classes for filtering half masks against particles.'},use:{tr:'Toz ve partikül maruziyetinin bulunduğu, risk değerlendirmesine uygun solunum koruması gereken işler.',en:'Tasks with dust/particle exposure where risk assessment requires suitable respiratory protection.'},markings:{tr:'EN 149 ve FFP sınıfı dahil ürün işaretlerini kontrol edin; seçimi maruziyet değerlendirmesine göre yapın.',en:'Check EN 149 and FFP class markings; select protection from the exposure assessment.'}},
{slug:'en-352-hearing-protection',code:'EN 352',category:'Hearing protection',title:{tr:'İşitme Koruyucu Standardı',en:'Hearing Protection Standard'},purpose:{tr:'Kulaklık ve kulak tıkacı dahil işitme koruyucular için standart ailesidir.',en:'Standard family for hearing protectors including earmuffs and earplugs.'},use:{tr:'Gürültü risk değerlendirmesinin işitme koruması gerektirdiği çalışma alanları.',en:'Work areas where noise risk assessment requires hearing protection.'},markings:{tr:'İlgili EN 352 bölümünü, ürün işaretlerini ve üreticinin gürültü azaltma verilerini kontrol edin.',en:'Check the applicable EN 352 part, product markings and manufacturer attenuation data.'}},
{slug:'en-iso-20345-safety-footwear',code:'EN ISO 20345',category:'Foot protection',title:{tr:'Emniyet Ayakkabısı Standardı',en:'Safety Footwear Standard'},purpose:{tr:'Emniyet ayakkabılarının temel ve ek koruyucu özelliklerini kapsar.',en:'Covers basic and additional protective properties of safety footwear.'},use:{tr:'Endüstri, inşaat, depo, bakım ve ayak yaralanması riski bulunan işler.',en:'Industrial, construction, warehouse and maintenance work with foot hazards.'},markings:{tr:'EN ISO 20345 işaretini ve ürünün koruma sınıfı/ek özellik kodlarını kontrol edin.',en:'Check EN ISO 20345 marking and the footwear protection class/additional property codes.'}}
];
export const getPPEStandard=(slug:string)=>ppeStandards.find(x=>x.slug===slug);