export type Localized={tr:string;en:string};
export type FamilyItem={code:string;relation:Localized};
export type ConfusionItem={label:Localized;detail:Localized};
export type PPEExperience={
  labelWhere:Localized[];
  family:FamilyItem[];
  confused:ConfusionItem[];
  wrongChoice:{scenario:Localized;why:Localized;better:Localized};
};

const T=(tr:string,en:string):Localized=>({tr,en});
const F=(code:string,tr:string,en:string):FamilyItem=>({code,relation:T(tr,en)});
const C=(tr:string,en:string,detailTr:string,detailEn:string):ConfusionItem=>({label:T(tr,en),detail:T(detailTr,detailEn)});

export const ppeExperience:Record<string,PPEExperience>={
  'EN 397':{
    labelWhere:[T('Kabuk içindeki kalıcı standart/tip işareti ve üretici etiketi','Permanent standard/type marking and manufacturer label inside the shell'),T('Baret iç yüzeyi / siper altındaki beden ve izlenebilirlik bilgisi','Size and traceability information inside shell / under brim'),T('Üretici kullanım talimatı ve beyan edilen ek performans işaretleri','Manufacturer instructions and declared additional-performance markings')],
    family:[F('EN 397:2025','Endüstriyel koruyucu baretler; güncel sürüm T1/T2 tiplerini ayırır','Industrial protective helmets; current edition distinguishes T1/T2 types'),F('EN 50365:2023','Canlı çalışma için elektriksel yalıtımlı baretler ayrı uzmanlık standardıdır; iş gerektiriyorsa ayrıca doğrulanır','Electrically insulating helmets for live working are covered by a separate specialist standard; verify when required by the task'),F('EN 12492:2025','Dağcılık tipi baretler ayrı ürün standardıdır; yalnız görünüşe bakarak eşdeğer kabul edilmez','Mountaineering helmets are a separate product standard; do not assume equivalence from appearance')],
    confused:[C('T1 ≠ T2','T1 ≠ T2','Güncel EN 397’de T1 tepe darbe performansına; T2 ise ek olarak daha yüksek enerjili tepe ve tepe dışı darbe performansına sahiptir.','In current EN 397, T1 addresses crown impact performance; T2 adds higher-energy crown and off-crown impact performance.')],
    wrongChoice:{scenario:T('Elektrik riski veya yüksekte çalışma bulunan işte yalnız “EN 397” yazısını görüp baret tipini ve ek performansları kontrol etmemek.','For electrical or work-at-height hazards, accepting a helmet solely because it says “EN 397” without checking type and additional performance.'),why:T('T1/T2 tipi ve özel uygulama performansları işe göre ayrıca doğrulanmalıdır.','T1/T2 type and special-application performance must be verified for the task.'),better:T('Risk değerlendirmesi + EN 397 sürümü/T1-T2 işareti + üretici teknik dokümanı + gerekiyorsa ilgili özel standardı birlikte kontrol et.','Check the risk assessment, EN 397 edition/T1-T2 marking, manufacturer documentation and any task-specific specialist standard together.')}
  },
  'EN 361':{
    labelWhere:[T('Kemer kolonuna dikilmiş ürün etiketi','Product label sewn to the harness webbing'),T('Sırt / bel bölgesindeki seri ve beden etiketi','Serial and size label around back / waist area'),T('A veya A/2 düşüş durdurma bağlantı işaretlerinin yanında','Beside A or A/2 fall-arrest attachment markings')],
    family:[F('EN 361','Tam vücut düşüş durdurma kemeri','Full-body fall-arrest harness'),F('EN 358','İş konumlandırma ve tutma sistemleriyle karıştırılmamalı','Do not confuse with work-positioning/restraint systems'),F('EN 813','Oturma kemeri fonksiyonları ayrı değerlendirilir','Sit-harness functions are assessed separately')],
    confused:[C('Düşüş durdurma noktası ≠ konumlandırma noktası','Fall-arrest point ≠ positioning point','Her D halkası düşüş durdurma için tasarlanmış değildir; ürün işaretini okuyun.','Not every D-ring is intended for fall arrest; read the product marking.')],
    wrongChoice:{scenario:T('Yan taraftaki konumlandırma D halkasını düşüş durdurma bağlantısı olarak kullanmak.','Using a side positioning D-ring as the fall-arrest attachment point.'),why:T('Bağlantı noktasının fonksiyonu ürün tasarımı ve işaretine bağlıdır.','Attachment-point function depends on product design and marking.'),better:T('Düşüş durdurma için A/A/2 olarak tanımlanan noktayı ve sistem uyumluluğunu doğrula.','Verify the A/A/2 fall-arrest point and system compatibility.')}
  },
  'EN 355':{
    labelWhere:[T('Enerji emici paket üzerindeki dikili ürün etiketi','Sewn product label on the energy-absorber pack'),T('Bağlantı halatı (lanyard) üzerindeki ürün / seri etiketi','Product / serial label on the lanyard'),T('Üretici talimatındaki kullanıcı ağırlığı, sistem uzunluğu ve düşüş açıklığı sınırları','User-mass, system-length and fall-clearance limits in manufacturer instructions')],
    family:[F('EN 355','Enerji emiciler; lanyarda veya başka sistem bileşenlerine entegre olabilir','Energy absorbers; may be integrated into a lanyard or other system components'),F('EN 354','Bağlantı halatları (lanyard) ayrı bileşen standardıdır','Lanyards are a separate component standard'),F('EN 360','Geri sarımlı düşüş durdurucular farklı ürün ailesidir','Retractable fall arresters are a different product family')],
    confused:[C('Enerji emici ≠ bağlantı halatının tamamı','Energy absorber ≠ the entire lanyard','Enerji emici düşüş enerjisini yöneten bileşendir; şok emicili lanyard ise emici ile bağlantı halatının birlikte kullanıldığı yaygın alt sistemdir.','The energy absorber is the element managing fall energy; a shock-absorbing lanyard is a common subsystem combining absorber and lanyard.')],
    wrongChoice:{scenario:T('Enerji emicili lanyardı kullanıp gerekli düşüş açıklığını hesaplamamak.','Using an energy-absorbing lanyard without checking required fall clearance.'),why:T('Enerji emici açıldığında sistem uzar; aşağıdaki engeller ve zemin hesaba katılmalıdır.','The system extends when the absorber deploys; obstacles and the level below must be considered.'),better:T('Üretici verileriyle ankraj yüksekliği, bağlantı halatı, emicinin açılma mesafesi ve güvenlik payını birlikte değerlendir.','Use manufacturer data to assess anchor height, lanyard, absorber deployment and safety margin together.')}
  },
  'EN 362':{
    labelWhere:[T('Karabina/bağlantı gövdesindeki lazer veya kalıcı işaret','Laser or permanent marking on connector body'),T('Gövde üzerinde B/M/T/A/Q sınıfı ve dayanım işaretleri','B/M/T/A/Q class and strength markings on the body'),T('Üretici, model ve izlenebilirlik kodu','Manufacturer, model and traceability code')],
    family:[F('EN 362','Kişisel düşüş koruma sistemlerindeki B/M/T/A/Q sınıf bağlantı elemanları','B/M/T/A/Q class connectors in personal fall-protection systems'),F('EN 795','Ankraj cihazları ayrı bir bileşen ailesidir','Anchor devices are a separate component family'),F('EN 361','Kemer bağlantı noktalarıyla sistem uyumluluğu kontrol edilir','System compatibility is checked with harness attachment points')],
    confused:[C('kN işareti ≠ her yönde aynı dayanım','kN marking ≠ same strength in every direction','Karabina sınıfı, yönü, kapı durumu ve yükleme ekseni kritik olabilir.','Connector class, orientation, gate condition and loading axis can be critical.')],
    wrongChoice:{scenario:T('Karabinayı kapı üzerine veya ürünün tasarlanmadığı eksende yüklemek.','Loading a connector across the gate or on an axis it was not designed for.'),why:T('Bağlantı elemanının sınıfı ve işaretlenmiş dayanımı yükleme yönüne bağlıdır.','Connector class and marked strength depend on loading direction.'),better:T('Sınıfı doğrula; bağlantının tasarlanan eksende, kapalı ve kilitli çalıştığını ve bileşenlerin uyumlu olduğunu kontrol et.','Verify the class, intended loading axis, closed/locked gate and component compatibility.')}
  },
  'EN 166':{
    labelWhere:[T('Eski ürünlerde lens veya çerçeve üzerindeki EN 166 işareti','EN 166 marking on lens or frame of legacy products'),T('Sap / yan kol üzerindeki üretici ve legacy kodlar','Manufacturer and legacy codes on temple / side arm'),T('Yeni ürünlerde EN ISO 16321-1 serisi işaretleri ve uygunluk belgesi','EN ISO 16321-1 series markings and conformity documentation on new products')],
    family:[F('EN 166:2001','Eski/legacy göz koruma referansı','Legacy eye-protection reference'),F('EN ISO 16321-1:2022+A1:2025','Yeni iş/mesleki göz-yüz koruması için güncel genel referans','Current general reference for new occupational eye/face protection'),F('EN ISO 16321-2 / -3','Kaynak ve mesh gibi özel uygulamalar için ilgili bölümler ayrıca değerlendirilir','Relevant parts are considered separately for welding, mesh and special applications')],
    confused:[C('EN 166 legacy ≠ yeni sertifikasyonda güncel standart','Legacy EN 166 ≠ current standard for new certification','11 Kasım 2025 sonrasında yeni ürün/yenilenen sertifikasyonda EN ISO 16321 serisi esas alınır; mevcut eski sertifikalar kendi geçerlilik koşullarına tabi olabilir.','After 11 November 2025 the EN ISO 16321 series applies to new products/renewed certification; existing legacy certificates may remain subject to their validity conditions.')],
    wrongChoice:{scenario:T('Kimyasal sıçrama riskinde yalnız açık yanlı güvenlik gözlüğünü yeterli kabul etmek.','Treating open-sided safety spectacles as sufficient for a chemical splash hazard.'),why:T('Koruma şekli, kapsama alanı ve sıçrama için ürünün beyan edilen performansı işe uygun olmalıdır.','Protector type, coverage and declared splash performance must match the task.'),better:T('Risk türüne uygun gözlük/goggle/yüz koruyucu tipini ve ürünün güncel standart/işaretlemesini doğrula.','Verify the protector type and current standard/marking for the actual hazard.')}
  },
  'EN 388':{
    labelWhere:[T('Eldiven sırtındaki EN 388 piktogramı ve performans kodu','EN 388 pictogram and performance code on glove back'),T('Manşet üzerindeki basılı / dikili etiket','Printed / sewn label on cuff'),T('Ambalaj ve üretici teknik föyündeki tam altı konumlu kod yapısı','Full up-to-six-position code structure on packaging and manufacturer datasheet')],
    family:[F('EN 388:2016+A1:2018','Mekanik riskler ve altı konuma kadar performans kodu','Mechanical risks with an up-to-six-position performance code'),F('EN ISO 374','Kimyasal riskler ayrı değerlendirilir','Chemical risks are assessed separately'),F('EN 407','Isı ve termal riskler ayrı değerlendirilir','Heat and thermal risks are assessed separately')],
    confused:[C('Yüksek kesilme seviyesi ≠ tüm risklerde güçlü eldiven','High cut level ≠ strong glove for every hazard','Kesilme performansı kimyasal, ısı veya iğne delinmesi gibi farklı risklerin yerine geçmez.','Cut performance does not replace chemical, thermal or needle-puncture protection.')],
    wrongChoice:{scenario:T('Keskin metal ile kimyasal temasın birlikte olduğu işte yalnız EN 388 kesilme koduna göre eldiven seçmek.','Selecting gloves only by EN 388 cut rating for a task involving both sharp metal and chemicals.'),why:T('Mekanik ve kimyasal riskler ayrı performans verileri gerektirir.','Mechanical and chemical hazards require separate performance data.'),better:T('Tüm tehlikeleri belirle; gerekiyorsa mekanik ve kimyasal koruma verilerini birlikte sağlayan ürünü üretici verileriyle doğrula.','Identify all hazards and verify a product with the required mechanical and chemical performance using manufacturer data.')}
  },
  'EN ISO 374':{
    labelWhere:[T('Eldiven sırtındaki kimyasal piktogram ve Tip A/B/C işareti','Chemical pictogram and Type A/B/C marking on glove back'),T('Manşet üzerindeki standart ve kimyasal harf kodları','Standard and chemical letter codes on cuff'),T('Üretici kimyasal uyumluluk, geçirgenlik ve bozunma tablosu','Manufacturer chemical-compatibility, permeation and degradation data')],
    family:[F('EN ISO 374-1:2016+A1:2018','Kimyasal risk sınıflandırması ve Tip A/B/C yapısı','Chemical-risk classification and Type A/B/C structure'),F('EN ISO 374-5:2016','Mikroorganizma riskleriyle ilgili bölüm','Part addressing micro-organism risks'),F('EN 388','Mekanik dayanım ayrıca değerlendirilir','Mechanical performance is assessed separately')],
    confused:[C('Tip A ≠ her kimyasala karşı koruma','Type A ≠ protection against every chemical','A/B/C tipi belirli test kimyasallarındaki laboratuvar performansını ifade eder; gerçek kimyasal için üretici uyumluluk/geçirgenlik verisini kontrol etmek gerekir.','A/B/C type describes laboratory performance against defined test chemicals; manufacturer compatibility/permeation data must be checked for the actual chemical.')],
    wrongChoice:{scenario:T('“Tip A” gördüğü için eldiveni sahadaki her çözücü için uygun kabul etmek.','Assuming a Type A glove is suitable for every solvent on site.'),why:T('Kimyasal uyumluluk; kimyasalın türü, konsantrasyonu, temas süresi ve eldiven malzemesine bağlıdır.','Chemical compatibility depends on substance, concentration, contact time and glove material.'),better:T('SDS + üretici kimyasal uyumluluk/geçirgenlik tablosu + gerçek temas koşullarını birlikte kontrol et.','Check the SDS, manufacturer chemical compatibility/permeation data and actual exposure conditions together.')}
  },
  'EN 149':{
    labelWhere:[T('Maskenin gövdesi üzerindeki EN 149, FFP ve NR/R/D baskısı','EN 149, FFP and NR/R/D marking printed on the mask body'),T('Ambalaj üzerindeki standart/sürüm, sınıf ve kullanım işaretleri','Standard/edition, class and use markings on packaging'),T('Üretici adı, model ve uygunluk işaretleri','Manufacturer, model and conformity markings')],
    family:[F('EN 149:2001+A1:2009','Partikül filtreli yarım maskeler; halen yayımlanmış güncel sürüm','Filtering half masks against particles; still the current published edition'),F('EN 143','Değiştirilebilir partikül filtreleri farklı sistemlerde kullanılır','Replaceable particle filters are used in different respirator systems'),F('EN 14387','Gaz/buhar filtreleri farklı tehlikelere yöneliktir','Gas/vapour filters address different hazards')],
    confused:[C('FFP3 ≠ gaz/buhar filtresi','FFP3 ≠ gas/vapour filter','FFP sınıfı partikül korumasıdır; solvent buharı gibi gaz/buhar tehlikesi için uygun solunum koruyucu ve filtre sistemi ayrıca seçilmelidir.','FFP class is for particles; gas/vapour hazards such as solvent vapour require a suitable respirator/filter system.')],
    wrongChoice:{scenario:T('Solvent buharı bulunan alanda FFP3 maskeyi “en yüksek seviye” olduğu için seçmek.','Choosing an FFP3 mask for solvent vapour because it is the “highest level”.'),why:T('EN 149 FFP sınıfları partikül tehlikelerine yöneliktir.','EN 149 FFP classes address particle hazards.'),better:T('Tehlikenin partikül mü gaz/buhar mı olduğunu belirle; uygun solunum koruyucu, filtre ve yüze uyum/sızdırmazlık gereksinimini üretici verileriyle doğrula.','Identify whether the hazard is particle or gas/vapour and verify the suitable respirator, filter and face-fit/seal requirements.')}
  },
  'EN 352':{
    labelWhere:[T('Kulaklık kupası / kafa bandı üzerindeki EN 352 bölüm ve ürün etiketi','EN 352 part and product label on earmuff cup / headband'),T('Kulak tıkacı ambalajı ve dağıtıcı etiketi','Earplug packaging and dispenser label'),T('Üretici teknik föyündeki SNR ve H/M/L verileri','SNR and H/M/L data in manufacturer datasheet')],
    family:[F('EN 352-1:2020','Bağımsız/baş bantlı kulaklıklar','Independent/headband earmuffs'),F('EN 352-2:2020+A1:2024','Kulak tıkaçları','Earplugs'),F('EN 352-3:2020','Baş/yüz koruyucuya takılan kulaklıklar; diğer elektronik/özel tiplerde ilgili bölüm ayrıca doğrulanır','Mounted earmuffs; verify the relevant part separately for electronic/special types')],
    confused:[C('En yüksek SNR ≠ otomatik en iyi seçim','Highest SNR ≠ automatically the best choice','Aşırı koruma iletişim, alarm ve çevresel farkındalığı gereksiz azaltabilir.','Overprotection can unnecessarily reduce communication, alarms and situational awareness.')],
    wrongChoice:{scenario:T('Gürültü ölçümüne bakmadan sadece en yüksek SNR değerli kulaklığı seçmek.','Choosing only the earmuff with the highest SNR without considering the noise assessment.'),why:T('Koruma seviyesi gerçek gürültü spektrumu, maruziyet ve iletişim ihtiyaçlarıyla birlikte değerlendirilmelidir.','Protection level should be assessed with actual noise spectrum, exposure and communication needs.'),better:T('Gürültü değerlendirmesi + üretici SNR/H-M-L verisi + doğru takma/uyum kontrolünü birlikte yap.','Combine noise assessment, manufacturer SNR/H-M-L data and correct fitting.')}
  },
  'EN ISO 20345':{
    labelWhere:[T('Ayakkabı dilindeki standart/sürüm ve S sınıfı etiketi','Standard/edition and S-category label on footwear tongue'),T('İç astar / saya üzerindeki beden ve ek özellik işaretleri','Size and additional-property markings on inner lining / upper'),T('Kutu ve üretici teknik föyündeki P/PL/PS, SR, WPA/WR ve diğer performans kodları','P/PL/PS, SR, WPA/WR and other performance codes on box and manufacturer datasheet')],
    family:[F('EN ISO 20345:2022+A1:2024','Genel amaçlı, koruyucu burunlu emniyet ayakkabısı için güncel referans','Current reference for general-purpose safety footwear with protective toe cap'),F('EN ISO 20346','Koruyucu ayakkabı ailesi farklı performans gereksinimine sahiptir','Protective footwear family has different performance requirements'),F('EN ISO 20347','Mesleki ayakkabı emniyet ayakkabısıyla aynı değildir','Occupational footwear is not the same as safety footwear')],
    confused:[C('S7 ≠ her özel riske uygun','S7 ≠ suitable for every special hazard','Yüksek S sınıfı görmek; kimyasal, elektriksel, erimiş metal veya itfaiye gibi özel risklerin otomatik karşılandığı anlamına gelmez.','A high S category does not automatically cover special chemical, electrical, molten-metal or firefighting hazards.')],
    wrongChoice:{scenario:T('S3/S7 gibi yüksek sınıf gördüğü için ürünü sıcak yüzey veya kimyasal maruziyet için otomatik uygun kabul etmek.','Assuming a higher S-category such as S3/S7 is automatically suitable for hot surfaces or chemical exposure.'),why:T('Özel riskler ek performans işaretleri veya ayrı/tamamlayıcı standart ve ürün çözümü gerektirebilir.','Special hazards may require additional performance markings or a separate/complementary standard and product solution.'),better:T('S sınıfını işe özgü tehlikeler, P/PL/PS ve gerekli SR/WPA/WR/HRO/FO gibi ek işaretlerle birlikte doğrula.','Verify the S category together with task-specific hazards, P/PL/PS and required additional markings such as SR/WPA/WR/HRO/FO.')}
  },
  'EN ISO 21420':{labelWhere:[T('Eldiven/ambalaj üzerindeki standart ve ürün etiketi','Standard and product label on glove/packaging'),T('Üretici teknik föyü','Manufacturer technical datasheet')],family:[F('EN ISO 21420','Koruyucu eldivenler için genel gereklilikler','General requirements for protective gloves'),F('EN 388 / EN ISO 374 / EN 407','Tehlikeye özgü performans standartları ayrıca gerekir','Hazard-specific performance standards are additionally required')],confused:[C('EN ISO 21420 ≠ belirli risk performansı','EN ISO 21420 ≠ specific hazard performance','Genel ürün standardıdır; mekanik/kimyasal/termal koruma seviyesini tek başına göstermez.','It is a general product standard and does not by itself state mechanical/chemical/thermal protection.')],wrongChoice:{scenario:T('Yalnız EN ISO 21420 işaretini görüp eldiveni kimyasal veya kesilme riskine uygun kabul etmek.','Accepting a glove for chemical or cut risk only because EN ISO 21420 is marked.'),why:T('İşe özgü risk standardı ayrıca doğrulanmalıdır.','The task-specific hazard standard must also be verified.'),better:T('EN ISO 21420 + gerçek tehlikeye uygun EN 388/EN ISO 374/EN 407 vb. performansını birlikte kontrol et.','Check EN ISO 21420 together with EN 388/EN ISO 374/EN 407 etc. as appropriate to the real hazard.')}},
  'EN 407':{labelWhere:[T('Eldiven sırtındaki termal risk piktogramı ve performans kodu','Thermal-risk pictogram and performance code on glove back'),T('Manşet/ambalaj etiketi','Cuff/packaging label')],family:[F('EN 407:2020','Termal risklere karşı el koruma','Hand protection against thermal risks'),F('EN ISO 21420','Genel eldiven gerekleri','General glove requirements'),F('EN 12477','Kaynakçı eldivenleri ayrı ürün standardıdır','Welder gloves are a separate product standard')],confused:[C('Yüksek temas ısısı ≠ tüm termal risklerde yüksek koruma','High contact-heat level ≠ high protection against every thermal hazard','Altı performans konumu farklı termal tehlikeleri temsil eder.','The six performance positions represent different thermal hazards.')],wrongChoice:{scenario:T('Yalnız temas ısısı seviyesi yüksek diye eldiveni alev veya erimiş metal işi için seçmek.','Selecting a glove for flame or molten metal only because contact-heat level is high.'),why:T('İlgili performans konumları ayrı test edilir.','Relevant performance positions are tested separately.'),better:T('Gerçek tehlikeyi belirle ve karşılık gelen EN 407 performans konumunu üretici verisiyle doğrula.','Identify the real hazard and verify the corresponding EN 407 performance position with manufacturer data.')}},
  'EN ISO 11611':{labelWhere:[T('Giysi iç etiketi / bakım etiketi','Garment inner/care label'),T('Üretici teknik föyü ve uygunluk beyanı','Manufacturer datasheet and declaration of conformity')],family:[F('EN ISO 11611','Kaynak ve benzeri proses koruyucu giysi','Welding/allied-process protective clothing'),F('EN ISO 11612','Genel ısı/alev koruyucu giysi; kapsam farklıdır','Heat/flame protective clothing with a different scope')],confused:[C('Kaynak giysisi ≠ kaynak eldiveni/yüz siperi','Welding clothing ≠ welding gloves/face shield','Giysi standardı el, göz/yüz ve ayak korumasını tek başına tamamlamaz.','The clothing standard does not by itself complete hand, eye/face and foot protection.')],wrongChoice:{scenario:T('EN ISO 11611 giysi giyildiği için kaynak başlığı ve eldiveni gereksiz saymak.','Treating welding helmet and gloves as unnecessary because EN ISO 11611 clothing is worn.'),why:T('Farklı vücut bölgeleri için ayrı PPE gerekir.','Separate PPE is required for different body areas.'),better:T('Kaynak risk değerlendirmesine göre giysi + yüz/göz + el + ayak korumasını sistem olarak seç.','Select clothing + face/eye + hand + foot protection as a system from the welding risk assessment.')}},
  'EN ISO 11612':{labelWhere:[T('Giysi iç etiketi ve performans kodları','Garment inner label and performance codes'),T('Üretici teknik föyü','Manufacturer technical datasheet')],family:[F('EN ISO 11612','Isı ve aleve karşı koruyucu giysi','Protective clothing against heat/flame'),F('EN ISO 11611','Kaynak proseslerine özel giysi standardı','Welding-process-specific clothing standard')],confused:[C('EN ISO 11612 ≠ her yüksek sıcaklık senaryosuna otomatik uygunluk','EN ISO 11612 ≠ automatic suitability for every high-temperature scenario','İşaretlenen A-F performansları hangi ısı tehlikelerine karşı test edildiğini gösterir.','Marked A-F performances indicate which thermal hazards were tested.')],wrongChoice:{scenario:T('Üründe yalnız temel alev performansı varken erimiş metal sıçramasına karşı da koruduğunu varsaymak.','Assuming molten-metal splash protection when only basic flame performance is marked.'),why:T('Erimiş metal performansı ayrı test ve işaret gerektirir.','Molten-metal performance requires separate testing and marking.'),better:T('İşin ısı tehlikesiyle ürün üzerindeki performans kodlarını birebir eşleştir.','Match task heat hazards directly to the marked product performance codes.')}},
  'EN ISO 20471':{labelWhere:[T('Giysi iç etiketi üzerindeki standart ve sınıf işareti','Standard and class marking on garment inner label'),T('Üretici bakım/yıkama talimatı','Manufacturer care/wash instructions')],family:[F('EN ISO 20471:2013+A1:2016','Yüksek görünürlüklü uyarı giysisi','High-visibility warning clothing'),F('EN 17353','Orta risk görünürlük ekipmanları farklı standarda tabidir','Enhanced visibility equipment for medium-risk situations is a different standard')],confused:[C('Reflektif şerit ≠ otomatik EN ISO 20471 uygunluğu','Reflective strip ≠ automatic EN ISO 20471 compliance','Giysi sınıfı minimum floresan ve retroreflektif malzeme alanlarına bağlıdır.','Garment class depends on minimum fluorescent and retroreflective material areas.')],wrongChoice:{scenario:T('Her reflektif yeleği yüksek risk trafik sahasında EN ISO 20471 Class 3 kabul etmek.','Treating every reflective vest as EN ISO 20471 Class 3 for high-risk traffic areas.'),why:T('Sınıf ürün etiketi ve tasarım alanlarıyla doğrulanır.','Class must be verified from product marking and garment design areas.'),better:T('Risk seviyesini belirle ve ürün etiketindeki EN ISO 20471 sınıfını doğrula.','Determine risk level and verify the EN ISO 20471 class on the product label.')}},
  'EN IEC 61482-2':{labelWhere:[T('Giysi iç etiketi / ark işareti','Garment inner label / arc marking'),T('Üretici ark performans teknik föyü','Manufacturer arc-performance datasheet')],family:[F('EN IEC 61482-2','Elektrik arkı termal tehlikelerine karşı giysi','Clothing against electric-arc thermal hazards'),F('EN 60903','Elektrik çarpması için yalıtkan eldiven ayrı standarda tabidir','Insulating gloves for electric shock are a separate standard')],confused:[C('Ark koruması ≠ elektriksel yalıtım','Arc protection ≠ electrical insulation','Giysi arkın termal etkisini azaltır; elektrik çarpmasını kapsamaz.','Clothing addresses arc thermal effects, not electric shock.')],wrongChoice:{scenario:T('Ark dereceli giysiyi gerilim temasına karşı yalıtım olarak görmek.','Treating arc-rated clothing as electrical insulation against voltage contact.'),why:T('Elektrik çarpması için ayrı yalıtkan PPE ve çalışma yöntemi gerekir.','Electric-shock risk requires separate insulating PPE and work methods.'),better:T('Ark termal riski + elektrik çarpması riskini ayrı değerlendir ve her biri için uygun PPE seç.','Assess arc thermal risk and electric-shock risk separately and select PPE for each.')}},
  'EN 1149-5':{labelWhere:[T('Giysi iç etiketi ve elektrostatik işaret','Garment inner label and electrostatic marking'),T('Üretici topraklama/kullanım talimatı','Manufacturer earthing/use instructions')],family:[F('EN 1149-5:2018','Elektrostatik koruyucu giysi gereklilikleri','Electrostatic protective clothing requirements'),F('EN 16350','Elektrostatik dağıtıcı koruyucu eldivenler ayrı standarda tabidir','Electrostatic dissipative protective gloves are a separate standard')],confused:[C('Antistatik ≠ elektrik çarpmasına karşı koruma','Antistatic ≠ electric-shock protection','EN 1149-5 şebeke gerilimine karşı koruma sağlamaz.','EN 1149-5 does not protect against mains voltage.')],wrongChoice:{scenario:T('EN 1149-5 giysiyi canlı elektrik işinde yalıtkan giysi gibi kullanmak.','Using EN 1149-5 clothing as insulating clothing for live electrical work.'),why:T('Standart elektrostatik kıvılcım riskine yöneliktir, elektrik şokuna değil.','The standard addresses electrostatic ignition risk, not electric shock.'),better:T('Elektrostatik ve elektrik çarpması risklerini ayrı değerlendir.','Assess electrostatic and electric-shock hazards separately.')}},
  'EN 50365':{labelWhere:[T('Baret içindeki kalıcı standart/üretici işareti','Permanent standard/manufacturer marking inside helmet'),T('Üretici elektriksel kullanım talimatı','Manufacturer electrical-use instructions')],family:[F('EN 50365:2023','Canlı çalışma için elektriksel yalıtımlı baret','Electrically insulating helmet for live working'),F('EN 397','Endüstriyel baret standardıdır; tek başına yalıtım kanıtı değildir','Industrial helmet standard; not by itself proof of electrical insulation')],confused:[C('EN 397 elektrik opsiyonu ≠ EN 50365 canlı çalışma baret kapsamı','EN 397 electrical option ≠ EN 50365 live-working helmet scope','Özel elektriksel uygulamada ilgili yalıtım standardı ayrıca doğrulanır.','For specialist electrical use, the relevant insulating standard is verified separately.')],wrongChoice:{scenario:T('Yalnız EN 397 işaretli bareti canlı elektrik işi için seçmek.','Selecting a helmet marked only EN 397 for live electrical work.'),why:T('Canlı çalışma elektriksel yalıtım gereksinimi ayrıca doğrulanmalıdır.','Live-working electrical insulation requirements must be verified separately.'),better:T('EN 50365 işareti + üretici gerilim/kullanım sınırlarını kontrol et.','Check EN 50365 marking plus manufacturer voltage/use limits.')}},
  'EN 60903':{labelWhere:[T('Eldiven üzerindeki standart/sınıf işareti','Standard/class marking on glove'),T('Periyodik test kayıt alanı / üretici etiketi','Periodic-test record area / manufacturer label')],family:[F('EN 60903','Canlı çalışma için yalıtkan ve kompozit eldiven','Insulating and composite gloves for live working'),F('EN 388','Mekanik risk eldiveni; elektriksel yalıtım standardı değildir','Mechanical-risk glove; not an electrical-insulation standard')],confused:[C('Mekanik eldiven ≠ yalıtkan eldiven','Mechanical glove ≠ insulating glove','Kesilme/aşınma performansı elektriksel dayanım anlamına gelmez.','Cut/abrasion performance does not mean electrical insulation.')],wrongChoice:{scenario:T('EN 388 eldiveni canlı elektrik çalışmasında yalıtkan eldiven yerine kullanmak.','Using an EN 388 glove instead of an insulating glove for live electrical work.'),why:T('Elektriksel yalıtım farklı test/sınıflandırma gerektirir.','Electrical insulation requires different testing/classification.'),better:T('Gerilime uygun EN 60903 sınıfı ve geçerli test durumunu doğrula.','Verify the EN 60903 class appropriate to voltage and valid test status.')}},
  'EN 136':{labelWhere:[T('Maske gövdesi/çerçevesindeki standart ve model işareti','Standard/model marking on mask body/frame'),T('Üretici kullanım ve bağlantı talimatı','Manufacturer use and connection instructions')],family:[F('EN 136:1998','Tam yüz maskeleri','Full face masks'),F('EN 140','Yarım maskeler ayrı ürün standardıdır','Half masks are a separate product standard'),F('EN 143 / EN 14387','Partikül ve gaz/buhar filtreleri ayrı ürün standartlarıdır','Particle and gas/vapour filters are separate product standards')],confused:[C('Tam yüz maskesi ≠ doğru filtre seçimi','Full face mask ≠ correct filter selection','Maske yüz parçasıdır; koruma kirleticiye uygun filtre veya hava besleme sistemiyle oluşur.','The mask is a facepiece; protection depends on the contaminant-appropriate filter or supplied-air system.')],wrongChoice:{scenario:T('EN 136 maskeye herhangi bir filtre takarak her kimyasala karşı uygun kabul etmek.','Assuming any filter on an EN 136 mask is suitable for every chemical.'),why:T('Filtre tipi kirletici, konsantrasyon ve kullanım sınırına göre seçilir.','Filter type is selected by contaminant, concentration and use limits.'),better:T('Risk/SDS + maske bağlantısı + uygun filtre standardı ve üretici verisini birlikte kontrol et.','Check risk/SDS, mask connection, appropriate filter standard and manufacturer data together.')}},
};

export const getPPEExperience=(code:string)=>ppeExperience[code];