import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ppeStandards} from './data';
import {getPPEVisual,pexels} from './visual-data';

type P={params:Promise<{locale:string}>};
type Locale='tr'|'en';

export async function generateMetadata({params}:P):Promise<Metadata>{
 const {locale}=await params; const l:Locale=locale==='tr'?'tr':'en'; const tr=l==='tr'; const canonical=`https://www.sernem.com/${l}/ppe-standards`;
 return {title:tr?'KKD Standartları: EN Standartları ve Kullanım Rehberi | SERNEM':'PPE Standards: EN Standards & Selection Guide | SERNEM',description:tr?'Baret, emniyet kemeri, gözlük, eldiven, maske, kulaklık ve iş ayakkabısı için temel EN/EN ISO KKD standartlarını, kullanım alanlarını ve işaretlemeleri inceleyin.':'Explore key EN/EN ISO PPE standards for helmets, harnesses, eye protection, gloves, respirators, hearing protection and safety footwear.',alternates:{canonical,languages:{tr:'https://www.sernem.com/tr/ppe-standards',en:'https://www.sernem.com/en/ppe-standards','x-default':'https://www.sernem.com/en/ppe-standards'}},openGraph:{title:tr?'KKD Standartları | SERNEM':'PPE Standards | SERNEM',description:tr?'KKD üzerindeki EN/EN ISO kodlarını saha odaklı teknik rehberlerle okuyun.':'Read EN/EN ISO PPE markings with field-focused technical guides.',url:canonical,type:'website',siteName:'SERNEM'}};
}

export default async function Page({params}:P){
 const {locale}=await params;if(!['tr','en'].includes(locale))notFound(); const l=locale as Locale; const tr=l==='tr'; const hero=getPPEVisual('EN 361');
 return <main className='min-h-screen bg-[#eef3f8] pb-20 text-slate-950'>
  <div className='mx-auto max-w-[1380px] px-4 pt-7 md:px-7'>
   <section className='relative overflow-hidden rounded-[30px] border border-slate-800 bg-slate-950 text-white shadow-[0_28px_70px_rgba(15,23,42,.24)]'>
    <img src={pexels(hero.photo,1800)} alt={hero.alt[l]} className='absolute inset-0 h-full w-full object-cover opacity-30'/>
    <div className='absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/94 to-slate-950/55'/>
    <div className='relative grid gap-8 p-7 md:p-11 lg:grid-cols-[1.1fr_.9fr] lg:p-14'>
     <div><div className='inline-flex rounded-full border border-emerald-300/20 bg-emerald-400/10 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-emerald-200'>{tr?'SERNEM KKD Standartları Kütüphanesi':'SERNEM PPE Standards Library'}</div><h1 className='mt-6 max-w-4xl text-4xl font-black tracking-tight md:text-6xl'>{tr?'KKD standartlarını sadece ezberleme — üründe oku.':'Don’t just memorize PPE standards — read them on the product.'}</h1><p className='mt-5 max-w-3xl text-base leading-8 text-slate-300 md:text-lg'>{tr?'Baret, emniyet kemeri, karabina, gözlük, eldiven, maske, işitme koruyucu ve iş ayakkabısındaki EN/EN ISO işaretlerini; sınıf, kullanım, saha kontrolü ve yanlış seçim örnekleriyle tek merkezden inceleyin.':'Explore EN/EN ISO markings on helmets, harnesses, connectors, eyewear, gloves, respirators, hearing protectors and footwear with classes, field checks and wrong-selection examples.'}</p><div className='mt-7 flex flex-wrap gap-2 text-xs font-bold text-slate-300'><span className='rounded-full border border-white/10 bg-white/[.06] px-3 py-2'>10 {tr?'teknik standart rehberi':'technical standard guides'}</span><span className='rounded-full border border-white/10 bg-white/[.06] px-3 py-2'>TR / EN</span><span className='rounded-full border border-white/10 bg-white/[.06] px-3 py-2'>{tr?'Kod çözümleme':'Code decoder'}</span><span className='rounded-full border border-white/10 bg-white/[.06] px-3 py-2'>{tr?'Saha kontrolü':'HSE Field Check'}</span></div></div>
     <div className='grid gap-3 sm:grid-cols-2 lg:self-end'><div className='rounded-2xl border border-white/10 bg-white/[.07] p-5 backdrop-blur'><div className='text-3xl font-black'>10</div><div className='mt-2 text-sm font-bold text-slate-200'>{tr?'Ana KKD standardı':'Core PPE standards'}</div></div><div className='rounded-2xl border border-white/10 bg-white/[.07] p-5 backdrop-blur'><div className='text-3xl font-black'>30s</div><div className='mt-2 text-sm font-bold text-slate-200'>{tr?'Saha kontrol formatı':'Field-check format'}</div></div><div className='rounded-2xl border border-white/10 bg-white/[.07] p-5 backdrop-blur sm:col-span-2'><div className='text-xs font-black uppercase tracking-[.14em] text-cyan-300'>{tr?'Amaç':'Purpose'}</div><p className='mt-2 text-sm leading-6 text-slate-300'>{tr?'“Bu kod ne?” sorusunu; “Bu üründe ne anlama geliyor ve sahada ne kontrol etmeliyim?” cevabına dönüştürmek.':'Turn “What is this code?” into “What does it mean on this product and what should I check in the field?”'}</p></div></div>
    </div>
   </section>

   <section className='mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3'>{ppeStandards.map((s,i)=>{const vis=getPPEVisual(s.code);return <Link key={s.slug} href={`/${l}/ppe-standards/${s.slug}`} className='group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl'><div className='relative h-52 overflow-hidden bg-slate-900'><img src={pexels(vis.photo,900)} alt={vis.alt[l]} className='h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]'/><div className='absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/25 to-transparent'/><div className='absolute left-4 top-4 rounded-lg border border-white/15 bg-slate-950/70 px-3 py-2 font-mono text-sm font-black text-white backdrop-blur'>{s.code}</div><div className='absolute bottom-4 left-4 right-4'><div className='text-[11px] font-black uppercase tracking-[.14em] text-white/65'>0{String(i+1).padStart(2,'0')} · {tr?'TEKNİK KKD REHBERİ':'TECHNICAL PPE GUIDE'}</div><h2 className='mt-1 text-xl font-black text-white'>{s.title[l]}</h2></div></div><div className='p-6'><p className='text-sm leading-6 text-slate-600'>{s.purpose[l]}</p><div className='mt-5 flex items-center justify-between gap-4'><span className='text-sm font-black text-blue-700'>{tr?'Standardı incele →':'View standard →'}</span><span className='rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-black text-slate-600'>{tr?'Kod + saha kontrolü':'Code + field check'}</span></div></div></Link>})}</section>

   <section className='mt-6 grid gap-4 lg:grid-cols-[1.1fr_.9fr]'><div className='rounded-2xl border border-slate-200 bg-white p-7 shadow-sm'><div className='text-xs font-black uppercase tracking-[.16em] text-blue-700'>{tr?'NASIL KULLANILIR?':'HOW TO USE THIS LIBRARY'}</div><h2 className='mt-2 text-2xl font-black'>{tr?'Sahada 4 adımda kontrol et':'Check in 4 steps in the field'}</h2><div className='mt-5 grid gap-3 sm:grid-cols-2'>{[(tr?'1 · Ürün tipini doğrula':'1 · Verify product type'),(tr?'2 · EN/EN ISO kodunu oku':'2 · Read the EN/EN ISO code'),(tr?'3 · Sınıf ve ek işaretleri çöz':'3 · Decode class and additional marks'),(tr?'4 · Risk + üretici verisiyle eşleştir':'4 · Match against risk + manufacturer data')].map(x=><div key={x} className='rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-bold text-slate-700'>{x}</div>)}</div></div><div className='rounded-2xl bg-slate-950 p-7 text-white shadow-xl'><div className='text-xs font-black uppercase tracking-[.16em] text-amber-300'>{tr?'ÖNEMLİ':'IMPORTANT'}</div><h2 className='mt-2 text-2xl font-black'>{tr?'Standart kodu tek başına satın alma kararı değildir.':'A standards code is not a procurement decision by itself.'}</h2><p className='mt-4 text-sm leading-7 text-slate-300'>{tr?'Risk değerlendirmesi, performans sınıfı, ürünün gerçek işaretleri, üretici talimatları, diğer KKD’lerle uyumluluk ve kullanım koşulları birlikte doğrulanmalıdır.':'Risk assessment, performance class, actual product markings, manufacturer instructions, PPE compatibility and conditions of use must be verified together.'}</p></div></section>
  </div>
 </main>;
}
