"""SERNEM Manual Handling Toolbox Talk content."""

MANUAL_HANDLING = {'base': 'manual-handling-toolbox-talk',
 'tr': {'title': 'ELLE TAŞIMA TOOLBOX TALK',
        'subtitle': 'Yükleri doğru değerlendirin, güvenli kaldırın ve gereksiz zorlanmayı önleyin.',
        'application_subtitle': 'Kaldırma, taşıma, itme, çekme ve elle konumlandırma işleri öncesinde '
                                'uygulanır.',
        'duration': '5–7 DAKİKA',
        'objective_title': 'AMAÇ',
        'objective': 'Elle taşıma sırasında bel, sırt, omuz, el ve kas-iskelet yaralanmalarını önlemek; '
                     'yükün, çalışma alanının ve kişinin kapasitesinin işe başlamadan önce '
                     'değerlendirilmesini sağlamak.',
        'explanation_title': 'KONU ANLATIMI',
        'explanation': ['Elle taşıma yalnızca ağır yüklerin kaldırılması değildir. Taşıma, indirme, itme, '
                        'çekme, tutma ve tekrarlı hareketler de kas-iskelet sistemini zorlayabilir.',
                        'Yükün ağırlığı kadar şekli, tutma noktaları, dengesizliği, görüşü engellemesi ve '
                        'taşıma mesafesi de değerlendirilmelidir.',
                        'Mümkün olan her durumda forklift, transpalet, vinç, el arabası veya başka bir '
                        'mekanik yardım kullanılmalıdır.',
                        'Yük güvenli şekilde taşınamıyorsa çalışan tek başına kaldırmaya zorlanmamalıdır.'],
        'scenario_title': 'GERÇEKÇİ SAHA SENARYOSU',
        'scenario': ['Bir çalışan, zeminden yaklaşık 30 kilogramlık düzensiz şekilli bir ekipman parçasını '
                     'tek başına kaldırmaya çalışır.',
                     'Yükün uygun tutma noktası yoktur ve taşıma yolu üzerindeki malzemeler çalışanın '
                     'hareketini sınırlar.',
                     'Çalışan yükü kaldırırken belinden ani şekilde dönerek yaralanır.'],
        'remember_title': 'UNUTMAYIN',
        'remember': ['Yükü kaldırmadan önce ağırlığını ve ağırlık merkezini değerlendirin.',
                     'Ayaklarınızı dengeli konumlandırın ve yükü vücudunuza yakın tutun.',
                     'Belden eğilmek yerine dizlerinizi bükün.',
                     'Yük taşırken gövdenizi döndürmeyin; ayaklarınızla yön değiştirin.',
                     'Yardım istemek zayıflık değil, doğru güvenlik davranışıdır.'],
        'hazards_title': 'ANA TEHLİKELER',
        'hazards': ['Bel ve sırt incinmeleri',
                    'Kas zorlanmaları ve burkulmalar',
                    'El ve parmak sıkışmaları',
                    'Yükün düşmesi',
                    'Kayma, takılma ve düşme',
                    'Görüşün engellenmesi',
                    'Tekrarlı hareketlere bağlı zorlanmalar'],
        'controls_title': 'TEMEL KONTROLLER',
        'controls': ['Yükü kaldırmadan önce ağırlığını, boyutunu, şeklini ve tutma noktalarını '
                     'değerlendirin.',
                     'Mekanik kaldırma ve taşıma ekipmanlarını öncelikli olarak kullanın.',
                     'Taşıma yolunu önceden kontrol edin ve engelleri kaldırın.',
                     'Gerekli olduğunda ekip halinde kaldırma yapın ve tek bir kişiyi yönlendirme için '
                     'belirleyin.',
                     'Yükü vücuda yakın tutun ve ani hareketlerden kaçının.',
                     'Uygun eldiven ve iş ayakkabısı kullanın.',
                     'Kapasitenizi aşan veya kontrol edemediğiniz yükleri kaldırmayın.'],
        'supervisor_title': 'SUPERVISOR KONUŞMA METNİ',
        'supervisor_script': ['Bugün elle taşıma sırasında en çok hangi işlerde zorlanıyoruz?',
                              'Sahada kullanabileceğimiz mekanik yardımcı ekipmanlar nelerdir?',
                              'Taşıma yolu üzerinde yük taşımayı zorlaştıran engeller var mı?',
                              'Tek kişiyle yapılmaması gereken işler hangileridir?'],
        'questions_title': 'EKİBE SORULAR',
        'questions': ['Bu yükü tek başınıza güvenli şekilde kaldırabilir misiniz?',
                      'Yükün ağırlık merkezi nerede?',
                      'Taşıma yolu temiz ve güvenli mi?',
                      'Mekanik yardım veya ikinci bir çalışan gerekli mi?',
                      'Yük görüş alanınızı kapatıyor mu?'],
        'verification_title': 'İŞE BAŞLAMADAN ÖNCE DOĞRULAYIN',
        'verification': ['Yük ve taşıma yöntemi değerlendirildi.',
                         'Taşıma yolu temizlendi.',
                         'Gerekli mekanik yardım hazır.',
                         'Ekip halinde kaldırma gerekiyorsa görevler belirlendi.',
                         'Uygun KKD kullanılıyor.'],
        'attendance_title': 'KATILIM VE KAYIT',
        'fields': ['Tarih', 'Saha / Bölge', 'Supervisor', 'Katılımcılar', 'İmza'],
        'table_headers': ['Ad Soyad', 'Görev', 'İmza'],
        'notes_title': 'NOTLAR',
        'footer': 'Bu toolbox genel rehberlik sağlar. Sahaya özgü risk değerlendirmesi, iş yöntemi ve şirket '
                  'prosedürleri uygulanmalıdır.'},
 'en': {'title': 'MANUAL HANDLING TOOLBOX TALK',
        'subtitle': 'Assess loads correctly, lift safely and prevent unnecessary strain.',
        'application_subtitle': 'Use before lifting, carrying, pushing, pulling or manually positioning '
                                'loads.',
        'duration': '5–7 MINUTES',
        'objective_title': 'OBJECTIVE',
        'objective': 'Prevent back, shoulder, hand and musculoskeletal injuries during manual handling by '
                     'assessing the load, work area and individual capacity before starting.',
        'explanation_title': 'TOPIC EXPLANATION',
        'explanation': ['Manual handling includes lifting, lowering, carrying, pushing, pulling, holding and '
                        'repetitive movements.',
                        "The load's shape, grip points, stability, travel distance and effect on visibility "
                        'must be considered, not only its weight.',
                        'Use forklifts, pallet trucks, cranes, trolleys or other mechanical aids whenever '
                        'reasonably practicable.',
                        'Workers must not be pressured to lift a load that cannot be handled safely.'],
        'scenario_title': 'REALISTIC SITE SCENARIO',
        'scenario': ['A worker attempts to lift an irregular 30-kilogram equipment part from the floor '
                     'without assistance.',
                     'The load has poor grip points and materials obstruct the carrying route.',
                     'The worker twists while lifting and suffers a back injury.'],
        'remember_title': 'REMEMBER',
        'remember': ['Assess the load and centre of gravity before lifting.',
                     'Keep a stable stance and hold the load close to your body.',
                     'Bend your knees instead of bending from the waist.',
                     'Turn with your feet instead of twisting your torso.',
                     'Asking for assistance is the correct safety decision.'],
        'hazards_title': 'MAIN HAZARDS',
        'hazards': ['Back and spinal injuries',
                    'Muscle strains and sprains',
                    'Hand and finger trapping',
                    'Dropped loads',
                    'Slips, trips and falls',
                    'Restricted visibility',
                    'Repetitive strain injuries'],
        'controls_title': 'KEY CONTROLS',
        'controls': ["Assess the load's weight, size, shape and grip points.",
                     'Use mechanical lifting and transport equipment wherever possible.',
                     'Inspect and clear the carrying route before starting.',
                     'Use team lifting where required and appoint one person to coordinate.',
                     'Keep the load close to the body and avoid sudden movements.',
                     'Wear suitable gloves and safety footwear.',
                     'Do not lift loads beyond your safe capacity or control.'],
        'supervisor_title': 'SUPERVISOR SCRIPT',
        'supervisor_script': ['Which manual-handling tasks create the most difficulty today?',
                              'What mechanical aids are available in our work area?',
                              'Are there obstacles along the planned carrying route?',
                              'Which tasks must not be completed by one person?'],
        'questions_title': 'QUESTIONS FOR THE TEAM',
        'questions': ['Can you safely control this load alone?',
                      "Where is the load's centre of gravity?",
                      'Is the carrying route clear?',
                      'Is mechanical assistance or a second worker required?',
                      'Does the load restrict your view?'],
        'verification_title': 'VERIFY BEFORE STARTING',
        'verification': ['The load and handling method have been assessed.',
                         'The carrying route is clear.',
                         'Required mechanical aids are available.',
                         'Team-lifting roles are agreed where required.',
                         'Suitable PPE is being used.'],
        'attendance_title': 'ATTENDANCE AND RECORD',
        'fields': ['Date', 'Site / Area', 'Supervisor', 'Participants', 'Signature'],
        'table_headers': ['Name', 'Position', 'Signature'],
        'notes_title': 'NOTES',
        'footer': 'This toolbox provides general guidance. Apply site-specific risk assessments, work '
                  'methods and company procedures.'}}
