export const premiumMasterSlugs = [
  "abrasive-blasting-safety",
  "battery-charging",
  "chemical-safety",
  "compressed-gas-cylinders",
  "confined-space",
  "crane-banksman-safety",
  "crane-outrigger-setup",
  "dropped-object-prevention-zones",
  "dropped-objects",
  "electrical-safety",
  "excavation-safety",
  "extension-leads-cable-management",
  "fire-safety",
  "forklift-safety",
  "gas-testing-atmospheric-monitoring",
  "grinding-cutting-safety",
  "hand-power-tools",
  "heat-stress",
  "high-pressure-water-jetting",
  "hot-work",
  "housekeeping",
  "ladder-safety",
  "lifting-operations",
  "line-breaking-process-opening",
  "loto",
  "man-basket-personnel-lifting",
  "manual-handling",
  "mobile-equipment-safety",
  "noise-hearing-protection",
  "permit-to-work",
  "pinch-points",
  "ppe-safety",
  "pressure-testing",
  "respiratory-protection",
  "rigging-inspection",
  "scaffold-modification-control",
  "simultaneous-operations",
  "spill-response",
  "stored-energy-hydraulic-systems",
  "temporary-work-platforms",
  "vehicle-pedestrian-interface",
  "working-at-height",
  "working-near-open-edges",
  "working-over-water",
] as const;

export const premiumMasterSlugSet = new Set<string>(premiumMasterSlugs);
