import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, FileText, ShieldCheck, Crosshair } from "lucide-react";
import LocalizedFooter from "./LocalizedFooter";
import ProductShowcase from "./ProductShowcase";
import { HomepageMotion, RiskWorkflow } from "./HomepageMotion";
import s from "./homepage.module.css";

export default function CinematicHome({ locale }: { locale: "tr" | "en" }) {
  const tr = locale === "tr";
  const t = (en: string, turkish: string) => tr ? turkish : en;
  const action = (path: string, en: string, turkish: string, primary = false) => <Link href={`/${locale}${path}`} className={primary ? s.primary : s.action}>{t(en, turkish)}<ArrowUpRight size={17} aria-hidden="true" /></Link>;
  return <HomepageMotion><main>
    <section className={s.hero} aria-labelledby="home-title">
      <video className={s.heroVideo} src="/videos/sernem-refinery-hero.mp4" poster="/images/sernem-hero-refinery.png" autoPlay muted loop playsInline controls={false} preload="auto" aria-hidden="true" disablePictureInPicture />
      <div className={s.heroScrim}/>
      <div className={`${s.container} ${s.heroContent}`}>
        <p className={s.eyebrow}><span className={s.signal}/> {t("ENGINEERED FOR THE REAL WORLD", "GERÇEK SAHALAR İÇİN TASARLANDI")}</p>
        <h1 id="home-title">{t("Serious operations.", "Zorlu operasyonlar.")}<br/><em>{t("Stronger safety.", "Güçlü iş güvenliği.")}</em></h1>
        <p className={s.heroLead}>{t("From the first risk assessment to the final report. One working platform for the people responsible for safety.", "İlk risk analizinden son rapora. İş güvenliğinin sorumluluğunu taşıyanlar için tek çalışma platformu.")}</p>
        <div className={s.actions}>{action("/tools", "Explore Tools", "Araçları Keşfet", true)}{action("/tools/quick-risk-assessment", "Build Risk Assessment", "Risk Analizi Oluştur")}</div>
        <div className={s.heroBottom}><div><span className={s.eyebrow}>SERNEM / {t("FIELD OPERATIONS", "SAHA OPERASYONLARI")}</span><p>{t("Plan with clarity. Act with confidence.", "Net planlama. Güvenli uygulama.")}</p></div><div className={s.heroPreview}><span className={s.signal}/><b>HSE Performance</b><span>TRIR / LTIFR / DART</span><ArrowRight size={18}/></div></div>
      </div>
      <span className={s.heroIndex}>01 — 10 / SERNEM</span>
    </section>

    <section className={s.industries} aria-label={t("Industries", "Sektörler")}><div className={s.container}><p className={s.eyebrow}>{t("DIFFERENT ENVIRONMENTS. ONE STANDARD OF CARE.", "FARKLI SAHALAR. AYNI GÜVENLİK YAKLAŞIMI.")}</p><ul>{[t("Refinery & Petrochemical", "Rafineri & Petrokimya"), t("EPC Projects", "EPC Projeleri"), t("Construction", "İnşaat"), t("Heavy Industry", "Ağır Sanayi"), t("Energy", "Enerji")].map((item,i) => <li key={item}><span>0{i+1}</span>{item}</li>)}</ul></div></section>

    <section className={`${s.operations} ${s.section}`} aria-labelledby="operations-title">
      <div className={s.container}><div className={s.sectionHeading} data-reveal><div><p className={s.eyebrow}>01 / {t("OPERATIONAL VISIBILITY", "OPERASYONEL GÖRÜNÜRLÜK")}</p><h2 id="operations-title">{t("The scale is enormous.", "Operasyonlar büyük.")}<br/><em>{t("The detail matters.", "Ayrıntılar önemli.")}</em></h2></div><p>{t("Bring field observations, incident records and monthly HSE data into focus. Turn performance into a clearer management picture.", "Saha gözlemlerini, olay kayıtlarını ve aylık HSE verilerini görünür kılın. Performansı net bir yönetim görünümüne dönüştürün.")}</p></div>
      <div className={s.operationStory}>
        <div className={s.windEnvironment}><video data-src="/videos/sernem-wind-operations.mp4" muted loop playsInline controls={false} preload="none" aria-hidden="true" disablePictureInPicture/><div className={s.windCaption}><span className={s.eyebrow}>{t("LARGE-SCALE OPERATIONS", "BÜYÜK ÖLÇEKLİ OPERASYONLAR")}</span><h3>{t("Every observation. A better perspective.", "Her gözlem. Daha net bir bakış.")}</h3><span>01 / {t("FIELD → DATA", "SAHA → VERİ")}</span></div></div>
        <div className={s.dashboard} data-reveal><div className={s.frameBar}><b>SERNEM <span>/ HSE PERFORMANCE</span></b><span>{t("ILLUSTRATIVE DATA", "ÖRNEK VERİLER")}</span></div><div className={s.dashboardBody}><div className={s.dashboardTitle}><div><p className={s.eyebrow}>{t("PERFORMANCE OVERVIEW", "PERFORMANS GÖRÜNÜMÜ")}</p><h3>{t("Operational picture", "Operasyonel görünüm")}</h3></div><span className={s.tag}>{t("JAN — JUN", "OCA — HAZ")} / 2026</span></div>
          <div className={s.metrics} data-reveal>{[["TRIR","0.42"],["LTIFR","0.21"],[t("Severity Rate", "Şiddet Oranı"),"4.20"],["DART","0.21"]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
          <div className={s.chart} data-reveal><div className={s.chartHeading}><b>{t("Monthly KPI trends", "Aylık KPI eğilimleri")}</b><span><i/> TRIR <i/> LTIFR</span></div><svg viewBox="0 0 600 160" role="img" aria-label={t("Illustrative TRIR and LTIFR trends over six months", "Altı aylık örnek TRIR ve LTIFR eğilimleri")}><path className={s.chartGrid} d="M0 25H600 M0 70H600 M0 115H600 M0 159H600"/><path className={s.trendLine} pathLength="1" d="M0 38L120 55L240 48L360 88L480 101L600 116"/><path className={s.trendSecondary} pathLength="1" d="M0 90L120 81L240 111L360 107L480 128L600 138"/></svg><div className={s.chartMonths}>{(tr ? ["OCA","ŞUB","MAR","NİS","MAY","HAZ"] : ["JAN","FEB","MAR","APR","MAY","JUN"]).map(m => <span key={m}>{m}</span>)}</div></div>
          <div className={s.observations} data-reveal><div><span className={s.eyebrow}>02 / {t("OBSERVATIONS → ACTION", "GÖZLEMLER → AKSİYON")}</span><h4>{t("Follow through on findings.", "Bulguları aksiyona dönüştürün.")}</h4></div><div className={s.finding}><span>OBS-024</span><b>{t("Access route obstruction", "Erişim yolunda engel")}</b><span className={s.status}>{t("Assigned", "Atandı")}</span></div><div className={s.finding}><span>OBS-023</span><b>{t("Barrier reinstated", "Bariyer yeniden kuruldu")}</b><span className={s.closed}><Check size={13}/>{t("Closed", "Kapandı")}</span></div><p className={s.caption}>{t("Responsibility / Target dates / Photo evidence", "Sorumlu / Hedef tarihler / Fotoğraflı kanıt")}</p></div>
          <div className={s.reportStrip} data-reveal><FileText size={26}/><div><span className={s.eyebrow}>03 / {t("MANAGEMENT INSIGHT", "YÖNETİM İÇGÖRÜSÜ")}</span><b>{t("From monthly records to professional reports.", "Aylık kayıtlardan profesyonel raporlara.")}</b></div><span>PDF / EXCEL</span></div>
        </div></div>
      </div><div className={s.operationsLink}>{action("/hse-performance", "Open HSE Performance", "HSE Performance’ı Aç", true)}<span className={s.caption}>{t("Incident management · Monthly data · KPI dashboard · Reports", "Olay yönetimi · Aylık veriler · KPI paneli · Raporlar")}</span></div></div>
    </section>

    <ProductShowcase locale={locale}/>

    <section className={`${s.section} ${s.risk}`} aria-labelledby="risk-title"><div className={s.container}><div className={s.sectionHeading} data-reveal><div><p className={s.eyebrow}>03 / {t("RISK ASSESSMENT", "RİSK ANALİZİ")}</p><h2 id="risk-title">{t("Make the risk visible.", "Riski görünür kılın.")}<br/><em>{t("Make the controls clear.", "Kontrolleri netleştirin.")}</em></h2></div><div><p>{t("A considered workflow, from activity selection to editable HIRARC records. Hazards, controls and residual risk, connected in one assessment.", "Faaliyet seçiminden düzenlenebilir HIRARC kayıtlarına. Tehlikeler, kontroller ve kalan risk tek değerlendirmede.")}</p>{action("/tools/quick-risk-assessment", "Build Risk Assessment", "Risk Analizi Oluştur")}</div></div><RiskWorkflow tr={tr}/></div></section>

    <section className={`${s.section} ${s.inspections}`} aria-labelledby="inspection-title"><div className={`${s.container} ${s.inspectionLayout}`}><div className={s.inspectionCopy} data-reveal><p className={s.eyebrow}>04 / {t("FIELD EXECUTION", "SAHA UYGULAMASI")}</p><h2 id="inspection-title">{t("Good plans need", "İyi planlar,")}<br/><em>{t("field verification.", "sahada doğrulanır.")}</em></h2><p>{t("Take a structured approach to the worksite. Check conditions, record findings and identify corrective actions before the next step.", "Sahada sistematik ilerleyin. Koşulları kontrol edin, bulguları kaydedin ve bir sonraki adımdan önce düzeltici aksiyonları belirleyin.")}</p>{action("/checklists", "Explore Field Checklists", "Saha Kontrol Listeleri") }<div className={s.inspectionTopics}>{t("HOT WORK / LOTO / LIFTING / SCAFFOLDING / CONFINED SPACE", "SICAK ÇALIŞMA / LOTO / KALDIRMA / İSKELE / KAPALI ALAN")}</div></div><div className={s.fieldStack}><div className={s.checklist} data-reveal><div className={s.frameBar}><b>SERNEM / {t("INSPECTION", "DENETİM")}</b><span>{t("PREVIEW", "ÖNİZLEME")}</span></div><div className={s.checklistContent}><span className={s.eyebrow}>WAH / 001</span><h3>{t("Work at height", "Yüksekte çalışma")}</h3><div className={s.completion}><span>{t("Checklist completion", "Kontrol listesi tamamlanma")}</span><b>3 / 4</b></div><div className={s.completionTrack}><span/></div>{[t("Access equipment inspected", "Erişim ekipmanı kontrol edildi"),t("Edge protection in place", "Kenar koruması mevcut"),t("Work area controlled", "Çalışma alanı kontrol altında"),t("Rescue arrangements verified", "Kurtarma düzenlemeleri doğrulandı")].map((item,i) => <div className={s.checkRow} key={item}><span className={i < 3 ? s.check : s.pending}>{i < 3 ? <Check size={14}/> : "—"}</span>{item}<small>{i < 3 ? t("YES", "EVET") : t("OPEN", "AÇIK")}</small></div>)}</div></div><div className={s.fieldNote} data-reveal><Crosshair size={20}/><span className={s.eyebrow}>{t("FINDING / FOLLOW-UP", "BULGU / TAKİP")}</span><h4>{t("Verify before proceeding.", "İlerlemeden önce doğrulayın.")}</h4><p>{t("Record outstanding findings and corrective actions. Premium AI assessment supports a structured review of checklist results.", "Açık bulguları ve düzeltici aksiyonları kaydedin. Premium AI değerlendirmesi, kontrol sonuçlarını yapılandırılmış biçimde incelemeyi destekler.")}</p></div></div></div></section>

    <section className={`${s.section} ${s.documentation}`} aria-labelledby="documents-title"><div className={`${s.container} ${s.documentLayout}`}><div className={s.documentStage} data-reveal><div className={s.backDocument}><span>SERNEM / {t("ATTENDANCE RECORD", "KATILIM KAYDI")}</span><h4>{t("The briefing. Recorded.", "Bilgilendirme. Kayıt altında.")}</h4>{Array.from({length:7},(_,i)=><div key={i}><span>0{i+1}</span><span/><span/></div>)}</div><div className={s.frontDocument}><div className={s.documentBrand}><b>SERNEM</b><span>HSE / TOOLBOX</span></div><p className={s.eyebrow}>{t("PRE-JOB BRIEFING", "İŞ ÖNCESİ BİLGİLENDİRME")}</p><h3>{t("Working at height", "Yüksekte çalışma")}</h3><p>{t("Plan the task. Discuss the hazards. Confirm the controls.", "İşi planlayın. Tehlikeleri konuşun. Kontrolleri doğrulayın.")}</p>{[t("Key hazards", "Temel tehlikeler"),t("Critical controls", "Kritik kontroller"),t("Team discussion", "Ekip görüşmesi")].map((label,i)=><div className={s.documentBlock} key={label}><span>0{i+1}</span><div><h4>{label}</h4><div className={s.printLine}/><div className={s.printLine}/><div className={s.printLine}/></div></div>)}<div className={s.documentFoot}><span>{t("DOCUMENT PREVIEW", "DOKÜMAN ÖNİZLEMESİ")}</span><span>01 / 03</span></div></div></div><div className={s.documentCopy} data-reveal><p className={s.eyebrow}>05 / {t("KNOWLEDGE → DOCUMENTATION", "BİLGİ → DOKÜMANTASYON")}</p><h2 id="documents-title">{t("Field knowledge.", "Saha bilgisi.")}<br/><em>{t("Professionally delivered.", "Profesyonel sunum.")}</em></h2><p>{t("Give the briefing the document it deserves. Practical toolbox topics, clear safety content and attendance records, ready for the crew.", "Saha bilgilendirmesine hak ettiği dokümanı verin. Pratik toolbox konuları, net güvenlik içeriği ve ekip için katılım kayıtları.")}</p>{action("/toolbox", "Explore Toolbox Talks", "Toolbox İçeriklerini İncele")}<div className={s.documentLinks}>{action("/tools/method-statement", "Method Statements", "Method Statement")}{action("/downloads", "Professional Resources", "Profesyonel Kaynaklar")}</div></div></div></section>

    <section className={`${s.section} ${s.intelligence}`} aria-labelledby="ai-title"><div className={s.container}><div className={s.aiIntro} data-reveal><p className={s.eyebrow}>06 / {t("HSE INTELLIGENCE", "HSE ZEKÂSI")}</p><h2 id="ai-title">{t("Better questions.", "Daha iyi sorular.")} <em>{t("Structured answers.", "Yapılandırılmış yanıtlar.")}</em></h2></div><div className={s.aiLayout}><div className={s.aiPrompt} data-reveal><span className={s.eyebrow}>{t("CONTEXT / FIELD QUESTION", "BAĞLAM / SAHA SORUSU")}</span><h3>“{t("What should we review before work at height?", "Yüksekte çalışmadan önce neleri incelemeliyiz?")}”</h3><p>{t("HSE-specific guidance, with risk summaries, critical controls and relevant knowledge sources. Built to support professional judgment.", "Risk özetleri, kritik kontroller ve ilgili bilgi kaynaklarıyla HSE odaklı rehberlik. Profesyonel değerlendirmeyi desteklemek için.")}</p>{action("/ai-assistant", "Ask SERNEM AI", "SERNEM AI’a Sor")}</div><div className={s.aiOutput} data-reveal><div className={s.frameBar}><b>SERNEM AI / {t("STRUCTURED RESULT", "YAPILANDIRILMIŞ SONUÇ")}</b><span>{t("EXAMPLE", "ÖRNEK")}</span></div>{[[t("Risk summary", "Risk özeti"),t("Falls from height · Falling objects · Access conditions", "Yüksekten düşme · Düşen cisimler · Erişim koşulları")],[t("Safety analysis", "Güvenlik analizi"),t("Review the task, work environment and existing protective measures.", "İşi, çalışma ortamını ve mevcut koruyucu önlemleri inceleyin.")],[t("Recommendations", "Öneriler"),t("Verify access, edge protection and rescue arrangements against site conditions.", "Erişimi, kenar korumasını ve kurtarma düzenlemelerini saha koşullarına göre doğrulayın.")]].map(([title,detail],i)=><div className={s.aiResult} key={title}><span>0{i+1}</span><div><h4>{title}</h4><p>{detail}</p></div></div>)}<div className={s.aiSource}><span>{t("KNOWLEDGE SOURCE", "BİLGİ KAYNAĞI")}</span><Link href={`/${locale}/knowledge-base/working-at-height`}>{t("SERNEM / Working at height", "SERNEM / Yüksekte çalışma")}<ArrowUpRight size={14}/></Link></div></div></div></div></section>

    <section className={s.premium} aria-labelledby="premium-title"><div className={s.container} data-reveal><div className={s.premiumTop}><span className={s.eyebrow}>SERNEM / PREMIUM</span><ShieldCheck size={28} strokeWidth={1}/></div><div className={s.premiumLayout}><div><h2 id="premium-title">{t("Raise the standard", "Profesyonel işinizde")}<br/><em>{t("of your everyday work.", "standardı yükseltin.")}</em></h2><p>{t("Professional documents. Advanced resources. HSE intelligence. Give your company’s daily safety work a more considered finish.", "Profesyonel dokümanlar. Gelişmiş kaynaklar. HSE zekâsı. Şirketinizin günlük iş güvenliği çalışmalarına daha güçlü bir sunum kazandırın.")}</p>{action("/upgrade", "Discover SERNEM Premium", "SERNEM Premium’u Keşfet", true)}</div><div className={s.premiumBenefits}>{[t("Professional report & document output", "Profesyonel rapor ve doküman çıktıları"),t("Premium templates & resources", "Premium şablonlar ve kaynaklar"),t("Premium AI assistance", "Premium AI desteği")].map((benefit,i)=><div key={benefit}><span>0{i+1}</span><h3>{benefit}</h3><ArrowUpRight size={18}/></div>)}<span className={s.caption}>{t("Explore the membership and included features.", "Üyeliği ve dahil olan özellikleri inceleyin.")}</span></div></div></div></section>
  </main><div className={s.footer}><div className={`${s.container} ${s.footerWordmark}`} aria-hidden="true">SERNEM<span>®</span></div><LocalizedFooter locale={locale}/></div></HomepageMotion>;
}
