"use client";

import { useState } from "react";
import { Link } from "../../../i18n/navigation";
import {
  Activity,
  BarChart3,
  BookOpen,
  Bot,
  Calculator,
  CheckCircle2,
  ClipboardCheck,
  Download,
  FileText,
  Gauge,
  Grid3X3,
  Images,
  LayoutDashboard,
  Layers3,
  LockKeyhole,
  MessageSquareText,
  ShieldCheck,
  Sparkles,
  X,
} from "lucide-react";

type Props = { locale: "tr" | "en"; onClose: () => void };
type Accent = "blue" | "violet" | "emerald" | "cyan" | "amber";
type Product = {
  id: string;
  number: string;
  titleTr: string;
  titleEn: string;
  subtitleTr: string;
  subtitleEn: string;
  eyebrowTr: string;
  eyebrowEn: string;
  descriptionTr: string;
  descriptionEn: string;
  href: string;
  icon: typeof ShieldCheck;
  status: "LIVE" | "BETA";
  accent: Accent;
  stats: { value: string; labelTr: string; labelEn: string; detailTr: string; detailEn: string }[];
  featuresTr: string[];
  featuresEn: string[];
};

const products: Product[] = [
  { id:"risk", number:"01", titleTr:"Risk Analizi", titleEn:"Risk Assessment", subtitleTr:"HIRARC · Risk Yönetimi", subtitleEn:"HIRARC · Risk Management", eyebrowTr:"RİSK YÖNETİMİ", eyebrowEn:"RISK MANAGEMENT", descriptionTr:"100 faaliyet ve 900 hazır risk ile profesyonel HIRARC değerlendirmeleri oluşturun.", descriptionEn:"Build professional HIRARC assessments using 100 activities and 900 ready risks.", href:"/tools/quick-risk-assessment", icon:ShieldCheck, status:"LIVE", accent:"blue", stats:[s("100","Faaliyet","Activities","Hazır faaliyet kütüphanesi","Ready activity library"),s("900","Hazır Risk","Ready Risks","Yapılandırılmış içerik","Structured content"),s("HIRARC","Metodoloji","Methodology","Risk değerlendirme","Risk assessment"),s("PDF","Çıktı","Export","Profesyonel rapor","Professional report")], featuresTr:["Tehlike tanımlama","Risk değerlendirme","Kontroller ve önlemler","Kalan risk","PDF raporlama"], featuresEn:["Hazard identification","Risk evaluation","Controls and measures","Residual risk","PDF reporting"] },
  { id:"method", number:"02", titleTr:"Method Statement", titleEn:"Method Statement", subtitleTr:"Çalışma Yöntemi · PDF", subtitleEn:"Work Method · PDF", eyebrowTr:"DOKÜMANTASYON", eyebrowEn:"DOCUMENTATION", descriptionTr:"Hazır çalışma yöntemlerini proje bilgilerinizle özelleştirin ve profesyonel Method Statement çıktısı oluşturun.", descriptionEn:"Customize ready work methods with project information and create professional Method Statement outputs.", href:"/tools/method-statement", icon:FileText, status:"LIVE", accent:"violet", stats:[s("20","Hazır Method","Ready Methods","Çalışma yöntemi kütüphanesi","Work method library"),s("PDF","Profesyonel Çıktı","Professional Export","Sahaya hazır doküman","Field-ready document"),s("REV","Revizyon","Revision","Doküman kontrolü","Document control"),s("HSE","Kontroller","Controls","İş güvenliği adımları","Safety controls")], featuresTr:["Hazır çalışma yöntemleri","Proje bilgisi özelleştirme","HSE kontrol adımları","Revizyon yapısı","PDF çıktısı"], featuresEn:["Ready work methods","Project customization","HSE control steps","Revision structure","PDF export"] },
  { id:"simops", number:"03", titleTr:"SIMOPS Planner", titleEn:"SIMOPS Planner", subtitleTr:"Operasyon · Çakışma Kontrolü", subtitleEn:"Operations · Conflict Control", eyebrowTr:"OPERASYON PLANLAMA", eyebrowEn:"OPERATION PLANNING", descriptionTr:"Eş zamanlı operasyonları görün, çalışma çakışmalarını değerlendirin ve kritik faaliyetleri tek ekranda yönetin.", descriptionEn:"Visualize simultaneous operations, assess conflicts and manage critical activities from one screen.", href:"/tools/simops", icon:Layers3, status:"LIVE", accent:"violet", stats:[s("SIMOPS","Planlama","Planning","Eş zamanlı işler","Simultaneous work"),s("LIVE","Çakışmalar","Conflicts","Operasyon görünümü","Operation view"),s("HSE","Kontroller","Controls","Kritik tedbirler","Critical measures"),s("GRID","Görünüm","View","Operasyon matrisi","Operation matrix")], featuresTr:["Eş zamanlı işler","Operasyon çakışmaları","Kritik risk görünümü","Kontrol planlaması","Saha koordinasyonu"], featuresEn:["Simultaneous activities","Operation conflicts","Critical risk overview","Control planning","Field coordination"] },
  { id:"ai", number:"04", titleTr:"SERNEM AI", titleEn:"SERNEM AI", subtitleTr:"HSE Rehberliği · Kaynaklı", subtitleEn:"HSE Guidance · Source-backed", eyebrowTr:"HSE REHBERLİĞİ", eyebrowEn:"HSE GUIDANCE", descriptionTr:"Saha sorularını analiz edin; risk özeti, kritik kontroller, KKD, izinler ve ilgili HSE kaynaklarını tek cevapta görün.", descriptionEn:"Analyze field questions and receive risk summaries, controls, PPE, permits and relevant HSE sources.", href:"/ai-assistant", icon:Bot, status:"BETA", accent:"emerald", stats:[s("AI","HSE Asistan","HSE Assistant","Saha odaklı rehberlik","Field guidance"),s("SRC","Kaynaklı","Sources","İlgili kaynaklar","Relevant sources"),s("PPE","KKD","PPE","KKD değerlendirmesi","PPE guidance"),s("CTRL","Kontroller","Controls","Kritik tedbirler","Critical controls")], featuresTr:["Risk özeti","Kritik kontroller","KKD ve izinler","İlgili kaynaklar","HSE odaklı analiz"], featuresEn:["Risk summary","Critical controls","PPE and permits","Relevant sources","HSE-focused analysis"] },
  { id:"dashboard", number:"05", titleTr:"Dashboard", titleEn:"Dashboard", subtitleTr:"Workspace · Analytics", subtitleEn:"Workspace · Analytics", eyebrowTr:"ÇALIŞMA ALANI", eyebrowEn:"WORKSPACE", descriptionTr:"Analizlerinizi, kayıtlarınızı ve HSE çalışmalarınızı tek merkezden yönetin.", descriptionEn:"Manage assessments, records and HSE activity from one central workspace.", href:"/dashboard", icon:LayoutDashboard, status:"LIVE", accent:"cyan", stats:[s("360°","Workspace","Workspace","Tek çalışma alanı","One workspace"),s("DATA","Aktivite","Activity","Kullanıcı işlemleri","User activity"),s("HSE","Kayıtlar","Records","Çalışmalarınız","Your HSE work"),s("FAST","Erişim","Access","Hızlı navigasyon","Fast navigation")], featuresTr:["Tek çalışma alanı","Kayıtlı çalışmalar","Aktivite görünümü","Hızlı erişim","Kişisel HSE alanı"], featuresEn:["One workspace","Saved work","Activity view","Quick access","Personal HSE area"] },
  { id:"inspection", number:"06", titleTr:"Denetimler", titleEn:"Inspections", subtitleTr:"Saha Kontrolü · Checklist", subtitleEn:"Field Control · Checklists", eyebrowTr:"SAHA KONTROLÜ", eyebrowEn:"FIELD CONTROL", descriptionTr:"Yapılandırılmış kontrol listeleri ile saha denetimlerini daha hızlı ve tutarlı yürütün.", descriptionEn:"Run field inspections faster and more consistently using structured checklists.", href:"/checklists", icon:ClipboardCheck, status:"LIVE", accent:"emerald", stats:[s("FIELD","Saha","Field","Operasyon kontrolleri","Operational controls"),s("LIST","Checklist","Checklist","Yapılandırılmış kontrol","Structured inspection"),s("75%","İlerleme","Progress","Tamamlama görünümü","Completion view"),s("HSE","Uygunluk","Compliance","Saha doğrulaması","Field verification")], featuresTr:["Hazır kontrol listeleri","Saha doğrulaması","İlerleme takibi","Uygunluk kontrolü","Aksiyon görünümü"], featuresEn:["Ready checklists","Field verification","Progress tracking","Compliance checks","Action view"] },
  { id:"toolbox", number:"07", titleTr:"Toolbox Talk", titleEn:"Toolbox Talk", subtitleTr:"Saha Konuşmaları · TR / EN", subtitleEn:"Field Talks · TR / EN", eyebrowTr:"SAHA KONUŞMALARI", eyebrowEn:"FIELD BRIEFINGS", descriptionTr:"Sahaya hazır Toolbox Talk içerikleriyle günlük ekip bilgilendirmelerini profesyonel yürütün.", descriptionEn:"Run professional daily field briefings with ready-to-use Toolbox Talk content.", href:"/toolbox", icon:MessageSquareText, status:"LIVE", accent:"violet", stats:[s("TBM","Toolbox","Toolbox","Saha konuşmaları","Field briefings"),s("TR/EN","Çift Dil","Bilingual","Türkçe ve İngilizce","Turkish and English"),s("READY","Hazır İçerik","Ready Content","Sahaya hazır format","Field-ready format"),s("PDF","Paylaşım","Sharing","Ücretsiz hesap ile","With free account")], featuresTr:["Sahaya hazır konuşmalar","TR / EN içerik","Konu bazlı yapı","Ücretsiz hesapla PDF","Profesyonel çıktı"], featuresEn:["Field-ready talks","TR / EN content","Topic-based structure","PDF with free account","Professional output"] },
  { id:"posters", number:"08", titleTr:"Poster & Levhalar", titleEn:"Posters & Signs", subtitleTr:"Saha Görselleri · Güvenlik", subtitleEn:"Field Visuals · Safety", eyebrowTr:"GÖRSEL GÜVENLİK", eyebrowEn:"VISUAL SAFETY", descriptionTr:"Profesyonel güvenlik posterleri ve saha levhalarıyla kritik HSE mesajlarını görünür hale getirin.", descriptionEn:"Make critical HSE messages visible with professional safety posters and field signs.", href:"/posters", icon:Images, status:"LIVE", accent:"emerald", stats:[s("POSTER","Görseller","Visuals","Profesyonel posterler","Professional posters"),s("SIGN","Levhalar","Signs","Saha levhaları","Field signs"),s("PRINT","Yazdırılabilir","Printable","Sahaya hazır çıktı","Field-ready output"),s("HSE","Farkındalık","Awareness","Görsel iletişim","Visual communication")], featuresTr:["Profesyonel posterler","Güvenlik levhaları","Yazdırılabilir tasarım","Saha farkındalığı","Görsel iletişim"], featuresEn:["Professional posters","Safety signs","Printable design","Field awareness","Visual communication"] },
  { id:"performance", number:"09", titleTr:"HSE Performance", titleEn:"HSE Performance", subtitleTr:"KPI · Olay · Gözlem", subtitleEn:"KPI · Incidents · Observations", eyebrowTr:"PERFORMANS YÖNETİMİ", eyebrowEn:"PERFORMANCE MANAGEMENT", descriptionTr:"TRIR, LTIFR, olaylar, gözlemler ve aylık KPI verilerini tek görünümde yönetin.", descriptionEn:"Manage TRIR, LTIFR, incidents, observations and monthly KPI data in one view.", href:"/hse-performance", icon:Gauge, status:"LIVE", accent:"cyan", stats:[s("TRIR","KPI","KPI","Olay oranı","Incident rate"),s("LTIFR","KPI","KPI","Kayıp zaman oranı","Lost-time rate"),s("OBS","Gözlem","Observations","Saha takibi","Field tracking"),s("TREND","Trend","Trend","Aylık görünüm","Monthly view")], featuresTr:["TRIR ve LTIFR","Olay yönetimi","Gözlem takibi","Aylık KPI","Trend analizi"], featuresEn:["TRIR and LTIFR","Incident management","Observation tracking","Monthly KPI","Trend analysis"] },
  { id:"downloads", number:"10", titleTr:"İndirme Merkezi", titleEn:"Download Center", subtitleTr:"Doküman · Şablon · Kaynak", subtitleEn:"Documents · Templates · Resources", eyebrowTr:"KAYNAK MERKEZİ", eyebrowEn:"RESOURCE CENTER", descriptionTr:"Poster, levha, şablon ve profesyonel HSE kaynaklarını tek merkezden keşfedin.", descriptionEn:"Discover posters, signs, templates and professional HSE resources from one center.", href:"/downloads", icon:Download, status:"LIVE", accent:"blue", stats:[s("PDF","Doküman","Documents","Hazır çıktılar","Ready outputs"),s("A4/A3","Format","Format","Yazdırılabilir","Printable"),s("TR/EN","Dil","Language","Çift dil","Bilingual"),s("HSE","Kaynak","Resource","Saha kullanımı","Field use")], featuresTr:["Poster ve levhalar","Profesyonel şablonlar","A4 / A3 format","TR / EN kaynak","Tek indirme merkezi"], featuresEn:["Posters and signs","Professional templates","A4 / A3 format","TR / EN resources","One download center"] },
  { id:"knowledge", number:"11", titleTr:"Bilgi Merkezi", titleEn:"Knowledge Base", subtitleTr:"Rehber · Standart · Saha Bilgisi", subtitleEn:"Guides · Standards · Field Knowledge", eyebrowTr:"HSE BİLGİ MERKEZİ", eyebrowEn:"HSE KNOWLEDGE BASE", descriptionTr:"Hot Work, LOTO, kapalı alan, yüksekte çalışma ve diğer HSE konularında yapılandırılmış rehberlere ulaşın.", descriptionEn:"Access structured guidance for Hot Work, LOTO, confined space, work at height and other HSE topics.", href:"/knowledge-base", icon:BookOpen, status:"LIVE", accent:"amber", stats:[s("14+","Konu","Topics","HSE rehberleri","HSE guides"),s("LOTO","Enerji","Energy","Kontrol rehberi","Control guide"),s("PTW","İzin","Permit","Çalışma izni","Permit to work"),s("FIELD","Saha","Field","Pratik bilgi","Practical guidance")], featuresTr:["Konu bazlı rehberler","Kritik kontroller","Standart referansları","Saha uygulaması","İlgili araç bağlantıları"], featuresEn:["Topic-based guides","Critical controls","Standard references","Field application","Related tool links"] },
  { id:"calculators", number:"12", titleTr:"HSE Hesaplayıcıları", titleEn:"HSE Calculators", subtitleTr:"TRIR · LTIFR · Risk Matrix", subtitleEn:"TRIR · LTIFR · Risk Matrix", eyebrowTr:"HSE HESAPLAMA", eyebrowEn:"HSE CALCULATIONS", descriptionTr:"Risk Matrix, TRIR, LTIFR ve Severity Rate hesaplamalarını hızlı ve tutarlı şekilde yapın.", descriptionEn:"Run Risk Matrix, TRIR, LTIFR and Severity Rate calculations quickly and consistently.", href:"/tools", icon:Calculator, status:"LIVE", accent:"blue", stats:[s("TRIR","Oran","Rate","Kaydedilebilir olay","Recordable incidents"),s("LTIFR","Oran","Rate","Kayıp zamanlı olay","Lost-time incidents"),s("SR","Şiddet","Severity","Kayıp gün etkisi","Lost-day impact"),s("5×5","Matris","Matrix","Risk seviyesi","Risk level")], featuresTr:["Risk Matrix","TRIR","LTIFR","Severity Rate","Hızlı saha hesabı"], featuresEn:["Risk Matrix","TRIR","LTIFR","Severity Rate","Fast field calculation"] },
];

function s(value:string,labelTr:string,labelEn:string,detailTr:string,detailEn:string){return{value,labelTr,labelEn,detailTr,detailEn};}

const accentMap = {
  blue:{active:"border-blue-400/60 bg-blue-500/[0.12] shadow-[0_0_0_1px_rgba(59,130,246,.22),0_12px_35px_rgba(37,99,235,.18)]",icon:"border-blue-400/25 bg-blue-500/10 text-blue-300",glow:"bg-blue-500/20",text:"text-blue-300",dot:"bg-blue-400"},
  violet:{active:"border-violet-400/50 bg-violet-500/[0.10]",icon:"border-violet-400/25 bg-violet-500/10 text-violet-300",glow:"bg-violet-500/20",text:"text-violet-300",dot:"bg-violet-400"},
  emerald:{active:"border-emerald-400/45 bg-emerald-500/[0.08]",icon:"border-emerald-400/25 bg-emerald-500/10 text-emerald-300",glow:"bg-emerald-500/20",text:"text-emerald-300",dot:"bg-emerald-400"},
  cyan:{active:"border-cyan-400/45 bg-cyan-500/[0.08]",icon:"border-cyan-400/25 bg-cyan-500/10 text-cyan-300",glow:"bg-cyan-500/20",text:"text-cyan-300",dot:"bg-cyan-400"},
  amber:{active:"border-amber-400/45 bg-amber-500/[0.08]",icon:"border-amber-400/25 bg-amber-500/10 text-amber-300",glow:"bg-amber-500/20",text:"text-amber-300",dot:"bg-amber-400"},
};

export default function ProductExplorer({locale,onClose}:Props){
  const tr=locale==="tr"; const [activeId,setActiveId]=useState("risk");
  const active=products.find(p=>p.id===activeId)??products[0]; const styles=accentMap[active.accent];
  return <div id="sernem-navigation" className="fixed inset-0 z-[9999] overflow-y-auto bg-[#020817]/[0.985] shadow-[0_45px_140px_rgba(0,0,0,.72)] backdrop-blur-2xl">
    <div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute left-[10%] top-[-240px] h-[520px] w-[520px] rounded-full bg-blue-600/[0.11] blur-[150px]"/><div className="absolute right-[-100px] top-[30%] h-[420px] w-[420px] rounded-full bg-emerald-500/[0.06] blur-[150px]"/></div>
    <div className="relative mx-auto w-full max-w-[1480px] px-5 pb-8 pt-20 sm:px-7 lg:px-8 lg:pt-20">
      <button type="button" onClick={onClose} aria-label={tr?"Keşfet menüsünü kapat":"Close explorer"} className="absolute right-8 top-5 z-20 flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 bg-white/[0.035] text-slate-500 transition hover:bg-white/[0.07] hover:text-white"><X size={18}/></button>
      <div className="grid gap-5 lg:grid-cols-[360px_1fr]">
        <aside className="flex min-h-0 min-w-0 flex-col">
          <div className="pr-12"><div className="inline-flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.22em] text-emerald-400"><Sparkles size={14}/>SERNEM PRODUCT SUITE</div><h2 className="mt-3 text-[36px] font-black leading-[.98] tracking-[-.045em] text-white"><span className="block">12 {tr?"bağlantılı":"connected"}</span><span className="block bg-gradient-to-r from-emerald-300 via-cyan-300 to-blue-400 bg-clip-text text-transparent">{tr?"HSE modülü":"HSE modules"}</span></h2><p className="mt-4 max-w-sm text-sm font-medium leading-6 text-slate-300">{tr?"Risk yönetiminden saha performansına kadar çalışan modülleri aynı profesyonel ürün deneyiminde keşfedin.":"Explore working HSE modules in one professional product experience, from risk management to field performance."}</p></div>
          <div className="mt-5 max-h-[650px] overflow-y-auto rounded-[22px] border border-white/[0.08] bg-slate-950/40 pr-1">
            {products.map(product=>{const Icon=product.icon;const selected=product.id===activeId;const ps=accentMap[product.accent];return <button key={product.id} type="button" onMouseEnter={()=>setActiveId(product.id)} onFocus={()=>setActiveId(product.id)} onClick={()=>setActiveId(product.id)} className={`group relative flex w-full items-center gap-3 border-b border-white/[0.065] px-4 py-3 text-left transition-all duration-300 last:border-b-0 ${selected?ps.active:"border-transparent bg-transparent hover:bg-white/[0.035]"}`}>{selected&&<div className={`absolute bottom-2 left-0 top-2 w-[2px] rounded-full ${ps.dot}`}/>}<span className={`w-7 shrink-0 text-xs font-black ${selected?ps.text:"text-slate-500"}`}>{product.number}</span><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border ${ps.icon}`}><Icon size={20} strokeWidth={1.8}/></span><span className="min-w-0 flex-1"><span className={`block truncate text-sm font-black ${selected?"text-white":"text-slate-200"}`}>{tr?product.titleTr:product.titleEn}</span><span className="mt-1 block truncate text-[11px] font-medium text-slate-400">{tr?product.subtitleTr:product.subtitleEn}</span></span><span className={`rounded-full border px-2 py-1 text-[8px] font-black tracking-[.12em] ${product.status==="BETA"?"border-cyan-400/20 bg-cyan-400/[.07] text-cyan-300":"border-emerald-400/20 bg-emerald-400/[.07] text-emerald-300"}`}>{product.status}</span></button>})}
          </div>
        </aside>
        <section className="min-w-0">
          <div className="grid grid-cols-2 gap-2.5 xl:grid-cols-4">{active.stats.map((stat,index)=>{const icons=[<Activity key="a" size={22}/>,<ShieldCheck key="b" size={22}/>,<Grid3X3 key="c" size={22}/>,<FileText key="d" size={22}/>];return <div key={`${active.id}-${stat.labelEn}`} className="flex min-h-[92px] items-center gap-3 rounded-2xl border border-white/[0.09] bg-white/[0.028] px-4 py-3"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border ${styles.icon}`}>{icons[index]}</span><div className="min-w-0"><div className="text-xl font-black text-white">{stat.value}</div><div className="text-xs font-bold text-slate-300">{tr?stat.labelTr:stat.labelEn}</div><div className="mt-.5 truncate text-[10px] text-slate-400">{tr?stat.detailTr:stat.detailEn}</div></div></div>})}</div>
          <div className="relative mt-3 overflow-hidden rounded-[25px] border border-blue-400/35 bg-gradient-to-br from-blue-600/[0.11] via-slate-950 to-slate-950 shadow-[0_0_50px_rgba(37,99,235,.12)]"><div className={`pointer-events-none absolute right-[-100px] top-[-160px] h-[420px] w-[420px] rounded-full blur-[130px] ${styles.glow}`}/><div className="relative grid min-h-[500px] lg:grid-cols-[.72fr_1.28fr]"><div className="flex flex-col justify-between border-b border-white/[0.08] p-6 lg:border-b-0 lg:border-r lg:p-8"><div><div className={`inline-flex items-center gap-2 rounded-full border border-white/[0.08] bg-white/[0.035] px-3 py-1.5 text-[9px] font-black tracking-[.17em] ${styles.text}`}><span className={`h-1.5 w-1.5 rounded-full ${styles.dot}`}/>{tr?active.eyebrowTr:active.eyebrowEn}</div><h3 className="mt-5 text-3xl font-black tracking-[-.045em] text-white xl:text-[38px]">{tr?active.titleTr:active.titleEn}</h3><p className="mt-4 max-w-sm text-sm font-medium leading-7 text-slate-300">{tr?active.descriptionTr:active.descriptionEn}</p><div className="mt-5 space-y-2.5">{(tr?active.featuresTr:active.featuresEn).map(feature=><div key={feature} className="flex items-center gap-2.5 text-xs text-slate-300"><CheckCircle2 size={14} className="shrink-0 text-blue-400"/>{feature}</div>)}</div></div><div className="mt-7 flex flex-wrap items-center gap-3"><Link href={active.href} onClick={onClose} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-black text-white transition hover:bg-blue-500">{tr?"Ürünü Aç":"Open Product"}<span>→</span></Link><span className="text-xs font-bold text-slate-400">{tr?"Gerçek ürün önizlemesi":"Real product preview"}</span></div></div><div className="flex items-center justify-center p-5 sm:p-7"><Preview id={active.id} tr={tr}/></div></div></div>
          <div className="mt-3 grid gap-2 rounded-2xl border border-white/[0.08] bg-white/[0.02] p-2 sm:grid-cols-2 xl:grid-cols-4"><Trust icon={<LockKeyhole size={19}/>} title={tr?"Güvenli Çalışma Alanı":"Secure Workspace"}/><Trust icon={<LayoutDashboard size={19}/>} title={tr?"Bağlantılı Modüller":"Connected Modules"}/><Trust icon={<ShieldCheck size={19}/>} title={tr?"HSE Odaklı":"HSE Focused"}/><Trust icon={<BarChart3 size={19}/>} title={tr?"Sürekli Gelişen":"Continuously Growing"}/></div>
        </section>
      </div>
    </div>
  </div>;
}

function Preview({id,tr}:{id:string;tr:boolean}){
  const shell=(title:string,subtitle:string,icon:React.ReactNode,body:React.ReactNode)=><div className="mx-auto w-full max-w-[650px] overflow-hidden rounded-[20px] border border-white/[0.10] bg-[#091225]/95 shadow-[0_30px_70px_rgba(0,0,0,.40)]"><div className="flex items-center justify-between border-b border-white/[0.08] px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-blue-400/20 bg-blue-500/[0.08] text-blue-300">{icon}</span><div><div className="text-sm font-black text-white">{title}</div><div className="mt-.5 text-[10px] text-slate-500">{subtitle}</div></div></div><span className="rounded-full border border-emerald-400/20 bg-emerald-400/[.07] px-2.5 py-1 text-[8px] font-black tracking-[.12em] text-emerald-300">LIVE</span></div><div className="p-5">{body}</div></div>;
  if(id==="risk") return shell(tr?"Risk Değerlendirmesi":"Risk Assessment","HIRARC · Work at Height",<ShieldCheck size={18}/>,<><div className="grid gap-2 sm:grid-cols-2"><Data label={tr?"Faaliyet":"Activity"} value={tr?"Yüksekte Çalışma":"Working at Height"}/><Data label={tr?"Risk Puanı":"Risk Score"} value="16 · 4 × 4"/></div><div className="mt-3 grid grid-cols-5 gap-1">{Array.from({length:25}).map((_,i)=><div key={i} className={`aspect-square rounded ${i>18?"bg-red-500/80":i>9?"bg-amber-400/75":"bg-emerald-500/65"} ${i===13?"ring-2 ring-white":""}`}/>)}</div></>);
  if(id==="method") return shell("Method Statement",tr?"Profesyonel HSE Dokümanı":"Professional HSE Document",<FileText size={18}/>,<div className="rounded-xl bg-slate-100 p-5 text-slate-950"><div className="flex justify-between"><div><div className="text-[10px] font-black text-emerald-600">SERNEM</div><div className="mt-1 text-xl font-black">METHOD STATEMENT</div></div><div className="text-right text-[9px] font-bold text-slate-500">SRN-MS-001<br/>REV 1.0</div></div><div className="mt-5 grid gap-2">{(tr?["Proje Bilgileri","İşin Kapsamı","Sorumluluklar","Çalışma Sırası","HSE Kontrolleri"]:["Project Information","Scope of Work","Responsibilities","Work Sequence","HSE Controls"]).map((x,i)=><div key={x} className="flex items-center gap-3 rounded-lg border border-slate-200 bg-white p-3"><span className="text-[10px] font-black text-slate-400">0{i+1}</span><span className="text-xs font-bold">{x}</span></div>)}</div></div>);
  if(id==="simops") return shell("SIMOPS Planner",tr?"Eş Zamanlı Operasyonlar":"Simultaneous Operations",<Layers3 size={18}/>,<div className="space-y-2">{(tr?[["Sıcak Çalışma","Alan A","YÜKSEK"],["Kaldırma Operasyonu","Alan A","ORTA"],["İskele Çalışması","Alan B","DÜŞÜK"]]:[["Hot Work","Area A","HIGH"],["Lifting Operation","Area A","MEDIUM"],["Scaffolding","Area B","LOW"]]).map(([a,b,c])=><div key={a} className="grid grid-cols-[1fr_80px_70px] rounded-xl border border-white/[0.07] bg-slate-950/55 px-4 py-3 text-xs"><b>{a}</b><span className="text-slate-500">{b}</span><span className="text-right text-amber-300">{c}</span></div>)}</div>);
  if(id==="ai") return shell("SERNEM AI",tr?"HSE Bilgi Asistanı":"HSE Knowledge Assistant",<Bot size={18}/>,<><div className="rounded-xl border border-white/[0.07] bg-slate-950/70 p-4 text-sm font-bold">{tr?"Kapalı alana giriş öncesinde hangi kontroller yapılmalıdır?":"What controls are required before confined space entry?"}</div><div className="mt-3 grid grid-cols-2 gap-2">{(tr?["Risk Özeti","Kritik Kontroller","KKD ve İzinler","İlgili Kaynaklar"]:["Risk Summary","Critical Controls","PPE & Permits","Related Sources"]).map(x=><div key={x} className="rounded-xl border border-emerald-400/15 bg-emerald-500/[.05] px-4 py-3 text-xs"><span className="mr-2 text-emerald-400">✓</span>{x}</div>)}</div></>);
  if(id==="inspection") return shell(tr?"Saha Denetimi":"Field Inspection",tr?"Yapılandırılmış HSE Kontrol Listesi":"Structured HSE Checklist",<ClipboardCheck size={18}/>,<div className="space-y-2">{(tr?["Erişim & Bariyerler","KKD Uygunluğu","Düzen & Temizlik","İzin Doğrulaması"]:["Access & Barricades","PPE Compliance","Housekeeping","Permit Verification"]).map((x,i)=><div key={x} className="flex justify-between rounded-xl border border-white/[0.07] bg-slate-950/55 px-4 py-3 text-xs"><b>{x}</b><span className={i===3?"text-amber-400":"text-emerald-400"}>{i===3?"!":"✓"}</span></div>)}</div>);
  if(id==="toolbox") return shell("Toolbox Talk",tr?"Sahaya Hazır Ekip Konuşması":"Field-Ready Team Briefing",<MessageSquareText size={18}/>,<div className="rounded-xl bg-slate-100 p-5 text-slate-950"><div className="flex justify-between"><b>{tr?"YÜKSEKTE ÇALIŞMA":"WORKING AT HEIGHT"}</b><span className="text-[10px] font-black text-amber-700">PDF</span></div><ul className="mt-4 space-y-2 text-[11px]"><li>• {tr?"Çalışmadan önce riskleri belirleyin.":"Identify risks before starting."}</li><li>• {tr?"Doğru KKD kullanın.":"Use the correct PPE."}</li><li>• {tr?"Onaylı erişim ekipmanı kullanın.":"Use approved access equipment."}</li></ul></div>);
  if(id==="posters") return shell(tr?"Poster & Levhalar":"Posters & Signs",tr?"Profesyonel Saha Görselleri":"Professional Field Visuals",<Images size={18}/>,<div className="grid grid-cols-3 gap-3">{[["⚠","WAH"],["⛑","PPE"],["🔥","HOT"],["◉","CS"],["↑","LIFT"],["⚡","ELEC"]].map(([a,b])=><div key={b} className="min-h-24 rounded-xl border border-white/[0.08] bg-slate-950 p-4"><div className="text-2xl">{a}</div><div className="mt-3 text-[10px] font-black">SRN · {b}</div></div>)}</div>);
  if(id==="performance"||id==="dashboard") return shell(id==="performance"?"HSE Performance":"SERNEM Dashboard",tr?"KPI ve çalışma alanı":"KPI & Workspace",id==="performance"?<Gauge size={18}/>:<LayoutDashboard size={18}/>,<><div className="grid grid-cols-4 gap-2">{["TRIR","LTIFR","OBS","KPI"].map((x,i)=><div key={x} className="rounded-xl border border-white/[0.07] bg-slate-950/55 p-3"><div className="text-lg font-black">{["0.42","0.18","126","94%"][i]}</div><div className="text-[9px] text-slate-500">{x}</div></div>)}</div><div className="mt-4 flex h-28 items-end gap-2">{[38,52,44,71,59,84,72,94,78,88].map((h,i)=><div key={i} className="flex-1 rounded-t bg-gradient-to-t from-blue-600/40 to-blue-400/80" style={{height:`${h}%`}}/>)}</div></>);
  if(id==="downloads") return shell(tr?"İndirme Merkezi":"Download Center",tr?"Hazır HSE Kaynakları":"Ready HSE Resources",<Download size={18}/>,<div className="space-y-2">{["Toolbox Talk PDF","Safety Poster A4","Method Statement Template","Risk Assessment Guide"].map((x,i)=><div key={x} className="flex items-center justify-between rounded-xl border border-white/[0.07] bg-slate-950/55 px-4 py-3 text-xs"><span>{x}</span><span className="text-blue-300">{i%2?"A4":"PDF"}</span></div>)}</div>);
  if(id==="knowledge") return shell(tr?"Bilgi Merkezi":"Knowledge Base",tr?"HSE Rehberleri":"HSE Guides",<BookOpen size={18}/>,<div className="grid grid-cols-2 gap-2">{["Hot Work","LOTO","Confined Space","Work at Height","PTW","Scaffolding"].map(x=><div key={x} className="rounded-xl border border-white/[0.07] bg-slate-950/55 px-4 py-4 text-xs font-bold">{x}</div>)}</div>);
  return shell(tr?"HSE Hesaplayıcıları":"HSE Calculators",tr?"Hızlı ve güvenilir hesaplama":"Fast, reliable calculations",<Calculator size={18}/>,<div className="grid grid-cols-2 gap-3">{[["TRIR","0.42"],["LTIFR","0.18"],["Severity Rate","12.4"],["Risk Matrix","5×5"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/[0.07] bg-slate-950/55 p-4"><div className="text-[10px] text-slate-500">{a}</div><div className="mt-2 text-2xl font-black">{b}</div></div>)}</div>);
}

function Data({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between rounded-xl border border-white/[0.07] bg-slate-950/55 px-4 py-3"><span className="text-[9px] text-slate-500">{label}</span><span className="text-xs font-black text-white">{value}</span></div>}
function Trust({icon,title}:{icon:React.ReactNode;title:string}){return <div className="flex items-center gap-3 rounded-xl px-4 py-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-blue-400/10 bg-blue-500/[0.05] text-blue-300">{icon}</span><div className="text-xs font-black text-slate-200">{title}</div></div>}
