"""
PILOT — Working at Height Toolbox Talk PDF generator (SERNEM).

Bu betik YALNIZCA `working-at-height` toolbox'ı için yeni, profesyonel,
uluslararası HSE dokümanı tasarımını üretir. Diğer toolbox'lar için ortak
generate-toolbox-talks-v2.py betiği kullanılmaya devam eder; bu dosya ona
DOKUNMAZ ve onu import ETMEZ.

Üretilen dosyalar (public/downloads):
  - working-at-height-toolbox-talk-tr.pdf              (STANDART SERNEM tasarımı)
  - working-at-height-toolbox-talk-en.pdf              (STANDART SERNEM tasarımı)
  - working-at-height-toolbox-talk-tr-branded-base.pdf (LOGOLU varyant tabanı)
  - working-at-height-toolbox-talk-en-branded-base.pdf (LOGOLU varyant tabanı)

STANDART varyant   : SERNEM markası ön planda, profesyonel SERNEM dokümanı.
BRANDED-BASE varyant: Şirket kimliği ön planda. Header'da BÜYÜK SERNEM markası
                      yoktur; üst-sol köşede şirket logosu için rezerve boş alan
                      bırakılır (Next.js route.ts logoyu buraya basar). Footer'da
                      yalnızca küçük ve zarif "Generated by SERNEM" ibaresi kalır.

İçerik teknik kaynaklar (uydurma yok):
  - OSHA 29 CFR 1926 Subpart M — Fall Protection (construction), 6 ft (1.8 m)
  - OSHA 29 CFR 1910 Subpart D — Walking-Working Surfaces (general industry), 4 ft (1.2 m)
  - ISO 45001:2018, Clause 8.1.2 — Hierarchy of Controls
  - IOSH & NEBOSH: yalnızca iyi uygulama rehberliği (standart olarak tanımlanmaz)

Çalıştırma:  (cwd = app/)
  python3 scripts/generate-working-at-height.py
"""

from datetime import date
from pathlib import Path

from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

# --------------------------------------------------------------------------- #
# Çıktı dizini + fontlar (v2 ile aynı DejaVu kaydı — Türkçe karakter desteği)
# --------------------------------------------------------------------------- #
OUT = Path("public/downloads")
OUT.mkdir(parents=True, exist_ok=True)

_regular = Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
_bold = Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf")

if _regular.exists() and _bold.exists():
    pdfmetrics.registerFont(TTFont("SRN-Regular", str(_regular)))
    pdfmetrics.registerFont(TTFont("SRN-Bold", str(_bold)))
    REGULAR = "SRN-Regular"
    BOLD = "SRN-Bold"
else:  # pragma: no cover - yalnızca font yoksa
    REGULAR = "Helvetica"
    BOLD = "Helvetica-Bold"

# --------------------------------------------------------------------------- #
# Kurumsal palet (SERNEM marka renkleriyle hizalı)
# --------------------------------------------------------------------------- #
NAVY = HexColor("#0B1B33")
NAVY_DEEP = HexColor("#061329")
BLUE = HexColor("#2563EB")
BLUE_DK = HexColor("#1D4ED8")
GREEN = HexColor("#10B981")
RED = HexColor("#DC2626")
AMBER = HexColor("#B45309")
DARK = HexColor("#0F172A")
SLATE = HexColor("#475569")
MUTE = HexColor("#64748B")
LIGHT = HexColor("#F8FAFC")
CARD = HexColor("#FFFFFF")
BORDER = HexColor("#D8DEE9")
PALE_BLUE = HexColor("#EFF6FF")
PALE_GREEN = HexColor("#ECFDF5")
PALE_RED = HexColor("#FEF2F2")
PALE_AMBER = HexColor("#FEF3C7")
PALE_SLATE = HexColor("#F1F5F9")

PAGE_W, PAGE_H = A4
MARGIN = 16 * mm
CONTENT_W = PAGE_W - 2 * MARGIN
HEADER_H = 40 * mm
FOOTER_H = 14 * mm
BOTTOM_LIMIT = FOOTER_H + 8 * mm

# --------------------------------------------------------------------------- #
# Rezerve şirket logosu alanı (BRANDED-BASE) — route.ts ile SENKRON olmalı.
# route.ts working-at-height için logoyu şu kutuya basar:
#   logoX = LOGO_BOX_X, top = PAGE_H - LOGO_BOX_TOP,
#   maxWidth = LOGO_BOX_W, maxHeight = LOGO_BOX_H
# --------------------------------------------------------------------------- #
LOGO_BOX_X = 16 * mm
LOGO_BOX_TOP = 13 * mm      # üstten boşluk (logonun üst kenarı)
LOGO_BOX_W = 54 * mm
LOGO_BOX_H = 20 * mm


# --------------------------------------------------------------------------- #
# Düşük seviyeli çizim yardımcıları
# --------------------------------------------------------------------------- #
def _text(c, s, x, y, size=9, font=REGULAR, color=DARK):
    c.setFillColor(color)
    c.setFont(font, size)
    c.drawString(x, y, s)


def _right(c, s, x, y, size=9, font=REGULAR, color=DARK):
    c.setFillColor(color)
    c.setFont(font, size)
    c.drawRightString(x, y, s)


def _wrap(c, value, width, size=9, font=REGULAR):
    if value is None:
        value = ""
    words = str(value).split()
    lines, cur = [], ""
    for w in words:
        cand = f"{cur} {w}".strip()
        if c.stringWidth(cand, font, size) <= width:
            cur = cand
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def _shield(c, cx, top, w, outer=NAVY_DEEP, inner=BLUE):
    """Küçük SERNEM kalkan amblemi (üst-orta noktası `top`, genişlik `w`)."""
    h = w * 1.02
    x0 = cx - w / 2.0
    y0 = top - h

    def poly(scale):
        sw = w * scale
        sh = h * scale
        ox = cx - sw / 2.0
        oy = top - (h - sh) / 2.0 - sh
        pts = [
            (ox + sw * 0.5, oy + sh * 1.00),
            (ox + sw * 1.00, oy + sh * 0.78),
            (ox + sw * 1.00, oy + sh * 0.36),
            (ox + sw * 0.5, oy + sh * 0.00),
            (ox + sw * 0.00, oy + sh * 0.36),
            (ox + sw * 0.00, oy + sh * 0.78),
        ]
        p = c.beginPath()
        p.moveTo(*pts[0])
        for pt in pts[1:]:
            p.lineTo(*pt)
        p.close()
        return p

    c.setFillColor(outer)
    c.drawPath(poly(1.0), fill=1, stroke=0)
    c.setFillColor(inner)
    c.drawPath(poly(0.80), fill=1, stroke=0)

    # beyaz onay işareti
    c.setStrokeColor(white)
    c.setLineWidth(w * 0.11)
    c.setLineCap(1)
    c.setLineJoin(1)
    p = c.beginPath()
    p.moveTo(x0 + w * 0.30, y0 + h * 0.52)
    p.lineTo(x0 + w * 0.45, y0 + h * 0.38)
    p.lineTo(x0 + w * 0.72, y0 + h * 0.66)
    c.drawPath(p, fill=0, stroke=1)


# --------------------------------------------------------------------------- #
# Header / Footer
# --------------------------------------------------------------------------- #
def _doc_control_block(c, meta, x_right, y_top, on_dark):
    """Sağ üstte doküman kontrol mini-tablosu."""
    label_col = MUTE if not on_dark else HexColor("#93C5FD")
    value_col = DARK if not on_dark else white
    rows = [
        (meta["l_docno"], meta["docno"]),
        (meta["l_rev"], meta["rev"]),
        (meta["l_date"], meta["issue"]),
    ]
    y = y_top
    for label, value in rows:
        _right(c, label, x_right - 40 * mm, y, 7, BOLD, label_col)
        _right(c, value, x_right, y, 7.5, REGULAR, value_col)
        y -= 4.6 * mm


def _header(c, meta, first_page):
    variant = meta["variant"]
    if variant == "standard":
        # Koyu kurumsal bant
        c.setFillColor(NAVY)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, HEADER_H, fill=1, stroke=0)
        # yeşil aksан çizgi
        c.setFillColor(GREEN)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, 1.6 * mm, fill=1, stroke=0)

        _shield(c, MARGIN + 5 * mm, PAGE_H - 8 * mm, 9 * mm)
        wm_x = MARGIN + 12 * mm
        _text(c, "SERNEM", wm_x, PAGE_H - 13.6 * mm, 15, BOLD, white)
        hse_x = wm_x + c.stringWidth("SERNEM", BOLD, 15) + 4
        _text(c, "HSE", hse_x, PAGE_H - 13.6 * mm, 15, BOLD, GREEN)
        _text(c, meta["kicker"], MARGIN + 12 * mm, PAGE_H - 18.8 * mm,
              7.5, BOLD, HexColor("#93C5FD"))

        _text(c, meta["title"], MARGIN, PAGE_H - 29 * mm, 17, BOLD, white)
        _text(c, meta["subtitle"], MARGIN, PAGE_H - 35 * mm, 8.5, REGULAR,
              HexColor("#CBD5E1"))

        _doc_control_block(c, meta, PAGE_W - MARGIN, PAGE_H - 10 * mm,
                           on_dark=True)
    else:
        # BRANDED-BASE: açık header, şirket kimliği ön planda
        c.setFillColor(CARD)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, HEADER_H, fill=1, stroke=0)
        # ince mavi aksan alt çizgi
        c.setFillColor(BLUE)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, 1.4 * mm, fill=1, stroke=0)

        # Rezerve logo alanı (route.ts logoyu buraya basar) — boş bırakılır.
        # Sağ üst: doküman kontrol
        _doc_control_block(c, meta, PAGE_W - MARGIN, PAGE_H - 8 * mm,
                           on_dark=False)

        # Başlık bloğu (logonun altında)
        _text(c, meta["kicker"], MARGIN, PAGE_H - 30.5 * mm, 7.5, BOLD, BLUE)
        _text(c, meta["title"], MARGIN, PAGE_H - 37 * mm, 15, BOLD, NAVY)

    # ipucu: alt içerik başlangıç y'si
    return PAGE_H - HEADER_H - 9 * mm


def _footer(c, meta, page_no):
    y = FOOTER_H
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.6)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)

    if meta["variant"] == "standard":
        _text(c, meta["footer_left"], MARGIN, y - 5.5 * mm, 7, REGULAR, MUTE)
    else:
        # Küçük ve zarif "Generated by SERNEM"
        _text(c, meta["gen_by"], MARGIN, y - 5.5 * mm, 7, REGULAR, MUTE)

    _text(c, f"{meta['docno']} · Rev {meta['rev']}",
          PAGE_W / 2.0 - 26 * mm, y - 5.5 * mm, 7, REGULAR, MUTE)
    _right(c, meta["page_lbl"].format(n=page_no), PAGE_W - MARGIN, y - 5.5 * mm,
           7, BOLD, SLATE)


# --------------------------------------------------------------------------- #
# Sayfa/akış yönetimi
# --------------------------------------------------------------------------- #
class Doc:
    def __init__(self, c, meta):
        self.c = c
        self.meta = meta
        self.page = 1
        self.y = _header(c, meta, True)
        _footer(c, meta, self.page)

    def new_page(self):
        self.c.showPage()
        self.page += 1
        # koyu standart varyantta arka planı beyaz bırak
        self.y = _header(self.c, self.meta, False)
        _footer(self.c, self.meta, self.page)

    def need(self, h):
        if self.y - h < BOTTOM_LIMIT:
            self.new_page()

    def gap(self, h):
        self.y -= h


def _section_title(doc, title, accent, keep=0):
    c = doc.c
    doc.need(12 * mm + keep)
    y = doc.y
    c.setFillColor(accent)
    c.rect(MARGIN, y - 3.4 * mm, 3.2 * mm, 5.2 * mm, fill=1, stroke=0)
    _text(c, title, MARGIN + 6 * mm, y - 2.2 * mm, 11, BOLD, NAVY)
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.6)
    c.line(MARGIN + 6 * mm, y - 6 * mm, PAGE_W - MARGIN, y - 6 * mm)
    doc.y = y - 11 * mm


def _paragraph(doc, textval, size=9.2, color=SLATE, leading=5.0 * mm):
    c = doc.c
    for line in _wrap(c, textval, CONTENT_W, size, REGULAR):
        doc.need(leading + 1 * mm)
        _text(c, line, MARGIN, doc.y, size, REGULAR, color)
        doc.y -= leading


def _bullets(doc, items, marker_color=BLUE):
    c = doc.c
    ind = 6 * mm
    for item in items:
        lines = _wrap(c, item, CONTENT_W - ind, 9, REGULAR)
        block_h = len(lines) * 4.8 * mm + 1.6 * mm
        doc.need(block_h)
        # işaret
        c.setFillColor(marker_color)
        c.circle(MARGIN + 1.4 * mm, doc.y + 1.4 * mm, 1.1 * mm, fill=1, stroke=0)
        first = True
        for line in lines:
            _text(c, line, MARGIN + ind, doc.y, 9, REGULAR, DARK if first else SLATE)
            doc.y -= 4.8 * mm
            first = False
        doc.y -= 1.6 * mm


def _tiers(doc, tiers):
    """Kontrol hiyerarşisi — 4 kademeli renkli kartlar."""
    c = doc.c
    colors = [
        (GREEN, PALE_GREEN),
        (BLUE, PALE_BLUE),
        (BLUE_DK, PALE_BLUE),
        (SLATE, PALE_SLATE),
    ]
    for idx, tier in enumerate(tiers):
        accent, fill = colors[idx % len(colors)]
        head = f"{idx + 1}. {tier['name']}"
        body_lines = _wrap(c, tier["text"], CONTENT_W - 12 * mm, 8.8, REGULAR)
        card_h = 8 * mm + len(body_lines) * 4.5 * mm + 3 * mm
        doc.need(card_h + 2 * mm)
        y = doc.y
        c.setFillColor(fill)
        c.roundRect(MARGIN, y - card_h, CONTENT_W, card_h, 2.2 * mm,
                    fill=1, stroke=0)
        c.setFillColor(accent)
        c.roundRect(MARGIN, y - card_h, 2.6 * mm, card_h, 1.2 * mm,
                    fill=1, stroke=0)
        _text(c, head, MARGIN + 6 * mm, y - 6 * mm, 9.6, BOLD, NAVY)
        ty = y - 11 * mm
        for line in body_lines:
            _text(c, line, MARGIN + 6 * mm, ty, 8.8, REGULAR, SLATE)
            ty -= 4.5 * mm
        doc.y = y - card_h - 3 * mm


def _warning(doc, title, body):
    c = doc.c
    lines = _wrap(c, body, CONTENT_W - 20 * mm, 9.4, BOLD)
    box_h = 12 * mm + len(lines) * 5 * mm
    doc.need(box_h + 2 * mm)
    y = doc.y
    c.setFillColor(PALE_RED)
    c.roundRect(MARGIN, y - box_h, CONTENT_W, box_h, 2.4 * mm, fill=1, stroke=0)
    c.setFillColor(RED)
    c.roundRect(MARGIN, y - box_h, 3 * mm, box_h, 1.4 * mm, fill=1, stroke=0)
    # uyarı üçgeni
    c.setFillColor(RED)
    tx, tyt = MARGIN + 10 * mm, y - 8.4 * mm
    p = c.beginPath()
    p.moveTo(tx, tyt)
    p.lineTo(tx - 3.2 * mm, tyt - 5.4 * mm)
    p.lineTo(tx + 3.2 * mm, tyt - 5.4 * mm)
    p.close()
    c.drawPath(p, fill=1, stroke=0)
    c.setFillColor(white)
    c.setFont(BOLD, 8)
    c.drawCentredString(tx, tyt - 4.6 * mm, "!")
    _text(c, title, MARGIN + 16 * mm, y - 7.4 * mm, 10, BOLD, RED)
    ty = y - 14 * mm
    for line in lines:
        _text(c, line, MARGIN + 16 * mm, ty, 9.4, BOLD, HexColor("#7F1D1D"))
        ty -= 5 * mm
    doc.y = y - box_h - 3 * mm


def _checklist(doc, items):
    """İki sütunlu onay kutucuklu saha checklist'i."""
    c = doc.c
    col_w = (CONTENT_W - 8 * mm) / 2.0
    col_x = [MARGIN, MARGIN + col_w + 8 * mm]
    # her satır tek satıra sığacak şekilde tasarlandı
    row_h = 8.6 * mm
    rows = (len(items) + 1) // 2
    block_h = rows * row_h + 3 * mm
    doc.need(block_h)
    for i, item in enumerate(items):
        col = i % 2
        row = i // 2
        x = col_x[col]
        y = doc.y - row * row_h
        c.setStrokeColor(BLUE)
        c.setLineWidth(1.0)
        c.rect(x, y - 3.6 * mm, 3.6 * mm, 3.6 * mm, fill=0, stroke=1)
        for line in _wrap(c, item, col_w - 7 * mm, 8.6, REGULAR)[:1]:
            _text(c, line, x + 6 * mm, y - 3.2 * mm, 8.6, REGULAR, DARK)
    doc.y -= block_h


def _standards(doc, items):
    c = doc.c
    lines = [_wrap(c, it, CONTENT_W - 12 * mm, 8.2, REGULAR) for it in items]
    n = sum(len(l) for l in lines)
    box_h = 6 * mm + n * 4.3 * mm + 4 * mm
    doc.need(box_h + 2 * mm)
    y = doc.y
    c.setFillColor(PALE_SLATE)
    c.roundRect(MARGIN, y - box_h, CONTENT_W, box_h, 2.2 * mm, fill=1, stroke=0)
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.6)
    c.roundRect(MARGIN, y - box_h, CONTENT_W, box_h, 2.2 * mm, fill=0, stroke=1)
    ty = y - 7 * mm
    for group in lines:
        c.setFillColor(BLUE)
        c.circle(MARGIN + 7 * mm, ty + 1.3 * mm, 0.9 * mm, fill=1, stroke=0)
        first = True
        for line in group:
            _text(c, line, MARGIN + 10 * mm, ty, 8.2, REGULAR,
                  DARK if first else MUTE)
            ty -= 4.3 * mm
            first = False
    doc.y = y - box_h - 3 * mm


def _attendance(doc, meta):
    c = doc.c
    fields = meta["att_fields"]
    headers = meta["att_headers"]
    rows = 12
    row_h = 8.4 * mm
    # üst bilgi alanı (2x2) + tablo başlığı + satırlar
    info_h = 16 * mm
    table_h = 8 * mm + rows * row_h
    total = info_h + table_h + 4 * mm
    doc.need(total)
    y = doc.y

    # bilgi alanı kutucukları
    fw = (CONTENT_W - 6 * mm) / 2.0
    positions = [
        (MARGIN, y - 6 * mm),
        (MARGIN + fw + 6 * mm, y - 6 * mm),
        (MARGIN, y - 14 * mm),
        (MARGIN + fw + 6 * mm, y - 14 * mm),
    ]
    for (label, (fx, fy)) in zip(fields, positions):
        _text(c, label + ":", fx, fy, 8, BOLD, SLATE)
        c.setStrokeColor(BORDER)
        c.setLineWidth(0.6)
        lx = fx + c.stringWidth(label + ": ", BOLD, 8) + 2 * mm
        c.line(lx, fy - 0.6 * mm, fx + fw, fy - 0.6 * mm)
    y -= info_h

    # tablo başlığı
    col_w = [12 * mm, 62 * mm, CONTENT_W - 12 * mm - 62 * mm - 36 * mm, 36 * mm]
    xs = [MARGIN]
    for w in col_w:
        xs.append(xs[-1] + w)
    c.setFillColor(NAVY)
    c.rect(MARGIN, y - 8 * mm, CONTENT_W, 8 * mm, fill=1, stroke=0)
    for i, htext in enumerate(headers):
        _text(c, htext, xs[i] + 2.5 * mm, y - 5.4 * mm, 8, BOLD, white)
    ry = y - 8 * mm
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.6)
    for r in range(rows):
        top = ry - r * row_h
        if r % 2 == 1:
            c.setFillColor(PALE_SLATE)
            c.rect(MARGIN, top - row_h, CONTENT_W, row_h, fill=1, stroke=0)
        c.setStrokeColor(BORDER)
        c.rect(MARGIN, top - row_h, CONTENT_W, row_h, fill=0, stroke=1)
        for xi in xs[1:-1]:
            c.line(xi, top - row_h, xi, top)
        _text(c, str(r + 1), xs[0] + 4 * mm, top - 5.4 * mm, 8, REGULAR, SLATE)
    doc.y = ry - rows * row_h - 4 * mm


# --------------------------------------------------------------------------- #
# İçerik (TR / EN) — teknik, doğrulanmış referanslarla
# --------------------------------------------------------------------------- #
def content(lang):
    today = date.today().strftime("%d.%m.%Y")
    if lang == "tr":
        return {
            "lang": "tr",
            "kicker": "HSE TOOLBOX TALK",
            "title": "YÜKSEKTE ÇALIŞMA",
            "subtitle": "Düşmeleri, düşen cisimleri ve ölümcül yaralanmaları önleyin.",
            "docno": "SRN-TBT-WAH-001",
            "rev": "00",
            "issue": today,
            "l_docno": "DOKÜMAN NO",
            "l_rev": "REVİZYON",
            "l_date": "YAYIN TARİHİ",
            "page_lbl": "Sayfa {n}",
            "footer_left": "SERNEM HSE · Yüksekte Çalışma Toolbox Talk",
            "gen_by": "Generated by SERNEM",
            "s_purpose": "AMAÇ VE KAPSAM",
            "purpose": (
                "Bu Toolbox Talk, yüksekte çalışma faaliyetlerinde düşme, düşen "
                "cisim ve ölümcül yaralanma risklerini azaltmayı amaçlar. Kapsam; "
                "platform, iskele, merdiven, çatı, zemin açıklıkları ve ekipman "
                "üstü gibi bir kişinin seviye farkından düşerek yaralanabileceği "
                "tüm çalışmaları içerir. Kontroller, ISO 45001:2018 kontrol "
                "hiyerarşisi yaklaşımıyla; işe başlamadan önce çalışma izni, risk "
                "değerlendirmesi ve saha doğrulaması ile birlikte uygulanır."
            ),
            "s_hazards": "BAŞLICA TEHLİKELER",
            "hazards": [
                "Korumasız kenar, açıklık ve platformlardan düşme.",
                "Kırılgan yüzeyler ve çatılardan geçme veya düşme.",
                "Merdiven, iskele ve erişim ekipmanının hatalı kullanımı.",
                "Alet, ekipman ve malzemelerin alt seviyelere düşmesi.",
                "MEWP (yükseltici platform) devrilmesi, sıkışma veya sepetten fırlama.",
                "Olumsuz hava (rüzgâr, buz), kaygan yüzey ve yetersiz aydınlatma.",
                "Uygun olmayan veya yetersiz dayanımlı ankraj noktaları.",
                "Düşüş sonrası askıda kalma (suspension trauma) ve yetersiz kurtarma.",
            ],
            "s_controls": "KRİTİK KONTROL ÖNLEMLERİ (KONTROL HİYERARŞİSİ)",
            "tiers": [
                {
                    "name": "KAÇININ (Elimination)",
                    "text": (
                        "Mümkün olduğunda yüksekte çalışmaktan kaçının. İşi zeminde "
                        "hazırlayın, ön montaj yapın veya uzatmalı/yerden kumandalı "
                        "ekipman kullanın."
                    ),
                },
                {
                    "name": "DÜŞMEYİ ÖNLEYİN (Kollektif koruma)",
                    "text": (
                        "Korkuluk, çalışma platformu, kapak ve bariyerleri öncelikle "
                        "kullanın; doğru kurulmuş iskele veya MEWP tercih edin. Korkuluk "
                        "sistemleri uygun yükseklik ve dayanımda olmalıdır "
                        "(OSHA: üst korkuluk ~1,07 m / 42 inch)."
                    ),
                },
                {
                    "name": "SONUCU AZALTIN (Düşüş durdurma)",
                    "text": (
                        "Kollektif koruma uygulanamıyorsa güvenlik ağı ya da kişisel "
                        "düşme durdurma sistemi kullanın: tam vücut emniyet kemeri ve "
                        "onaylı ankraj (çalışan başına ≥ 5.000 lb / ~22 kN). Yeterli "
                        "düşüş açıklığını ve salınım düşüşü riskini doğrulayın."
                    ),
                },
                {
                    "name": "YÖNETSEL ve KKD (Son çare)",
                    "text": (
                        "Çalışma izni, yetkin kişi (competent person) gözetimi, ekipman "
                        "muayenesi, uygulanabilir kurtarma planı ve eğitim ile destekleyin. "
                        "KKD tek başına yeterli koruma değildir."
                    ),
                },
            ],
            "warn_title": "ÖNEMLİ UYARI",
            "warn": (
                "Denetlenmemiş veya uygun olmayan düşme koruması ile ASLA yüksekte "
                "çalışmayın. İnşaat işlerinde 1,8 m (6 ft), genel sanayide 1,2 m "
                "(4 ft) ve üzeri düşme mesafelerinde koruma zorunludur. Düşük "
                "yükseklikten düşüşler bile ölümcül olabilir."
            ),
            "s_checklist": "SAHA CHECKLIST'İ (İŞE BAŞLAMADAN ÖNCE)",
            "checklist": [
                "Çalışma izni ve risk değerlendirmesi onaylı",
                "Güvenli erişim ve korkuluklar tamam",
                "İskele / platform muayene edildi (etiketli)",
                "Ankraj noktaları belirlendi ve dayanımı doğrulandı",
                "Emniyet kemeri ve lanyard muayene edildi",
                "Alt bölge bariyerlendi, aletler bağlandı",
                "Hava, yüzey ve aydınlatma koşulları uygun",
                "Kurtarma planı ve ekipmanı hazır",
                "Personel yetkin ve bilgilendirildi",
            ],
            "s_standards": "STANDARTLAR VE REFERANSLAR",
            "standards": [
                "OSHA 29 CFR 1926 Subpart M — Fall Protection (inşaat); 1,8 m (6 ft) eşik.",
                "OSHA 29 CFR 1910 Subpart D — Walking-Working Surfaces (genel sanayi); 1,2 m (4 ft) eşik.",
                "ISO 45001:2018, Madde 8.1.2 — Kontrol Hiyerarşisi (Elemine et → İkame → Mühendislik → Yönetsel → KKD).",
                "IOSH ve NEBOSH iyi uygulama rehberliği ile uyumludur.",
            ],
            "s_attendance": "KATILIM VE ONAY",
            "att_fields": ["Proje / Saha", "Tarih", "Konuşmayı yapan", "Çalışma alanı"],
            "att_headers": ["No", "Ad Soyad", "Firma / Görev", "İmza"],
        }
    return {
        "lang": "en",
        "kicker": "HSE TOOLBOX TALK",
        "title": "WORKING AT HEIGHT",
        "subtitle": "Prevent falls, falling objects and fatal injuries.",
        "docno": "SRN-TBT-WAH-001",
        "rev": "00",
        "issue": today,
        "l_docno": "DOCUMENT NO",
        "l_rev": "REVISION",
        "l_date": "ISSUE DATE",
        "page_lbl": "Page {n}",
        "footer_left": "SERNEM HSE · Working at Height Toolbox Talk",
        "gen_by": "Generated by SERNEM",
        "s_purpose": "PURPOSE AND SCOPE",
        "purpose": (
            "This Toolbox Talk aims to reduce the risk of falls, falling objects "
            "and fatal injuries during work at height. Its scope covers all tasks "
            "where a person could fall from one level to another and be injured — "
            "including platforms, scaffolds, ladders, roofs, floor openings and "
            "equipment surfaces. Controls follow the ISO 45001:2018 hierarchy of "
            "controls and are applied together with a permit to work, a risk "
            "assessment and a pre-task site check before work begins."
        ),
        "s_hazards": "KEY HAZARDS",
        "hazards": [
            "Falls from unprotected edges, openings and working platforms.",
            "Walking on or falling through fragile surfaces and roofs.",
            "Incorrect use of ladders, scaffolds and access equipment.",
            "Tools, equipment and materials dropped to lower levels.",
            "MEWP overturn, entrapment or ejection from the basket.",
            "Adverse weather (wind, ice), slippery surfaces and poor lighting.",
            "Unapproved or inadequately rated anchor points.",
            "Suspension trauma after a fall and inadequate rescue provision.",
        ],
        "s_controls": "CRITICAL CONTROL MEASURES (HIERARCHY OF CONTROLS)",
        "tiers": [
            {
                "name": "AVOID (Elimination)",
                "text": (
                    "Avoid work at height where reasonably practicable. Prepare or "
                    "pre-assemble the work at ground level, or use extendable / "
                    "ground-operated equipment."
                ),
            },
            {
                "name": "PREVENT FALLS (Collective protection)",
                "text": (
                    "Give priority to guardrails, working platforms, covers and "
                    "barriers; use correctly erected scaffolds or a MEWP. Guardrail "
                    "systems must be of adequate height and strength "
                    "(OSHA: top rail ~1.07 m / 42 in)."
                ),
            },
            {
                "name": "MINIMISE CONSEQUENCES (Fall arrest)",
                "text": (
                    "Where collective protection is not practicable, use a safety net "
                    "or a personal fall-arrest system: a full-body harness and an "
                    "approved anchor (\u2265 5,000 lb / ~22 kN per worker). Verify "
                    "adequate fall clearance and swing-fall exposure."
                ),
            },
            {
                "name": "ADMINISTRATIVE & PPE (Last resort)",
                "text": (
                    "Support controls with a permit to work, competent-person "
                    "supervision, equipment inspection, a workable rescue plan and "
                    "training. PPE alone is not adequate protection."
                ),
            },
        ],
        "warn_title": "CRITICAL WARNING",
        "warn": (
            "NEVER work at height without inspected, suitable fall protection. Fall "
            "protection is required at 1.8 m (6 ft) or more in construction and at "
            "1.2 m (4 ft) or more in general industry. Even a fall from a low height "
            "can be fatal."
        ),
        "s_checklist": "SITE CHECKLIST (BEFORE STARTING WORK)",
        "checklist": [
            "Permit to work and risk assessment approved",
            "Safe access and guardrails complete",
            "Scaffold / platform inspected and tagged",
            "Anchor points identified and strength verified",
            "Harness and lanyard inspected",
            "Area below barricaded, tools tethered",
            "Weather, surface and lighting suitable",
            "Rescue plan and equipment ready",
            "Personnel competent and briefed",
        ],
        "s_standards": "STANDARDS AND REFERENCES",
        "standards": [
            "OSHA 29 CFR 1926 Subpart M — Fall Protection (construction); 1.8 m (6 ft) trigger.",
            "OSHA 29 CFR 1910 Subpart D — Walking-Working Surfaces (general industry); 1.2 m (4 ft) trigger.",
            "ISO 45001:2018, Clause 8.1.2 — Hierarchy of Controls (Eliminate \u2192 Substitute \u2192 Engineering \u2192 Administrative \u2192 PPE).",
            "Aligned with IOSH and NEBOSH good-practice guidance.",
        ],
        "s_attendance": "ATTENDANCE AND APPROVAL",
        "att_fields": ["Project / Site", "Date", "Presented by", "Work area"],
        "att_headers": ["No", "Full Name", "Company / Role", "Signature"],
    }


# --------------------------------------------------------------------------- #
# Doküman oluşturma
# --------------------------------------------------------------------------- #
def build(variant, lang, filename):
    meta = content(lang)
    meta["variant"] = variant

    c = canvas.Canvas(str(OUT / filename), pagesize=A4)
    c.setTitle(f"{meta['title']} — Toolbox Talk")

    doc = Doc(c, meta)

    _section_title(doc, meta["s_purpose"], BLUE)
    _paragraph(doc, meta["purpose"])
    doc.gap(2 * mm)

    _section_title(doc, meta["s_hazards"], RED)
    _bullets(doc, meta["hazards"], marker_color=RED)
    doc.gap(1 * mm)

    _section_title(doc, meta["s_controls"], GREEN)
    _tiers(doc, meta["tiers"])
    doc.gap(1 * mm)

    _warning(doc, meta["warn_title"], meta["warn"])
    doc.gap(1 * mm)

    _section_title(doc, meta["s_checklist"], BLUE)
    _checklist(doc, meta["checklist"])
    doc.gap(2 * mm)

    _section_title(doc, meta["s_standards"], SLATE)
    _standards(doc, meta["standards"])
    doc.gap(1 * mm)

    _section_title(doc, meta["s_attendance"], NAVY, keep=78 * mm)
    _attendance(doc, meta)

    c.showPage()
    c.save()
    print(f"  ✓ {filename}")


def main():
    print("Working at Height — Toolbox Talk PDF üretimi")
    build("standard", "tr", "working-at-height-toolbox-talk-tr.pdf")
    build("standard", "en", "working-at-height-toolbox-talk-en.pdf")
    build("branded", "tr", "working-at-height-toolbox-talk-tr-branded-base.pdf")
    build("branded", "en", "working-at-height-toolbox-talk-en-branded-base.pdf")
    print(f"Tamamlandı → {OUT.resolve()}")


if __name__ == "__main__":
    main()
