"""
PILOT — Working at Height Toolbox Talk PDF generator (SERNEM).

Bu betik YALNIZCA `working-at-height` toolbox'ı için yeni, profesyonel,
uluslararası HSE dokümanı tasarımını üretir. Diğer toolbox'lar için ortak
generate-toolbox-talks-v2.py betiği kullanılmaya devam eder; bu dosya ona
DOKUNMAZ ve onu import ETMEZ.

Üretilen dosyalar (public/downloads):
  - working-at-height-toolbox-talk-tr.pdf              (STANDART SERNEM tasarımı)
  - working-at-height-toolbox-talk-en.pdf              (STANDART SERNEM tasarımı)
  - working-at-height-toolbox-talk-tr-branded-base.pdf (LOGOLU varyant tabanı)
  - working-at-height-toolbox-talk-en-branded-base.pdf (LOGOLU varyant tabanı)

STANDART varyant   : SERNEM markası ön planda, profesyonel SERNEM dokümanı.
BRANDED-BASE varyant: Şirket kimliği ön planda. Header'da BÜYÜK SERNEM markası
                      yoktur; üst-sol köşede şirket logosu için rezerve boş alan
                      bırakılır (Next.js route.ts logoyu buraya basar). Footer'da
                      yalnızca küçük ve zarif "Generated by SERNEM" ibaresi kalır.

İçerik teknik kaynaklar (uydurma yok):
  - OSHA 29 CFR 1926 Subpart M — Fall Protection (construction), 6 ft (1.8 m)
  - OSHA 29 CFR 1910 Subpart D — Walking-Working Surfaces (general industry), 4 ft (1.2 m)
  - ISO 45001:2018, Clause 8.1.2 — Hierarchy of Controls
  - IOSH & NEBOSH: yalnızca iyi uygulama rehberliği (standart olarak tanımlanmaz)

Çalıştırma:  (cwd = app/)
  python3 scripts/generate-working-at-height.py
"""

from datetime import date
from pathlib import Path

from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.graphics import renderPDF
try:
    from svglib.svglib import svg2rlg
except ImportError:  # Allows the shared content model to be imported by DOCX tooling.
    svg2rlg = None

# --------------------------------------------------------------------------- #
# Çıktı dizini + fontlar (v2 ile aynı DejaVu kaydı — Türkçe karakter desteği)
# --------------------------------------------------------------------------- #
OUT = Path("public/downloads")
OUT.mkdir(parents=True, exist_ok=True)
ICON_DIR = Path(__file__).resolve().parent / "assets" / "toolbox-icons"
ICON_PNG_DIR = Path(__file__).resolve().parent / "assets" / "toolbox-icons-png"
IMAGE_DIR = Path(__file__).resolve().parent / "assets" / "toolbox-images"
_ICON_CACHE = {}

_regular = Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
_bold = Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf")

if _regular.exists() and _bold.exists():
    pdfmetrics.registerFont(TTFont("SRN-Regular", str(_regular)))
    pdfmetrics.registerFont(TTFont("SRN-Bold", str(_bold)))
    REGULAR = "SRN-Regular"
    BOLD = "SRN-Bold"
else:  # pragma: no cover - yalnızca font yoksa
    REGULAR = "Helvetica"
    BOLD = "Helvetica-Bold"

# --------------------------------------------------------------------------- #
# Kurumsal palet (SERNEM marka renkleriyle hizalı)
# --------------------------------------------------------------------------- #
NAVY = HexColor("#0B1B33")
NAVY_DEEP = HexColor("#061329")
BLUE = HexColor("#2563EB")
BLUE_DK = HexColor("#1D4ED8")
GREEN = HexColor("#10B981")
RED = HexColor("#DC2626")
AMBER = HexColor("#B45309")
DARK = HexColor("#0F172A")
SLATE = HexColor("#475569")
MUTE = HexColor("#64748B")
LIGHT = HexColor("#F8FAFC")
CARD = HexColor("#FFFFFF")
BORDER = HexColor("#D8DEE9")
PALE_BLUE = HexColor("#EFF6FF")
PALE_GREEN = HexColor("#ECFDF5")
PALE_RED = HexColor("#FEF2F2")
PALE_AMBER = HexColor("#FEF3C7")
PALE_SLATE = HexColor("#F1F5F9")
PALE_PURPLE = HexColor("#F5F3FF")
PURPLE = HexColor("#7C3AED")
SAFETY_YELLOW = HexColor("#FACC15")

PAGE_W, PAGE_H = A4
MARGIN = 16 * mm
CONTENT_W = PAGE_W - 2 * MARGIN
HEADER_H = 40 * mm
FOOTER_H = 14 * mm
BOTTOM_LIMIT = FOOTER_H + 8 * mm

# --------------------------------------------------------------------------- #
# Rezerve şirket logosu alanı (BRANDED-BASE) — route.ts ile SENKRON olmalı.
# route.ts working-at-height için logoyu şu kutuya basar:
#   logoX = LOGO_BOX_X, top = PAGE_H - LOGO_BOX_TOP,
#   maxWidth = LOGO_BOX_W, maxHeight = LOGO_BOX_H
# --------------------------------------------------------------------------- #
LOGO_BOX_X = 16 * mm
LOGO_BOX_TOP = 13 * mm      # üstten boşluk (logonun üst kenarı)
LOGO_BOX_W = 54 * mm
LOGO_BOX_H = 20 * mm


# --------------------------------------------------------------------------- #
# Düşük seviyeli çizim yardımcıları
# --------------------------------------------------------------------------- #
def _text(c, s, x, y, size=9, font=REGULAR, color=DARK):
    c.setFillColor(color)
    c.setFont(font, size)
    c.drawString(x, y, s)


def _right(c, s, x, y, size=9, font=REGULAR, color=DARK):
    c.setFillColor(color)
    c.setFont(font, size)
    c.drawRightString(x, y, s)


def _wrap(c, value, width, size=9, font=REGULAR):
    if value is None:
        value = ""
    words = str(value).split()
    lines, cur = [], ""
    for w in words:
        cand = f"{cur} {w}".strip()
        if c.stringWidth(cand, font, size) <= width:
            cur = cand
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def _shield(c, cx, top, w, outer=NAVY_DEEP, inner=BLUE):
    """Küçük SERNEM kalkan amblemi (üst-orta noktası `top`, genişlik `w`)."""
    h = w * 1.02
    x0 = cx - w / 2.0
    y0 = top - h

    def poly(scale):
        sw = w * scale
        sh = h * scale
        ox = cx - sw / 2.0
        oy = top - (h - sh) / 2.0 - sh
        pts = [
            (ox + sw * 0.5, oy + sh * 1.00),
            (ox + sw * 1.00, oy + sh * 0.78),
            (ox + sw * 1.00, oy + sh * 0.36),
            (ox + sw * 0.5, oy + sh * 0.00),
            (ox + sw * 0.00, oy + sh * 0.36),
            (ox + sw * 0.00, oy + sh * 0.78),
        ]
        p = c.beginPath()
        p.moveTo(*pts[0])
        for pt in pts[1:]:
            p.lineTo(*pt)
        p.close()
        return p

    c.setFillColor(outer)
    c.drawPath(poly(1.0), fill=1, stroke=0)
    c.setFillColor(inner)
    c.drawPath(poly(0.80), fill=1, stroke=0)

    # beyaz onay işareti
    c.setStrokeColor(white)
    c.setLineWidth(w * 0.11)
    c.setLineCap(1)
    c.setLineJoin(1)
    p = c.beginPath()
    p.moveTo(x0 + w * 0.30, y0 + h * 0.52)
    p.lineTo(x0 + w * 0.45, y0 + h * 0.38)
    p.lineTo(x0 + w * 0.72, y0 + h * 0.66)
    c.drawPath(p, fill=0, stroke=1)


# --------------------------------------------------------------------------- #
# Header / Footer
# --------------------------------------------------------------------------- #
def _doc_control_block(c, meta, x_right, y_top, on_dark):
    """Sağ üstte doküman kontrol mini-tablosu."""
    label_col = MUTE if not on_dark else HexColor("#93C5FD")
    value_col = DARK if not on_dark else white
    rows = [
        (meta["l_docno"], meta["docno"]),
        (meta["l_rev"], meta["rev"]),
        (meta["l_date"], meta["issue"]),
    ]
    y = y_top
    for label, value in rows:
        _right(c, label, x_right - 40 * mm, y, 7, BOLD, label_col)
        _right(c, value, x_right, y, 7.5, REGULAR, value_col)
        y -= 4.6 * mm


def _header(c, meta, first_page):
    variant = meta["variant"]
    if variant == "standard":
        # Koyu kurumsal bant
        c.setFillColor(NAVY)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, HEADER_H, fill=1, stroke=0)
        # yeşil aksан çizgi
        c.setFillColor(GREEN)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, 1.6 * mm, fill=1, stroke=0)

        _shield(c, MARGIN + 5 * mm, PAGE_H - 8 * mm, 9 * mm)
        wm_x = MARGIN + 12 * mm
        _text(c, "SERNEM", wm_x, PAGE_H - 13.6 * mm, 15, BOLD, white)
        hse_x = wm_x + c.stringWidth("SERNEM", BOLD, 15) + 4
        _text(c, "HSE", hse_x, PAGE_H - 13.6 * mm, 15, BOLD, GREEN)
        _text(c, meta["kicker"], MARGIN + 12 * mm, PAGE_H - 18.8 * mm,
              7.5, BOLD, HexColor("#93C5FD"))

        _text(c, meta["title"], MARGIN, PAGE_H - 29 * mm, 17, BOLD, white)
        _text(c, meta["subtitle"], MARGIN, PAGE_H - 35 * mm, 8.5, REGULAR,
              HexColor("#CBD5E1"))

        _doc_control_block(c, meta, PAGE_W - MARGIN, PAGE_H - 10 * mm,
                           on_dark=True)
    else:
        # BRANDED-BASE: açık header, şirket kimliği ön planda
        c.setFillColor(CARD)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, HEADER_H, fill=1, stroke=0)
        # ince mavi aksan alt çizgi
        c.setFillColor(BLUE)
        c.rect(0, PAGE_H - HEADER_H, PAGE_W, 1.4 * mm, fill=1, stroke=0)

        # Rezerve logo alanı (route.ts logoyu buraya basar) — boş bırakılır.
        # Sağ üst: doküman kontrol
        _doc_control_block(c, meta, PAGE_W - MARGIN, PAGE_H - 8 * mm,
                           on_dark=False)

        # Başlık bloğu (logonun altında)
        _text(c, meta["kicker"], MARGIN, PAGE_H - 30.5 * mm, 7.5, BOLD, BLUE)
        _text(c, meta["title"], MARGIN, PAGE_H - 37 * mm, 15, BOLD, NAVY)

    # ipucu: alt içerik başlangıç y'si
    return PAGE_H - HEADER_H - 9 * mm


def _footer(c, meta, page_no):
    y = FOOTER_H
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.6)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)

    if meta["variant"] == "standard":
        _text(c, meta["footer_left"], MARGIN, y - 5.5 * mm, 7, REGULAR, MUTE)
    else:
        # Küçük ve zarif "Generated by SERNEM"
        _text(c, meta["gen_by"], MARGIN, y - 5.5 * mm, 7, REGULAR, MUTE)

    _text(c, f"{meta['docno']} · Rev {meta['rev']}",
          PAGE_W / 2.0 - 26 * mm, y - 5.5 * mm, 7, REGULAR, MUTE)
    _right(c, meta["page_lbl"].format(n=page_no), PAGE_W - MARGIN, y - 5.5 * mm,
           7, BOLD, SLATE)


# --------------------------------------------------------------------------- #
# Sayfa/akış yönetimi
# --------------------------------------------------------------------------- #
class Doc:
    def __init__(self, c, meta):
        self.c = c
        self.meta = meta
        self.page = 1
        self.y = _header(c, meta, True)
        _footer(c, meta, self.page)

    def new_page(self):
        self.c.showPage()
        self.page += 1
        # koyu standart varyantta arka planı beyaz bırak
        self.y = _header(self.c, self.meta, False)
        _footer(self.c, self.meta, self.page)

    def need(self, h):
        if self.y - h < BOTTOM_LIMIT:
            self.new_page()

    def gap(self, h):
        self.y -= h


def _section_title(doc, title, accent, keep=0):
    c = doc.c
    doc.need(12 * mm + keep)
    y = doc.y
    c.setFillColor(accent)
    c.rect(MARGIN, y - 3.4 * mm, 3.2 * mm, 5.2 * mm, fill=1, stroke=0)
    _text(c, title, MARGIN + 6 * mm, y - 2.2 * mm, 11, BOLD, NAVY)
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.6)
    c.line(MARGIN + 6 * mm, y - 6 * mm, PAGE_W - MARGIN, y - 6 * mm)
    doc.y = y - 11 * mm


def _paragraph(doc, textval, size=9.2, color=SLATE, leading=5.0 * mm):
    c = doc.c
    for line in _wrap(c, textval, CONTENT_W, size, REGULAR):
        doc.need(leading + 1 * mm)
        _text(c, line, MARGIN, doc.y, size, REGULAR, color)
        doc.y -= leading


def _bullets(doc, items, marker_color=BLUE):
    c = doc.c
    ind = 6 * mm
    for item in items:
        lines = _wrap(c, item, CONTENT_W - ind, 9, REGULAR)
        block_h = len(lines) * 4.8 * mm + 1.6 * mm
        doc.need(block_h)
        # işaret
        c.setFillColor(marker_color)
        c.circle(MARGIN + 1.4 * mm, doc.y + 1.4 * mm, 1.1 * mm, fill=1, stroke=0)
        first = True
        for line in lines:
            _text(c, line, MARGIN + ind, doc.y, 9, REGULAR, DARK if first else SLATE)
            doc.y -= 4.8 * mm
            first = False
        doc.y -= 1.6 * mm


def _hazard_icon(c, kind, cx, cy, color):
    """Compact vector safety pictograms; no icon fonts or external assets."""
    c.saveState()
    c.setStrokeColor(color)
    c.setFillColor(color)
    c.setLineWidth(1.5)
    c.setLineCap(1)
    c.setLineJoin(1)

    if kind == "fall":
        c.circle(cx - 3 * mm, cy + 4 * mm, 1.4 * mm, fill=1, stroke=0)
        c.line(cx - 2 * mm, cy + 2.5 * mm, cx + 1 * mm, cy - 1 * mm)
        c.line(cx - 1 * mm, cy + 1 * mm, cx - 5 * mm, cy - 1 * mm)
        c.line(cx + 1 * mm, cy - 1 * mm, cx + 5 * mm, cy - 4 * mm)
        c.line(cx + 0.5 * mm, cy - 0.5 * mm, cx - 2 * mm, cy - 5 * mm)
        c.setStrokeColor(color)
        c.line(cx - 7 * mm, cy - 6 * mm, cx + 7 * mm, cy - 6 * mm)
    elif kind == "fragile":
        c.rect(cx - 7 * mm, cy - 3 * mm, 14 * mm, 6 * mm, fill=0, stroke=1)
        p = c.beginPath()
        p.moveTo(cx - 1 * mm, cy + 3 * mm)
        p.lineTo(cx + 2 * mm, cy)
        p.lineTo(cx - 1 * mm, cy - 1 * mm)
        p.lineTo(cx + 2 * mm, cy - 3 * mm)
        c.drawPath(p, fill=0, stroke=1)
        c.circle(cx - 4 * mm, cy + 6 * mm, 1.2 * mm, fill=1, stroke=0)
    elif kind == "ladder":
        c.line(cx - 5 * mm, cy - 6 * mm, cx - 1 * mm, cy + 7 * mm)
        c.line(cx + 2 * mm, cy - 6 * mm, cx + 6 * mm, cy + 7 * mm)
        for off in (-3, 0, 3, 6):
            c.line(cx - 3.8 * mm + off * .31 * mm, cy + off * mm,
                   cx + 4.7 * mm + off * .31 * mm, cy + off * mm)
    elif kind == "objects":
        c.rect(cx - 6 * mm, cy + 1 * mm, 4 * mm, 4 * mm, fill=1, stroke=0)
        c.rect(cx + 1 * mm, cy + 5 * mm, 3 * mm, 3 * mm, fill=1, stroke=0)
        c.line(cx - 4 * mm, cy, cx - 4 * mm, cy - 4 * mm)
        c.line(cx - 6 * mm, cy - 2 * mm, cx - 4 * mm, cy - 4 * mm)
        c.line(cx - 2 * mm, cy - 2 * mm, cx - 4 * mm, cy - 4 * mm)
        c.arc(cx + 1 * mm, cy - 7 * mm, cx + 8 * mm, cy, 0, 180)
    elif kind == "mewp":
        c.circle(cx - 4 * mm, cy - 5 * mm, 1.5 * mm, fill=0, stroke=1)
        c.circle(cx + 5 * mm, cy - 5 * mm, 1.5 * mm, fill=0, stroke=1)
        c.line(cx - 5 * mm, cy - 3.5 * mm, cx + 6 * mm, cy - 3.5 * mm)
        c.line(cx, cy - 3 * mm, cx + 2 * mm, cy + 3 * mm)
        c.rect(cx - 1 * mm, cy + 3 * mm, 7 * mm, 4 * mm, fill=0, stroke=1)
        c.circle(cx + 2 * mm, cy + 9 * mm, 1.2 * mm, fill=1, stroke=0)
    elif kind == "weather":
        c.circle(cx - 3 * mm, cy + 3 * mm, 3 * mm, fill=0, stroke=1)
        c.circle(cx + 2 * mm, cy + 4 * mm, 4 * mm, fill=0, stroke=1)
        c.line(cx - 6 * mm, cy, cx + 6 * mm, cy)
        for x in (-4, 0, 4):
            c.line(cx + x * mm, cy - 2 * mm, cx + (x - 1) * mm, cy - 5 * mm)
    elif kind == "anchor":
        c.circle(cx, cy + 2 * mm, 5 * mm, fill=0, stroke=1)
        c.circle(cx, cy + 2 * mm, 2 * mm, fill=0, stroke=1)
        c.line(cx, cy - 3 * mm, cx, cy - 7 * mm)
        c.line(cx - 4 * mm, cy - 7 * mm, cx + 4 * mm, cy - 7 * mm)
    else:  # suspension / rescue
        c.circle(cx, cy + 6 * mm, 1.4 * mm, fill=1, stroke=0)
        c.line(cx, cy + 4 * mm, cx, cy - 2 * mm)
        c.line(cx, cy + 2 * mm, cx - 4 * mm, cy)
        c.line(cx, cy + 2 * mm, cx + 4 * mm, cy)
        c.line(cx, cy - 2 * mm, cx - 3 * mm, cy - 6 * mm)
        c.line(cx, cy - 2 * mm, cx + 3 * mm, cy - 6 * mm)
        c.setStrokeColor(color)
        c.line(cx + 7 * mm, cy + 8 * mm, cx + 7 * mm, cy - 7 * mm)

    c.restoreState()


def _hazard_cards(doc, cards):
    """Eight consistent enterprise HSE cards using embedded SVG pictograms."""
    c = doc.c
    gap = 4 * mm
    cols = 4
    card_w = (CONTENT_W - gap * (cols - 1)) / cols
    card_h = 31 * mm
    rows = (len(cards) + cols - 1) // cols
    total_h = rows * card_h + (rows - 1) * gap
    doc.need(total_h + 2 * mm)
    y_top = doc.y
    for i, card in enumerate(cards):
        row, col = divmod(i, cols)
        x = MARGIN + col * (card_w + gap)
        y = y_top - row * (card_h + gap)
        c.setFillColor(CARD)
        c.setStrokeColor(BORDER)
        c.setLineWidth(.7)
        c.roundRect(x, y - card_h, card_w, card_h, 1.8 * mm,
                    fill=1, stroke=1)
        c.setFillColor(NAVY)
        c.roundRect(x, y - 2.0 * mm, card_w, 2.0 * mm, .8 * mm,
                    fill=1, stroke=0)

        # Small safety-yellow identifier; icon itself stays sober and monochrome.
        c.setFillColor(SAFETY_YELLOW)
        c.circle(x + 5 * mm, y - 6 * mm, 2.1 * mm, fill=1, stroke=0)
        c.setFillColor(NAVY)
        c.setFont(BOLD, 6.5)
        c.drawCentredString(x + 5 * mm, y - 7.0 * mm, str(i + 1))

        icon_name = {"ladder": "access"}.get(card[0], card[0])
        icon_path = ICON_DIR / f"{icon_name}.svg"
        target = 14 * mm
        if svg2rlg is None:
            png = ImageReader(str(ICON_PNG_DIR / f"{icon_name}.png"))
            png_w, png_h = png.getSize()
            scale = min(target / png_w, target / png_h)
            draw_w, draw_h = png_w * scale, png_h * scale
            c.drawImage(
                png,
                x + (card_w - draw_w) / 2,
                y - 22 * mm,
                width=draw_w,
                height=draw_h,
                preserveAspectRatio=True,
                mask="auto",
            )
        else:
            drawing = _ICON_CACHE.get(card[0])
            if drawing is None:
                drawing = svg2rlg(str(icon_path))
                _ICON_CACHE[card[0]] = drawing
            scale = min(target / drawing.width, target / drawing.height)
            c.saveState()
            c.translate(x + (card_w - drawing.width * scale) / 2,
                        y - 22 * mm)
            c.scale(scale, scale)
            renderPDF.draw(drawing, c, 0, 0)
            c.restoreState()

        label_lines = _wrap(c, card[1], card_w - 5 * mm, 7.2, BOLD)[:2]
        ly = y - 25.0 * mm
        for line in label_lines:
            c.setFillColor(NAVY)
            c.setFont(BOLD, 7.2)
            c.drawCentredString(x + card_w / 2, ly, line)
            ly -= 3.6 * mm
    doc.y = y_top - total_h - 4 * mm


def _remember_panel(doc, title, rows):
    c = doc.c
    panel_h = 34 * mm
    doc.need(panel_h + 2 * mm)
    y = doc.y
    c.setFillColor(NAVY)
    c.roundRect(MARGIN, y - panel_h, CONTENT_W, panel_h, 3 * mm,
                fill=1, stroke=0)
    _shield(c, MARGIN + 8 * mm, y - 5 * mm, 7.5 * mm, outer=white, inner=BLUE)
    _text(c, title, MARGIN + 17 * mm, y - 8 * mm, 9.5, BOLD, white)
    col_w = (CONTENT_W - 20 * mm) / 3
    for i, (letter, textval) in enumerate(rows):
        col = i % 3
        row = i // 3
        x = MARGIN + 7 * mm + col * col_w
        ty = y - 17 * mm - row * 9 * mm
        c.setFillColor(BLUE)
        c.circle(x + 3 * mm, ty + 1.5 * mm, 2.7 * mm, fill=1, stroke=0)
        c.setFillColor(white)
        c.setFont(BOLD, 8)
        c.drawCentredString(x + 3 * mm, ty - .8 * mm, letter)
        _text(c, textval, x + 8 * mm, ty, 7.6, REGULAR, HexColor("#E2E8F0"))
    doc.y = y - panel_h - 3 * mm


def _metric_strip(doc, title, metrics):
    """Three auditable field thresholds; fills the overview page meaningfully."""
    c = doc.c
    panel_h = 40 * mm
    doc.need(panel_h + 2 * mm)
    y = doc.y
    _text(c, title, MARGIN, y - 2 * mm, 9.5, BOLD, NAVY)
    y -= 7 * mm
    gap = 4 * mm
    card_w = (CONTENT_W - 2 * gap) / 3
    colors = [(BLUE, PALE_BLUE), (GREEN, PALE_GREEN), (AMBER, PALE_AMBER)]
    for i, (value, label) in enumerate(metrics):
        x = MARGIN + i * (card_w + gap)
        accent, fill = colors[i]
        c.setFillColor(fill)
        c.setStrokeColor(BORDER)
        c.setLineWidth(.55)
        c.roundRect(x, y - 29 * mm, card_w, 29 * mm, 2.6 * mm,
                    fill=1, stroke=1)
        c.setFillColor(accent)
        c.roundRect(x, y - 29 * mm, 3 * mm, 29 * mm, 1.2 * mm,
                    fill=1, stroke=0)
        _text(c, value, x + 8 * mm, y - 11 * mm, 15, BOLD, accent)
        for n, line in enumerate(_wrap(c, label, card_w - 12 * mm, 7.4, REGULAR)[:2]):
            _text(c, line, x + 8 * mm, y - 18 * mm - n * 4 * mm,
                  7.4, REGULAR, SLATE)
    doc.y = y - 32 * mm


def _photo_panel(doc, title, caption, filename):
    """Premium documentary image panel with preserved aspect ratio."""
    c = doc.c
    img = ImageReader(str(IMAGE_DIR / filename))
    source_w, source_h = img.getSize()
    # Fit the real remaining page space instead of forcing a new page.
    available_h = doc.y - BOTTOM_LIMIT - 17 * mm
    if available_h < 34 * mm:
        doc.new_page()
        available_h = doc.y - BOTTOM_LIMIT - 17 * mm
    img_h = min(48 * mm, available_h)
    img_w = img_h * source_w / source_h
    if img_w > CONTENT_W:
        img_w = CONTENT_W
        img_h = img_w * source_h / source_w
    y = doc.y

    c.setFillColor(NAVY)
    c.roundRect(MARGIN, y - 9 * mm, CONTENT_W, 9 * mm, 2 * mm,
                fill=1, stroke=0)
    c.setFillColor(SAFETY_YELLOW)
    c.rect(MARGIN, y - 9 * mm, 3 * mm, 9 * mm, fill=1, stroke=0)
    _text(c, title, MARGIN + 7 * mm, y - 6.1 * mm, 9, BOLD, white)

    image_x = MARGIN + (CONTENT_W - img_w) / 2
    image_y = y - 10.5 * mm - img_h
    c.setStrokeColor(BORDER)
    c.setLineWidth(.7)
    c.roundRect(image_x - .8 * mm, image_y - .8 * mm,
                img_w + 1.6 * mm, img_h + 1.6 * mm, 1.5 * mm,
                fill=0, stroke=1)
    c.drawImage(img, image_x, image_y, width=img_w, height=img_h,
                preserveAspectRatio=True, mask="auto")
    _text(c, caption, image_x, image_y - 4.2 * mm, 7.1, REGULAR, MUTE)
    doc.y = image_y - 7 * mm


def _tiers(doc, tiers):
    """Kontrol hiyerarşisi — 4 kademeli renkli kartlar."""
    c = doc.c
    colors = [
        (GREEN, PALE_GREEN),
        (BLUE, PALE_BLUE),
        (BLUE_DK, PALE_BLUE),
        (SLATE, PALE_SLATE),
    ]
    for idx, tier in enumerate(tiers):
        accent, fill = colors[idx % len(colors)]
        head = f"{idx + 1}. {tier['name']}"
        body_lines = _wrap(c, tier["text"], CONTENT_W - 12 * mm, 8.8, REGULAR)
        card_h = 8 * mm + len(body_lines) * 4.5 * mm + 3 * mm
        doc.need(card_h + 2 * mm)
        y = doc.y
        c.setFillColor(fill)
        c.roundRect(MARGIN, y - card_h, CONTENT_W, card_h, 2.2 * mm,
                    fill=1, stroke=0)
        c.setFillColor(accent)
        c.roundRect(MARGIN, y - card_h, 2.6 * mm, card_h, 1.2 * mm,
                    fill=1, stroke=0)
        _text(c, head, MARGIN + 6 * mm, y - 6 * mm, 9.6, BOLD, NAVY)
        ty = y - 11 * mm
        for line in body_lines:
            _text(c, line, MARGIN + 6 * mm, ty, 8.8, REGULAR, SLATE)
            ty -= 4.5 * mm
        doc.y = y - card_h - 3 * mm


def _warning(doc, title, body):
    c = doc.c
    lines = _wrap(c, body, CONTENT_W - 20 * mm, 9.4, BOLD)
    box_h = 12 * mm + len(lines) * 5 * mm
    doc.need(box_h + 2 * mm)
    y = doc.y
    c.setFillColor(PALE_RED)
    c.roundRect(MARGIN, y - box_h, CONTENT_W, box_h, 2.4 * mm, fill=1, stroke=0)
    c.setFillColor(RED)
    c.roundRect(MARGIN, y - box_h, 3 * mm, box_h, 1.4 * mm, fill=1, stroke=0)
    # uyarı üçgeni
    c.setFillColor(RED)
    tx, tyt = MARGIN + 10 * mm, y - 8.4 * mm
    p = c.beginPath()
    p.moveTo(tx, tyt)
    p.lineTo(tx - 3.2 * mm, tyt - 5.4 * mm)
    p.lineTo(tx + 3.2 * mm, tyt - 5.4 * mm)
    p.close()
    c.drawPath(p, fill=1, stroke=0)
    c.setFillColor(white)
    c.setFont(BOLD, 8)
    c.drawCentredString(tx, tyt - 4.6 * mm, "!")
    _text(c, title, MARGIN + 16 * mm, y - 7.4 * mm, 10, BOLD, RED)
    ty = y - 14 * mm
    for line in lines:
        _text(c, line, MARGIN + 16 * mm, ty, 9.4, BOLD, HexColor("#7F1D1D"))
        ty -= 5 * mm
    doc.y = y - box_h - 3 * mm


def _checklist(doc, items):
    """İki sütunlu onay kutucuklu saha checklist'i."""
    c = doc.c
    col_w = (CONTENT_W - 8 * mm) / 2.0
    col_x = [MARGIN, MARGIN + col_w + 8 * mm]
    # her satır tek satıra sığacak şekilde tasarlandı
    row_h = 8.6 * mm
    rows = (len(items) + 1) // 2
    block_h = rows * row_h + 3 * mm
    doc.need(block_h)
    for i, item in enumerate(items):
        col = i % 2
        row = i // 2
        x = col_x[col]
        y = doc.y - row * row_h
        c.setStrokeColor(BLUE)
        c.setLineWidth(1.0)
        c.rect(x, y - 3.6 * mm, 3.6 * mm, 3.6 * mm, fill=0, stroke=1)
        for line in _wrap(c, item, col_w - 7 * mm, 8.6, REGULAR)[:1]:
            _text(c, line, x + 6 * mm, y - 3.2 * mm, 8.6, REGULAR, DARK)
    doc.y -= block_h


def _standards(doc, items):
    """Compact 2x2 reference cards that translate standards into field action."""
    c = doc.c
    gap = 4 * mm
    card_w = (CONTENT_W - gap) / 2
    prepared = []
    for item in items:
        body = _wrap(c, item["body"], card_w - 11 * mm, 7.4, REGULAR)
        prepared.append((item["code"], item["title"], body))

    row_heights = []
    for row in range(2):
        row_items = prepared[row * 2:row * 2 + 2]
        max_lines = max(len(item[2]) for item in row_items)
        row_heights.append(14 * mm + max_lines * 3.8 * mm)

    total_h = sum(row_heights) + gap
    doc.need(total_h + 2 * mm)
    top = doc.y
    accents = [BLUE, GREEN, AMBER, SLATE]
    fills = [PALE_BLUE, PALE_GREEN, PALE_AMBER, PALE_SLATE]

    idx = 0
    for row, card_h in enumerate(row_heights):
        row_top = top - sum(row_heights[:row]) - row * gap
        for col in range(2):
            code, title, body_lines = prepared[idx]
            x = MARGIN + col * (card_w + gap)
            accent = accents[idx]
            c.setFillColor(fills[idx])
            c.setStrokeColor(BORDER)
            c.setLineWidth(.55)
            c.roundRect(x, row_top - card_h, card_w, card_h, 2.2 * mm,
                        fill=1, stroke=1)
            c.setFillColor(accent)
            c.roundRect(x, row_top - card_h, 2.5 * mm, card_h, 1.1 * mm,
                        fill=1, stroke=0)
            _text(c, code, x + 6 * mm, row_top - 6 * mm, 7, BOLD, accent)
            _text(c, title, x + 6 * mm, row_top - 10.5 * mm, 8.2, BOLD, NAVY)
            ty = row_top - 15 * mm
            for line in body_lines:
                _text(c, line, x + 6 * mm, ty, 7.4, REGULAR, SLATE)
                ty -= 3.8 * mm
            idx += 1
    doc.y = top - total_h - 3 * mm


def _attendance(doc, meta):
    c = doc.c
    fields = meta["att_fields"]
    headers = meta["att_headers"]
    rows = 12
    # Generous handwritten sign-off rows on the dedicated approval sheet.
    row_h = 11.5 * mm
    # üst bilgi alanı (2x2) + tablo başlığı + satırlar
    info_h = 18 * mm
    table_h = 8 * mm + rows * row_h
    total = info_h + table_h + 4 * mm
    doc.need(total)
    y = doc.y

    # bilgi alanı kutucukları
    fw = (CONTENT_W - 6 * mm) / 2.0
    positions = [
        (MARGIN, y - 6 * mm),
        (MARGIN + fw + 6 * mm, y - 6 * mm),
        (MARGIN, y - 15.5 * mm),
        (MARGIN + fw + 6 * mm, y - 15.5 * mm),
    ]
    for (label, (fx, fy)) in zip(fields, positions):
        _text(c, label + ":", fx, fy, 8, BOLD, SLATE)
        c.setStrokeColor(BORDER)
        c.setLineWidth(0.6)
        lx = fx + c.stringWidth(label + ": ", BOLD, 8) + 2 * mm
        c.line(lx, fy - 0.6 * mm, fx + fw, fy - 0.6 * mm)
    y -= info_h

    # tablo başlığı
    col_w = [12 * mm, 62 * mm, CONTENT_W - 12 * mm - 62 * mm - 36 * mm, 36 * mm]
    xs = [MARGIN]
    for w in col_w:
        xs.append(xs[-1] + w)
    c.setFillColor(NAVY)
    c.rect(MARGIN, y - 8 * mm, CONTENT_W, 8 * mm, fill=1, stroke=0)
    for i, htext in enumerate(headers):
        _text(c, htext, xs[i] + 2.5 * mm, y - 5.4 * mm, 8, BOLD, white)
    ry = y - 8 * mm
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.6)
    for r in range(rows):
        top = ry - r * row_h
        if r % 2 == 1:
            c.setFillColor(PALE_SLATE)
            c.rect(MARGIN, top - row_h, CONTENT_W, row_h, fill=1, stroke=0)
        c.setStrokeColor(BORDER)
        c.rect(MARGIN, top - row_h, CONTENT_W, row_h, fill=0, stroke=1)
        for xi in xs[1:-1]:
            c.line(xi, top - row_h, xi, top)
        _text(c, str(r + 1), xs[0] + 4 * mm, top - 5.4 * mm, 8, REGULAR, SLATE)
    doc.y = ry - rows * row_h - 4 * mm


# --------------------------------------------------------------------------- #
# İçerik (TR / EN) — teknik, doğrulanmış referanslarla
# --------------------------------------------------------------------------- #
def ORIGINAL_CONTENT(lang):
    today = date.today().strftime("%d.%m.%Y")
    if lang == "tr":
        return {
            "lang": "tr",
            "kicker": "HSE TOOLBOX TALK",
            "title": "YÜKSEKTE ÇALIŞMA",
            "subtitle": "Düşmeleri, düşen cisimleri ve ölümcül yaralanmaları önleyin.",
            "docno": "SRN-TBT-WAH-001",
            "rev": "00",
            "issue": today,
            "l_docno": "DOKÜMAN NO",
            "l_rev": "REVİZYON",
            "l_date": "YAYIN TARİHİ",
            "page_lbl": "Sayfa {n}",
            "footer_left": "SERNEM HSE · Yüksekte Çalışma Toolbox Talk",
            "gen_by": "Generated by SERNEM",
            "s_purpose": "AMAÇ VE KAPSAM",
            "purpose": (
                "Bu Toolbox Talk, yüksekte çalışma faaliyetlerinde düşme, düşen "
                "cisim ve ölümcül yaralanma risklerini azaltmayı amaçlar. Kapsam; "
                "platform, iskele, merdiven, çatı, zemin açıklıkları ve ekipman "
                "üstü gibi bir kişinin seviye farkından düşerek yaralanabileceği "
                "tüm çalışmaları içerir. Kontroller, ISO 45001:2018 kontrol "
                "hiyerarşisi yaklaşımıyla; işe başlamadan önce çalışma izni, risk "
                "değerlendirmesi ve saha doğrulaması ile birlikte uygulanır."
            ),
            "s_hazards": "BAŞLICA TEHLİKELER",
            "hazards": [
                "Korumasız kenar, açıklık ve platformlardan düşme.",
                "Kırılgan yüzeyler ve çatılardan geçme veya düşme.",
                "Merdiven, iskele ve erişim ekipmanının hatalı kullanımı.",
                "Alet, ekipman ve malzemelerin alt seviyelere düşmesi.",
                "MEWP (yükseltici platform) devrilmesi, sıkışma veya sepetten fırlama.",
                "Olumsuz hava (rüzgâr, buz), kaygan yüzey ve yetersiz aydınlatma.",
                "Uygun olmayan veya yetersiz dayanımlı ankraj noktaları.",
                "Düşüş sonrası askıda kalma (suspension trauma) ve yetersiz kurtarma.",
            ],
            "hazard_cards": [
                ("fall", "KENARDAN DÜŞME"),
                ("fragile", "KIRILGAN YÜZEY"),
                ("ladder", "GÜVENSİZ ERİŞİM"),
                ("objects", "DÜŞEN CİSİM"),
                ("mewp", "MEWP / PLATFORM"),
                ("weather", "HAVA KOŞULLARI"),
                ("anchor", "ANKRAJ HATASI"),
                ("rescue", "ASKIDA KALMA"),
            ],
            "metric_title": "SAHADA DOĞRULANACAK KRİTİK DEĞERLER",
            "metrics": [
                ("1,8 m", "OSHA inşaat düşme koruması eşiği"),
                ("1,2 m", "OSHA genel sanayi koruma eşiği"),
                ("22 kN", "Çalışan başına ankraj dayanımı"),
            ],
            "s_controls": "KRİTİK KONTROL ÖNLEMLERİ (KONTROL HİYERARŞİSİ)",
            "tiers": [
                {
                    "name": "KAÇININ (Elimination)",
                    "text": (
                        "Mümkün olduğunda yüksekte çalışmaktan kaçının. İşi zeminde "
                        "hazırlayın, ön montaj yapın veya uzatmalı/yerden kumandalı "
                        "ekipman kullanın."
                    ),
                },
                {
                    "name": "DÜŞMEYİ ÖNLEYİN (Kollektif koruma)",
                    "text": (
                        "Korkuluk, çalışma platformu, kapak ve bariyerleri öncelikle "
                        "kullanın; doğru kurulmuş iskele veya MEWP tercih edin. Korkuluk "
                        "sistemleri uygun yükseklik ve dayanımda olmalıdır "
                        "(OSHA: üst korkuluk ~1,07 m / 42 inch)."
                    ),
                },
                {
                    "name": "SONUCU AZALTIN (Düşüş durdurma)",
                    "text": (
                        "Kollektif koruma uygulanamıyorsa güvenlik ağı ya da kişisel "
                        "düşme durdurma sistemi kullanın: tam vücut emniyet kemeri ve "
                        "onaylı ankraj (çalışan başına ≥ 5.000 lb / ~22 kN). Yeterli "
                        "düşüş açıklığını ve salınım düşüşü riskini doğrulayın."
                    ),
                },
                {
                    "name": "YÖNETSEL ve KKD (Son çare)",
                    "text": (
                        "Çalışma izni, yetkin kişi (competent person) gözetimi, ekipman "
                        "muayenesi, uygulanabilir kurtarma planı ve eğitim ile destekleyin. "
                        "KKD tek başına yeterli koruma değildir."
                    ),
                },
            ],
            "warn_title": "ÖNEMLİ UYARI",
            "warn": (
                "Denetlenmemiş veya uygun olmayan düşme koruması ile ASLA yüksekte "
                "çalışmayın. İnşaat işlerinde 1,8 m (6 ft), genel sanayide 1,2 m "
                "(4 ft) ve üzeri düşme mesafelerinde koruma zorunludur. Düşük "
                "yükseklikten düşüşler bile ölümcül olabilir."
            ),
            "s_checklist": "SAHA CHECKLIST'İ (İŞE BAŞLAMADAN ÖNCE)",
            "checklist": [
                "Çalışma izni ve risk değerlendirmesi onaylı",
                "Güvenli erişim ve korkuluklar tamam",
                "İskele / platform muayene edildi (etiketli)",
                "Ankraj noktaları belirlendi ve dayanımı doğrulandı",
                "Emniyet kemeri ve lanyard muayene edildi",
                "Alt bölge bariyerlendi, aletler bağlandı",
                "Hava, yüzey ve aydınlatma koşulları uygun",
                "Kurtarma planı ve ekipmanı hazır",
                "Personel yetkin ve bilgilendirildi",
            ],
            "s_standards": "STANDARTLAR VE SAHA GEREKLİLİKLERİ",
            "standards_intro": (
                "Bu referanslar yalnızca yasal eşikleri göstermez; sahadaki güvenli çalışma düzeninin nasıl kurulacağını da tanımlar. "
                "Yerel mevzuat veya işveren kuralı daha sıkıysa her zaman daha yüksek standart uygulanır."
            ),
            "standards": [
                {
                    "code": "OSHA 1926 SUBPART M",
                    "title": "İNŞAATTA DÜŞME KORUMASI",
                    "body": "1,8 m ve üzerinde açık kenarları, zemin boşluklarını ve çalışma platformlarını korkuluk, kapak veya kişisel düşüş durdurma sistemi ile koruyun.",
                },
                {
                    "code": "OSHA 1910 SUBPART D",
                    "title": "YÜRÜME-ÇALIŞMA YÜZEYLERİ",
                    "body": "Genel sanayide 1,2 m ve üzerindeki düşme risklerini kontrol edin. Erişim yollarını, merdivenleri, açıklıkları ve yüzey bütünlüğünü işe başlamadan doğrulayın.",
                },
                {
                    "code": "ISO 45001:2018 · 8.1.2",
                    "title": "KONTROL HİYERARŞİSİ",
                    "body": "Önce yüksekte çalışmayı ortadan kaldırın. Ardından kolektif korumayı seçin; kişisel düşüş durdurma sistemi ve KKD son savunma hattıdır.",
                },
                {
                    "code": "SAHA İYİ UYGULAMASI",
                    "title": "YETKİNLİK VE KURTARMA",
                    "body": "Etiketli iskele, doğrulanmış ankraj, ekipman ön kullanım kontrolü, bariyerli alt bölge ve işe özel uygulanabilir kurtarma planı olmadan çalışmaya başlamayın.",
                },
            ],
            "s_evidence": "İŞE BAŞLAMADAN ÖNCE ASGARİ KANITLAR",
            "standards_evidence": [
                "Onaylı çalışma izni ve göreve özel risk değerlendirmesi",
                "Geçerli iskele etiketi veya platform muayene kaydı",
                "Ankraj seçimi ve gerekli dayanım doğrulaması",
                "Emniyet kemeri, lanyard / SRL ön kullanım kontrolü",
                "Alt bölge bariyeri ve düşen cisim kontrolü",
                "İşe özel kurtarma planı, ekipmanı ve sorumlu kişiler",
            ],
            "s_discussion": "SÜPERVİZÖR KONUŞMA NOKTALARI",
            "standards_discussion": [
                "Bu iş zeminde veya uzaktan yöntemle yapılabilir mi?",
                "Kolektif koruma neden kişisel düşüş durdurmadan önce gelir?",
                "Bir düşüş sonrası askıda kalan kişiyi kim, nasıl ve ne kadar sürede kurtaracak?",
            ],
            "s_attendance": "KATILIM VE ONAY",
            "remember_title": "HATIRLA — SERNEM",
            "remember": [
                ("S", "Dur ve düşün"),
                ("E", "Riski değerlendir"),
                ("R", "Ortadan kaldır / azalt"),
                ("N", "Asla varsayma"),
                ("E", "Korumayı doğrula"),
                ("M", "İzle ve iletişim kur"),
            ],
            "photo_title": "GÜVENLİ YÜKSEKTE ÇALIŞMA DÜZENİ",
            "photo_caption": "Tam korkuluk · Baş üstü ankraj · SRL · Bağlı aletler · Bariyerli alt bölge · Hazır kurtarma",
            "att_fields": ["Proje / Saha", "Tarih", "Konuşmayı yapan", "Çalışma alanı"],
            "att_headers": ["No", "Ad Soyad", "Firma / Görev", "İmza"],
        }
    return {
        "lang": "en",
        "kicker": "HSE TOOLBOX TALK",
        "title": "WORKING AT HEIGHT",
        "subtitle": "Prevent falls, falling objects and fatal injuries.",
        "docno": "SRN-TBT-WAH-001",
        "rev": "00",
        "issue": today,
        "l_docno": "DOCUMENT NO",
        "l_rev": "REVISION",
        "l_date": "ISSUE DATE",
        "page_lbl": "Page {n}",
        "footer_left": "SERNEM HSE · Working at Height Toolbox Talk",
        "gen_by": "Generated by SERNEM",
        "s_purpose": "PURPOSE AND SCOPE",
        "purpose": (
            "This Toolbox Talk aims to reduce the risk of falls, falling objects "
            "and fatal injuries during work at height. Its scope covers all tasks "
            "where a person could fall from one level to another and be injured — "
            "including platforms, scaffolds, ladders, roofs, floor openings and "
            "equipment surfaces. Controls follow the ISO 45001:2018 hierarchy of "
            "controls and are applied together with a permit to work, a risk "
            "assessment and a pre-task site check before work begins."
        ),
        "s_hazards": "KEY HAZARDS",
        "hazards": [
            "Falls from unprotected edges, openings and working platforms.",
            "Walking on or falling through fragile surfaces and roofs.",
            "Incorrect use of ladders, scaffolds and access equipment.",
            "Tools, equipment and materials dropped to lower levels.",
            "MEWP overturn, entrapment or ejection from the basket.",
            "Adverse weather (wind, ice), slippery surfaces and poor lighting.",
            "Unapproved or inadequately rated anchor points.",
            "Suspension trauma after a fall and inadequate rescue provision.",
        ],
        "hazard_cards": [
            ("fall", "FALL FROM HEIGHT"),
            ("fragile", "FRAGILE SURFACE"),
            ("ladder", "UNSAFE ACCESS"),
            ("objects", "FALLING OBJECTS"),
            ("mewp", "MEWP / PLATFORM"),
            ("weather", "WEATHER"),
            ("anchor", "ANCHOR FAILURE"),
            ("rescue", "SUSPENSION"),
        ],
        "metric_title": "CRITICAL VALUES TO VERIFY IN THE FIELD",
        "metrics": [
            ("1.8 m", "OSHA construction fall-protection trigger"),
            ("1.2 m", "OSHA general-industry protection trigger"),
            ("22 kN", "Anchor capacity required per worker"),
        ],
        "s_controls": "CRITICAL CONTROL MEASURES (HIERARCHY OF CONTROLS)",
        "tiers": [
            {
                "name": "AVOID (Elimination)",
                "text": (
                    "Avoid work at height where reasonably practicable. Prepare or "
                    "pre-assemble the work at ground level, or use extendable / "
                    "ground-operated equipment."
                ),
            },
            {
                "name": "PREVENT FALLS (Collective protection)",
                "text": (
                    "Give priority to guardrails, working platforms, covers and "
                    "barriers; use correctly erected scaffolds or a MEWP. Guardrail "
                    "systems must be of adequate height and strength "
                    "(OSHA: top rail ~1.07 m / 42 in)."
                ),
            },
            {
                "name": "MINIMISE CONSEQUENCES (Fall arrest)",
                "text": (
                    "Where collective protection is not practicable, use a safety net "
                    "or a personal fall-arrest system: a full-body harness and an "
                    "approved anchor (\u2265 5,000 lb / ~22 kN per worker). Verify "
                    "adequate fall clearance and swing-fall exposure."
                ),
            },
            {
                "name": "ADMINISTRATIVE & PPE (Last resort)",
                "text": (
                    "Support controls with a permit to work, competent-person "
                    "supervision, equipment inspection, a workable rescue plan and "
                    "training. PPE alone is not adequate protection."
                ),
            },
        ],
        "warn_title": "CRITICAL WARNING",
        "warn": (
            "NEVER work at height without inspected, suitable fall protection. Fall "
            "protection is required at 1.8 m (6 ft) or more in construction and at "
            "1.2 m (4 ft) or more in general industry. Even a fall from a low height "
            "can be fatal."
        ),
        "s_checklist": "SITE CHECKLIST (BEFORE STARTING WORK)",
        "checklist": [
            "Permit to work and risk assessment approved",
            "Safe access and guardrails complete",
            "Scaffold / platform inspected and tagged",
            "Anchor points identified and strength verified",
            "Harness and lanyard inspected",
            "Area below barricaded, tools tethered",
            "Weather, surface and lighting suitable",
            "Rescue plan and equipment ready",
            "Personnel competent and briefed",
        ],
        "s_standards": "STANDARDS AND FIELD REQUIREMENTS",
        "standards_intro": (
            "These references do more than define legal thresholds; they establish how a safe work-at-height system is built in the field. "
            "Where local law or the employer rule is stricter, always apply the higher standard."
        ),
        "standards": [
            {
                "code": "OSHA 1926 SUBPART M",
                "title": "CONSTRUCTION FALL PROTECTION",
                "body": "At 1.8 m (6 ft) or more, protect open edges, floor openings and work platforms with guardrails, covers or a personal fall-arrest system.",
            },
            {
                "code": "OSHA 1910 SUBPART D",
                "title": "WALKING-WORKING SURFACES",
                "body": "In general industry, control fall exposure at 1.2 m (4 ft) or more. Verify access routes, ladders, openings and surface integrity before work starts.",
            },
            {
                "code": "ISO 45001:2018 · 8.1.2",
                "title": "HIERARCHY OF CONTROLS",
                "body": "Eliminate work at height first. Then prioritise collective protection; personal fall arrest and PPE are the final lines of defence.",
            },
            {
                "code": "FIELD GOOD PRACTICE",
                "title": "COMPETENCE AND RESCUE",
                "body": "Do not start without a tagged scaffold, verified anchor, pre-use equipment checks, a barricaded drop zone and a workable task-specific rescue plan.",
            },
        ],
        "s_evidence": "MINIMUM EVIDENCE BEFORE START",
        "standards_evidence": [
            "Approved permit to work and task-specific risk assessment",
            "Valid scaffold tag or platform inspection record",
            "Anchor selection and required strength verification",
            "Pre-use inspection of harness, lanyard / SRL",
            "Drop-zone barricade and falling-object controls",
            "Task-specific rescue plan, equipment and named responders",
        ],
        "s_discussion": "SUPERVISOR DISCUSSION POINTS",
        "standards_discussion": [
            "Can this task be completed from ground level or by a remote method?",
            "Why must collective protection come before personal fall arrest?",
            "After a fall, who will rescue the suspended person, how, and within what time?",
        ],
        "s_attendance": "ATTENDANCE AND APPROVAL",
        "remember_title": "REMEMBER — SERNEM",
        "remember": [
            ("S", "Stop and think"),
            ("E", "Evaluate the risk"),
            ("R", "Remove or reduce"),
            ("N", "Never assume"),
            ("E", "Ensure protection"),
            ("M", "Monitor and communicate"),
        ],
        "photo_title": "SAFE WORK AT HEIGHT SETUP",
        "photo_caption": "Full guardrails · Overhead anchor · SRL · Tethered tools · Barricaded drop zone · Rescue ready",
        "att_fields": ["Project / Site", "Date", "Presented by", "Work area"],
        "att_headers": ["No", "Full Name", "Company / Role", "Signature"],
    }


# --------------------------------------------------------------------------- #
# Doküman oluşturma
# --------------------------------------------------------------------------- #

def content(lang, slug="working-at-height"):
    import json

    if slug == "working-at-height":
        return ORIGINAL_CONTENT(lang)

    data_file = Path(__file__).with_name("premium-toolbox-remaining-26.json")
    data = json.loads(data_file.read_text(encoding="utf-8"))

    if slug not in data:
        raise KeyError(f"Toolbox bulunamadı: {slug}")

    src = data[slug][lang]
    tr = lang == "tr"

    def arr(value):
        if isinstance(value, list):
            return [str(x).strip() for x in value if str(x).strip()]
        if isinstance(value, str) and value.strip():
            return [value.strip()]
        return []

    def txt(value, default=""):
        if isinstance(value, str):
            return value.strip()
        if isinstance(value, list):
            return " ".join(str(x).strip() for x in value if str(x).strip())
        return default

    title = txt(src.get("title"), slug.replace("-", " ").title())
    subtitle = txt(src.get("subtitle"))
    objective = txt(src.get("objective"))
    explanation = arr(src.get("explanation"))
    hazards = arr(src.get("hazards"))
    controls = arr(src.get("controls"))
    verification = arr(src.get("verification"))
    questions = arr(src.get("questions"))

    supervisor = txt(src.get("supervisor_script"))
    remember_src = txt(src.get("remember"))

    if not hazards:
        hazards = verification or controls or [objective]

    if not controls:
        controls = verification or hazards or [objective]

    if not verification:
        verification = controls[:6]

    # Master yalnız bu 8 ikon kimliğini destekliyor.
    icon_kinds = [
        "fall", "fragile", "ladder", "objects",
        "mewp", "weather", "anchor", "rescue"
    ]

    hazard_cards = []
    for i, item in enumerate(hazards[:8]):
        hazard_cards.append((icon_kinds[i], item[:62]))

    # En az birkaç kart olsun.
    while len(hazard_cards) < min(4, len(icon_kinds)):
        item = controls[len(hazard_cards) % len(controls)]
        i = len(hazard_cards)
        hazard_cards.append((icon_kinds[i], item[:62]))

    # Master metric strip tam 3 kayıt bekliyor.
    metric_source = hazards + controls
    metrics = []
    for i in range(3):
        item = metric_source[i % len(metric_source)]
        metrics.append((f"{i+1:02}", item))

    # Master 4 kontrol hiyerarşisi kartı bekliyor.
    tier_names_tr = [
        "RİSKİ ORTADAN KALDIR / AZALT",
        "MÜHENDİSLİK VE FİZİKSEL KONTROLLER",
        "İŞ YÖNTEMİ VE SAHA KONTROLLERİ",
        "KKD, DOĞRULAMA VE GÖZETİM",
    ]
    tier_names_en = [
        "ELIMINATE / REDUCE THE RISK",
        "ENGINEERING & PHYSICAL CONTROLS",
        "WORK METHOD & FIELD CONTROLS",
        "PPE, VERIFICATION & SUPERVISION",
    ]

    tier_names = tier_names_tr if tr else tier_names_en
    tiers = []

    for i in range(4):
        group = controls[i::4]
        if not group:
            group = verification[i::4]
        if not group:
            group = [objective]

        tiers.append({
            "name": tier_names[i],
            "text": " • ".join(group[:3]),
        })

    # Standards kart yapısı master'daki 2x2 biçimine uygun.
    reqs = verification + controls
    standards = []

    for i in range(4):
        body = reqs[i % len(reqs)]
        standards.append({
            "code": f"SERNEM FIELD {i+1:02}",
            "title": (
                f"SAHA DOĞRULAMA {i+1}"
                if tr else
                f"FIELD VERIFICATION {i+1}"
            ),
            "body": body,
        })

    standards_evidence = verification[:6] or controls[:6]
    standards_discussion = questions[:3]

    if not standards_discussion:
        standards_discussion = [
            (
                "Bu işte bugün değişen bir saha koşulu var mı?"
                if tr else
                "Has any field condition changed for this task today?"
            ),
            (
                "Kontroller işe başlamadan önce doğrulandı mı?"
                if tr else
                "Have the controls been verified before starting work?"
            ),
            (
                "Koşullar değişirse işi kim durduracak?"
                if tr else
                "Who will stop the work if conditions change?"
            ),
        ]

    remember = (
        [
            ("S", "Dur ve düşün"),
            ("E", "Riski değerlendir"),
            ("R", "Ortadan kaldır / azalt"),
            ("N", "Asla varsayma"),
            ("E", "Korumayı doğrula"),
            ("M", "İzle ve iletişim kur"),
        ]
        if tr
        else
        [
            ("S", "Stop and think"),
            ("E", "Evaluate the risk"),
            ("R", "Remove or reduce"),
            ("N", "Never assume"),
            ("E", "Ensure protection"),
            ("M", "Monitor and communicate"),
        ]
    )

    warning = supervisor or remember_src or controls[0]

    today = date.today().strftime("%d.%m.%Y")

    return {
        "lang": lang,
        "kicker": "HSE TOOLBOX TALK",
        "title": title.upper(),
        "subtitle": subtitle,

        "docno": f"SRN-TBT-{slug.upper()[:18]}",
        "rev": "00",
        "issue": today,

        "l_docno": "DOKÜMAN NO" if tr else "DOCUMENT NO",
        "l_rev": "REVİZYON" if tr else "REVISION",
        "l_date": "YAYIN TARİHİ" if tr else "ISSUE DATE",

        "page_lbl": "Sayfa {n}" if tr else "Page {n}",
        "footer_left": f"SERNEM HSE · {title}",
        "gen_by": "Generated by SERNEM",

        "s_purpose": "AMAÇ VE KAPSAM" if tr else "PURPOSE AND SCOPE",
        "purpose": objective or " ".join(explanation),

        "s_hazards": "BAŞLICA TEHLİKELER" if tr else "KEY HAZARDS",
        "hazard_cards": hazard_cards,

        "metric_title": (
            "SAHADA DOĞRULANACAK KRİTİK NOKTALAR"
            if tr else
            "CRITICAL POINTS TO VERIFY IN THE FIELD"
        ),
        "metrics": metrics,

        "remember_title": "HATIRLA — SERNEM" if tr else "REMEMBER — SERNEM",
        "remember": remember,

        "s_standards": (
            "SAHA GEREKLİLİKLERİ VE DOĞRULAMA"
            if tr else
            "FIELD REQUIREMENTS AND VERIFICATION"
        ),
        "standards_intro": (
            objective or " ".join(explanation[:2])
        ),
        "standards": standards,

        "s_evidence": (
            "İŞE BAŞLAMADAN ÖNCE DOĞRULAMA"
            if tr else
            "VERIFICATION BEFORE START"
        ),
        "standards_evidence": standards_evidence,

        "s_discussion": (
            "SÜPERVİZÖR KONUŞMA NOKTALARI"
            if tr else
            "SUPERVISOR DISCUSSION POINTS"
        ),
        "standards_discussion": standards_discussion,

        "photo_title": (
            "SAHA UYGULAMASI"
            if tr else
            "FIELD APPLICATION"
        ),
        "photo_caption": subtitle or objective,

        "s_controls": (
            "KRİTİK KONTROL ÖNLEMLERİ"
            if tr else
            "CRITICAL CONTROL MEASURES"
        ),
        "tiers": tiers,

        "warn_title": "KRİTİK UYARI" if tr else "CRITICAL WARNING",
        "warn": warning,

        "s_checklist": (
            "SAHA CHECKLISTİ — İŞE BAŞLAMADAN ÖNCE"
            if tr else
            "SITE CHECKLIST — BEFORE STARTING WORK"
        ),
        "checklist": verification[:10] or controls[:10],

        "s_attendance": (
            "KATILIM VE ONAY"
            if tr else
            "ATTENDANCE AND APPROVAL"
        ),

        "att_fields": (
            ["Proje / Saha", "Tarih", "Konuşmayı yapan", "Çalışma alanı"]
            if tr else
            ["Project / Site", "Date", "Presented by", "Work area"]
        ),

        "att_headers": (
            ["No", "Ad Soyad", "Firma / Görev", "İmza"]
            if tr else
            ["No", "Full Name", "Company / Role", "Signature"]
        ),
    }



def build_content(variant, meta, filename):
    """Render any toolbox content that follows the premium four-page schema."""
    meta = dict(meta)

    # AUTO MASTER META FALLBACK
    _lang = meta.get("lang", "en")
    _tr = _lang == "tr"

    _master_defaults = {
        "lang": _lang,
        "docno": "SRN-TBT-001",
        "rev": "00",
        "issue": meta.get("date", ""),
        "date": "",
        "l_docno": "DOKÜMAN NO" if _tr else "DOCUMENT NO",
        "l_rev": "REVİZYON" if _tr else "REVISION",
        "l_date": "YAYIN TARİHİ" if _tr else "ISSUE DATE",
        "gen_by": "SERNEM HSE",
        "footer_left": "SERNEM • HSE TOOLBOX TALK",
        "footer_right": "sernem.com",
        "page_lbl": "SAYFA" if _tr else "PAGE",
        "variant": "standard",
    }

    for _required_key in ['att_fields', 'att_headers', 'checklist', 'docno', 'footer_left', 'gen_by', 'hazard_cards', 'issue', 'kicker', 'l_date', 'l_docno', 'l_rev', 'metric_title', 'metrics', 'page_lbl', 'photo_caption', 'photo_title', 'purpose', 'remember', 'remember_title', 'rev', 's_attendance', 's_checklist', 's_controls', 's_discussion', 's_evidence', 's_hazards', 's_purpose', 's_standards', 'standards', 'standards_discussion', 'standards_evidence', 'standards_intro', 'subtitle', 'tiers', 'title', 'variant', 'warn', 'warn_title']:
        if _required_key not in meta or meta[_required_key] is None:
            meta[_required_key] = _master_defaults.get(_required_key, "")


    # Master layout compatibility defaults
    _is_tr = (
        meta.get("lang") == "tr"
        or meta.get("l_docno") == "DOKÜMAN NO"
        or meta.get("l_date") == "YAYIN TARİHİ"
    )

    _defaults = {
        "lang": "tr" if _is_tr else "en",
        "docno": meta.get("docno", "SRN-TBT-001"),
        "rev": meta.get("rev", "00"),
        "issue": meta.get("issue", meta.get("date", "")),
        "l_docno": "DOKÜMAN NO" if _is_tr else "DOCUMENT NO",
        "l_rev": "REVİZYON" if _is_tr else "REVISION",
        "l_date": "YAYIN TARİHİ" if _is_tr else "ISSUE DATE",
        "gen_by": "SERNEM HSE",
        "footer_left": "SERNEM • HSE TOOLBOX TALK",
        "footer_right": "sernem.com",
        "variant": meta.get("variant", "standard"),
    }

    for _k, _v in _defaults.items():
        if not meta.get(_k):
            meta[_k] = _v


    # Master PDF layout compatibility defaults
    _master_defaults = {
        "gen_by": "Generated by SERNEM",
        "issue": meta.get("date", ""),
        "l_docno": "DOKÜMAN NO" if meta.get("lang") == "tr" else "DOCUMENT NO",
        "l_rev": "REVİZYON" if meta.get("lang") == "tr" else "REVISION",
        "l_date": "YAYIN TARİHİ" if meta.get("lang") == "tr" else "ISSUE DATE",
    }

    for _key, _value in _master_defaults.items():
        meta.setdefault(_key, _value)
    meta["variant"] = variant

    c = canvas.Canvas(str(OUT / filename), pagesize=A4)
    c.setTitle(f"{meta['title']} — Toolbox Talk")

    doc = Doc(c, meta)

    _section_title(doc, meta["s_purpose"], BLUE)
    _paragraph(doc, meta["purpose"])
    doc.gap(2 * mm)

    _section_title(doc, meta["s_hazards"], RED)
    _hazard_cards(doc, meta["hazard_cards"])
    _metric_strip(doc, meta["metric_title"], meta["metrics"])
    _remember_panel(doc, meta["remember_title"], meta["remember"])

    # Four intentional compositions: overview, standards, controls, sign-off.
    doc.new_page()

    _section_title(doc, meta["s_standards"], SLATE, keep=70 * mm)
    _paragraph(doc, meta["standards_intro"], size=8.5, leading=4.4 * mm)
    doc.gap(2 * mm)
    _standards(doc, meta["standards"])
    doc.gap(1 * mm)

    _section_title(doc, meta["s_evidence"], BLUE)
    _checklist(doc, meta["standards_evidence"])
    doc.gap(1 * mm)

    _section_title(doc, meta["s_discussion"], GREEN)
    _bullets(doc, meta["standards_discussion"], marker_color=GREEN)
    doc.gap(1 * mm)

    _photo_panel(
        doc,
        meta["photo_title"],
        meta["photo_caption"],
        meta.get("photo_file", "working-at-height-safe-setup.jpg"),
    )

    doc.new_page()

    _section_title(doc, meta["s_controls"], GREEN)
    _tiers(doc, meta["tiers"])
    doc.gap(1 * mm)

    _warning(doc, meta["warn_title"], meta["warn"])
    doc.gap(1 * mm)

    _section_title(doc, meta["s_checklist"], BLUE)
    _checklist(doc, meta["checklist"])
    doc.gap(1 * mm)

    doc.new_page()

    _section_title(doc, meta["s_attendance"], NAVY, keep=78 * mm)
    _attendance(doc, meta)

    c.showPage()
    c.save()
    print(f"  ✓ {filename}")


def build(variant, lang, filename, slug="working-at-height"):
    build_content(variant, content(lang, slug), filename)


# --------------------------------------------------------------------------- #
# PREMIUM BATCH — remaining 26
# --------------------------------------------------------------------------- #

REMAINING_26 = [
    "safety-harness",
    "scaffold-safety",
    "line-of-fire",
    "slips-trips-falls",
    "welding-fumes",
    "cold-stress",
    "eye-face-protection",
    "hand-injury-prevention",
    "temporary-electrical-installations",
    "stop-work-authority",
    "barricading-exclusion-zones",
    "overhead-power-lines",
    "underground-services",
    "nitrogen-inert-gas-safety",
    "steam-hot-surfaces",
    "hose-coupling-safety",
    "painting-coating-safety",
    "lightning-severe-weather",
    "tag-line-safety",
    "load-stability-center-of-gravity",
    "forklift-loading-unloading",
    "flange-joint-integrity",
    "chemical-transfer-decanting",
    "hazardous-waste-handling",
    "portable-generator-safety",
    "demolition-dismantling",
]


def main():
    print("SERNEM Premium Toolbox Batch")
    print("Master layout: 4 pages")
    print("Remaining:", len(REMAINING_26))
    for i, slug in enumerate(REMAINING_26, 1):
        print(f"{i:02}. {slug}")

    print()
    print("✅ Premium 4-page master hazır.")
    print("⚠️ PDF üretimi henüz başlatılmadı; önce 26 içerik master şemaya map edilecek.")


if __name__ == "__main__":
    main()
